### ISSUE TITLE
Firefox hanging very frequently

### ISSUE THREAD

**Issue by Question2** [kkapsner/CanvasBlocker#100]
I'm using Firefox 50.1.0, and and I have noticed that it hangs very often (every few seconds) with your add-on enabled. With it disabled, I think it hangs less but I'm not sure. Ive tried to get the Mozilla devs to look at a hang report that the WhatIsHang program generated (see : https://bugzilla.mozilla.org/show_bug.cgi?id=1328178) but they have so far declined to do so.

Is there any chance you can take a look and see if your add-on might be causing it? I think this started after I updated to Firefox 49 or 50, but I'm not sure.

**Comment by kkapsner** [comment]
I think this could be related to #98. But CB is e10s ready so the shims are disabled.

**Comment by Question2** [comment]
@kkapsner : Did you manage to take a look at the hang report to see if it could be related to canvas blocker?

**Comment by kkapsner** [comment]
I do not see something that points to CB - but I'm not sure if that indicates anything.

**Comment by Question2** [comment]
@kkapsner : Is there any info that points to what is causing firefox to hang?

**Comment by EricRahm** [comment]
@kkapsner Looking at [about:memory reports](https://bugzilla.mozilla.org/show_bug.cgi?id=1328178#c19) it's pretty clear CanvasBlocker is leaking compartments. I'm sorry I don't have much more analysis for you than that.

**Comment by Question2** [comment]
@EricRahm : Thanks for the help!

@kkapsner : Any chance you can take a look at the memory issue?

**Comment by kkapsner** [comment]
@EricRahm: Thanks for the input. But I have a little bit of analysis: the usage of /loader in the frame script (https://github.com/kkapsner/CanvasBlocker/blob/bfaffc98dfe85100c15244454cc15900139b7177/data/frame.js#L8) instead of directly importing require.js (https://github.com/kkapsner/CanvasBlocker/blob/e4c65d415e78b5f3330c1e1d3872cd917217f4ca/data/frame.js#L10) makes this leak happen.

I'm not sure if I'm using the loader wrong or if that's a sdk bug...
... my route to solve this problem is at the moment to merge all the files into one big frame script.

**Comment by kkapsner** [comment]
Version 0.3.6 is out - please check if the problem is really solved when the version is approved by mozilla.

**Comment by Question2** [comment]
@kkapsner : Just tried with 0.3.6, still getting repeated freezes in firefox with the addon enabled.

**Comment by kkapsner** [comment]
hm... the memory leak is gone and I do not know what could cause the problem. Can you do another gecko profile and memory report?

**Comment by Question2** [comment]
[memory-report.json.gz](https://github.com/kkapsner/CanvasBlocker/files/853927/memory-report.json.gz)

Gecko profiler keeps crashing at the moment unfortunately, but i hope the memory report is useful.

**Comment by kkapsner** [comment]
It seems that CanvasBlocker uses ~1.4 MB not too few but reasonable for the amout of open stuff. I'm not sure what causes the problems - and the freezes do not happen when you disable the Addon?
