### ISSUE TITLE
Colision with another anti-fingerprint add-on

### ISSUE THREAD

**Issue by xtremertx** [kkapsner/CanvasBlocker#101]
I have found a problem when using **CanvasBlocker** together with **No Resource URI Leak 1.1.0**. Basically **No Resource URI Leak 1.1.0** is blocking resource fingerprinting that can reveal your OS and language by blocking URI scheme used by firefox  to call on-disk resources from internal modules and extensions using:

> resource://

Resource fingerprinting TEST HERE - [https://browserleaks.com/firefox#more](https://browserleaks.com/firefox)

I think this can be fixed by not using 'resource://' address in your addon based on the console error output:
![console_firefox](https://cloud.githubusercontent.com/assets/14142029/22141924/829b2ba0-def4-11e6-8e4e-80c2d26acc9f.PNG)

- resource://canvasblocker-at-kkapshner-dot-de/lib/notifications.js

To duplicate this error you need both add-ons installed and visit extratorrent.cc, main content is not shown, but after disabling resource addon, its all ok... (btw: yes i know its torrent side, but its currently only one with this bug i have found )))

Can someone look into this & it is solvable? (I'm not a JS developer myself, but desktop .NET one :/)

**Comment by kkapsner** [comment]
This page does not show anything when CB is installed alone as well. They seem to use a really weird obfuscator that uses a canvas. You could use a file specific white listing to allow the specific js-file:

![grafik](https://cloud.githubusercontent.com/assets/1105157/22242545/0691a416-e224-11e6-973e-e2df29b52c5a.png)


So I do not see a relation to the other Add-On.

The error message you posted is unrelated and will be gone in the next version.

**Comment by xtremertx** [comment]
OK, thx for clearing things to me.

**Comment by kkapsner** [comment]
You're welcome.
