### ISSUE TITLE
Persistence per session?

### ISSUE THREAD

**Issue by rekixex** [kkapsner/CanvasBlocker#103]
I tested the default block mode of CanvasBlocker (_fake readout API_) with the random number generator set to _persistent_ on https://panopticlick.eff.org/ and https://browserleaks.com/canvas. Tests confirmed that CanvasBlocker successfully fakes readout API.

However, I repeated the tests in a new tab (in the same session) and hash of canvas fingerprint changed.

This could allow websites to detect that visitor faked readout API. I think that it would be better to fake readout API per **new session**, not per **new tab**. It could make harder for websites to detect that visitor faked readout API.

@kkapsner What is your opinion on this?

**Comment by kkapsner** [comment]
I think you're right - it should be persistent per session and not per tab. Still trying to wrap my head around this to work with e10s, but I think there is a way.

**Comment by kkapsner** [comment]
Version 0.3.6 is out - please check if the problem is really solved when the version is approved by mozilla.

**Comment by rekixex** [comment]
@kkapsner 

Thank you for your effort, I will try it out and report back. :)

**Comment by rekixex** [comment]
@kkapsner I repeated the tests on https://panopticlick.eff.org/ and https://browserleaks.com/canvas (CanvasBlocker version 0.3.6) and I can confirm it is working as expected (fake readout API per **new session**, _not_ per **new tab**).

Important enhancement, thanks again. :)

**Comment by rekixex** [comment]
@kkapsner I repeated the tests on https://panopticlick.eff.org/ and https://browserleaks.com/canvas (CanvasBlocker version 0.3.6) and I can confirm it is working as expected (_fake readout API_ with the random number generator set to _persistent_: persistence per **new session**, _not_ per **new tab**).

Important enhancement, thanks again. :)

**Comment by kkapsner** [comment]
You're welcome.
