### ISSUE TITLE
No options in CanvasBlocker with Firefox for Android

### ISSUE THREAD

**Issue by Kolusion** [kkapsner/CanvasBlocker#104]
I am using CanvasBlocker 0.3.5 with Firefox for Android 51.0.2 and I am unable to access options as there is no options button.

**Comment by kkapsner** [comment]
Since I do not have an Android device you have to help me a little bit:
Is the option still mission with the newest version? Which is the latest version where the options are available?

**Comment by rmenessec** [comment]
I can't seem to download a release earlier than 0.3.1. No releases that I'm able to download actually display options. It may be an issue with the e10s support; I see that was added on the just previous release, although I can't download 0.22 to test. I've tested **every** 0.3.x release.

I'm using the Aurora branch; currently 53.0a2; some extensions are unavailable for Firefox for Android in the beta and stable releases, even if compatible, unless all forms of extension version and signature checking in Firefox are disabled. This is now only possible in the Aurora and nightly branches.

**Comment by kkapsner** [comment]
The "EDIT" could point in the direction where the problem lies. Can you please try https://github.com/kkapsner/CanvasBlocker/raw/without-stylePreferencePane/canvasblocker.xpi - this is version 0.3.6 without the modifications I did for the preference pane.

Using Aurora you should be able to install it...

**Comment by rmenessec** [comment]
If I open the link you provided, Firefox simply downloads the XPI. There is no prompt to install the extension.

Unfortunately, it's not possible to install a local XPI that I'm aware of. Mozilla have gone to such lengths to "protect" users from that they forgot to allow developers to install their own addons in the Aurora and nightly Firefox for Android releases.

Firefox for Android does not have a UI equivalent to "Install Add-on From File..." in about:addons. [The official instructions](https://support.mozilla.org/t5/Problems-with-add-ons-plugins-or/Unable-to-install-add-ons-extensions-or-themes/ta-p/1258#w_you-are-asked-to-download-the-add-on-rather-than-installing-it) actually claim that I should install the file by dragging and dropping it.

Like iOS, Android has a single-tasking UI. There's no "dragging and dropping", or at least not between applications.

Do you have an alternate procedure that I can use to install the addon?  The only method I'm aware of at present is to install addons from addons.mozilla.org...

**Comment by kkapsner** [comment]
Then try the following link: http://canvasblocker.kkapsner.de/fennec/

**Comment by spodermenpls** [comment]
I just installed Firefox for Android and CanvasBlocker on my Jolla Phone. It does function according to Browserleaks.com, but I can't display the settings menu (Screenshot: http://www.bilder-upload.eu/upload/91b67c-1487157143.png).
I installed your new version on Nightly (what a pain in the ass the signment crap is), but it did not make any difference (http://www.bilder-upload.eu/upload/964773-1487158011.png). I noticed when you switch from "deactivate" to "activate", the word "Settings" appears for a split second before it vanishes.

**Comment by rmenessec** [comment]
@kkapsner , sorry for the delay. I'm getting the same results as @spodermenpls , although I'm using Firefox on a Google Nexus 6 and the factory ROM.

**Comment by kkapsner** [comment]
Hm... that's bad. I'm using the standard SDK options - nothing special.

It seems that it's that bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1167246
But this should be fixed in version 48...

**Comment by spodermenpls** [comment]
I was able to make the settings appear by clicking the deactivate/activate-button of CanvasBlocker for maybe 15-20 times in a row. On my Jolla Tablet (where I found it out), the settings panel is displayed normally, but on my Jolla Phone it is being displayed about 4 times in a row.
I don't know right now if the add-on functions normally while surfing (includes respecting the made settings), though.

**Comment by kkapsner** [comment]
Thanks for the testing - this is really weird behaviour and really seems to be a Fennec Bug.

... so I have to try to get my hands on a device so I can see this for my own and to get a better understanding what's exactly wrong.

**Comment by rmenessec** [comment]
There are several options for setting up Android emulation. The [Genymotion](https://www.genymotion.com/fun-zone/) project uses VirtualBox to paravirtualize x86 Android on x86 hardware. [The Android SDK](https://developer.android.com/studio/run/emulator.html) appears to use QEMU to emulate a typical ARM Android platform. I've heard good things abut [Andy](http://andyroid.net/). There may be others.

**Comment by spodermenpls** [comment]
Fennec 52.0 didn't solve this issue, unfortunately.

**Comment by rmenessec** [comment]
Fennec 54.0a2 is refusing to display the Addons tab at all—well, the contents thereof—with or without e10s enabled. I'm going to guess that that's a Mozilla issue. 😉

**Comment by spodermenpls** [comment]
I got this issue only with the new 55.0 Nightly version.

**Comment by kkapsner** [comment]
I also think this is a Mozilla issue.

**Comment by spodermenpls** [comment]
With the new Nightly and Release versions, the options are being displayed normally and without problems again, I think this issue is solved for now.

**Comment by kkapsner** [comment]
Great - thanks for testing.
