### ISSUE TITLE
CanvasBlocker broken on Firefox ESR

### ISSUE THREAD

**Issue by evdw87** [kkapsner/CanvasBlocker#105]
I just installed CanvasBlocker 0.3.6 on Firefox ESR 45.7.0 with a clean profile and it no longer works. No matter what setting I use, it just doesn't do anything. Error console shows nothing either. CanvasBlocker 0.3.5 worked fine. I hope you can track it down.

Thanks!

**Comment by kkapsner** [comment]
Actually I forgot to check with ESR...

But the bug is already found and will be fixed in the next version.

**Comment by kkapsner** [comment]
Version 0.3.7 is avaliable - please check if your issue is solved.
