### ISSUE TITLE
"TypeError" warnings in Cyberfox console

### ISSUE THREAD

**Issue by GitCurious** [kkapsner/CanvasBlocker#108]
TypeError: window.wrappedJSObject[object] is undefined

intercept.js:44:11

I do not remember seeing these issues before - is it a problem ?

**Comment by kkapsner** [comment]
Which version of Cyberfox are you using? Does this version support WebGL2? I don't think it should be a problem since WebGL2 should be intercepted as the last object. But "should" is no certainty.

**Comment by GitCurious** [comment]
I guess that was an upcoming fix ? - Thankyou !

**Comment by kkapsner** [comment]
No - I just realized the problem with this issue. The fix just was not complicated.

**Comment by kkapsner** [comment]
Version 0.3.7 is avaliable - please check if your issue is solved.

**Comment by GitCurious** [comment]
Thankyou.

There are no visible errors in the console after updating to v0.3.7

**Comment by kkapsner** [comment]
Great - thank you for checking.
