### ISSUE TITLE
0.3.6: Block mode = ask for readout API permission fails to ask for permission

### ISSUE THREAD

**Issue by flaw19plane** [kkapsner/CanvasBlocker#109]
The issue occurs when uploading add images at marktplaats.nl. [Marktplaats.nl is using plupload.net version 1.5.2](http://s.marktplaats.com/aurora/res/javascript/bower_components/plupload/js/plupload.full.min.js). When uploading images, CanvasBlocker does never ask for permissions, and the plupload javascript code errors out at an exception in:

> Permission denied to access property "code", line 14, col 17290

`catch(c){o.trigger("error",c.code)}}`

Result:
Not uploading images, not any user feedback.

Expectation:
I would have expect CanvasBlocker to ask for permission.

Workaround:
add marktplaats.nl to the CanvasBlocker "White list".

---
Environment:
- Firefox 51.0.1 on Mac OS X
- CanvasBlocker 0.3.6
- White list == Black list == empty
- Other extensions: Noscript, uBlock, Ghostery
- Block mode = ask for readout API permission

**Comment by kkapsner** [comment]
Will be fixed in the next version.

**Comment by kkapsner** [comment]
Version 0.3.7 is avaliable - please check if your issue is solved.

**Comment by flaw19plane** [comment]
@kkapsner Issue is solved.

**Comment by kkapsner** [comment]
Great. Thank you for the feedback.
