### ISSUE TITLE
Firefox ESR white-/blacklist breaks extension

### ISSUE THREAD

**Issue by evdw87** [kkapsner/CanvasBlocker#111]
Testing with Firefox ESR 45.8.0 and CanvasBlocker 0.3.7:

While using brackets on the whitelist (file exclusion) the extension no longer functions.
While using brackets on the blacklist (file inclusion) canvas is disabled.

I used the proposed expression as shown on #101

**Comment by kkapsner** [comment]
The proposed expression in #101 is not for the usual whitelist but for the file specific whitelist. These are different lists.

Since the white-/blacklist accept regular expressions this expression will be translated into a form that will match any domain.

**Comment by evdw87** [comment]
Damn, I feel stupid. Funny enough it worked fine on the regular Firefox. Maybe I overlooked it because there's no option from the notification bar. Also, it might be worth to change the sorting inside the options, but that's just my opinion. Thanks for your quick response!

**Comment by kkapsner** [comment]
No problem.

I agree that the file whiteliste is correlated to the other lists, but I think it's such an expert setting that putting on otp o
