### ISSUE TITLE
Persistence between sessions

### ISSUE THREAD

**Issue by modfixit** [kkapsner/CanvasBlocker#113]
Great plugin, thank you. Persistence between "sessions" (closing FF and reopening) does not seem to work, even with "store persistent data" selected. Persistence during a session does work as expected.

prefs.js does maintain the hash between sessions ("extensions.CanvasBlocker@kkapsner.de.persistentRndStorage", "{\"browserleaks.com\" ...) but it seems it's not being used.

This would be a really great feature to have. Also: you should have a "donate" button somewhere, this plugin is valuable to a lot of us that value security, and while we really like open source software we also know it costs time and money to maintain things like this and would like to help out 👍

**Comment by kkapsner** [comment]
There seems to be a problem with the loading of addons for tabs that are first displayed after start - but only if they are not the first in the tabs list... weird. But I found a solution for it (by accident - it's a workaround for a bug in the SDK...)

But if you refresh the page everything should be fine again.
