### ISSUE TITLE
A sample image only display at second time refresh page.

### ISSUE THREAD

**Issue by plkjny05129** [kkapsner/CanvasBlocker#115]
this sample image which is the last at bottom, it did not display at the first time load webpage, refresh page second time would display the image. use in CanvasBlocker default configure.
http://www.runoob.com/html/html5-canvas.html

**Comment by kkapsner** [comment]
This has nothing to do with CB. This image never displays on the first load. Also when CB is deactivated and even in Chrome - it's a bug on this website.
