### ISSUE TITLE
CanvasBlocker 0.3.7 doesn't work with Firefox 55

### ISSUE THREAD

**Issue by ghost** [kkapsner/CanvasBlocker#116]
Hello

I'm using CanvasBlocker 0.3.7 with Firefox 55 [64bit] on Windows 7 [64bit], and looks like it doesn't work anymore, as going to https://browserleaks.com/canvas, while having set: "readout API" or "block everything", doesn't do anything to protect me from Canvas Fingerprinting.

**Comment by kkapsner** [comment]
This is already known and fixed with 231e33ffb7091001a1de7cf482c5f1ee4563f874
My filed bug was rejected: https://bugzilla.mozilla.org/show_bug.cgi?id=1358807
