### ISSUE TITLE
Canvas Blocker doesnt work with www.msn.com

### ISSUE THREAD

**Issue by winie89** [kkapsner/CanvasBlocker#117]
Hi,

Canvas Block doesn't work with the link: **www.msn.com**
The webpage request to read the REAL Canvas. The "fake canvas" proposed by Canvas Blocker a rejected by msn.com.

**Comment by kkapsner** [comment]
How can I reproduce the problem. If I go to this site everything seems fine - I don't even get a faking notification.

**Comment by winie89** [comment]
Hi,
sorry for the late answer. It work's. I discover that it was a problem with HTTPSEverywhere. Thanks
