### ISSUE TITLE
Listed as experimental --> next step Full Review?

### ISSUE THREAD

**Issue by StealthBlackOxide** [kkapsner/CanvasBlocker#118]
AMO lists CanvasBlocker currently as "experimental". Are there any plans to bring this add-on to "Full Review" stage?
I think it works great so why not try to give more people access to it (better listed in search results etc.). 

Why experimental is inferor to full review according to Mozilla: 
IT COULD:
-Change Firefox preferences without user consent.
-Contain obvious coding errors.
-Conflict with other well-behaved add-ons.
-Use APIs known to cause performance or stability problems.
IT DOESN'T:
-Clearly disclose all user data handling in a Privacy Policy.
-Be easy to use and provide a consistent user experience.
-Appeal to a general audience.

**Comment by AdKiller** [comment]
yes please make it fully reviewed.

**Comment by spodermenpls** [comment]
Is there a particular reason for still listing it as "Experimental"? There may be still room for improvement, but CB clearly has none of the cited attributes of a true "exprimental" extension, as well-seasoned as it is already.

**Comment by kkapsner** [comment]
The reason is that I just never changed it... ;)

I think the webExtension version will by fully reviewed.

**Comment by kkapsner** [comment]
Version 0.4.0 is not fully reviewed.

**Comment by spodermenpls** [comment]
@kkapsner You probably mean "is now fully reviewed", right?

**Comment by kkapsner** [comment]
Ups... yes - corrected it.
