### ISSUE TITLE
This map website hanged with CB

### ISSUE THREAD

**Issue by plkjny05129** [kkapsner/CanvasBlocker#120]
http://gaode.com/place/B001908F04
Block mode use FAKE readout API, view this website, make Firefox hanged and lag, can not move the map.
Normal in use Block readout API.

**Comment by kkapsner** [comment]
I see the problem and it seems that it will be fixed after the switching to webextension. In the meantime you can check if setting the maximal faking size (see #119) helps.

**Comment by kkapsner** [comment]
The next WebExtension does not show the problem. Therefore I will close this issue.
