### ISSUE TITLE
Fake ReadoutAPI breaks material.angular.io

### ISSUE THREAD

**Issue by RoxKilly** [kkapsner/CanvasBlocker#121]
As of June 26 2017, [`material.angular.io`](https://material.angular.io) will fail to load if CanvasBlocker's fake ReadoutAPI is active. Because CanvasBlocker does not notify the user that it has taken action (even with notifications enabled in settings), it is difficult for the user to figure out what's going on.

[Discovered here](https://github.com/ghacksuserjs/ghacks-user.js/issues/156#issuecomment-311034312)

**Comment by kkapsner** [comment]
I think I know why this is happening. But I have to check if I can fix that.
