### ISSUE TITLE
Initialize random number generator on a per site basis

### ISSUE THREAD

**Issue by Joel889** [kkapsner/CanvasBlocker#123]
It would be nice to initialize the random number generator on a per site basis (discarding the old hash once all tabs of that website have been closed for X minutes). That would be a great improvement compared to changing the hash after every canvas call, or having to keep the same hash for the entire browser session.

Thank you

**Comment by kkapsner** [comment]
I already added a new random number generator that will return the same faked data for one page load.
Also the browser session hash is already per domain. So I do not see how this (quite complicated) behaviour could improve the AddOn. It would only add an extra layer of implementation complexity.

**Comment by Joel889** [comment]
> the browser session hash is already **per domain**

Are you referring to an upcoming release, because refreshing this link creates a new hash every time.
[https://browserleaks.com/canvas]()

**Comment by kkapsner** [comment]
You have to use the "persitent" random number generator to get the "per domain" behaviour.
