### ISSUE TITLE
Notification on initial visit only (per browsing session).

### ISSUE THREAD

**Issue by Joel889** [kkapsner/CanvasBlocker#124]
I know the notification bar can be disabled completely, or set to disappear after X seconds, or web pages can be added to a quiet list, which won't show the notification bar anymore. 

Regardless, it would be nice if the notification only shows up once per website per browser session. During casual surfing, the notification can become annoying and people might browse a few pages on a site, but otherwise never visit that website again to justify adding it to the quiet list (there is an extension similar to yours that behaves that way by default, but is not as good as yours otherwise).

**Comment by kkapsner** [comment]
The next verison will have the notifications in a complete different way since WebExtensions do not support them. There will be a little icon in the adress bar that is much less obtrusive.
