### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [kkapsner/CanvasBlocker#126]
Hey @kkapsner 

One thing I am in the process of doing with the ghacks user.js [wiki page for extensions](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Extensions) is to add **Privacy Policy** links (like below). If an extension has one that respects privacy, awesome, if not, no such "badge" (and if it has one one that stinks, it will not be recommended).

Would you be interested in penning up a simple privacy policy like those below - either in a wiki page, a root md, or a "privacy policy" on AMO

* [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) <sup>✔ [Privacy](https://github.com/gorhill/uBlock/wiki/Privacy-policy)</sup> | [GitHub](https://github.com/gorhill/uBlock) << GitHub wiki page example
* [Decentraleyes](https://addons.mozilla.org/firefox/addon/decentraleyes/) <sup>✔ [Privacy](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/privacy/)</sup> | [GitHub](https://github.com/Synzvato/decentraleyes)  << AMO example

Thanks :)

**Comment by kkapsner** [comment]
Good point - added a privacy policy at AMO.
