### ISSUE TITLE
Random generator option - Spoof Tor Browser canvas

### ISSUE THREAD

**Issue by Agglutinator** [kkapsner/CanvasBlocker#128]
Firefox has an option "privacy.resistFingerprinting" in about:config that let it look like Tor Browser.
For that purpose it would be great to have the same spoofed canvas like the Tor Browser

Browserleaks: Your Fingerprint
Signature	✔ A4E1854E
Uniqueness	× False (Tor Browser signature)

Panopticlick:
Hash of canvas fingerprint 	a273d6a847f0e2a57fa0161158f12fed

Would it be possible to add a persistent option, so it will behave always like this?

**Comment by kkapsner** [comment]
This is a duplicate to #125 - and for the same reasons this is rejected.

But if you want the behaviour with thie native Firefox setting, why are you not using this setting?

**Comment by Thorin-Oakenpants** [comment]
@Agglutinator 
privacy.resistFingerprinting is not to make users look like TBB .. it's to help make the subset of Firefox users who enable this pref to have the same (enforced) values for FP probes - thus creating significant numbers in order to make said combined `FP`<sup>1</sup> values useless (lower entropy) . It is also to reduce code changes/differences between FF ESR and TBB (tor uplift project).

<sup>1</sup> The `FP` being a set of values derived from many "attacks", every changing and evolving

> Browserleaks: Your Fingerprint
Signature ✔ A4E1854E
Uniqueness × False (Tor Browser signature)

^^ THIS means exactly jack sh*t :) The derived signature is destroyed if another value is added - many of which will unmask your browser anyway.

**Comment by concatime** [comment]
Up. I think it’s a good idea to add a default hash of canvas fp. If more people share the same hash, the usefulness of this method will decrease. This way, TorBrowser users can "hide" into the mass with people using `privacy.resistFingerprinting` or this add-on.

**Comment by kkapsner** [comment]
If you want to hide in the "masses" you can still use RFP and CB in parallel: have RFP be the first line of defence and let CB protect the instances where you have to allow a page.

**Comment by concatime** [comment]
Well, yes.. but no. Using `privacy.resistFingerprinting` will force a value of user-agent with "Windows NT" in it, but does NOT change the platform accordingly. Worse, it locks the platform to `Linux x86_64`. So setting `general.platform.override` to `Win32` does not work.
> Changing the user agent without changing to a corresponding platform will make your browser nearly unique.

[Source](//wiki.archlinux.org/index.php/Firefox/Privacy#Change_user_agent_and_platform).
I know, this is a bug in firefox, but it takes too much hassle to report.

**Comment by kkapsner** [comment]
Did you try to set the navigator properties with CB and RFP?
In CB you should be able to set all properties.

**Comment by concatime** [comment]
Set the navigator properties to what? How can this tackle firefox’s bug? In CB, which properties?
I do not understand your comment. Maybe it’s just me. If so, I’m sorry.

**Comment by kkapsner** [comment]
CB has functionality to set the navigator properties:
![image](https://user-images.githubusercontent.com/1105157/59122538-50139280-895b-11e9-9ba4-35f837c940fb.png)
This should allow you to set a consistent set of properties.

**Comment by concatime** [comment]
Works like a charm :)

**Comment by kkapsner** [comment]
Great. Finally a second use case for the navigator protection (first was to hide the used OS in these settings - spoofing the navigator to disguise as a different browser brand is in my opinion pointless).
