### ISSUE TITLE
Please explain Show calling logfile and Display complete calling stack options

### ISSUE THREAD

**Issue by vawael** [kkapsner/CanvasBlocker#13]
Hi,

I really like your plugin, but it seems like some pages stop working, when it's activated, even when I try different block modes. With the latest version (0.1.4) I don't even seem to get the pop ups to appear anymore. Now I was wondering how the settings Show calling logfile and Display complete calling stack are working in order to get an idea what's going on on those pages.

Unrelated to this, I assume any changes in the preferences are applied right away, i.e. as soon as I change something and re-load a webpage, the new settings come into effect, is this correct?

Thank you and best regards,
vawael

**Comment by kkapsner** [comment]
These two options show you the position of the code in the JS-files that tried to call the API. If you are not familiar with JS and a little bit reverse engeneering you will have a tough time to figure out what's going on.

Can you tell me an example of a page that stopped working and where you do not get a pop up. If you chose one of the "ask for permission" modes you should always get a pop up.

Yes, the changes are applied right away. Sometimes you do not even have to reload the page... but these cases are rare.
