### ISSUE TITLE
New update on 0.4.0.1 - WebGL Image Hash

### ISSUE THREAD

**Issue by qingmui** [kkapsner/CanvasBlocker#136]
When I use the old version: 0.3.8 Release.
Test From Browserleaks.com
The WebGL Image hash info is also changed every time. (Which I guess that is good)
With the new version, the WebGL image hash info is not changed.

Are there any reason why you change that?
Thanks

**Comment by kkapsner** [comment]
The reason is: it's a bug... introduced by the hotfix 0.4.0.1

**Comment by kkapsner** [comment]
Hotfix 0.4.0.2 is out, which solves the problem.
