### ISSUE TITLE
Block everything breaks Twitter web links

### ISSUE THREAD

**Issue by Daisenki** [kkapsner/CanvasBlocker#137]
The setting block everything breaks the Twitter web timeline, it removes the links to YouTube or others websites inside tweets. Issue happens in version 0.4.0.0-0.4.0.2, but not in version 0.3.8.

With block everything:
<img width="458" alt="1" src="https://user-images.githubusercontent.com/22057956/31431513-42d1e90a-ae74-11e7-8aa6-e753d9d8f709.PNG">

With block readout api:
<img width="450" alt="2" src="https://user-images.githubusercontent.com/22057956/31431534-556c916e-ae74-11e7-8141-6cf7137d660f.PNG">

```
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive. (unknown)
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead. (unknown)
TypeError: 'canvas' called on an object that does not implement interface CanvasRenderingContext2D. modifiedAPI.js:272:10
Loading failed for the <script> with source “resource://support-at-lastpass-dot-com/data/pageWebRequestEvents.js”.  917994135176478720:1
Loading failed for the <script> with source “resource://support-at-lastpass-dot-com/data/pageWebRequestEvents.js”.  918021685042974720:1
```

```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead. (unknown)
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive. (unknown)
Loading failed for the <script> with source “resource://support-at-lastpass-dot-com/data/pageWebRequestEvents.js”.  twitter.com:1
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.  twitter.com:1
TypeError: 'canvas' called on an object that does not implement interface CanvasRenderingContext2D.  modifiedAPI.js:272:10
Loading failed for the <script> with source “resource://support-at-lastpass-dot-com/data/pageWebRequestEvents.js”.  917786751518855168:1
```

**Comment by Daisenki** [comment]
Browser Console:
`Use of nsIFile in content process is deprecated.  NetUtil.jsm:307:12
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/903523724326039552/aF40OnXA_normal.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/915671359832969216/4BmiP0i8_normal.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/782855977506902016/yXPi2L6L_normal.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/804398447440891905/Jhk5TTwe_normal.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/908428548439990273/-t5L1xu7_normal.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/914884332661112832/P62EIluM_normal.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/877863149155876864/eMt4_b5O_normal.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/782855977506902016/yXPi2L6L_bigger.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/798456037724618752/j5JkGlYj_bigger.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://pbs.twimg.com/profile_images/912348913943924736/lSu2VWBr_bigger.jpg”  main.js:143
Rejecting HTTP Referer “https://twitter.com/JMaxBlank/status/917782514722312193” for “https://abs.twimg.com/k/de/7.pages_permalink.de.9188cc40fd4f1f8125a9.js”  main.js:143
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:304
TypeError: sourceMap is undefined  worker.js:847:61
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.  (unknown)
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
Rejecting HTTP Referer “https://twitter.com/i/cards/tfw/v1/917782514722312193?cardname=summary_large_image&autoplay_disabled=true&earned=true&edge=true&lang=de&card_height=344&night_mode=true&scribe_context=%7B%22client%22%3A%22web%22%2C%22page%22%3A%22home%22%2C%22section%22%3A%22permalink_overlay%22%2C%22component%22%3A%22tweet%22%7D&bearer_token=AAAAAAAAAAAAAAAAAAAAAPYXBAAAAAAACLXUNDekMxqa8h%252F40K4moUkGsoc%253DTYfbDKbT3jJPCEVnMYqilB28NHfOPqkca3qaAxGfsyKCs0wRbw” for “https://ton.twimg.com/tfw/css/native_bundle_v1_9f4963f8598a2de0325b71660fc42ddb9c34cbe0.css”  main.js:143
Rejecting HTTP Referer “https://twitter.com/i/cards/tfw/v1/917782514722312193?cardname=summary_large_image&autoplay_disabled=true&earned=true&edge=true&lang=de&card_height=344&night_mode=true&scribe_context=%7B%22client%22%3A%22web%22%2C%22page%22%3A%22home%22%2C%22section%22%3A%22permalink_overlay%22%2C%22component%22%3A%22tweet%22%7D&bearer_token=AAAAAAAAAAAAAAAAAAAAAPYXBAAAAAAACLXUNDekMxqa8h%252F40K4moUkGsoc%253DTYfbDKbT3jJPCEVnMYqilB28NHfOPqkca3qaAxGfsyKCs0wRbw” for “https://ton.twimg.com/tfw/js/native_bundle_v1_cbb8f51aebf841a9ca5f1e1939a5f5c3d49d7c70.js”  main.js:143
TypeError: can't access dead object  tab.js:1641:1
TypeError: 'canvas' called on an object that does not implement interface CanvasRenderingContext2D.  modifiedAPI.js:272:10
Loading failed for the <script> with source “resource://support-at-lastpass-dot-com/data/pageWebRequestEvents.js”.  917782514722312193:1
Rejecting HTTP Referer “https://twitter.com/i/cards/tfw/v1/917782514722312193?cardname=summary_large_image&autoplay_disabled=true&earned=true&edge=true&lang=de&card_height=344&night_mode=true&scribe_context=%7B%22client%22%3A%22web%22%2C%22page%22%3A%22home%22%2C%22section%22%3A%22permalink_overlay%22%2C%22component%22%3A%22tweet%22%7D&bearer_token=AAAAAAAAAAAAAAAAAAAAAPYXBAAAAAAACLXUNDekMxqa8h%252F40K4moUkGsoc%253DTYfbDKbT3jJPCEVnMYqilB28NHfOPqkca3qaAxGfsyKCs0wRbw” for “https://pbs.twimg.com/card_img/917639187003789312/odH9zZvc?format=jpg&name=600x314”  main.js:143`

**Comment by kkapsner** [comment]
I can reproduce your problem and will fix it.
