### ISSUE TITLE
blemish in all flip-menu

### ISSUE THREAD

**Issue by Ropeclimber** [kkapsner/CanvasBlocker#138]
Hello,
first thank you for the greatful addon.
I am detect a blemish in all flip-menu.
The choice opens not under itself direct
but some centimeters further down.
Version 0.4.0.2 with FF 56.0 & FF 570b7 
I hope, i describe for understanding.

Greetings

**Comment by kkapsner** [comment]
I am not able to reproduce the problem on FF 56.0.1 - but I know it's broken in FF 57 (nightly) for a while. This is a Firefox bug that also affects other Addons.
Since I'm just using standard HTML-Elements here there is unfortuantelly nothing I can do to fix this.
