### ISSUE TITLE
Time limit on Persistent Random Number Generator

### ISSUE THREAD

**Issue by Joel889** [kkapsner/CanvasBlocker#139]
Instead of flushing the persistent random number generator upon closing/starting FF, perhaps there could be an advanced setting to stipulate a time limit. This would be useful if FF isn't frequently restarted. 

Perhaps one way to implement this feature would be by saving the timestamp when the persistent random number generator was last initiated and flush it after x days. If FF is restarted frequently then nothing would change since the timestamp would get overwritten.

**Comment by kkapsner** [comment]
Seems like a reasonable idea - let's see when I have time to impement it.

**Comment by OdinGitDat** [comment]
I was about to request this feature, but I thought that the persistent option made the canvas actually persistent across multiple sessions/reboots. If that is not the case then what does the 'store persistent data' option do?

**Comment by kkapsner** [comment]
If you use the persistent random number generator and set the "store persistent data" flag the "random" data is stored across reboots. If you don't it is only for this session.

**Comment by OdinGitDat** [comment]
Okay that makes sense. Maybe you should clarify that a bit further in the settings. Although I would like to have more control over when the persistent data is flushed.

**Comment by kkapsner** [comment]
I will add a sentence to the description.
For the control: what are you thinking of exactly?

**Comment by OdinGitDat** [comment]
Well, basically what Canvas Defender [has](https://dl.dropboxusercontent.com/s/5c54bd36t93hj04/firefox_2017-11-02_20-56-54.png).

**Comment by Joel889** [comment]
> For the control: what are you thinking of exactly?
Why not allow the user to enter a value. Perhaps a numeric textbox, followed by a drop down menu to specify the unit (Minutes, Hours, Days).
