### ISSUE TITLE
Action taken when declining permission prompt

### ISSUE THREAD

**Issue by jstetten** [kkapsner/CanvasBlocker#142]
Great add-on.

If I use either the `ask for readout API permission` or `ask for permission` options, what happens when I _decline_ permission to a site? Is the canvas API blocked (as I assume) or is it spoofed?

It would be nice to only allow some sites API access on-the-fly and spoof all the rest, so users could combine the benefits of both modes.

What do you think?

**Comment by kkapsner** [comment]
When the permission is declined, the API is blocked.

So you mean the question should be between allowing and spoofing (faking)? Also hard set like it is now or changeable via a setting?
