### ISSUE TITLE
Not compatible with firefox ESR (52.4)

### ISSUE THREAD

**Issue by c33s** [kkapsner/CanvasBlocker#143]
as mozilla decided to realy break things and kill very good addons the only way to keep that good addons is to downgrade to firefox ESR which is version 52.4.

it would be good to have access to a version which is compatible with ESR in a more prominent way than the well hidden https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/versions/

even i think its mozillas fault, that they don't detect a correct version of your addon on their addon page.

also it would be good to backport major features to the old version. i think with the release of ff57 more people will switch to ff esr

**Comment by nhantrn** [comment]
+1

**Comment by kkapsner** [comment]
Technically the current version is compatible with FF 52.4 - but practically the user defined settings are not working and therefore I could only provide a version with fixed settings.

For backporting I just do not have the time to do it.

**Comment by c33s** [comment]
what about using `about:config`? so you can define "fixed" settings but if someone wants to config something it is at least not a hardcoded string somewhere in the extension.

**Comment by kkapsner** [comment]
WebExtensions do not have access to about:config-settings.

But it seems there has been some change in the latest ESR 52.4.1 (and the next version of CB will also have changes in the settings management)  - most of the settings seem to work. So I will set the minimum version of FF to 52.4.1

**Comment by c33s** [comment]
> WebExtensions do not have access to about:config-settings.
i think mozilla failed with this webestensions step. -.-

@kkapsner thank you for your effort porting your extension to a webextension.

**Comment by kkapsner** [comment]
I'm not sure if the step was wrong - but it was surely executed bad.

**Comment by kkapsner** [comment]
Version 0.4.1 is out and should be reviewed soon by Mozilla.
