### ISSUE TITLE
Could become obselete with Firefox 58(?)

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#144]
Reading [this article](https://nakedsecurity.sophos.com/2017/10/30/firefox-takes-a-bite-out-of-the-canvas-super-cookie/) it seems your add-on could become obsolete…

I am not yet sure, whether it will be activated by default in Firefox 58 (or only when `privacy.resistFingerprinting` is set to true), but at least the basic functionality could become obsolete…

If you want to continue the add-on, because it has some more methods for canvas blocking (e.g. including spoofing, etc.) you should at least ensure, that it works correctly with `privacy.resistFingerprinting=true`, respectively with canvas being handled by Firefox naively.

**Comment by kkapsner** [comment]
It's a sort of "ask for permission" - but with reload required. So the addon still provides useful features - especially the faking mode.

Despite the fact that this feature is not quite working 100% CB seems to work fine with it.

**Comment by EchoDev** [comment]
@kkapsner What would you recommend. If Firefox asks to allow the site to access the canvas image data should we always allow it and rely on on CB or should we block it?

If you block the access (This is by default and does not require a reload of the page) in Firefox your signature shows up as A4E1854E (Tor Browser signature).

**Comment by rugk** [comment]
Indeed, resistFingerprinting does much more than just asking about about canvas, it spoofs your user agent, it sets your system time to UTC when asked by websites, etc.
So it can certainly break websites.
