### ISSUE TITLE
Add to Chrome webstore

### ISSUE THREAD

**Issue by vlldk** [kkapsner/CanvasBlocker#145]
Can you add this to the Chrome webstore? It's an webextension so should be fine right?

**Comment by kkapsner** [comment]
No - it will not run in Chrome as exportFunction is missing there: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#Sharing_objects_with_page_scripts

**Comment by vlldk** [comment]
Noo! :( is there a workaround?

**Comment by kkapsner** [comment]
I don't think so. No in a reasonable way.

**Comment by kkapsner** [comment]
Here is the new link: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Sharing_objects_with_page_scripts

**Comment by Morrigan-Ship** [comment]
Please add chrome version
