### ISSUE TITLE
Page action not always showing

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#149]
Some pages might confuse the page action display (e.g. https://www.adidas.it/). It is only shown briefly and then hidden.

**Comment by kkapsner** [comment]
This is due to iframes that are loaded afterwards... this page is kind of a mess.

**Comment by return42** [comment]
Hi @kkapsner, I'am asking for reopen this issue. I found a strange behavior, may be I'am totally wrong: when vistiing https://www.adidas.it/ I can see the Page-Action icon. But if I visit https://multiloginapp.com which also uses Canvas FP the Page-Action icon is not shown. I'am using 0.4.3c, same behavior with the current 0.4.4alpha20171219.

**Comment by kkapsner** [comment]
How do you know they use a canvas fingerprint?

**Comment by return42** [comment]
Hi @kkapsner, thanks for taking time. 

> How do you know they use a canvas fingerprint?

Using block mode 'ask for permission' a dialog pops up.

**Comment by kkapsner** [comment]
Ah... yes they use the canvas-API. But they do not use the readout API. If you switch to "ask for readout permission" not dialog pops up.
Therefore nothing has to be faked.

**Comment by return42** [comment]
> But they do not use the readout API

Ah, OK that's my mistake .. thanks for clarifying!

**Comment by kkapsner** [comment]
No problem. Better ask once too much than once to less.
