### ISSUE TITLE
Issue on Firefox ESR

### ISSUE THREAD

**Issue by iripu** [kkapsner/CanvasBlocker#151]
Fake readout notifications does not show on ESR version 52. May be latest versions does not work with Firefox ESR any more.

**Comment by DaarkWel** [comment]
Same here, Firefox 52.5.0 ESR, Linux.
Also, it kinda breaks direct link images via https, like https://occlub.ru/images/posts/news/2016/09/27/AMD-AM4-Chipset-1.jpg

**Comment by kkapsner** [comment]
This is weird. It's working for me with 52.5.0

Please create a fresh profile and test with only CB added. If the problem still exists please post your settings here (there is a new settings export button in the options page - you have to activate expert mode to see it).

**Comment by DaarkWel** [comment]
ok, on new profile there's no problem with direct link https' images, perhaps it's some of my other addons or preferences.

But there's still no notifications.

{
	"logLevel": 1,
	"whiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1510752661985,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"isStillDefault": false,
	"storageVersion": 0.2
}

**Comment by kkapsner** [comment]
On which URL did you check the notifications?
Do you see a notification on http://kkapsner.github.io/CanvasBlocker/test/test.html

**Comment by DaarkWel** [comment]
I just notice — I see a "fingerprint" icon on urlbar, and an info bubble if I click it. Is it notification? Should it be "auto-pop-uped" on page load (not that I need it)? On earlier versions of CanvasBlocker notification was completely different and I didn't notice changes. Sorry :)

**Comment by scarf** [comment]
i have this issue too with firefox esr 52.5.0 64-bit linux.  also direct links to videos don't play either.  as soon as i disable canvas blocker and reload the image/video, it displays properly, so it is strange to hear about DaarkWel's comment that a new profile with CB enabled also works.... perhaps it is a conflict with another add-on?

**Comment by kkapsner** [comment]
Please give me the URLs to the images/videos you have problems with and your settings (export - see above). Then I might be able to sort this problem out.

About the clearing out. This is a good idea to have a "factory reset" button. I think I will include one in the next release. For the time being you could delete the json-file for the addon in your profile folder.

**Comment by scarf** [comment]
Well for example the image in the second post still doesn't display.  I couldn't find the json-file for the addon in my profile folder, there are several json files but none seem to be related to CB.  Is there a specific way to find it?
The current settings are below.
 Thanks

```
{
	"logLevel": 1,
	"whiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1511128332635,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"isStillDefault": false,
	"storageVersion": 0.2
}
```

**Comment by kkapsner** [comment]
Also with these two addons installed I'm not able to reproduce your problem. Are there any related errors in the browser console?

**Comment by scarf** [comment]
Well what the heck.
 i see this message whether or not CB is enabled:
```
19:45:32.993 Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'unsafe-eval' * blob: data:”). Source: (function (ERROR) {

    const V8_STACK_.... 1 AMD-AM4-Chipset-1.jpg:1
```

**Comment by DaarkWel** [comment]
Yea, I also narrowed it down to CB and uBlock Origin. With both this addons enabled — no "direct" images. And in browser console just

`GET https://occlub.ru/images/posts/news/2016/09/27/AMD-AM4-Chipset-1.jpg [HTTP/1.1 200 OK 1985ms]`

**Comment by kkapsner** [comment]
@scarf: this error message is definitely not produced by CB.
@DaarkWel: can you please test on a new profile with only CB and uBlock installed? I'm not able to reproduce the problem.

**Comment by DaarkWel** [comment]
On new profile with only CB and uB — it's OK. Then I copied prefs.js from old profile to new — no images. And then I restored original prefs.js in new profile — still no direct images. Weird. Not sure it CB issue but disabling CB instantly makes direct images "loadable&visible".

I'll make new profile with all my addons and preferences and will try there but it'll take some time.

**Comment by kkapsner** [comment]
Thanks for your effort. Please let me know which setting causes the problem.

**Comment by Thorin-Oakenpants** [comment]
I'm 99% sure this is the same issue I had re the emoji items not showing - remember that kkapsner (see https://github.com/kkapsner/CanvasBlocker/issues/127#issuecomment-334918368 )

In the end I changed to block (rather than fake) and was going to readdress it after I upgrade to FF57 and have zero legacy addons (almost there!!) - because there have been so many weird side-effects from mixing legacy+non-legacy. That said I have zero legacy addons that modify content, incoming or outgoing, and it still persists.

--side note--
I keep getting console errors - 2 instances of this error on every web page load

> XML Parsing Error: syntax error
Location: jar:file:///D:/Portable/FirefoxPortable/Data/profile/extensions/CanvasBlocker@kkapsner.de.xpi!/releaseNotes.txt
Line Number 1, Column 1:  releaseNotes.txt:1:1

When I disable Canvas Blocker, I get these two errors
> No matching message handler for the given recipient. MessageChannel.jsm:634
> Error: WebExtension context not found! ExtensionParent.jsm:778:13

When I enable CB, I get these two errors
> XML Parsing Error: syntax error
Location: jar:file:///D:/Portable/FirefoxPortable/Data/profile/extensions/CanvasBlocker@kkapsner.de.xpi!/releaseNotes.txt
Line Number 1, Column 1:  releaseNotes.txt:1:1
> TypeError: can't access dead object[Learn More] (unknown)

^^ does anyone else get these?

**Comment by kkapsner** [comment]
I think with the current "a" and "b" versions this issue is solved.

If someone of you still encounters some problems with Firefox ESR (52) they can reopen this issue.
