### ISSUE TITLE
0.4.2 causes audio player to not display or work correctly

### ISSUE THREAD

**Issue by Ass9999** [kkapsner/CanvasBlocker#152]
This is on Firefox 52. The latest version 0.4.2 causes the Firefox audio player to not display or work correctly. For example, go to Windows Explorer and drag an .mp3 file into Firefox. The audio player for this local file isn't right, unless reverting to the previous version of this add-on.
If it's intended, whitelisting is unknown. "C:" isn't quite a website to add to the list.

**Comment by kkapsner** [comment]
I'm not able to reproduce your problem. Which specific version of Firefox are you using? 32 or 64 bit? Which Windows are you on?
Can you give me a screenshot what's wrong?

**Comment by Ass9999** [comment]
Thank you for your answer. About Firefox says "Firefox ESR 52.5.0 (64-bit)." It's on 64-bit Windows 10. I'm sorry but the problem was in part exaggerated by a theme I that have. Without it, the different is just a box-shadow that appears to be on your end, as changing between CanvasBlocker versions changes it up, and I don't think anything else should be affecting it. Because the difference is what it is, you might not have noticed it and thought it was normal. On top of the image is how Firefox really is, on the bottom is what CanvasBlocker causes it to become.
![comparision](https://user-images.githubusercontent.com/33493741/32952500-67ffba56-cba5-11e7-9c9e-c56688213f03.png)

**Comment by kkapsner** [comment]
I'm still not able to reproduce the problem. Can you please post your settings (export settings button in the expert mode).

**Comment by Ass9999** [comment]
{
	"logLevel": 1,
	"whiteList": "",
	"blackList": "",
	"blockMode": "blockReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1510947453474,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"isStillDefault": false,
	"storageVersion": 0.2
}

**Comment by kkapsner** [comment]
Are you using 32- or 64-bit? I still cannot reproduce...

**Comment by Ass9999** [comment]
64-bit. Oh well, never mind it then. It's hard to say exactly how it's happening anyway,

**Comment by kkapsner** [comment]
OK... weird problem.
