### ISSUE TITLE
Site detects CanvasBlocker and recognizes 'fake readout API' mode

### ISSUE THREAD

**Issue by sacrileger** [kkapsner/CanvasBlocker#153]
It would appear that this site in particular:
https://textfree\.us/#/login$
is detecting CanvasBlocker and unless the site (textfree) is whitelisted which allows it to take a perfect fingerprint, it does not work.  It recognizes "fake readout API" mode and disables login functions.  What is the workaround?  If there is one at all?

(linux mint, firefox 57 (64-bit))

**Comment by kkapsner** [comment]
Can please give me your settings ("export settings" in expert mode at the bottom)?

**Comment by spodermenpls** [comment]
The login page seems to work fine on my end (despite a faked readout), even though I don't have an account to successfully login with. What does "disables login functions" mean in detail?

**Comment by sacrileger** [comment]
@kkapsner , here are the canvasblocker settings.
{
	"logLevel": 1,
	"whiteList": "^https://textfree\\.us/#/login$",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1510882381905,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"isStillDefault": false,
	"storageVersion": 0.2
}

**Comment by sacrileger** [comment]
@spodermenpls , the actual login fails unless "textfree.us" is whitelisted. 
sorry for the confusion.

**Comment by kkapsner** [comment]
I looked into this site and it seems that they really try to detect canvas faking. (Or maybe it's some sort of bot detection...) You could try to use the file specific white list - or you wait until the next version where you will be able to set the fake mode per site (fake input could be a good choice for this site).

**Comment by kkapsner** [comment]
@sacrileger: please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3-Beta.3 and add a URL specific block mode for this page.

**Comment by sacrileger** [comment]
@kkapsner : I  disabled the CB 0.4.2, installed the beta 0.4.3.beta.3 and found a new field = "site specific settings" and noticed there is no white list field, just .  I typed in the URL which tests for canvas blocking.  Are there any additional parameters or specific settings?

**Comment by kkapsner** [comment]
The white and black lists are hidden but still present (you can modify your settings in the settings export). Just enter the domain of the page in the field, click "+" and then you can specify the block mode. A dot alone will not match anything. It should look something like this:
![grafik](https://user-images.githubusercontent.com/1105157/33859559-c4d831d0-ded4-11e7-86e7-450ac19677b3.png)

You can also just whitelist the domain in the notification.

**Comment by sacrileger** [comment]
@kkapsner : is there any chance the beta version is still reading the hidden whitelist from the disabled release version?  The beta version appears to behave exactly the same way as the release version.  I tried to force some output via URL specific 'notifications'  - that did not work... no notifications were shown.  How do I force output into a debug log file?

**Comment by kkapsner** [comment]
In your Firefox profile folder there is a folder called browser-extension-data where you find a folder for each extension. You can simply copy the storage.js to the beta (Firefox should be closed...).

PS: the notification is just a simple icon in the address bar (kind of a fingerprint) that only appears when something is faked: ![pageaction](https://user-images.githubusercontent.com/1105157/33876231-3621b230-df25-11e7-9e48-b49fec6c7f4e.png)

**Comment by sacrileger** [comment]
@kkapsner : thank you.  I get "API blocked on textfree.us because CanvasBlocker-settings were not loaded in time (1)." notification.   I tried again by closing the browser and restarting.  Same result.

**Comment by kkapsner** [comment]
Hm... that's bad and weird because it is working for me. Can you please try on a fresh Firefox profile?


The topic of WebExtension and settings is a nightmare... this new message was introduced due to #160 and #163. Since this issues only affect FF ESR (52) maybe I should provide two versions: one for ESR and one for 57...

**Comment by sacrileger** [comment]
@kkapsner : I will try a fresh profile today. I am using FF 57.0.1.
  Meanwhile, the same notification appears on http://blackburnnews.com/ with my current setup.

**Comment by kkapsner** [comment]
At blackburnnews it's the same code as on #147 - some emoji-Code from WordPress... so nothing I would care about.

**Comment by sacrileger** [comment]
@kkapsner : i've tested the CB beta thoroughly with a fresh profile with no installed add-ons other than adblock, noscript and CB.  I got no  "API blocked on "...." because CanvasBlocker-settings were not loaded in time" notifications on either page (textfree.us or blackburnnews.com).

I tested four (login/no login) scenarios with 'site specific settings'.  Here are the results:

1. fakereadout - no login
2. blockreadout - no login
3. fake at input - login
4. ask for readaout API permission - no login unless allowed

since "refusing readout API" is clear, would you please explain why 'fake at input' achieves login and the other two scenarios dont?

**Comment by sacrileger** [comment]
@kkapsner , btw, now that I am more alert to what CB does, I noticed that mostly sites I visited and were created by WordPress generated the  "API blocked on "...." because CanvasBlocker-settings were not loaded in time" notification.

**Comment by kkapsner** [comment]
I created a new version (0.4.3b) which should solve your problem and provide a way to specify the block mode URL specifically.
