### ISSUE TITLE
Panopticlick says my canvas fingerprint is unique...

### ISSUE THREAD

**Issue by h-2** [kkapsner/CanvasBlocker#154]
... although I am using CanvasBlocker. I am doing something wrong?

Firefox 57.0
FreeBSD11

Also in use: uBlock Origin, User Agent Switcher, Disconnect

**Comment by kkapsner** [comment]
It's totally fine to have a unique fingerprint - as long as it changes. That's the point of the fake readout (with the non persistent rng) providing different fingerprints everytime they are generated.

**Comment by h-2** [comment]
Ah, ok, that's good to know! So the plugin just seeds some randomness into Canvas and also GL contexts?
If this doesn't break anything else, why doesn't Firefox do it by default?

**Comment by kkapsner** [comment]
What the addon does depends on the settings. But the default settings just add some randomness.

I understand why Firefox does not do that by default. Some legitimate applications need predictable canvas without any randomness. That's why this addon also has a whitelist.

**Comment by macgeekpro** [comment]
Sorry for opening this issue again. Just want to confirm that if I run the canvas test conducted at Panopticlick, it says my browser has a unique fingerprint  but if i run the same test at https://browserleaks.com/canvas, it says my browser's uniqueness is false. All tests are run w/ default configs. Am I being protected correctly? Screenshots of the test results below:

[result from browserleaks](https://imgur.com/ONVUcQi)
[result from Panopticlick](https://imgur.com/rq2qhoy)

**Comment by andreasaba68** [comment]
Hi there I have just done a similar test, panopticlick shows exactly the same fingerprint, even if I restart the browser, clean cookies & co, and open a private session. Win7 Home Premium FF 63.0.3 (64-bit), WebGL disabled, let me know if I can provide more infos
