### ISSUE TITLE
XML Parsing Error: syntax error +

### ISSUE THREAD

**Issue by GitCurious** [kkapsner/CanvasBlocker#155]
Hello KK,

since version 0.4.2 I am seeing regular entries in the console, like this:

**XML Parsing Error: syntax error
Location: jar:file:///E:/Waterfox/extensions/CanvasBlocker@kkapsner.de.xpi!/releaseNotes.txt
Line Number 1, Column 1:**

and...ones like this for all visited sites:

**Security Error: Content at https://github.com/kkapsner/CanvasBlocker/ may not load or link to moz-extension://9c8264de-61a0-4ef5-b777-b285adefa569/releaseNotes.txt.**

I do not know if these _new_ console events are "real" errors or just informative messages that can be ignored.

If I revert to version 0.4.1 the console is quiet with no messages triggered by CanvasBlocker

[waterfox 55.2.2]

**Comment by kkapsner** [comment]
I'm already aware of the first error. It is not really an error/problem but I will try to get rid of it.

The second one is kind of new to me - but I think it has the same root.

**Comment by kkapsner** [comment]
OK - I also get the second one. Let's see what I can do about it.
