### ISSUE TITLE
Release notes spam stops other addons from injecting on browser launch homepage.

### ISSUE THREAD

**Issue by ceribik** [kkapsner/CanvasBlocker#156]
See the following issue for more details:

https://github.com/gorhill/uBlock/issues/3253

I was getting a lot of repeated errors (about 50) when starting my browser with this addon enabled. Note that I only have about 10 homepages. I didn't copy down the exact error but it was to do with launching the release notes. 

This was preventing other addons (e.g. uBlock) from injecting into homepages on browser launch. By toggling this extension off and on again, it stopped the error spam and fixed this issue.

**Comment by kkapsner** [comment]
I got rid of the error message in #155. But maybe we still have a problem here. I will have to investigate the problem further. It might be a deeper problem.

**Comment by kkapsner** [comment]
Can you please try the new beta: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3-Beta.1

**Comment by kkapsner** [comment]
I think it is the same issue than #160.
There is a new beta: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3-Beta.3

Please confirm.

**Comment by ceribik** [comment]
I stopped using the addon so I can't help sorry.

**Comment by kkapsner** [comment]
OK.
