### ISSUE TITLE
fake Fingerprinting  or block doesn't work on these test why?

### ISSUE THREAD

**Issue by skyerjoe** [kkapsner/CanvasBlocker#157]
I found an german Test on an fingerprint which the addon fails by either fake or block fingerprint.

Could someone explain me why ? : 
http://www.browsercheck.pcwelt.de/fingerprint

regards skyerjoe

**Comment by kkapsner** [comment]
This page does not use the canvas fingerprinting technique. Therefore this addon does nothing on this site. It uses the user agent, your screen definition, timezone, some browser capabilities and your plugins
