### ISSUE TITLE
Cyberfox x64 - clash with addons

### ISSUE THREAD

**Issue by marzametal** [kkapsner/CanvasBlocker#16]
Hi... 
I run Cyberfox 64bit with a handful of addons. One of them is Random Agent Spoofer - 
https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/

I run into an issue with RAS, it offers spoofing of time zone and screen resolution. After creating a fresh profile, adding RAS and then adding my addons back 1 by 1... I have confirmed that CanvasBlocker clashes with time and resolution spoofing.

...just thought I'd mention it, maybe there can be a workaround/tweak worked out between the developers. Any feedback would be great too. Thanks!

**Comment by kkapsner** [comment]
What do you exactly mean with "clashes"?
Can you give me a "step by step" to reproduce the problem?

**Comment by marzametal** [comment]
Thanks for your reply...

When I installed a clean Cyberfox profile, the first thing I did was install RAS. I used the Panopticlick website to test out results. The spoofed time zone and screen resolution showed up perfectly on the site. I added the rest of my addons 1 by 1 and they did not affect the spoofed time zone and screen resolution.

After I added CanvasBlocker, and checked Panopticlick, my "real" time zone and screen resolution showed instead of the spoofed results. I disabled CanvasBlocker, restarted Cyberfox and checked time zone and screen resolution again, and the spoofed results were back.

It tried fresh again, new profile. This time I only installed RAS and CanvasBlocker. Before CB, spoofed time zone and screen resolution showed up on Panopticlick. After CB, spoofed results disappeared, real results displayed.

**Comment by kkapsner** [comment]
Thank you for the detailed instruction.

I can not reproduce the problem neither in Firefox 35.0 nor in Cyberfox 35.0.
Which operating system are you using?

**Comment by marzametal** [comment]
I figured out what was causing this, I am stupid. :)
I am using your addon for canvas blocking, however I also enabled canvas blocking in the other addon. All is well now that I disabled the other tickbox. Sorry for the dramas!

**Comment by kkapsner** [comment]
No problem.
