### ISSUE TITLE
Detects the canvas and webGL spoofing

### ISSUE THREAD

**Issue by madflash001** [kkapsner/CanvasBlocker#162]
The site fp.whatleaks.com (need registration) detects the canvas and webGL spoofing.
Login -> New fingerprint -> Look at "Canvas protection", "WebGL protection 2", "WebGL2 protection 2".
The spoofing of canvas is found in 90% of cases.
WebGL - 100%

Also on browserleaks.com/proxy spoofing of canvas is found in ~  50% of cases.

**Comment by madflash001** [comment]
In my experience, fp.whatleaks.com compares the colors of the pixels on the left side of the canvas. When I changed the canvas on the right side, the spoofing was not detected.
I can not say anything about webGL.

**Comment by madflash001** [comment]
"Minimal fake size" helps to avoid detection of canvas.
WebGL spoofing is still detected.

**Comment by kkapsner** [comment]
Thanks for your input. I already know that CB can be detected: http://kkapsner.github.io/CanvasBlocker/test/detectionTest.html
There are some settings (fake input mode, not faked colours, minimal fake size), but at the end there will always be a way to tell if CB is installed - because it changes the way canvas work in Firefox.

I'm not sure how I can solve this problem.

**Comment by madflash001** [comment]
We should not change colors on canvases with 1-2 colors. Such canvases are used only for detection.
If you do this, you will avoid all detections except "function length" ([Bug 1081385](https://bugzilla.mozilla.org/show_bug.cgi?id=1081385)).
It needs to be added to the "Options", I think. This is more important than "Minimal fake size", also addition, it can completely replace it.

**Comment by kkapsner** [comment]
Hm... interesting thought. You can already use the "most common colours" feature but checking if a canvas contains more than X colours is faster. Let's see how easy this is to implement.

**Comment by madflash001** [comment]
Something like "If the canvas contains 95% of the same colors, then it is used for detecting". Maybe this is a good idea. In any case, the correct setting with the already available parameters does not result in to detection (except "function length").

**Comment by kkapsner** [comment]
This means I have to calculate the whole statistics for the canvas which can take a while for big ones. And 95% is quite easy to achieve - just make the canvas bigger. I think the number of used colours is more stable. But also that can easily be broken/detected. I updated the detection test to be harder to pass.

**Comment by madflash001** [comment]
This can not be avoided :(

**Comment by kkapsner** [comment]
I know - CB does something and that's why there will always be a way to detect it.

**Comment by kkapsner** [comment]
I added that "minimal colors" settings - it does not hurt much and gives the user options.

**Comment by davidhedlund** [comment]
https://github.com/kkapsner/CanvasBlocker/issues/200
