### ISSUE TITLE
Can not display PDF files with Adobe Reader unless CB is deactivated

### ISSUE THREAD

**Issue by mossroy** [kkapsner/CanvasBlocker#163]
Firefox 52.5.2 ESR (32-bit) on Windows 8.1
CanvasBlocker 0.4.2
Adobe Reader 2015.017.20053

With Firefox built-in PDF reader, it works well.
But this built-in PDF reader is disabled through CCK2 (autoconfig), with following settings :
```
defaultPref("pdfjs.disabled", true);
defaultPref("plugin.disable_full_page_plugin_for_types", "");
```
which lets Adobe Reader handle the PDF documents.

But PDF documents do not display any more if CB is activated : the Adobe plugin does not seem to be activated (no icon in the address bar), and the window content is either white blank (if opening a new window/tab) or stays on the previous page (if clicking on an icon that should open the document in the current window/tab).

Adding the URL to the white list, or even choosing "allow everything" as the block mode are not enough to workaround the issue : you have to disable CanvasBlocker.

**Comment by kkapsner** [comment]
Can you please retry with the current version of Adobe Reader? This version is quite outdated.

**Comment by mossroy** [comment]
You're right.
I upgraded Adobe Reader to the latest version (2018.009.20044) : Firefox detects the new plugin version, but I still have the same behavior.
The workaround to disable CanvasBlocker still works.

**Comment by kkapsner** [comment]
Just out of curiosity: why are you not using the built in PDF viewer?

**Comment by kkapsner** [comment]
I'm not able to reproduce the problem (but on Win 10...) do you have any other addons installed?

**Comment by mossroy** [comment]
This is in a corporate environment, where a few users need some PDF capabilities that are unfortunately not handled by the built-in PDF viewer, like https://bugzilla.mozilla.org/show_bug.cgi?id=739043

I have many other addons : I'll try to disable all of them except CanvasBlocker

**Comment by mossroy** [comment]
Interesting :
- if I disable all extensions except CanvasBlocker, it works (PDF files are displayed)
- With the following extensions enabled, the issue appears : CanvasBlocker 0.4.2, LocalLink 0.5.1-signed.1-signed, uBlock Origin 1.14.20. If I disable any of them, it works
- With the following extensions enabled, the issue appears : CanvasBlocker 0.4.2, LocalLink 0.5.1-signed.1-signed, Ghostery 8.0.0.34. If I disable any of them, it works
- With the following extensions enabled, the issue appears : CanvasBlocker 0.4.2, uBlock Origin 1.14.20, Calomel SSL Validation 0.82. If I disable any of them, it works
- With the following extensions enabled, the issue appears : CanvasBlocker 0.4.2, Ghostery 8.0.0.34, Calomel SSL Validation 0.82. If I disable any of them, it works
- But with the following extensions enabled, the issue does not appear : Ghostery 8.0.0.34, Calomel SSL Validation 0.82, uBlock Origin 1.14.20, LocalLink 0.5.1-signed.1-signed

So it seems to be related to CanvasBlocker in some way, but seems to be the result of some interaction between these extensions.

Are you be able to reproduce, this way?

**Comment by kkapsner** [comment]
Yes - I was able to reproduce now. But not with all combinations.
I think it has the same root than #160.

Please confirm that the latest beta release (https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3-Beta.3) fixes the issue (you should disable the normal version beforehand).

**Comment by mossroy** [comment]
Nice job : switching to 0.4.3-beta.3 seems to solve the issue for me

**Comment by kkapsner** [comment]
Great - one more test positive with this beta.

**Comment by kkapsner** [comment]
The new release is out:
https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3a-Release
https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3b-Release

You have to use 0.4.3a and disable auto update - sorry for the inconvenience. Firefox 59 will solve the problem once and for all... but then plugins do not work.
