### ISSUE TITLE
Prevents loading of websites and breaks JS

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#164]
I just had an issue where Firefox would not execute JS on some pages (although no add-on blocks it or so) and when restarting and restoring the tabs I see that all of my pinned tabs will never load (even as one is in the LAN, so it is certainly not a network error). It also affects some other tabs when these are not directly loaded from the cache.

Firefox 57
Fedora 27

**Comment by Cyuonut** [comment]
I can verify this problem. Some web pages stopped loading altogether or partly today on Firefox at home, and now also at work. I suspected it was because of some add-on, and disabling CanvasBlocker made everything work again.

If you need help spotting the problem, please let me know.

**Comment by kkapsner** [comment]
Can you please try version 0.4.3a?

Which additional addons are you using?

**Comment by Biggizen** [comment]
Same here. Until today there was no problem, but now I have to disable CavasBlocker for some sites like startpage.com to make them able to load. The same sites loaded without problem before today. I did not make any changes in the settings of CanvasBlocker.

**Comment by rugk** [comment]
Quite mysteriously that it kicked off today, indeed…

**Comment by kkapsner** [comment]
I published a new release yesterday night - so not that mysteriously.

**Comment by kkapsner** [comment]
But the problem is weird: no problem for me (same as #160 - but I assume same source)

Any special settings for the addons? Or just the default ones?

Can you please disable all other addons and see if the problem still occurs? If not: in which combination does it?
Can you try on a fresh Firefox profile?

**Comment by rugk** [comment]
Just the default settings for CanvasBlocker. Tried it in a another profile – could not reproduce.

**Comment by kkapsner** [comment]
That's exactly my problem. I need a way to reproduce it to sole the problem efficiently.

**Comment by kkapsner** [comment]
Can you please create a copy of your affected profile and change the order of the webExtensions in extensions.webextensions.uuids?
Is CanvasBlocker in front or in the back or in the middle?

**Comment by kkapsner** [comment]
I created three beta versions. Please check if any (or all?) solve the problem:
https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3-Beta.4
https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3-Beta.5
https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3-Beta.6

Also check if the problem is still present in
https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3-Beta.3

**Comment by Cyuonut** [comment]
I'm not sure if it's a CanvasBlocker problem, after all. Disabling it worked at the work computer, but not at home.

**Comment by kkapsner** [comment]
I'm quite sure it's a problem with a combination of addons and some special circumstances. I just want to remove the CB part.

Have tried to completely uninstall CB, restart Firefox and reinstalling CB?

**Comment by rugk** [comment]
So tried a few things…
* I could disable all other addons and only leave CanvasBlocker enabled and the issue was still there
* disabling CanvasBlocker and restarting FF, the issue was gone
* in `extensions.webextensions.uuids` the add-on was somewhere in the middle, changed it to be at the beginning, nothing changed…

**Comment by rugk** [comment]
AFter installing 0.4.3-Beta.6 the issue was gone, but when I tried to reproduce it with the other old version (disabled beta, re-enabled stable) it also was not e producible anymore.

**Comment by rugk** [comment]
So anyway: 0.4.3-Beta.6 fixes the issue. It also seems to be fixed with v0.4.3-Beta.3.

**Comment by kkapsner** [comment]
Thanks for the input. New release is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.4.3c-Release
I guess it will be validated and shipped by Mozilla soon.

**Comment by kkapsner** [comment]
Can you please check if the problem is still solved in the version on the beta channel: https://addons.mozilla.org/de/firefox/addon/canvasblocker/versions/beta

**Comment by rugk** [comment]
Unfortunately I just updated and the issue is not solved with v0.4.3c. Also the 0.4.4alpha20171219 does not make it work.

Maybe it is more about the settings/data collected from the add-on. So I looked into it and saw, e.g. the "max. fake size" set to 0, huh? (I did not manually change that, just so you know.)
I reset the settings, so maybe that helps…

**Comment by rugk** [comment]
Hey nice, after resetting the settings (Note I created https://github.com/kkapsner/CanvasBlocker/issues/170 before) it works. So it is clearly some bogus setting…

Just FYI in the previous versions I also had a whitelist (domains). This was also not shown in my current version.

And note **it still resets the "max fake size" to 0 (it's also present in the export `"maxFakeSize": 0,`). ANd when I reset the settings again and activate expert mode, it still shows me the setting as `0`… Huh, there is clearly something wrong with these settings.

FYI here is the full export (it is supposed to be nearly the default, as I clicked on that button few times):
```
{
	"logLevel": 1,
	"urlSettings": [],
	"whiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 0,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"isStillDefault": false,
	"storageVersion": 0.2
}
```

**Comment by rugk** [comment]
BTW this is what a test result looks like: https://screenshots.firefox.com/ZpFqVyuZFLVjxakG/browserleaks.com

**Comment by kkapsner** [comment]
Thanks for the effort. and This is great input! There was a settings version change between 0.4.2 and 0.4.3 and maybe the migration has the problem. Can you remember you settings before resetting? Something else than a whitelist entry?

PS: maxFakeSize of zero is OK. It means that any size will be faked (In the description it should mention that or is this not clear enough?)

**Comment by rugk** [comment]
> (In the description it should mention that or is this not clear enough?)

Umm, no… 😐
It just mentions you should never set the value under 1000000 or so… And 0 is below that 😃 .

Basically I just once added two domains to the whitelist. This was long before the WebExtension migration though. AFAIK I've changed nothing else.

**Comment by kkapsner** [comment]
At the beginning it states "(Enter zero to disable.)" - should this be more prominent?

OK - then I will try the migration with two domains in the whitelist. Hopefully this reproduces the problem and I can work on the fix efficiently.

**Comment by kkapsner** [comment]
No luck... still not reproducible - this is so annoying.

**Comment by kkapsner** [comment]
Does the blocking come back when you add the whitelist entries again?

**Comment by kkapsner** [comment]
At least I found a minor bug in the migration...

**Comment by rugk** [comment]
> At the beginning it states "(Enter zero to disable.)" - should this be more prominent?

I don't see that. Maybe the German translation is also outdated.

**Comment by kkapsner** [comment]
In German it says "Canvas, die eine größere Fläche als die hier angegebene Zahl haben, werden nicht vorgetäuscht. **(Null eingeben, um es zu deaktivieren.)** Dies ist ein Leistungsparameter, der das Einfrieren des Browsers verringern kann und der an die Rechenleistung des Gerätes angepasst sein soll.
ACHTUNG: Dies verringert die Sicherheit des Addons. Deswegen wird stark empfohlen, diesen Wert nicht unter 1 000 000 zu setzen.".

**Comment by kkapsner** [comment]
The latest alpha (https://addons.mozilla.org/de/firefox/addon/canvasblocker/versions/beta) fixes the issue. Indeed this is not an alpha any more and I will generate version 0.4.4 immediately - I guess it will be available in about 30 minutes.
