### ISSUE TITLE
Cleanup settings.js

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#166]
Settings version migration should be in separate file.
Settings events could also be separate.

**Comment by Thorin-Oakenpants** [comment]
It's far too quiet in this repo .. can you introduce some bugs on purpose or something :grin:

**Comment by kkapsner** [comment]
Sure - how bad? ;)

**Comment by Thorin-Oakenpants** [comment]
[Rock](https://en.wikipedia.org/wiki/Dwayne_"The_Rock"_Johnson)-size to keep us all on our toesies

**Comment by spodermenpls** [comment]
> It's far too quiet in this repo .. can you introduce some bugs on purpose or something 😁

How times have changed..
