### ISSUE TITLE
CanvasBlocker 0.4.3c issues that 0.4.3b doesn't have (on FF 57 only)

### ISSUE THREAD

**Issue by Darcidride** [kkapsner/CanvasBlocker#169]
## Description

Extracted from #firefox channel :

> "CanvasBlocker 0.4.3c" blocks all websites (blank pages instead of the websites)
> i deactivate this addon and now i can see the websites properly
> Ok definitely this addon, i downgraded this addon to 0.4.3b and it works perfectly as before, no issues with this addon activated, i need to send a mail to its main developer

Initial message (useless but if you want my first analysis) :

> Hi everyone, i moved from Firefox ESR 52 (Debian unstable repository), to the latest Firefox version 57.0.1 (64-bit) (Debian unstable repository), since this i can't access anymore internet with my Firefox 57.x, with Firefox 52 i can access properly to internet, also i can access internet from Chromium (i'm on Debian Buster by the way :)), also i can add i check this webpages and i'm not concerned by the potential fixed that this pages explains : https://support.mozilla.org/en-US/kb/firefox-cant-load-websites-other-browsers-can https://support.mozilla.org/en-US/kb/fix-problems-connecting-websites-after-updating - If someone can help me i will be glad to use Firefox Quantum for sure :) Mossop, justJanne no proxy settings, I already check all the KB pages i linked to you, for the webpage, it's just load infinitly with a blank page justJanne, no proxy on all of my browser

## Expected Behavior

What should happen : the website should be displayed

## Current Behavior

What happens :

- On firefox 57, with version 0.4.3c : websites aren't displayed = blank/empty/white page
- On firefox 57, with version 0.4.3b : websites are displayed and fake readout is working properly

## Possible Solution

Actually, downgrade to 0.4.3b version on Firefox 57 fixed it, but i think it's clear that something is not working properly on version 0.4.3c

## Steps to Reproduce

Steps to reproduce for the bug :
1. Install Firefox 57.0.1 (64-bit) (well, im on Debian Buster but i don't think it should change something because it's mainly an addon issue and not an OS issue)
2. Install CanvasBlocker 0.4.3c
3. Try to access, for example duckduckgo.com
4. You should see a White page

Steps to reproduce for the temporary solution :
1. Install Firefox 57.0.1 (64-bit) (well, im on Debian Buster but i don't think it should change something because it's mainly an addon issue and not an OS issue)
2. Install CanvasBlocker 0.4.3b (downgraded from 0.4.3c)
3. Try to access, for example duckduckgo.com
4. Website is displayed and fake readout is working properly

## Context

I affect me on all websites which fake canvas readout is here, im trying to access my favorite websites.
I reproduce the issue and find a temporary fix that i explain before in this Github issues.

## My Environment

* CanvasBlocker Version used: 0.4.3c (which doesn't work properly) and 0.4.3b (which works perfectly)
* Firefox version incl. 32- or 64-bit: Firefox 57.0.1 (64-bit)
* Operating System and version (desktop or mobile): Debian Buster 64 bits
* Installed addons: Too many to list :)

## My Settings

Expert mode : uncheck
Display descriptions : uncheck
Block mode : fake readout API
show notifications : yes

(Export feature doesn't seem to work on FF 57 with 0.4.3b version, sorry)

## Conclusion

Your work on this Firefox extension is amazing, thank you for your work, really! :)
I hope you can fix this prompty and without any difficulty in your side, i don't know anything in Webextension, but if i can help in some 'beta' tests, don't hesitate to tell me ;)

**Comment by kkapsner** [comment]
Thanks for the detailed report.
This is getting weirder and weirder... the "c" release was done to prevent exactly the problem you are facing.

Do you really reproduce the problem with your scenario? I'm on Firefox 57.0.2 and have the addon installed (0.4.3c) and everything is working. Can you please try which of the 0.4.3 betas is also affected: https://github.com/kkapsner/CanvasBlocker/releases

PS: I'm close to abandon 0.4.3 and reverting to 0.4.2 entirely (i.e. reverting the changes and calling it 0.4.4...).

**Comment by kkapsner** [comment]
Please try the version on the beta channel: https://addons.mozilla.org/de/firefox/addon/canvasblocker/versions/beta

**Comment by rugk** [comment]
This really sounds like https://github.com/kkapsner/CanvasBlocker/issues/164 for me. Can you export the settings (under expert mode).

Also when you enable expert mode (and cannot export the settings) you may still be able to take a screenshot. Have a look at the "max fake size" e.g. Is it `0` although the text advises to set it to 1000000 at least?

**Comment by kkapsner** [comment]
It would be great if you post the content of the following file here before resetting the settings: {Firefox-Profile-folder}/browser-extension-data/CanvasBlocker@kkapsner.de/storage.js
With this I may be able to reproduce the problem.

**Comment by Darcidride** [comment]
@kkapsner 
i confirm you with the 'c' version i have this issue.
Yes, I can reproduce the problem with the scenario i described above. (on Firefox 57.0.1 64bits)
I will give a try to the beta version you linked and tell you what it returns me
I know i need to check "expert" before click on "export", what i told you in my first message is that if i click on "export", a new blank tab is created in my browser, without any information on it.

@rugk 
I tried several times to put '1000000' instead of '0' but it didn't save it and return to '0' when i enter again in the settings tab of the addon

**Comment by Darcidride** [comment]
@kkapsner 
Well, some sensitive informations on this file but im giving it to you anyway : 

`{"storageVersion":0.3,"storePersistentRnd":false,"askOnlyOnce":"individual","showCompleteCallingStack":false,"rng":"nonPersistent","whiteList":"","persistentRndStorage":"","enableStackList":false,"notificationDisplayTime":30,"install-event-fired":true,"stackList":"","maxFakeSize":1000000,"ignoreList":"","blockMode":"fakeInput","showNotifications":true,"blackList":"","showCallingFile":false,"lastPersistentRndClearing":1513433019988,"urlSettings":[{"url":"github.com","showNotifications":false},{"url":"www.it-akademy.fr","showNotifications":false},{"url":"www.numerama.com","showNotifications":false},{"url":"www.leetchi.com","showNotifications":false},{"url":"pad.qbuissondebon.info","showNotifications":false},{"url":"philippe.scoffoni.net","showNotifications":false},{"url":"www.t411.li","showNotifications":false},{"url":"www.magmotardes.com","showNotifications":false},{"url":"www.dealabs.com","showNotifications":false},{"url":"www.google.fr","showNotifications":false},{"url":"computerz.solutions","showNotifications":false},{"url":"accounts.firefox.com","showNotifications":false},{"url":"passport.aliexpress.com","showNotifications":false},{"url":"trade.aliexpress.com","showNotifications":false},{"url":"scrummethodology.com","showNotifications":false},{"url":"login.aliexpress.com","showNotifications":false},{"url":"www.thesslstore.com","showNotifications":false},{"url":"www.memoinfo.fr","showNotifications":false},{"url":"www.rue89lyon.fr","showNotifications":false},{"url":"www.societe.com","showNotifications":false},{"url":"xorhub.com","showNotifications":false},{"url":"7labs.heypub.com","showNotifications":false},{"url":"magazine.odroid.com","showNotifications":false},{"url":"www.kickstarter.com","showNotifications":false},{"url":"www.youtube-nocookie.com","showNotifications":false},{"url":"www.scani.fr","showNotifications":false},{"url":"grisebouille.net","showNotifications":false},{"url":"xserverx.com","showNotifications":false},{"url":"qbuissondebon.info","showNotifications":false},{"url":"forum.proxmox.com","showNotifications":false},{"url":"www.interencheres.com","showNotifications":false},{"url":"www.cbf-permisbateau.fr","showNotifications":false},{"url":"www.t411.cl","showNotifications":false},{"url":"larivieredegoodies.com","showNotifications":false},{"url":"eu.api.ovh.com","showNotifications":false},{"url":"korben.info","showNotifications":false},{"url":"demo.yunohost.org","showNotifications":false},{"url":"shoppingcart.aliexpress.com","showNotifications":false},{"url":"itscenter.alipay.com","showNotifications":false},{"url":"www.aliexpress.com","showNotifications":false},{"url":"daily-manga.com","showNotifications":false},{"url":"carbonezero.info","showNotifications":false},{"url":"www.mangafr.top","showNotifications":false},{"url":"deadline.com","showNotifications":false},{"url":"www.youtube.com","showNotifications":false},{"url":"www.freenews.fr","showNotifications":false},{"url":"forums.macg.co","showNotifications":false},{"url":"198.27.80.126","showNotifications":false},{"url":"c-nergy.be","showNotifications":false},{"url":"veggieworld.de","showNotifications":false},{"url":"moto-securite.fr","showNotifications":false},{"url":"www.wair.fr","showNotifications":false},{"url":"9to5google.com","showNotifications":false},{"url":"www.joueurdugrenier.fr","showNotifications":false},{"url":"minetest.com","showNotifications":false},{"url":"www.t4c-neerya.com","showNotifications":false},{"url":"www.dummies.com","showNotifications":false},{"url":"techinfographics.com","showNotifications":false},{"url":"piwik.org","showNotifications":false},{"url":"eu.api.soyoustart.com","showNotifications":false},{"url":"grangerhub.com","showNotifications":false},{"url":"www.theandroidsoul.com","showNotifications":false},{"url":"actualite.housseniawriting.com","showNotifications":false},{"url":"www.linuxjobs.fr","showNotifications":false},{"url":"www.techniques-ingenieur.fr","showNotifications":false},{"url":"blog.grossoshop.net","showNotifications":false},{"url":"www.frandroid.com","showNotifications":false},{"url":"xiaomiadvices.com","showNotifications":false},{"url":"www.stechguide.com","showNotifications":false},{"url":"howtorootmobile.com","showNotifications":false},{"url":"huado.fr.aliexpress.com","showNotifications":false},{"url":"www.bazaardeluxe.be","showNotifications":false},{"url":"www.goeuro.fr","showNotifications":false},{"url":"www.nesblog.com","showNotifications":false},{"url":"www.high-tech-tests.com","showNotifications":false},{"url":"innofluence.eu","showNotifications":false},{"url":"www.onvautmieux.fr","showNotifications":false},{"url":"message.aliexpress.com","showNotifications":false},{"url":"passport.alibaba.com","showNotifications":false},{"url":"i.alibaba.com","showNotifications":false},{"url":"www.blog.rendez-voo.com","showNotifications":false},{"url":"www.zock-server.de","showNotifications":false},{"url":"www.bianoti.com","showNotifications":false},{"url":"www.smileandpay.com","showNotifications":false},{"url":"billetdebanque.panorabanques.com","showNotifications":false},{"url":"blogs.msdn.microsoft.com","showNotifications":false},{"url":"enjoyphoenix.fr","showNotifications":false}],"displayAdvancedSettings":true,"displayDescriptions":false}`

**Comment by Darcidride** [comment]
For the Beta version tested on my Firefox 57.0.1 :

- canvasblocker_beta-0.4.3RC1-an+fx.xpi => works fine, for example the website github.com is launched as expected
- canvasblocker_beta-0.4.3RC2-an+fx.xpi => works fine, for example the website github.com is launched as expected
- canvasblocker_beta-0.4.3RC3-an+fx.xpi => works fine, for example the website github.com is launched as expected
- canvasblocker_beta-0.4.3RC4-an+fx.xpi => works fine, for example the website github.com is launched as expected
- canvasblocker_beta-0.4.3RC5-an+fx.xpi => works fine, for example the website github.com is launched as expected
- canvasblocker_beta-0.4.3RC6-an+fx.xpi => works fine, for example the website github.com is launched as expected

**Comment by kkapsner** [comment]
Thanks for your trust and testing. This storage.js helps a ton! You can edit your post if you don't want it to be in public.
Can you please quit Firefox, create a backup of the storage.js, delete the part `"install-event-fired":true,` (I have no idea where this comes from...) and restart Firefox.

On the blank export page: can you please switch to console in the lower part. There could be some error messages.

**Comment by kkapsner** [comment]
Finally I'm able to reproduce the problem. It's indeed the "install-event-fired"... and I found the place in the code that struggles with it! You really helped me a lot!

**Comment by kkapsner** [comment]
The latest alpha (https://addons.mozilla.org/de/firefox/addon/canvasblocker/versions/beta) fixes the issue. Indeed this is not an alpha any more and I will generate version 0.4.4 immediately - I guess it will be available in about 30 minutes.

**Comment by Darcidride** [comment]
@kkapsner 
Happy to help you find where the error was :)
Thank you for the really quick fix!

**Comment by kkapsner** [comment]
This problem bothered me a lot.

Also big thanks to @rugk who found out that resetting all settings solved the problem for him which was the first clue.

**Comment by rugk** [comment]
Thanks, great work of you all, so it could be fixed.
