### ISSUE TITLE
Exporting settings does not work in 0.4.4alpha20171219

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#170]
## Expected Behavior

Works.

## Current Behavior

![grafik](https://user-images.githubusercontent.com/11966684/34150730-7e114388-e4a9-11e7-9539-d50139d49bb5.png)

Console:
```
TypeError: settingDefinition is undefined
[Weitere Informationen]
settings.js:350:1
```

## Steps to Reproduce (for bugs)

1. Activate export mode.
2. Click on the button to export the settings.

## Your Environment

* CanvasBlocker Version used: v0.4.4alpha20171219
* Firefox version incl. 32- or 64-bit: 57 64bit
* Operating System and version (desktop or mobile): desktop

**Comment by rugk** [comment]
After resetting the settings, it works again…

**Comment by kkapsner** [comment]
This is weird... what did you change on the settings? That was reverted by the reset=

**Comment by rugk** [comment]
Nothing, AFAIK. (maybe just from old versions some upgrade failed or so and some settings were corrupted… this is my only explanation) See https://github.com/kkapsner/CanvasBlocker/issues/164#issuecomment-352693144 for anything else.
