### ISSUE TITLE
Can you explain the getRng() function for me please?

### ISSUE THREAD

**Issue by Helpper** [kkapsner/CanvasBlocker#174]
Can you tell me why the algorithm can assure not to break users' visual effect please?
`getRng: function(length, window){
	var domain = window.document.location.host;
	if (!persistentRnd[domain]){
		// create the (sub-)domains random numbers if not existing
		persistentRnd[domain] = new Uint8Array(128);
		window.crypto.getRandomValues(persistentRnd[domain]);
	}
	var bitSet = persistentRnd[domain];
			
	return function(value, i){
		// use the last 7 bits from the value for the index of the
		// random number
		var index = value & 0x7F;
				
		// use the last 3 bits from the position and the first bit from
		// from the value to get bit to use from the random number
		var bitIndex = ((i & 0x03) << 1) | (value >>> 7);
				
		// extract the bit
		var bit = (bitSet[index] >>> bitIndex) & 0x01;
				
		// XOR the bit the the value to alter the last bit of it... or not
		return value ^ bit;
	};
}`

**Comment by kkapsner** [comment]
It depends on the blocking mode you are using. If you do a fake readout and the web page just uses canvas to draw something the displayed image is not altered at all. Only when the page tries to read the content this function changes the least significant bit (i.e. the value of the channel may change by a maximum of 1 - the range is from 0 to 255) which cannot be detected by the human eye.

If you use fake input the display is change - but still only by 1 which cannot be detected by the human eye.

In the code the crucial parts are the two lines. `& 0x01` reduces the value of bit to exactly one bit and `value ^ bit` just changes the last bit of value... or not... ;)

**Comment by Helpper** [comment]
Thank you for your detailed explanation!

**Comment by kkapsner** [comment]
You're welcome.
