### ISSUE TITLE
A way to view the image that was being read out

### ISSUE THREAD

**Issue by MzHub** [kkapsner/CanvasBlocker#175]
Either as preview or after blocking/faking, it would be nice to see what the image was that was being read out.

This would more easily let you pinpoint if and how the website is doing fingerprinting.

Example from [JS blocker](http://jsblocker.toggleable.com/). This isn't necessarily how it should be implemented, but to illustrate the idea.

![canvastracker](https://user-images.githubusercontent.com/2797207/34433136-c94ab922-ec85-11e7-88d7-4f99728a1855.png)

**Comment by kkapsner** [comment]
There is already the "Store image for inspection" option. But this is only displayed when the readout is faked. On ask mode it only makes sense when asking for the readout permission - let's see if I can create something useful.

**Comment by MzHub** [comment]
Ah, maybe I missed that option then. I tried looking for something like that. Thanks for clarification.
