### ISSUE TITLE
Dropdown Menu Goes Blank Ocassionally

### ISSUE THREAD

**Issue by Rictusempra** [kkapsner/CanvasBlocker#176]
## Description
This is not 100%, try more.

![image](https://user-images.githubusercontent.com/16912240/34466004-aeea5a92-ef00-11e7-888d-67a4aa7c4a1c.png)

## Possible Solution

Try more, it restores itself

## Your Environment
Firefox 58.0b13 x64 on Windows 10 Pro, CB 0.4.4b

## Your Settings

default

**Comment by kkapsner** [comment]
Hm... never saw myself. But it looks like a rendering issue of Firefox. Can you see the same problem with FF 59?

**Comment by Rictusempra** [comment]
This still happens at 59 but I'm pretty sure it is out of CB itself.
Sorry for my rush.

**Comment by kkapsner** [comment]
No problem. If the problem still happens when 58 gets stable we will have to investigate this problem in more detail.
