### ISSUE TITLE
Allow moving address bar icon into menu

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#177]
## Description

It would be nice if one could move the icon in the address bar into the "…" menu.

## Expected Behavior

When I right-click on the icon I can select "Move into overflow menu"… (or similar)
That is how it works for Firefox' built-in icons.

## Current Behavior

The entry is disabled:

![grafik](https://user-images.githubusercontent.com/11966684/34907102-a419092e-f879-11e7-9ea2-a4422b619d29.png)

## Possible Solution

Do WebExtensions offer this?

## Your Environment
* Firefox version incl. 32- or 64-bit: Firefox 57 64bit

**Comment by Rictusempra** [comment]
Isn't this available already?
Right click the CB icon.
Click to remove it. And you will see it in the ...

**Comment by rugk** [comment]
When I right-click I can only see the disabled options from Firefox. (see screenshot)

When I (left-)click on it I can "disable notifications", in which case the icon disappears at all. THat's not what I want. I want it in the overflow menu (`…`)  so I can access it, if I want, but it does not clutter the address bar.

**Comment by kkapsner** [comment]
The page action can only be hidden when it is displayed all the time. Since CB only displays it when something is faked it cannot be hidden.

There is nothing I can do about it. You could try to file a bug for Firefox.

**Comment by rugk** [comment]
Done: https://bugzilla.mozilla.org/show_bug.cgi?id=1433223

**Comment by rugk** [comment]
So it turns out this issue has been fixed in Firefox 58 released some days ago.

**Comment by kkapsner** [comment]
OK - didn't know that. Thanks for the information.
