### ISSUE TITLE
Not an issue, just a question about Block mode

### ISSUE THREAD

**Issue by Zylinder** [kkapsner/CanvasBlocker#18]
CanvasBlocker 0.1.4 working just fine with Firefox 35.0.1

A simple question regarding the Block mode :

If the readout API mode (either block or fake) runs well (and it does) what is the pertinence of the other modes? I mean, if the site has no readout of the canvas (or a fake one) why (when) would a user be interested in either white or black listing that domain, or even as well have that site ask permission?

If canvas is required for proper display (or even if not) but at the same time never has access to canvas' readout, why bother to choose any other mode than readout API mode?

As you see there's no issue, I'm just puzzled ... :)

**Comment by kkapsner** [comment]
The other modes are there for historical reasons. That were the first modes I implemented and later I made the readout API modes. So it's just grown...

I think at one point I will remove all the obsolete modes.

**Comment by Zylinder** [comment]
@kkapsner , ok. I'm no longer puzzled :) 
Thanks.
