### ISSUE TITLE
High CPU usage when using persistent RNG and clear interval set to more than 24 days

### ISSUE THREAD

**Issue by anon88841** [kkapsner/CanvasBlocker#180]
When you set CB settings to use persistent random number generator and set to store the persistent data for more than 24 days CPU usage suddenly goes through the roof from a few percent to 50-60%

Steps to Reproduce:

0. use default settings
1. set block mode to fake readout API
2. set Random number generator to persistent
3. check the box Store persistent data
4. set Clear interval of persisted data to higher than 24 days (eg. 25 days, 40 days, 2 months, 1 year, etc)
5. watch CPU usage suddenly jump 10x

CanvasBlocker Version used: 0.4.4b
Firefox 58.0.2 x64
Windows 10
Installed addons: Cookie Autodelete, Decentraleyes, Firefox Multi-Account Containers, Greasemonkey, HTTPS Everywhere, Stylus, uBlock Origin, uMatrix, Zoom Page WE

CanvasBlocker settings (cleared before pasting not to expose private data):
{
	"logLevel": 1,
	"urlSettings": [],
	"whiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "persistent",
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "{}",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 24,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1518795675933,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}

**Comment by kkapsner** [comment]
Thank you for your input. I can reproduce the problem and I think I know what's the problem... let's see how I can fix it.
