### ISSUE TITLE
CanvasBlocker Notifications

### ISSUE THREAD

**Issue by Newbie12345** [kkapsner/CanvasBlocker#183]
I have installed CanvasBlocker on my Firefox 59.0.1 64bit. I don't know if its working. On TOR browser you always have a notification that a web site is trying to access canvas. I then use Firefox on same web sites and there is no notification...nothing.

I am not a techie and would appreciate any advice from you.

Thanks

Newbie12345

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CanvasBlocker Version used:
* Firefox version incl. 32- or 64-bit:
* Operating System and version (desktop or mobile):
* Installed addons:

**Comment by kkapsner** [comment]
Dependent on your settings the behaviour of CB can be quite different. With the default settings you see a small fingerprinting icon in the address bar when CB fakes something on the web page. When you click on it you will see further informations: https://github.com/kkapsner/CanvasBlocker/blob/master/.documentation/pageAction.png

The best way to test if CB is running correctly is to go to http://kkapsner.github.io/CanvasBlocker/test/test.html which should show a different hash for each refresh on the standard settings.
