### ISSUE TITLE
Firefox takes 20-30 seconds to load first web page.

### ISSUE THREAD

**Issue by Floppyjoe** [kkapsner/CanvasBlocker#184]
The browser when first starting the computer and sometimes when toggling the internet off and on again will result in the first page taking about 25 seconds to load. The next pages all seem to load quickly.

When I load the browser I expect the first page to load just as fast as the following pages. I have now tried to disable the CanvasBlocker extension and the problem does not happen anymore.
It was the first extension that i disabled.

I have CanvasBlocker(0.4.4b), Disconnect, Google Disconnect, HTTPS Everywhere, NoScript, Privacy Badger, Twitter Disconnect, and Ublock Origin enabled.
I am using Firefox-ESR 52.7.2 64 bit and 32 bit.
It happens both on my Desktop and Laptop.

on Operating System : Debian Stretch 64 bit(Desktop) and 32 bit(Laptop).

Settings:
{
	"logLevel": 1,
	"urlSettings": [],
	"whiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1521825962294,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}

**Comment by Floppyjoe** [comment]
The problem seems to have temporarily stopped now.

**Comment by kkapsner** [comment]
Please try version 0.4.4a if it reappears. If it still exists with that please reopen the issue.

**Comment by Floppyjoe** [comment]
How do I go backwards one version.

**Comment by kkapsner** [comment]
First you have to disable automatic updates for CB and then you go to https://addons.mozilla.org/de/firefox/addon/canvasblocker/versions/ and install the version you like to have.
