### ISSUE TITLE
Dark text on dark background in tooltip.

### ISSUE THREAD

**Issue by j000** [kkapsner/CanvasBlocker#186]
## Description

There is no background colour defined for tooltip (so default is used), but there is one defined for text. 
![screenshot_20180424_124456](https://user-images.githubusercontent.com/4723207/39183276-c452490e-47bf-11e8-8532-da884f7f6575.png)
![screenshot_20180424_124528](https://user-images.githubusercontent.com/4723207/39183277-c47877c8-47bf-11e8-92a4-bfe420d4dacf.png)
![screenshot_20180424_124559](https://user-images.githubusercontent.com/4723207/39183279-c4c7e7ae-47bf-11e8-9bda-5b72f402834c.png)

## Expected Behavior

Tooltip should use default colours, so light text on dark background for dark themes and dark text on light background for light themes.

## Current Behavior

Unreadable dark text on dark background.

## Possible Solution

Don't define text colour, let Firefox use system default.

## Steps to Reproduce (for bugs)

1. Use system with dark theme.
2. Install Canvas Blocker.
3. Click on a tooltip.

## Your Environment

* CanvasBlocker Version used: 0.4.4b
* Firefox version incl. 32- or 64-bit: 58.0.1 (64-bit)
* Operating System and version (desktop or mobile): Gentoo Linux
* Installed addons: A lot, not a problem here :)

**Comment by j000** [comment]
Oh wait. I need to investigate further, I think issue is with Firefox's dark theme.

**Comment by kkapsner** [comment]
How does the doorhanger look that opens when you click on the three dots?

**Comment by j000** [comment]
![screenshot_20180425_083051](https://user-images.githubusercontent.com/4723207/39229568-9686b70e-4863-11e8-9754-8f2fc0c06923.png)

This is what I found: 
![screenshot_20180425_085432](https://user-images.githubusercontent.com/4723207/39230356-88f314cc-4866-11e8-98bd-05590571c632.png)

So this issue is not with your great extension, thanks :)

**Comment by kkapsner** [comment]
Thank you for rechecking.
