### ISSUE TITLE
Respect RFP in isPointInPath and isPointInStroke

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#189]
Do not return fake data when resistFingerPrinting is activated and the used did not allow the page to read the data.

See https://github.com/ghacksuserjs/ghacks-user.js/issues/429

**Comment by kkapsner** [comment]
great - that's how it's intended.

Thanks for verifying.

**Comment by Thorin-Oakenpants** [comment]
I know :) Awesome dude. PS: I love the new API whitelist *list* too - 10 methods. This will come in handy with tests :+1:

**Comment by kkapsner** [comment]
Yes - the API whitelist was very helpful with this bug as well. That's why I implemented it.
