### ISSUE TITLE
Feature Request: Site Management

### ISSUE THREAD

**Issue by mark-orion** [kkapsner/CanvasBlocker#19]
I would highly appreciate some kind of site management that stores white and blacklisted sites and that allows managing them.

**Comment by kkapsner** [comment]
Some kind of management is already present... I know it's neither easy to use nor pretty.

Can you make some suggestions how you would like this to look like. I think I would go for a simple list like NoScript does it.

**Comment by mark-orion** [comment]
On 26/03/15 18:26, kkapsner wrote:
>
> Some kind of management is already present... I know it's neither easy
> to use nor pretty.
>
> Can you make some suggestions how you would like this to look like. I
> think I would go for a simple list like NoScript does it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kkapsner/CanvasBlocker/issues/19#issuecomment-86657052>.
>
Ideally I would like a combination: A "whitelist site" button as part of
the Canvas warning dialog and an editable list of whitelisted sites.

**Comment by kkapsner** [comment]
Sounds good. Something like this is already on my todo-list.

This will be integrated in the solution of #14.

**Comment by kkapsner** [comment]
Can you please install der new XPI in https://github.com/kkapsner/CanvasBlocker/tree/notificationOnFakeReadout 

The notifications currently only work in fakeReadout mode but you can get the idea. And I'm not quite sure if we should implement this for the other modes as well.

**Comment by mark-orion** [comment]
I just installed the XPI and tried it out with Github as they use canvas and it works well. Thanks for this encancement !

**Comment by kkapsner** [comment]
You're welcome.
