### ISSUE TITLE
using maps.google.nl makes firefox complain about canvasblocker using too much cpu

### ISSUE THREAD

**Issue by udovdh** [kkapsner/CanvasBlocker#190]
## Description
While using maps.google.nl, firefox complains about canvasblocker using too much cpu with options to stop, wait and disable addon for a while.
This issue makes using maps.gogle.nl a hassle and makes me doubt the functionality of canvasblocker.

## Expected Behavior
I did not expect such messages from firefox about canvasblocker.

## Current Behavior
See above for behaviour.
See above for expected behaviour.

## Steps to Reproduce (for bugs)
http://maps.google.nl, browse a bit
1.
2.
3.
4.

## Your Environment

* CanvasBlocker Version used:
* Firefox version incl. 32- or 64-bit:
* Operating System and version (desktop or mobile):
* Installed addons:

**Comment by kkapsner** [comment]
It seems that google changed something in maps as this is the second time in a week someone complains about it. See #188 for the solution.

**Comment by udovdh** [comment]
Thanks, that appears to work!
