### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by tortugaverde98** [kkapsner/CanvasBlocker#194]
Thank you for canvasblocker. I would like to support your work with a donation. Please post your bitcoin address on the readme.

**Comment by kkapsner** [comment]
I added the address. Thanks for supporting CB.

**Comment by einsteinsfool** [comment]
I'd also like to support CB. Maybe you could also consider adding Monero? It's the most anonymous cryptocurrency and as your users probably care about that. If you have any questions about Monero or setting it up, let me know.
