### ISSUE TITLE
Add option to control when values change

### ISSUE THREAD

**Issue by tzimon** [kkapsner/CanvasBlocker#195]
From what I see from [browserleaks.com](https://browserleaks.com/canvas) right now the addon will fake canvas values on every site load or refresh. I think this is over the top, as the domain will know it's me anyway from IP and other fingerprinting vectors. Wouldn't this make it obvious to the website that I'm using some technique to report faked Canvas values? CanvasBlocker should provide an option to change the fingerprint only
* on domain change
* closing tab (would be synchronized with cookie deletion by addons like CookieAutoDelete)
* on browser startup (so it's the same for one session)
* after a specified time interval is over (and domain is changed)

**Comment by kkapsner** [comment]
Apart from the second one the "permanent" random number generator setting offers the functionality you want.

If you still want the "closing tab" functionality, please open a separate issue for it with some more details and reasoning. I do not quite get the use case.

**Comment by tzimon** [comment]
Oh, you're right. It wasn't easy to make out which of the settings it was from their names (probably because of the translation). But it offers a great control, thank you.
