### ISSUE TITLE
Bug on https://maps.google.fr/ and degrouptest.com

### ISSUE THREAD

**Issue by grysor** [kkapsner/CanvasBlocker#196]
Hello, I have canvasblocker version 0.4.5c
-I am under firefox quantum 60.0.1

There is a BIG BUG:
I go to the google maps site on my pc. Then I go satellite view.And it is the disaster, the entire screen of the map become total black color! And that's the rest for life! As soon as I deactivate canvasblocker then reload the page, the satellite view is displayed this time perfectly! Take the test you will see.
So it's a bit boring.I specify that in the parameters canvasblocker I'm in block mode: block readout API.
-If I choose: block mode> block everything, it's even worse, the website google maps does not work at all!
my screenshot of the bug :
http://img110.xooimage.com/views/a/b/d/bug1-549e010.png/
Can you upgrade canvasblocker to fix this problem please?

-One other little bug on a website:
In the canvasBlocker settings, next to "block mode", if I choose: "block everything" and I'm going to do an internet debit test here:
http://www.degrouptest.com/test-debit.php

nothing is displayed, the test does not start and the message "Loading nPerf plugin" remains displayed continuously.
-To fix the problem, I need to disable canvasblocker and then the flow test works and displays well and I can do the test.
my screenshot of the bug:
http://img110.xooimage.com/views/5/5/2/bug2-549e013.png/
- Can you fix this little bug? thanks for your extension :)

**Comment by kkapsner** [comment]
Google maps uses the readout API to render the satellite view. Therefore if you chose the block mode the site cannot work. To make it work you can change the block mode to fake readout.

The degrouptest bug is kind of weird - I do not quite understand what the website is doing there. But this page also seems a bit doggy to me. You can whitelist this page if you want to use it...

**Comment by grysor** [comment]
Hello thank you for your answer . I tried your solution: fake readout mode and google maps works perfectly! thank you :) I also placed degrouptest whitelist thank you very much

**Comment by kkapsner** [comment]
You're welcome.

But be aware the whitelisting means that you are no longer protected on this website. You should only whitelist pages you trust or whitelist only temporarily (this issue inspired me to create #197 to make this easier).

**Comment by kkapsner** [comment]
Maybe you can reevaluate your rating at AMO?
