### ISSUE TITLE
Panoptclick tests show my canvas fingerprint hash is staying the same 

### ISSUE THREAD

**Issue by DRigby26** [kkapsner/CanvasBlocker#199]
## Description
When I use the fake readout API and test it with Panoptclick, it shows that the hash of my canvas fingerprint is the same every time.

## Expected Behavior
As I understand it the fake readout API is supposed to produce a different readout every time the API is called.

## Current Behavior
The fake readout API is the same every time. 

## Steps to Reproduce (for bugs)

1. Go to the Panopticlick website. 
2. Test your browser several times and look at the results of the Hash of canvas fingerprint
3.
4.

## Your Environment

* CanvasBlocker Version used: Canvas 0.4.5 C
* Firefox version incl. 32- or 64-bit: Firefox 60.0.2 64 bit
* Operating System and version (desktop or mobile): Mac OSX 10.13.5
* Installed addons:

## Your Settings
My Block mode is set to fake readout API

**Comment by kkapsner** [comment]
I'm not able to reproduce your problem - I get a different hash every time.
Can you please provide your full settings (enable expert mode and then export the settings) - you may want to remove the "persistentRndStorage". Especially your "rng" can cause the issue.

**Comment by DRigby26** [comment]
{
	"logLevel": 1,
	"urlSettings": [],
	"whiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1528922554800,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"isStillDefault": false,
	"storageVersion": 0.3
}

**Comment by DRigby26** [comment]
Okay, I did a fresh install of Firefox without any extensions or anything and it now is working the way it is supposed to work so the problem was on my end. Thank you for this extension!

**Comment by DRigby26** [comment]
I narrowed down the problem to being when you have the resistFingerprinting config enabled for Firefox, it will stop this extension from working.

**Comment by kkapsner** [comment]
Thank you for digging deeper. The behaviour with resistFingerprinting is known and I thinks it's good the way it is (I could not even change it).
If you check my test page (http://kkapsner.github.io/CanvasBlocker/test/test.html) you will see that the resistFingerprinting generates a white image. But you are not always prompted for the permissions when the canvas is not visible...

You can find further information on this topic in https://github.com/ghacksuserjs/ghacks-user.js/issues/350 and https://github.com/ghacksuserjs/ghacks-user.js/issues/429

**Comment by Thorin-Oakenpants** [comment]
^^ Excellent! And many thanks kkapsner for all your hard work. It is important that RFP (privacy.resistFingerprinting) users look the same, across the board - and this includes canvas. RFP is an all or nothing buy-in, otherwise you will raise your entropy and stick out like a sore thumb.
