### ISSUE TITLE
Youtube (also general issue)

### ISSUE THREAD

**Issue by Ch4rg3r** [kkapsner/CanvasBlocker#20]
I got problems using HTML5, especially on YouTube. After deactivating CanvasBlocker it worked again.

No message popped up. Another problem, that occured on other websites is, even if a popup for blocking appeared, it will appear every time i reload the page (even on restart of firefox)

**Comment by kkapsner** [comment]
YouTube uses a canvas to display the loading symbol. If you use the "block readout-API" or "fake readout-API"-mode everything should work without a popup.

It is intentional to show the popup everytime. If you want to use an "ask"-mode you can enter your favorite sites in the whitelist.
