### ISSUE TITLE
Blocked fingerprintings

### ISSUE THREAD

**Issue by davidhedlund** [kkapsner/CanvasBlocker#201]
Can you please describe the status at https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/
* [AudioContext fingerprinting](https://github.com/kkapsner/CanvasBlocker/issues/71) (in progress)
* [Font fingerprinting](https://github.com/kkapsner/CanvasBlocker/issues/200) (just submitted)
* [HTML5 canvas fingerprinting](https://github.com/kkapsner/CanvasBlocker/issues/162) (working)
* [WebGL device fingerprinting](https://github.com/kkapsner/CanvasBlocker/issues/162) (working)
* Browser fingerprinting (out of scope since there are many such WebExtensions?)
* OS fingerprinting?

CanvasBlocker does more than blocking canvas fingerprinting, it's a fingerprinting blocking suite. Why not just rename the project or open a separate repo with everything incorporated and keep this repo just for CanvasBlocker?

**Comment by kkapsner** [comment]
I will update the description at AMO for the next release.

Up to now the name CanvasBlocker is correct as WebGL also uses canvas. With the introduction of Audio it's different. I see the point of changing the name to FingerprintBlocker but it may confuse people... not sure what's the right way to do it.

**Comment by kkapsner** [comment]
I added a section at AMO.

**Comment by davidhedlund** [comment]
@kkapsner Thanks. Should we keep the issue open?

**Comment by kkapsner** [comment]
The naming thing is still open...

**Comment by davidhedlund** [comment]
@kkapsner Yeah.

**Comment by spodermenpls** [comment]
I would leave the name as it is, since the other missing anti-fingerprint features (fonts, User Agent, screen size etc.) are already included in Firefox via "privacy.resistFingerprinting". With 35,000 users according to AMO, CB is pretty much an established add-on by now, and a "rebranding" just because of the added audio readout spoofing probably isn't worth the potential confusion and broken links.

**Comment by kkapsner** [comment]
I'm pretty on the same page. Let's keep the name. NoScript does also more than blocking scripts...
