### ISSUE TITLE
Q:  Minimal Fake Size

### ISSUE THREAD

**Issue by GitCurious** [kkapsner/CanvasBlocker#204]
Minimal Fake Size defaults to 1

Is there a reason why this couldn't, or shouldn't be 0 ?

**Comment by kkapsner** [comment]
Since a 1 pixel image cannot hold much information I think it is a good default value. You can set it to 0 but be aware that this might increase the chance of getting detected that you use CB: http://kkapsner.github.io/CanvasBlocker/test/detectionTest.html
