### ISSUE TITLE
all for one

### ISSUE THREAD

**Issue by alll41** [kkapsner/CanvasBlocker#205]
Hiding works better when everyone looks exactly like everyone else.  Please create an option to do this.

**Comment by kkapsner** [comment]
I do not quite agree. From a data analysis perspective a moving target is harder to hit than a target that looks identical to all the other targets.

But despite that you can use the "white" random number generator which will blank our the canvas. This basically renders the images in the canvas useless. (It's similar to the resistFingerprinting setting of Firefox)
