### ISSUE TITLE
Some Canvas spoofing measures can be detected

### ISSUE THREAD

**Issue by tzimon** [kkapsner/CanvasBlocker#206]
There is a new study on detecting fingerprinting countermeasures. It also shows flaws with state of the art canvas spoofing. I'm not sure if this addon is affected, but maybe it is what they mean by "CANVAS FP BLOCK". 
[https://hal.inria.fr/hal-01820197/document](https://hal.inria.fr/hal-01820197/document)
Especially relevant are the parts 
> 4.1.4 Checking Canvas Poisoning 
> 4.2.3 Analyzing the Detected Countermeasures

**Comment by Thorin-Oakenpants** [comment]
@tzimon the part you want to read from Antoine Vastel is https://antoinevastel.com/tracking/2018/07/01/eval-canvasdef.html

See https://github.com/ghacksuserjs/ghacks-user.js/issues/458 for our discussion. CB is not affected

**Comment by kkapsner** [comment]
I would not say CB is not affected at all (it does change the colors so it might trigger the color statistics flag - but we have the "ignore most frequent colors" setting which should reduce the risk), but for the most parts it should be fine.

**Comment by kkapsner** [comment]
I dug deeper and found a way to detect that CB altered the functions... the fix is almost finished and I will release the next version soon.

**Comment by kkapsner** [comment]
The new release is out.
