### ISSUE TITLE
"Block mode: allow only whitelist" disables the page action

### ISSUE THREAD

**Issue by ssokolow** [kkapsner/CanvasBlocker#207]
## Description

When I set "Block mode" to "allow only whitelist", the page action is present, but completely disabled.

## Expected Behavior

As with something like uMatrix, Self Destroying Cookies, Random User Agent, uBlock Origin, Decentraleyes, HTTPS Everywhere, etc., the action should serve as both a status display (ie. "Is this page potentially broken because an attempt to use the canvas was blocked?") and an easy way to toggle the current page's status on the whitelist.

## Current Behavior

I have to use the JavaScript console in the developer tools as a status display and go all the way into about:addons to add something to the whitelist.

## Possible Solution

1. Make the page action's appearance change if the current page attempted to access the canvas.
2. Expose some kind of whitelist control via the page action when "Block mode" is set to "allow only whitelist".

## Steps to Reproduce (for bugs)

1. Set "Block mode" to "allow only whitelist"
2. Visit http://www.matthewmichelotti.com/games/project_ice_puzzle/
3. Look at the page action

## Context

This makes it significantly more time-consuming to identify why a page isn't working and to try enabling the canvas to fix it.

## Your Environment

* CanvasBlocker Version used: 0.4.5c
* Firefox version incl. 32- or 64-bit: 62.0b6 (64-bit)
* Operating System and version (desktop or mobile): Kubuntu 14.04.5 LTS
* Installed addons:

  * Auto Tab Discard	0.2.8
  * Awesome RSS	1.2.7
  * CanvasBlocker	0.4.5c
  * cookies.txt	0.1
  * Decentraleyes	2.0.6
  * Download Star	2.0.1
  * File Backups	0.3.5
  * Form History Control (II)	2.0.3.2
  * Google search link fix	1.6.7
  * HistoryBlock	2.0
  * HTTPS Everywhere	2018.6.21
  * In-Page Pop-up Reporter	1.6
  * InlineDisposition Reloaded	2.0.1
  * Multiple Tab Handler	2.0.13
  * PinPatrol	0.4
  * Pure URL	1.3.0a
  * Random User-Agent	2.2.5
  * Reload in address bar	1.3
  * Self Destroying Cookies	0.1080
  * Session Boss	1.4
  * Stylus	1.4.13
  * Tab Count	1.0
  * Tree Style Tab	2.4.24
  * uBlock Origin	1.16.12
  * uMatrix	1.3.10
  * Unpaywall	3.77
  * Wayback Machine	1.8.6
  * Web ScrapBook	0.26.3

## Your Settings

```json
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "blog.ssokolow.com",
			"blockMode": "allowEverything"
		},
		{
			"url": "www.matthewmichelotti.com",
			"blockMode": "allowEverything"
		}
	],
	"whiteList": "",
	"blackList": "",
	"blockMode": "block",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1530990989020,
	"askOnlyOnce": "combined",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"isStillDefault": false,
	"storageVersion": 0.3
}
```

**Comment by kkapsner** [comment]
Good point. I will enable the page action when something is blocked, too.
