### ISSUE TITLE
Fingerprinting causes web pages to stop working.

### ISSUE THREAD

**Issue by Floppyjoe** [kkapsner/CanvasBlocker#211]
When I go to a site like Facebook with the new CanvasBlocker release the page does not render properly and all subsequent pages do not work at all. If I first browse pages without fingerprinting they seem to work but once I hit one that fingerprints, nothing seems to work. Why this is a bug should be apparent.

I would expect the Web pages to render properly.
Possible solution is to revert to an older version of CanvasBlocker that is properly signed.

Going to Facebook.com should show you the bug.

I am using the latest version of CanvasBlocker(0.5.0.1b)
Firefox version 52.9.0 (64bit)
Debian 9 Stretch (64bit)
Quite a few security related addons like Privacy badger AddBlocker, NoScript, etc.

Settings:
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	(Scrubbed several lines)
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "12",
	"blockRequestsFromDataURL": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}

**Comment by Floppyjoe** [comment]
I went to page: https://addons.mozilla.org/de/firefox/addon/canvasblocker/versions/ to install an earlier version but the Facebook and subsequent pages not working persists after installing version CanvasBlocker(0.5.0a)

**Comment by kkapsner** [comment]
Can you please check if setting blockRequestsFromDataURL to false fixes the issue?

Additional you can set the logLevel to verbose (100), open the browser console (Shift+Ctrl+J) and see what is written in the console when you browser to a page that is blocked.

**Comment by spodermenpls** [comment]
Facebook still works with the new CB version and blocked Data-URL requests on my end.. 🤔 I use Firefox 61.0.1 instead of 52.9 though.

**Comment by Floppyjoe** [comment]
blockRequestsFromDataURL to false fixes the issue for version 0.5.0a and in version 0.5.0.1b I do not see fingerprinting icon in url bar now but page seems to load okay on Facebook. I see fingerprinting I con on Gameknot.com when looking at other players profiles. in latest CanvasBlocker.

**Comment by Floppyjoe** [comment]
Are you at war with Facebook? =)

**Comment by kkapsner** [comment]
Not that I know...

**Comment by deadman3000** [comment]
Aye. Pages are not loading after visiting Facebook. Using Firefox 64 5.2.9.0. ESR

**Comment by kkapsner** [comment]
Version 0.5.1 fixes the issue. But in the release process Mozilla did not approve the "a" version and is not available. I try to get it signed and activated.

**Comment by kkapsner** [comment]
Version 0.5.1.0 is now out...
