### ISSUE TITLE
Cache for Audio API causes website to stop working

### ISSUE THREAD

**Issue by tzimon** [kkapsner/CanvasBlocker#216]
I wanted to test the Audio spoofing feature on [audiofingerprint.openwpm.com](https://audiofingerprint.openwpm.com/), but after pressing the Start button nothing happens and a [warning](https://support.mozilla.org/en-US/kb/warning-unresponsive-script) appears that says a script by an addon is causing Firefox to slow down. The 3 options are to stop the website, deactivate the addon or to wait. After waiting nothing happens.

Disabling the "Use cache" for Audio setting fixes the issue. The description already says that it reduces speed but in this case the website doesn't work at all.

**Comment by spodermenpls** [comment]
Does the same happen when you use @kkapsner's own (and much better written) Audio spoofing test site? http://kkapsner.github.io/CanvasBlocker/test/audioTest.html

**Comment by kkapsner** [comment]
I already know that (https://github.com/kkapsner/CanvasBlocker/issues/71#issuecomment-401638063) - this testing site is just written very inefficient.
