### ISSUE TITLE
Feature request (icon for toolbar)

### ISSUE THREAD

**Issue by Kherby** [kkapsner/CanvasBlocker#217]
I'm using this wonderfull addon with Waterfox 56.2.2 64bit and it's working fine so far.
But i really miss a icon to launch the settings page...
Could u please add an icon to the toolbar so we are able to access the settings page more easy?

Btw, i saw that a new version is available (0.5.2) and i wonder when it's gonna be available to download/update through mozilla addons ?

**Comment by kkapsner** [comment]
I can add a toolbar icon. I think I have some ideas what can be done there.

Version 0.5.2 is not fully finished yet. But I think it will be available soon.

**Comment by Thorin-Oakenpants** [comment]
Ooooh, I'm excited to see what the button does. I use (but do not necessarily rely on) my toolbar as a very quick visual reference to what's going on with a site

![toolbar](https://user-images.githubusercontent.com/16656956/43378425-6baad166-93b6-11e8-96f2-921a60a46b87.png)
*HTTPS Everywhere (7), uMatrix (clearly some red showing), uBlock Origin (16), ViolentMonkey (2), and Stylus (1) are all making changes on Techdirt*

Besides dropdown overlays on them, which are super handy, the icon colors / badge indicators are an excellent reference (eg decentraleyes very recently added a patch to change the icon color based on criteria).

So I am trembling with anticipation what's in the first version, and what's to come :) @kkapsner :kiss:

**Comment by kkapsner** [comment]
In the first version it will not change depending of something. We have the icon in the address bar for this. But it might come in future versions.

And the content of the popup is also not very exciting: 
![grafik](https://user-images.githubusercontent.com/1105157/43380989-663bb8b8-93d3-11e8-8e0d-4a76dce9f872.png)
(the "Test" is only available when expert mode is active)

I might include a search to quickly change some settings in the future.

**Comment by kkapsner** [comment]
I realized that the icon change is very simple and therefore implemented it...

**Comment by kkapsner** [comment]
Version 0.5.2 is out.
