### ISSUE TITLE
Log file location

### ISSUE THREAD

**Issue by NewGen66** [kkapsner/CanvasBlocker#218]
Hi , I tried hard to find log file for CB but was not able to.

The site that do fingerprinting does fingerprinting for milliseconds so that icon for fingerprint displays for a moment , I am not able to click on it as it needs to be very fast action. 

Thanks @kkapsner

**Comment by kkapsner** [comment]
There is no log file. I mean: it's not written to disk. But if you increase the log level you can see the entries in the browser console (Shift + Ctrl + J).
