### ISSUE TITLE
Review opens up AMO in German

### ISSUE THREAD

**Issue by jobbykil** [kkapsner/CanvasBlocker#219]
Just a minor issue. When opening the CB menu from the toolbar and clicking Review you're taken to the German AMO. I haven't written any extension myself but it should be possible to read the user's language for Firefox or from intl.accept_languages and send them to the localized version of AMO?

**Comment by neroux** [comment]
> it should be possible to read the user's language for Firefox or from intl.accept_languages and send them to the localized version of AMO?

Thats not even necessary. It should be enough to replace the URL at https://github.com/kkapsner/CanvasBlocker/blob/c2c916dd9262ef8d7eae0d07ab68125c33392260/browserAction/browserAction.js#L39 with https://addons.mozilla.org/firefox/addon/canvasblocker/reviews/

**Comment by kkapsner** [comment]
You are both right. I will fix this in the next version.

**Comment by kkapsner** [comment]
Please check https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha2
