### ISSUE TITLE
Version 0.1.5.1 works not longer under Android for Firefox 37

### ISSUE THREAD

**Issue by wadaki** [kkapsner/CanvasBlocker#22]
Hello,
I used the Add-on under Firefox in Android, but the new version is not longer compatible with FF 37.0.2

**Comment by kkapsner** [comment]
Hi wadaki,

thank you for your notice. I am aware of this but I do not have an Android to test the compatibility. I created a new branch with an xpi ( https://github.com/kkapsner/CanvasBlocker/blob/android/canvasblocker.xpi?raw=true ) that should install on Android. Please check if it works (especially the readout fake with the notifications).

**Comment by wadaki** [comment]
Hi knapser,

Thank you for your quick reply.

It was possible to install the xpi now. But I'm not sure if it works right.

I had in a version before a notification on this site, but there is no notice now:
http://stadt-bremerhaven.de/

How can I testing?

**Comment by kkapsner** [comment]
OK - go to http://projects.kkapsner.de/Ausmalen/ and check if you can see the the painting.
Then remove "kkapsner.de" from the whitelist and reload the page. If you are using the "fake readout"-mode a random image should be displayed.
If you are using one of the ask-modes you should be asked and if you are blocking something nothing should happen (the "tree" will appear if you are only blocking the readout).

**Comment by wadaki** [comment]
Nice, the test was possible and I can confirm that it's works well. The only one is, I don't saw a message box about the canvas.
I set off the ask-mode and tested again, but there is no notification with the new version.

**Comment by kkapsner** [comment]
OK... so you can use it.?

**Comment by wadaki** [comment]
Yes, it works. Thank you.

kkapsner <notifications@github.com> schrieb am 07.05.2015:

**Comment by kkapsner** [comment]
Great. Since the messages/notifications are not critical I will close this issue.
