### ISSUE TITLE
waterfox : broken settings page

### ISSUE THREAD

**Issue by crgithubmoth** [kkapsner/CanvasBlocker#221]
3 issues:
1. Clicking buttons on the left made items disappear permanently. Reset is gone, stuck.
2. Main Menu item canvasblocker does nothing.
3. Accessing settings via add-ons page is broken, settings page is in a 10% height scroll frame

## Steps to Reproduce (for bugs)

1. Click the icon to the left of the reset on the  settings page

## Context
Tried disabling, clearing cache, restarting browser, no change.
Looked in about:config, searched canvas, all show defaults.

## Your Environment

* CanvasBlocker Version used: 0.5.2b
* Firefox version incl. 32- or 64-bit:
Waterfox 56.1.0
* Operating System and version (desktop or mobile):
Android 7
* Installed addons:
 Ublock origin
Privacy settings
Https everywhere
Decentraleyes
Copy profile
Smart https
NoProfile

## Your Settings
Not accessible due to this bug

**Comment by crgithubmoth** [comment]
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {
		"displayAdvancedSettings": true,
		"blockMode": false,
		"displayDescriptions": true,
		"minFakeSize": true,
		"rng": false,
		"ignoreFrequentColors": false,
		"blackList": true,
		"sessionWhiteList": true,
		"whiteList": true,
		"enableStackList": true,
		"resetSettings": true
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "eff.org",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1533155581559,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": false,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "19",
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}

**Comment by ald0n** [comment]
Can confirm that at least in Firefox 62.0b6

**Comment by kkapsner** [comment]
The first point is intentional if you mean the little eye icon: 
![grafik](https://user-images.githubusercontent.com/1105157/43551606-e0ae64cc-95e7-11e8-81ee-83a9b4270582.png)
If you click the eye at the very top you will see the hidden settings again. I introduced that because I was bothered with the long "API white list" setting.

The

**Comment by ald0n** [comment]
@kkapsner 
>which of the points do you confirm?

almost the whole post
Browser restarting solve the issue in my case tho, now it's working as you expected :-)

**Comment by kkapsner** [comment]
Good to hear that it's working now. Maybe the update did not run completely before restarting...

**Comment by NewGen66** [comment]
Guys do not hesitate to donate toward his hard work, On some point its going to pay you back if not already.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha1 to the settings problem.

**Comment by crgithubmoth** [comment]
When I click the eye again, no hidden settings come back. It just toggles
hidng every setting.

**Comment by crgithubmoth** [comment]
Got new CB version [had to disable old version, both showed!?]
All hidden settings are back now, thanks!
Please add the CB version number to the settings page.

**Comment by crgithubmoth** [comment]
Still having the tiny frame, please add at the top a link that opens a new
tab
Menu item still not working

**Comment by kkapsner** [comment]
Good suggestions. Added both. The non working menu is weird. Have you checked the latest WaterFox?
Does the main menu button work for uBlock?

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha3

**Comment by crgithubmoth** [comment]
Ublock main menu works fine in waterfox
Thanks for the upgrade, will try it soon

**Comment by kkapsner** [comment]
Desktop or Mobile?
Everything workes fine in my Waterfox.

**Comment by crgithubmoth** [comment]
Waterfox56.1Android from google play store, got new beta3 CB:
Still tiny frame, but link works, easy now.
Menu item : Still not working
 (ublock works, https everywhere works, smart https & CB do not)

**Comment by crgithubmoth** [comment]
FYI: Using CB with Blend In & Privacy Settings,
Panopticlick: put eff.org on CB blacklist -> individual scores are now all low, UA under 350, rest under 30. 
Ublock Origin, Decentraleyes limit 3rd party IP tracking. 
Noprofile stops behavior scoring
Low confidence for basic trackers at least 
Sadly Few Mozilla users out there...
Kudos

**Comment by crgithubmoth** [comment]
More menu fails:
Privacy settings (in tools submenu)
Decentraleyes
Blend in

**Comment by crgithubmoth** [comment]
Tiny frame fails: 
Blend In
Decentraleyes

**Comment by crgithubmoth** [comment]
Another Tiny frame: smart https
Looks like a pattern  here, tiny frame= menu fail?

**Comment by crgithubmoth** [comment]
Is it possible to put CB menu item into Tools submenu?
Menu goes past screen,  have to scroll it.

**Comment by kkapsner** [comment]
CB builds the entire HTML markup via script in the settings and the menu popup. I think this is the problem. And an author usually sticks with one method. That could explain the correlation.

I could add an entry in the tools menu... but there is nothing that cannot be found elsewhere.

**Comment by kkapsner** [comment]
Can you please test Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-RC3

**Comment by crgithubmoth** [comment]
AFAICT rc3 works identical to beta3, tiny frame, main menu item not working. 
CB otherwise works.
3 red on detection page.

**Comment by kkapsner** [comment]
Which three are red? With the default settings you should only get one.

**Comment by kkapsner** [comment]
Ah... on Waterfox the fix for the other two is not integrated (I think it was Firefox 59 or 60 that solved them).

**Comment by kkapsner** [comment]
I have no big hopes... but nevertheless: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-RC2

**Comment by kkapsner** [comment]
Since I do not see the problem in Waterfox (56.2.3) on desktop I think you should report this as an issue on Waterfox mobile.

**Comment by crgithubmoth** [comment]
Waterfox 60.1 android + canvasblocker 0.5.5 has full size settings frame now.
Stuck script which had returned is gone again.
Main menu is now working.
Thanks!

**Comment by kkapsner** [comment]
Oh great! Did not expect that.

**Comment by crgithubmoth** [comment]
More issues with WF 60.1:
CB 0.5.5 settings page is missing expert mode, entire Lists section.

**Comment by kkapsner** [comment]
Please post your settings.
