### ISSUE TITLE
Reload loop with NoScript since 0.5.2b

### ISSUE THREAD

**Issue by ZingPing668** [kkapsner/CanvasBlocker#222]
## Description
When using NoScript and CanvasBlocker if the domain is not trusted in NoScript the page will reload loop until it is trusted. Trusting the domain becomes difficult when its reload looping. This only occurs with CanvasBlocker turned on and since the new version was released 01 Aug.

## Expected Behavior
Opening a new tab and visiting a website where the domain is not trusted in NoScript and CanvasBlocker turned on should allow the page to load with reduced JS functionallity.

## Current Behavior
Opening a new tab and visiting a website where the domain is not trusted in NoScript will cause the page to reload loop until the domain is trusted in NoScript. Disabling CanvasBlocker resolves the issue.

## Possible Solution
Unsure

## Steps to Reproduce (for bugs)
1. Install NoScript
2. Go to a webpage you havent visited before which is not trusted in NoScript (https://www.anz.com/INETBANK/bankmain.asp)
3. Page will reload loop until the domain is trusted in NoScript or CanvasBlocker is disabled.

## Your Environment

* CanvasBlocker Version used: 0.5.2b
* Firefox version incl. 32- or 64-bit: 61.0.1 64bit
* Operating System and version (desktop or mobile): Windows 10 1703
* Installed addons: 
NoScript 10.1.8.16
CanvasBlocker 0.5.2b
Ghostery 8.2.1
Adblock 3.16.0

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": *deleted*,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "24",
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"isStillDefault": false,
	"storageVersion": 0.3

**Comment by kkapsner** [comment]
I'm able to reproduce this problem. You can solve it temporarily by disabling "block data-URL pages". But I have to look into this. But I think the reload is triggered by NoScript.

**Comment by kkapsner** [comment]
You can also solve the problem by disabling and reenabling NoScript... I think it's another side effect of https://bugzilla.mozilla.org/show_bug.cgi?id=1477696

**Comment by kkapsner** [comment]
I not sure about the main loop but I think that NoScript checks if their CSP-Headers are according to the definition and if not they reload the tab. As the CSP-Headers are overwritten by the last WebExtension that sets them (if the web page itself does not send one) it will see the headers of CB and not its own -> infinite reload.

So there is nothing I can do about that issue - NoScript could do something, but I do not think they should. It would be better to have NoScript overwrite CBs headers as the other way around. Therefore make sure you have them run in the correct order.

The problem occurred after the update as this made CB add the headers event listener after NoScript.

I will add @hackademix in the loop, but I will close this issue soon as there is literally nothing I can do about that issue.

**Comment by kkapsner** [comment]
Opened an issue for noscript.

**Comment by hackademix** [comment]
Please check https://github.com/hackademix/noscript/releases/tag/10.1.8.17rc2 thanks.
