### ISSUE TITLE
Protonmail.com login hangs after 0.5.2b update

### ISSUE THREAD

**Issue by angela-d** [kkapsner/CanvasBlocker#223]
Protonmail login page (after entering username + password and attempting to sign in) hangs.  This seems weirdly isolated to Waterfox on desktop; the same version of Canvas Blocker on Firefox ESR is immune.

## Description

From console:
```html
Content Security Policy: Tried to send report to invalid URI: “https://canvasblocker.invalid/”  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at https://mail.protonmail.com/openpgp.worker.0dc7230dfd55e1dc5c33ce31832130e147cce550.js (“child-src filesystem: https://canvasblocker.invalid/”).  (unknown)
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI.  (unknown)
Content Security Policy: The page’s settings observed the loading of a resource at https://mail.protonmail.com/openpgp.worker.0dc7230dfd55e1dc5c33ce31832130e147cce550.js (“child-src 'none'”). A CSP report is being sent.
```

```...Tried to send report to invalid URI: “https://canvasblocker.invalid/”...```
## Expected Behavior

I should be able to access my inbox

## Current Behavior

With Canvas Blocker enabled, the login hangs.  Disabling Canvas Blocker, I can login without issue.

Also strange: 
- In a fresh session (not logged in) this behavior persists.
- If I disable Canvas Blocker, login, logout and re-enable canvas blocker, then try to login again - I can login without issue. (ie. same browser window session)

## Possible Solution
Plausibly isolated to a conflict extension..?

## Steps to Reproduce (for bugs)

1. In Waterfox, enable Canvas Blocker and attempt to login

## Context

Interestingly, I was able to login with Firefox ESR running 0.5.2b

## Your Environment

* CanvasBlocker Version used: 0.5.2b
* Firefox version incl. 32- or 64-bit: 64-bit for both
* Operating System and version (desktop or mobile): Debian 9.5
* Installed addons:
Waterfox:
```
Extensions
Name 	Version 	Enabled 	ID
CanvasBlocker	0.5.2b	true	CanvasBlocker@kkapsner.de
Cookie AutoDelete	2.2.0	true	CookieAutoDelete@kennydo.com
Decentraleyes	2.0.6	true	jid1-BoFifL9Vbdl2zQ@jetpack
DOM Inspector	2.0.16.1-signed	true	inspector@mozilla.org
FireFTP	2.0.31	true	{a7c6cf7f-112c-4500-a7ea-39801a327e5f}
GNOME Shell integration	10.1	true	chrome-gnome-shell@gnome.org
NoScript	5.1.8.4	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Old Reddit Redirect	1.1.0	true	{9063c2e9-e07c-4c2c-9646-cfe7ca8d0498}
Privacy Badger	2018.7.18.1	true	jid1-MnnxcxisBPnSXQ@jetpack
Status-4-Evar	2017.08.20.15	true	status4evar@caligonstudios.com
Text Contrast for Dark Themes	2.0.4	true	jid1-nMVE2oP40qeQDQ@jetpack
uBlock Origin	1.16.14	true	uBlock0@raymondhill.net
uMatrix	1.3.12	true	uMatrix@raymondhill.net
```

Firefox ESR: 
```
Application Update Service Helper	2.0	true	aushelper@mozilla.org
CanvasBlocker	0.5.2b	true	CanvasBlocker@kkapsner.de
Cookie AutoDelete	1.4.4	true	CookieAutoDelete@kennydo.com
Decentraleyes	1.3.10	true	jid1-BoFifL9Vbdl2zQ@jetpack
Multi-process staged rollout	1.10	true	e10srollout@mozilla.org
NoScript	5.1.8.4	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Old Reddit Redirect	1.1.1	true	{9063c2e9-e07c-4c2c-9646-cfe7ca8d0498}
Pocket	1.0.5	true	firefox@getpocket.com
Privacy Badger	2018.8.1	true	jid1-MnnxcxisBPnSXQ@jetpack
Status-4-Evar	2017.08.20.15	true	status4evar@caligonstudios.com
uBlock Origin	1.16.14	true	uBlock0@raymondhill.net
uMatrix	1.0.0	true	uMatrix@raymondhill.net
Web Compat	1.0	true	webcompat@mozilla.org
```
## Your Settings

```
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1533182522381,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "1",
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"isStillDefault": false,
	"storageVersion": 0.3
```

**Comment by kkapsner** [comment]
You should be able to log in when you disabled "Block data-URL pages" (you have to enter expert mode. The fix for #224 should solve the issue in the future.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha1 if it fixes the problem.

**Comment by angela-d** [comment]
0.5.3-Alpha1 works flawlessly!

**Comment by kkapsner** [comment]
Great to hear that. Unfortunately I do not know when the next full release will be. Maybe I find the time to create a hotfix for this issue.

**Comment by angela-d** [comment]
No worries, I'll stick with the alpha for now and keep an eye out for the official release.

Thanks for the excellent plugin and all of your hard work!

**Comment by kkapsner** [comment]
You're welcome.

**Comment by Scrxtchy** [comment]
Also having some issues on some sites

`0.5.3-Alpha1` fixed google maps not loading, but I seem to still be having issues with loading twitch streams
![image](https://user-images.githubusercontent.com/12771982/43933562-a49656dc-9c8d-11e8-810f-c696bdece47a.png)
The green line is where I switch addons from the stable to the alpha

Site functions normally if the addon is disabled

**Comment by NewGen66** [comment]
@Scrxtchy


This is happening to gmail too. it stops loading at 90% the blue bar.

**Comment by kkapsner** [comment]
Just got back from vacations - I will have a look at these issues.

**Comment by kkapsner** [comment]
Which browser and version are you using?

**Comment by Scrxtchy** [comment]
Waterfox

**Comment by kkapsner** [comment]
There might be a way to solve this issue. I will make a new Alpha in the next days.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha3

**Comment by Scrxtchy** [comment]
Working a lot better, google maps and twitch are both working as they should

**Comment by kkapsner** [comment]
Great.
