### ISSUE TITLE
Browser action menu not readable with dark theme

### ISSUE THREAD

**Issue by Sesshu** [kkapsner/CanvasBlocker#226]
## Description

When using a dark system theme, for example Adwaita dark under Gnome in GNU/Linux, the default text menu color in Firefox becomes a bright gray, while the background becomes dark. Because in the browser action menu of CanvasBlocker the background color is set to a bright color using CSS, while the text color isn't changed, having enabled a dark theme makes this menu illegible.

## Possible Solution
Set the text color in the CSS of the browser action menu to a dark color.

## Steps to Reproduce (for bugs)

1. Set the theme of your system to a dark one, for example Adwaita-dark under Gnome.
2. Start Firefox with CanvasBlocker and click on the CanvasBlocker icon to open up the menu.
Results should look like this: ![canvasblocker menu](https://user-images.githubusercontent.com/549767/43617283-6f189d34-96c1-11e8-9db8-4a1e7cef8a69.png)

## Your Environment

* CanvasBlocker Version used: 0.5.2b
* Firefox version incl. 32- or 64-bit: 61.0.1 64-bit
* Operating System and version (desktop or mobile): ArchLinux (no version numbering), desktop
* Installed addons: Only CanvasBlocker, used a fresh Firefox profile

## Your Settings

Default settings

**Comment by Thorin-Oakenpants** [comment]
> Possible Solution
> Set the text color in the CSS of the browser action menu to a dark color.

Set specific/unique element names, set the color for all elements including backgrounds. That way no theme or userChrome.css will unintentionally mess with it. Maybe make two sets (dark/light) and an option under CB settings

**Comment by kkapsner** [comment]
These icons are just images. I should be able to create a dark theme and to decouple it from the browser theme.

**Comment by kkapsner** [comment]
@Thorin-Oakenpants: please open a new issue for the two sets.

**Comment by kkapsner** [comment]
Please check https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha2

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha3
