### ISSUE TITLE
Annoying website popup switching to foreground after every update of CanvasBlocker 

### ISSUE THREAD

**Issue by Wasnix** [kkapsner/CanvasBlocker#227]
It sucks that CanvasBlocker opens new tab or window in foreground during update. Please make an option that supresses such annoying behavior.

**Comment by NewGen66** [comment]
is it the setting page?

**Comment by kkapsner** [comment]
Which Firefox version are you using?
This feature was created for Firefox version where it's not possible to access the settings page (e.g. Firefox for Android).

But I can create option to disable this.

**Comment by kkapsner** [comment]
Please check https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha2
