### ISSUE TITLE
about some options

### ISSUE THREAD

**Issue by yfdyh000** [kkapsner/CanvasBlocker#229]
I have some questions and doubts when translating the extension.

1. The relationship of the random number generator. The "completely white" is a fixed constant? "returned" sounds like a result to faked, though probably not.
2. No instructions for "Store image for inspection".
3. The logLevel is none, error, warning, message, notice and verbose, but generally it should be none, error, warning, notice, message and verbose.
4. The "hidden settings" feature are unexpected, its UX lacks an obvious way to do it and retrieve settings.  First of all, the default state is that all eyes are open, it is difficult to understand that the first eye should be closed to find the hidden settings that just the user tried. Compared to closing eyes, the icon use "-" may be more accurate, and the "hidden settings" words are closer to the "Expert mode", it should be labeled "Collapse" or "Folded" settings.
5. I feel displaying the export settings page is slow, it takes several seconds. I think it can be changed to Copy to clipboard and alert, or pop up "Save as" to a file, but this does not seem to be good for viewing and trimming private information and posting it to issues.

**Comment by kkapsner** [comment]
1. yes, "completely white" is a fixed constant. "returned" is just a technical term - there is no randomness involved.
2. This setting controls whether the real content of a faked canvas should be store. If you then open the page action popup (click on the icon in the address bar) you can see the images. I thought this would be self explanatory... obviously I was wrong.
3. I never thought twice about the order. Notice was less urgent than message to me. Can you give me an example of "generally"?
4. I'm not happy with the UX as well. Please open a separate issue for this. I'm not completely sure if I understand your suggestions correct.
5. In fact the export is not only an export but also an import (hidden feature ;))... but having a "save to file" way may be a good enhancement. Please open a separate issue for this as well.

**Comment by yfdyh000** [comment]
3: https://en.wikipedia.org/wiki/Syslog#Severity_levels

**Comment by yfdyh000** [comment]
4: my thoughts:
click ↑ (U+25B2) & ↓ (actions) / ↓ & → (status) to hide/show hidden settings.
↑ & ↓ (actions) to hide/show settings.

**Comment by kkapsner** [comment]
3. hm... there is no message only information... and information is less urgent than message in my option - but I'm no native speaker. My order would be message, notice, information.
4. Now I'm completely confused...

**Comment by kkapsner** [comment]
Please explain 4. again. I do not understand what you are trying to say (best would be with some imaged).

**Comment by kkapsner** [comment]
I think all point except 4 are addressed within the last releases.
Please open a new issue for 4 when you want to elaborate on this deeper. I just do not get what you mean.
