### ISSUE TITLE
New Feature Request - Whitelist

### ISSUE THREAD

**Issue by hubbathegit** [kkapsner/CanvasBlocker#230]
There are, and probably there will always be, a few sites which cause aggravation with extensions such as this one, no matter what version you use, and disabling becomes necessary for those sites to work normally. 

It would be great to have a whitelist so the user could add these rare sites to, instead of having to disable and re-enable CanvasBlocker all the time.

Thanks for considering. :>

**Comment by kkapsner** [comment]
You can also whitelist a domain or a specific URL in the page action popup: 
![grafik](https://user-images.githubusercontent.com/1105157/44299483-06d45280-a2f7-11e8-925b-e1736ddf41e3.png)
