### ISSUE TITLE
cosmetics: action menu light/dark themes

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [kkapsner/CanvasBlocker#232]
as requested from #226 

Thorin said
> Set specific/unique element names, set the color for all elements including backgrounds. That way no theme or userChrome.css will unintentionally mess with it. Maybe make two sets (dark/light) and an option under CB settings (edit: assuming you can change the icon colors as well, not sure if these are fonts)

kkapsner said
> These icons are just images. I should be able to create a dark theme and to decouple it from the browser theme.

That's this item:
![menu](https://user-images.githubusercontent.com/16656956/44344809-1ed7dd80-a481-11e8-8ab7-722909008515.png)

ToDo: grab color values from FF default theme and dark theme
calling @overdodactyl (from [Shadowfox](https://github.com/overdodactyl/ShadowFox))

**Comment by Thorin-Oakenpants** [comment]
As it currently stands the above image shows it's using
- `#919191` (RGB 145,145,145)
- `#FFFFFF` (RBG 255,255,255) - doesn't seem like white to me (tweaked my monitor, also f.lux) - white is an awful color, too bright IMO

Here's decentraleyes for interest (off white, darker grey)
![dc](https://user-images.githubusercontent.com/16656956/44345532-27311800-a483-11e8-93b2-a590b7b5c4c8.png)
background = `#F0F0F0` (RGB 240,240,240)
text = `#555555` (RGB 85,85,85)

**Comment by Thorin-Oakenpants** [comment]
FF dark theme is
![darktheme](https://user-images.githubusercontent.com/16656956/44345912-23ea5c00-a484-11e8-8cbd-839b2942fd90.png)
- `4A4A4A` (RGB 74,74,74)
- `F9F9Fa` (RGB 249,249,250) - IDK why the B value is +1

Suggest
Light: 240,240,240 + 75,75,75
Dark: the reverse (75 is so close to 74 to keep the same dark background)

**Comment by kkapsner** [comment]
Thanks for the deep dig. I will test your suggestions and see how I can handle the icons.

**Comment by Thorin-Oakenpants** [comment]
You're right. In fact, more so. Not only is the light a bit dull, but the dark looks like it has some sepia seeping in (see what I did there!), or rather, the FF one is has more blue (B value is +5, looks better IMO).  My suggestion was a bit silly. We should just use *exactly* what FF does (and yeah, I forgot the on-hover). Especially the light theme using white - that will un-dull it and make the contrast with the text better.

![dark](https://user-images.githubusercontent.com/16656956/44379069-cb52a780-a4f3-11e8-814f-2379b2be2844.png)
![light](https://user-images.githubusercontent.com/16656956/44379071-cdb50180-a4f3-11e8-8d05-23bc1e685f07.png)

The light text on dark can stay the same or be white, doesn't matter .. and .. the dark text on light can be black or dark grey, doesn't matter. The key is that the backgrounds and hover match, as this is 95% of the coloring (and the white background will remove any dullness)

**Comment by kkapsner** [comment]
There is also the default theme. I think I will create three themes (default, light and dark).

Do you think there are people who completely want to customize the theme? Should I create a way to use complete custom colours?

And I think the page action popup should also use the theme colours.

**Comment by kkapsner** [comment]
dark: ![grafik](https://user-images.githubusercontent.com/1105157/44425358-e670f600-a58b-11e8-9393-d9ac41ff4e14.png)

light: 
![grafik](https://user-images.githubusercontent.com/1105157/44425384-f983c600-a58b-11e8-9eb0-b963f991ceb3.png)

default:
![grafik](https://user-images.githubusercontent.com/1105157/44425394-07d1e200-a58c-11e8-9baf-7894eaf0c274.png)

**Comment by kkapsner** [comment]
The page action popup is a little bit tricky with the theme because of the coloured icons...

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha3

**Comment by kkapsner** [comment]
Somehow the default colours were completely off...

**Comment by kkapsner** [comment]
@Thorin-Oakenpants  I themed all pages for #341. Can you please have a look at https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-Alpha3?
