### ISSUE TITLE
Firefox to slow down

### ISSUE THREAD

**Issue by errorkod** [kkapsner/CanvasBlocker#235]
fix please error  on test site http://f.vision/ i see masage on FF 61.0.2 win.
a script in the extension "canvasbloker-beta" is causing Firefox to slow down

**Comment by kkapsner** [comment]
There is no way I can fix this. The audio fingerprinting is as poorly written as at https://audiofingerprint.openwpm.com/ (it seems they just copied the bad code...)

You can disable the audio cache to make things a little bit faster but will make you detectable and less protected.

I do not really get why this page needs to fingerprint you. I would not use/trust such a page.
