### ISSUE TITLE
getClientRects() provides a persistent fingerprint

### ISSUE THREAD

**Issue by DRigby26** [kkapsner/CanvasBlocker#236]
When using the testing page https://www.bromite.org/detect I found that the API getClientRects() will provide a persistent fingerprint.

**Comment by kkapsner** [comment]
Again a page the uses the very bad audio fingerprinting code... copy/paste without brain is not good.

But to your "problem". getClientRects() is not a Canvas-function and that's why it's not protected. Or is this just a feature request to protect that as well?

**Comment by crssi** [comment]
Can I humbly vote this issue to be a feature request? :heart: 

Thank you

**Comment by DRigby26** [comment]
Yes, I guess this would be a feature request. Sorry for not making that clear.

**Comment by kkapsner** [comment]
No Problem.

Do you have any research about the usability of this fingerprint? How much does this vary?
I do not want to fake some values that are the same most of the time and will increase your chance of being tracked when tampered with.

**Comment by DRigby26** [comment]
Yeah I found some stuff about it, and I'll quote: 
"getClientRects allows to get the exact pixel position and size of the box of a given DOM element. Depending on the resolution, font configuration and lots of other factors, the results of getClientRects are different, allowing for a very quick and easy fingerprinting vector, even better than the canvas fingerprinting that is fixed."
http://jcarlosnorte.com/security/2016/03/06/advanced-tor-browser-fingerprinting.html

**Comment by kkapsner** [comment]
I didn't know that you get subpixel precision with this...

Protecting this is a good idea and I have a way to do this. The question is how to protect... I think we should only fake if the value is not an integer - otherwise detection would be simple.
And floats should only be faked in the subpixel regime.

**Comment by DRigby26** [comment]
Yeah that sounds like a good approach to me.

**Comment by spodermenpls** [comment]
Does @Thorin-Oakenpants have some more knowledge about this to drop?

**Comment by Thorin-Oakenpants** [comment]
[TEST] https://browserleaks.com/rects

I'm already protected. Sup guys?

**Comment by Thorin-Oakenpants** [comment]
FYI: https://browserleaks.com/rects#further-reading - links to Norte's article, etc

**Comment by Thorin-Oakenpants** [comment]
I took some grabs on my system, if it helps.

chrome
![rects-chrome](https://user-images.githubusercontent.com/16656956/44740762-ca6cd780-aaea-11e8-9ef9-eed1ff58c3fc.png)

opera
![rects-opera](https://user-images.githubusercontent.com/16656956/44740778-cfca2200-aaea-11e8-9b47-382e16786d8f.png)

tbb 7.5.6
![rects-tbb-7 5 6](https://user-images.githubusercontent.com/16656956/44740800-da84b700-aaea-11e8-95b0-a398d5c61647.png)

FF nilla 63dev (whatever todays update version is)
![rects-ff63-default](https://user-images.githubusercontent.com/16656956/44740837-f25c3b00-aaea-11e8-92a7-787e5130596a.png)

my FF61 which limits fonts (browser.display.use_document_fonts-0) to georgia, arial, lucida console
![rects-ff](https://user-images.githubusercontent.com/16656956/44740907-220b4300-aaeb-11e8-8f17-762bb6e1f4e6.png)

There are some big diffs. Also seem TBB and FF, something is already rounding to 0.25's? Not that I understand any of it, TBH

I mean look at string 1 height (what would cause this diff)
- nilla FF63: 97.75
- my FF61: 109.86xxxxxxxxx..

**Comment by kkapsner** [comment]
It makes sense that opera and chrome are the same as they use the same rendering engine. The big differences between the FFs is quite surprising.

**Comment by kkapsner** [comment]
The rabbit hole of this API is quite deep...
![grafik](https://user-images.githubusercontent.com/1105157/45058967-940afb80-b09a-11e8-8cbb-95ef215de7c7.png)

And Google ads do weird stuff with it as well (got up to over 10000 notifications on the browserleaks test page from an ad - so I had to change the way the notifications work for this API).

Now it's time to polish and test.

**Comment by DRigby26** [comment]
Awesome good work!!

**Comment by kkapsner** [comment]
Please try/test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-Alpha1

**Comment by DRigby26** [comment]
It has been passing all the tests for me so far.

**Comment by spodermenpls** [comment]
No complaints here either, seems to work flawless on the CB test page.

**Comment by spodermenpls** [comment]
I just had to deactivate the DOMRect API protection for twiiter.com, it made videos in the feed flicker while scrolling and unplayable. I noticed on Twitter, as well as on Youtube that those sites use massive amounts of DOMRects requests (up to 1600 times per page), is this a signifcant drain on computing power (and hence laptop battery..), and what for do these sites use the DOMRects API so massively?

**Comment by spodermenpls** [comment]
While adding the exception for twitter.com, I noticed that the German locale string "inputURL" isn't translated, I propose to replace it with "Domain oder URL RegExp eingeben:".

**Comment by kkapsner** [comment]
I think they use it to determine the positions of all the elements so they know were to display the overlays.
The surprising thing is that I already reduced the number of notifications you get from this API. You only get on notification for all the calls that produce the same DOMRect (same position and dimensions).
Do you have an example URL for the flickering?

**Comment by spodermenpls** [comment]
A similar flickering happens with the right column of facebook.com, when scrolling..

**Comment by kkapsner** [comment]
OK - I see the flickering as well. No idea what happens there... The faking is done under 0.01 pixel.

But I also see it when I completely disable CB.

**Comment by kkapsner** [comment]
Should we also disable DOMRect by default? It's really heavy on performance (as the API is used very much).

**Comment by spodermenpls** [comment]
> But I also see it when I completely disable CB.

Really? That's weird, after a refresh (after whitelisting twitter.com) I don't get a single flicker anymore, when scrolling.

> Should we also disable DOMRect by default? It's really heavy on performance (as the API is used very much).

I think so.

**Comment by kkapsner** [comment]
It's less obvious and requires fast pace scrolling. But I see it.

> I think so.

@DRigby26 and @Thorin-Oakenpants: What are your opinions?

**Comment by spodermenpls** [comment]
Are you maybe talking about the normal "reload" of the video thumbnail when leaving and re-entering the visible area of the window? Twitter closes videos that are scrolled away from visibility, and that's also probably the cause of the issues with the spoofed DOMRects requests..

**Comment by DRigby26** [comment]
Since the DOMrect() protection has been added I've noticed how widely used it is on websites like the Google homepage along with many other sites. It seems to be a very popular and effective way of fingerprinting, so I'd say it would be important to protect by default and maybe just whitelist sites where it causes problems.

**Comment by spodermenpls** [comment]
The question is, are those DOMRect requests in majority used for legitimate purposes, or in majority for fingerprinting (like in case of the Canvas API)?

**Comment by DRigby26** [comment]
Well I don't use Facebook or Twitter and I haven't noticed any issues, so it seems like so far just those two websites use the API for functional purposes as well as fingerprinting I would imagine.

**Comment by spodermenpls** [comment]
Like @kkapsner mentioned, there's also a perfomance issue in the room, caused by the often huge amounts of requests, even if the spoofing doesn't break websites...

**Comment by DRigby26** [comment]
I ran a YouTube in Firefox with CB, then another video in Firefox Developer Edition without CB and compared the power draw of the two and it appears to be insignificant.

**Comment by spodermenpls** [comment]
The developer known as @kkapsner said:
> It's really heavy on performance (as the API is used very much)

@DRigby26 says:
> the power draw [...] appears to be insignificant

So I guess it's a drain on performance, but insignifcant to power consumption? 🤔

**Comment by Riajyuu** [comment]
I agree with poster here.
I go to some Discuz forum with the alpha. This API is called for over 40 times but I don't feel really slowed

**Comment by spodermenpls** [comment]
If every website would use the DOMRects just 40 times, we wouldn't have an issue, but a lot of sites use them in 3- to 4-figure amounts, which is noticeable in terms of loading/reaction time..

**Comment by kkapsner** [comment]
The API itself and the faking is not a performance issue (it's just 4 numbers and not thousands as in the Canvas/Audio case). But if it is called that many times (as mentioned above: the number of notifications is the minimum amount of calls to the API. It's the number of distinct DOMRects that are faked. I had to change it as I saw 5 digit numbers which had a very high performance impact.) it sums up.

And I did not measure the power consumption but CPU and RAM usage. CPU was slightly increased (expected and within measuring error) but RAM usage increased significantly (every notification has to store some information on what, when and where).

**Comment by kkapsner** [comment]
There is a way to disable notifications for a specific API. But it's only a display thing and still stores the data... I should change that.

But turning of notifications by default is not good.

The counter would also work, but there are situations where you want to also know the details of a DOMRect notification... maybe I should make a switch if the notification details should be stored or just the number per API.

**Comment by DRigby26** [comment]
Yeah I'd say that would be a good idea.

**Comment by spodermenpls** [comment]
> A similar flickering happens with facebook.com, when scrolling.. 

Entry No. 3 for Instagram.com ...

**Comment by kkapsner** [comment]
Maybe it get's better when the RAM usage is lowered. The new setting is almost finished.

**Comment by kkapsner** [comment]
Please try the new alpha: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-Alpha2

**Comment by spodermenpls** [comment]
Facebook works 98 % without flickering now (well enough for me), Twitter and Instagram are still not useabale. Did you already test how much the RAM consumption increases with just the counter (without details) now, with 1000+ requests?

**Comment by DRigby26** [comment]
Everything seems good on my end. When I test it on Twitter I don't notice any problems.

**Comment by kkapsner** [comment]
I do not see an increase: 
![grafik](https://user-images.githubusercontent.com/1105157/45450134-93481a00-b6d7-11e8-892e-27355fb4e3da.png)

**Comment by kkapsner** [comment]
Please check https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-Alpha3

**Comment by spodermenpls** [comment]
**Excellent** job, the flickering and bouncing issues are gone! 🍾

**Comment by kkapsner** [comment]
Great. Then this API protection has finally landed.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-RC1

**Comment by DRigby26** [comment]
It has been working great for me so far.

**Comment by kkapsner** [comment]
Great - thanks for testing.

**Comment by DRigby26** [comment]
So I just started testing the RC2 release and noticed that for the detection test CB is able to be detected for function code along with known pixel value 1 &10. I have resistFingerprint enabled and I know that the detection with known pixel value is inevitable but I haven't noticed the function code detection before.

**Comment by kkapsner** [comment]
Thanks for pointing this out. I have to fix that.

**Comment by kkapsner** [comment]
Found the issue: NoScript - please open an issue there.

**Comment by kkapsner** [comment]
Found the issue: NoScript - please open an issue there.

**Comment by DRigby26** [comment]
What is the issue exactly?

**Comment by kkapsner** [comment]
They alter some functions (in this case the getter and setter of window.name) in a way that is detectable. You can simply direct them to my detection test page.

**Comment by kkapsner** [comment]
0.5.4 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4

**Comment by DRigby26** [comment]
Awesome! and I just submitted that bug report with NoScript.

**Comment by Thorin-Oakenpants** [comment]
Hey, @kkapsner - do you want in on this? - https://bugzilla.mozilla.org/show_bug.cgi?id=1507879 . I was going to needinfo at you, your insight would be valuable IMO

TBB is fine (not entirely sure how they mitigate it - limited fonts and screen sizes etc?), but apparently no-one at Mozilla knew about this, so I told em. Now at some stage it will get covered under RFP

**Comment by csagan5** [comment]
> Again a page the uses the very bad audio fingerprinting code... copy/paste without brain is not good.

@kkapsner care to elaborate?

**Comment by kkapsner** [comment]
https://www.bromite.org/fp/audio.js:
```
		for (var i = 0; i < event.renderedBuffer.length; i++) {
			acc += event.renderedBuffer.getChannelData(0)[i].toString();
		}
```
and
```javascript
		for (var i = 4500; 5e3 > i; i++) {
		  pxi_output += Math.abs(event.renderedBuffer.getChannelData(0)[i]);
		}
``` call `event.renderedBuffer.getChannelData` very ofter with the exact same parameter (and retrieves the same object every time). Much better would be to call it once and to store the result in a variable.

You can have a look at https://canvasblocker.kkapsner.de/test/audioTest.html on how much faster this fingerprinting can be.
