### ISSUE TITLE
Google Photos Not Working - FireFox ESR 52.9.0 64-bit - Windows 10

### ISSUE THREAD

**Issue by framecap** [kkapsner/CanvasBlocker#237]
## Description
Google Photos won't upload photos.
Google Photos is a crucial service to backup your memories. 

## Expected Behavior
Google Photos should be able to backup like it had before with CanvasBlocker.

## Current Behavior
On Firefox 52.9.0 64-bit, Google Photos gets tuck at "Preparing to upload..." dialog box.

## Steps to Reproduce (for bugs)
1. https;//photos.google.com
2. Firefox ESR 52.9.0 64-bit
3. Select "Upload" from menu.
4. Gets stuck at the process.

## Context
Not able to backup.
Yes.
Should be able to backup without an error.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* CanvasBlocker Version used: 0.5.2b
* Firefox version incl. 32- or 64-bit: 64-bit
* Operating System and version (desktop or mobile): Windows 10 Enterprise 64-bit
* Installed addons: NoScript, HTTPS Everywhere

## Your Settings
Can't be given due to security reasons.

**Comment by framecap** [comment]
Alpha version worked without the need to disable "block data URLs" in expert mode. Tested that with version 0.5.2b too.

**Comment by kkapsner** [comment]
Great. I think the new version will be out soon.
