### ISSUE TITLE
Chess.com and WhatsApp Web issues

### ISSUE THREAD

**Issue by lookarts** [kkapsner/CanvasBlocker#239]
With CanvasBlocker activated I can't play against the computer (didn't try against humans) on chess.com. When I deativate it, I can play.

When I send videos via WhatsApp Web the video file is sent instead of the embed video itself. If I deactivate CanvasBlocker the video is embeded fine.

* CanvasBlocker 0.5.2b
* FirefoxESR 52.9.0 (64-bit)
* Debian 9.5 stretch x86_64 Linux 4.9.0-6-amd64
* Installed addons: 1-Click YouTube Video Downloader; Download Status Bar; Google search link fix; Google Similar Images; HTTPS Everywhere; NoScript; Roomy Bookmarks Toolbar; Self-Destructing Cookies; Tampermonkey; uBlock Origin; uMatrix

My CanvasBlock settings are default. I never touched it.

**Comment by kkapsner** [comment]
Please try the latest alpha: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-Alpha3

**Comment by kkapsner** [comment]
Better try the 0.5.3 RC1: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-RC1

**Comment by kkapsner** [comment]
Please try Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.3-RC3
