### ISSUE TITLE
Feature request: "Show Notifications" checkbox disables notifications by default

### ISSUE THREAD

**Issue by CopperEyeWall** [kkapsner/CanvasBlocker#24]
I find the notifications introduced in v0.1.5.1-Release to be annoying because the excellent fake readout API block mode is a "set-it-and-forget-it" setting which shouldn't require user input (such as needing to populate the ignore list to prevent notifications from showing regularly). The notifications are confusing to non-technical users, and they constantly appear because the fake readout API setting is Canvas Blocker's default blocking mode (as it should be).

To solve this issue, I suggest introducing a new setting named "Show Notifications" which only allows the notifications to be displayed if the setting is true. "Show Notifications" should default to false to not bother or confuse non-technical users who don't want to dig into the preferences, while allowing technical users to enable notifications if desired.

Suggested implementation:
* Create a new boolean pref named "showNotifications"
* Edit "/resources/canvasblocker/lib/main.js" to check showNotifications when deciding whether to display the notification:
  * Change line 147 from: `if (!ignoreList.match(contentURL)){`
  * to: `if (showNotifications && !ignoreList.match(contentURL)){`
* On the Addons Manager preferences page:
  * Put the Show Notifications checkbox into the same sub-section as the Ignore List (so that both options are between one pair of separator lines). If that's not possible, then put Show Notifications right above Ignore List, since the Ignore List is only relevant if notifications are allowed.
  * English description for the Show Notifications checkbox: "Show a notification when the block mode is set to 'fake readout API'."

Note: if you plan on displaying notifications for other blocking modes in the future, please also have "Show Notifications" apply to them as well for the same reasons.

Relates to the following issues:
* https://github.com/kkapsner/CanvasBlocker/issues/14
* https://github.com/kkapsner/CanvasBlocker/issues/19

This addon is great; please keep up the good work!

**Comment by kkapsner** [comment]
Thank you for your input. The "showNotifications" is already implemented and functional.
I would like to set the default to "true". This shows the user that (s)he can get this notifications BUT I added a button to the notifications that disables the notifications, so they can be disabled very quick.

I appreciate your preference page suggestions - I like them and changed it accordingly.

Please check out the latest xpi here on GitHub and tell me if you like it.

**Comment by CopperEyeWall** [comment]
I tested v0.1.6-Development this evening, and the "Show notifications" checkbox works well. I would still prefer it to default to "true" to avoid confusing non-technical users when they first install the addon, but it's not critical. Thanks for the fix!

**Comment by Mosrite** [comment]
When will it be possible again to disable notifications? I'm using the latest release from AMO and don't see an option to do this.
Your addon is really great. But the notification thing gets a bit annoying. For an average user it doesn't add any additional value. I haven't encountered a single site that won't work with spoofed APIs. So for me there's absolutely no reason to get notified about spoofed APIs and to interact with them.

**Comment by kkapsner** [comment]
I just uploaded version 0.1.6 to AMO - it will be available soon.

**Comment by Mosrite** [comment]
Thanks, the update's available now! :)

**Comment by kkapsner** [comment]
You're welcome.
