### ISSUE TITLE
site-specific settings propagate to all prefs

### ISSUE THREAD

**Issue by practik** [kkapsner/CanvasBlocker#245]
As discussed at https://github.com/kkapsner/CanvasBlocker/issues/243, I whitelisted a couple of specific sites for the Window API. Today I was surprised to find that those two settings have automatically propagated to every other preference where site-specific settings are possible (Block mode, Show notifications, Highlight page action icon, Change toolbar icon, and Audio API).

I find that … strange. And bad. I only wanted to disable Window API protection for the two domains in question, but CanvasBlocker has also disabled notifications and Audio API protection for them. (At least, I think that's what happened – like MicroBill at https://github.com/kkapsner/CanvasBlocker/issues/244#issue-357341890, I get confused about how to interpret the site-specific checkboxes.)

So now, to make CanvasBlocker behave as expected, I have to go uncheck the checkboxes under Show notifications and Audio API. But CanvasBlocker never gave me any indication that it created site-specific settings for those preferences, so how would I even know that I have to uncheck the checkboxes?

At least for the other three prefs (Block mode, Highlight page action icon, Change toolbar icon), CanvasBlocker has made the site-specific preferences the same as the global preferences. At a minimum, it should do the same for Show notifications and Audio API. In other words, if it's going to auto-create site-specific settings for those prefs, it should create them with checkboxes unchecked.

But really, why does it create them at all? It just seems like UI clutter and a potential source of user confusion to me …

My environment/settings: See https://github.com/kkapsner/CanvasBlocker/issues/243

**Comment by kkapsner** [comment]
Hm... the UI seems to lack some clarity here. These other settings are not created (you can look at your settings export and will see that only the ones you specified are stored:
![grafik](https://user-images.githubusercontent.com/1105157/45175434-bd986400-b20d-11e8-9dc5-2dc164cf90f5.png)
but
![grafik](https://user-images.githubusercontent.com/1105157/45175464-cd17ad00-b20d-11e8-9633-069bbd714c42.png)

As long as the input is grayed out a little bit it uses no site specific setting there. I just thought it would be convenient. If you set one site specific setting you might also want to set others.

You can also click the x next to the site specific setting to revert to the "global" setting: 
![grafik](https://user-images.githubusercontent.com/1105157/45175788-824a6500-b20e-11e8-8392-08c49a2cb890.png) -> 
![grafik](https://user-images.githubusercontent.com/1105157/45175809-8bd3cd00-b20e-11e8-85cb-5931b5efa7dc.png)

And there seems to be a misunderstanding of how these settings work for checkboxes. Having the checkbox ticked for a site specific setting does not mean it uses a different value. It just means that the value for this specific setting is true (on, yes). Example:
![grafik](https://user-images.githubusercontent.com/1105157/45175898-c9d0f100-b20e-11e8-8600-d86b77778a25.png)
Here the window API is protected for most pages. ip-check.info and local have site specific settings. For ip-check.info the window API is NOT protected (not ticked) and for local it IS protected (ticked - it's also grayed out to indicated that it's not set but only uses the default).

I hope this all clears the issue. If you have any suggestions how I can make this less confusing I would be glad to hear.

**Comment by practik** [comment]
> Having the checkbox ticked for a site specific setting does not mean it uses a different value. It just means that the value for this specific setting is true (on, yes).

Aha! That almost certainly explains my problem at #243: I thought I was disabling Window API protection by checking the checkbox, but I was actually _enabling_ it.

> I just thought it would be convenient. If you set one site specific setting you might also want to set others.

That makes sense, but I think it complicates the UI unnecessarily.

> If you have any suggestions how I can make this less confusing I would be glad to hear.

Maybe:
* Change "Site specific settings" to "Exceptions"
* If the global setting is a checkbox (Show notifications, Audio API, Window API), don't show additional checkboxes for the exceptions. If the global setting is `on`, then any exceptions must necessarily be `off`, and vice versa. That way you make it impossible for dummies like me to set our settings backwards :-)
* If the global setting is a menu (Block mode, Highlight page action icon, Change toolbar icon), then the menus for the exceptions should include all options _except_ the option selected globally. That way, again, you make it impossible to create "exceptions" that aren't actually exceptions.

> I hope this all clears the issue.

Yes it does – thank you!

**Comment by kkapsner** [comment]
I would rather change "Site specific settings" to "Site specific value". I think "Exceptions" could also be confusing (it would confuse me).

There is a reason to have all possible values available for the site. Let's assume you have a page that needs specific settings to work properly. You set this up and everything is fine.
After some time (you completely forgot that you set up specific settings for the page) you change some global settings. Now the specifics could match the global setting but if we just take the opposite (on a checkbox) this might be exactly wrong. And for the menu the UI would be even more confusing on what options are displayed.

**Comment by practik** [comment]
> After some time (you completely forgot that you set up specific settings for the page) you change some global settings. Now the specifics could match the global setting but if we just take the opposite (on a checkbox) this might be exactly wrong.

Right, so you would never just automatically flip the site-specific settings to their opposites. Instead, if the user changes the global setting, any site-specific settings that match the new global value should be discarded. And the user should get a warning, something like: "Changing this setting will delete the site-specific settings below; do you want to do this?"

> And for the menu the UI would be even more confusing on what options are displayed.

I'm not sure which menu you mean. The one that drops down from the page action icon?

**Comment by kkapsner** [comment]
> And the user should get a warning, something like: "Changing this setting will delete the site-specific settings below; do you want to do this?"

And what if the users says "no"? Not change the global setting? This is not a route I want to go.

> I'm not sure which menu you mean. The one that drops down from the page action icon?

No, I meant for the dropdown menus in the options (like "block mode").

**Comment by practik** [comment]
> This is not a route I want to go.

Fair enough, but just to answer your questions:

> And what if the users says "no"? Not change the global setting?

Yes, exactly. The warning is just meant to protect the user who changes the global setting by accident, so that they don't have to recreate all their site-specific settings afterwards. Probably the warning I suggested above is too brief; something like this would be better: "This will change your global setting to match the site-specific settings below, so the site-specific settings will be discarded. Continue?"

> for the menu the UI would be even more confusing on what options are displayed

I don't see why. For example, if you have Block mode set to "Fake readout API" globally, then the menu for site-specific settings would simply include everything _but_ "Fake readout API."

Anyway, I'll drop this idea now, also because of https://github.com/kkapsner/CanvasBlocker/issues/247#issuecomment-419503400. I'll make another suggestion below.

**Comment by practik** [comment]
To make it clearer that the site-specific checkboxes/menus have exactly the same function as their global counterparts, you could align them vertically. So instead of this –

![audioapi](https://user-images.githubusercontent.com/12074235/45232920-638bb300-b28e-11e8-8e0f-c0b0f30cea04.png)

– it would look more like this:

## Audio API
````
Protect audio API
    Block audio fingerprinting on all websites              ☑︎
Site-specific settings (click arrow to add)                 ▼
    example1.com                                            ☐
    example2.com                                            ☐
    [          ] +

**Comment by kkapsner** [comment]
The alignment is a good idea. I just have to think about how to do it

**Comment by kkapsner** [comment]
I thought about it and saw that this would require a huge refactoring of the options UI. So I tend to not do it as it's not worth the effort. With the new descriptions and the setting sanitation we are already good enough. What do you think?

**Comment by practik** [comment]
> With the new descriptions and the setting sanitation we are already good enough

I agree! I'll close this now. Thanks for considering my ideas.
