### ISSUE TITLE
Instructions on how to whitelist specific sites

### ISSUE THREAD

**Issue by spodermenpls** [kkapsner/CanvasBlocker#248]
Adding websites to the site specific value menus of the Audio-, Window- and DOMRect API isn't self-explanatory, therefore I propose to add a text like "To exclude specific websites from this protection, click on the black arrow to open the menu, add the domain or URL by clicking on "+" and remove its checkmark." (or "Um bestimmte Seiten von diesem Schutz auszuschließen, klicken Sie auf den schwarzen Pfeil um das Menü zu öffnen, fügen Sie die gewünschte Domain oder URL mit einem Klick auf "+" hinzu und entfernen Sie das zugehörige Häkchen." in German) after each description of the mentioned APIs.

This instruction could also be modified and added for the block mode- ("To set individual block modes for specific websites, click on the black arrow to open the menu, add the domain or URL by clicking on "+" and select the desired block mode." - "Um individuelle Blockiermodi für bestimmte Webseiten festzulegen, klicken Sie auf den schwarzen Pfeil um das Menü zu öffnen, fügen Sie die gewünschte Domain oder URL mit einem Klick auf "+" hinzu und wählen Sie den gewünschten Blockiermodus.") and notification menu ("To deactivate notifications for specific websites, click on the black arrow to open the menu, add the domain or URL by clicking on "+" and remove its checkmark." - "Um Benachrichtigungen für bestimmte Webseiten zu deaktivieren, klicken Sie auf den schwarzen Pfeil um das Menü zu öffnen, fügen Sie die Domain oder URL mit einem Klick auf "+" hinzu und entfernen sie das zugehörige Häkchen.").

**Comment by kkapsner** [comment]
> which also should be converted into a "site specific whitelist".

What do you exactly mean by this?

**Comment by spodermenpls** [comment]
This was my first proposal from my other issue, the texts are not up-to-date with the current settings design.. will update them soon, wait for it.

**Comment by spodermenpls** [comment]
It's updated and polished. @kkapsner

**Comment by kkapsner** [comment]
Thanks.

**Comment by spodermenpls** [comment]
While we're at it, the addon description on AMO ("Ändert die JS-API zum Ändern von <canvas> um Canvas-Fingerprinting zu verhindern." / "Blocks the JS-API for modifying <canvas> to prevent Canvas-Fingerprinting.</canvas>") should be overhauled to acknowledge the extended functionality of CanvasBlocker. @kkapsner

**Comment by spodermenpls** [comment]
Good job.

**Comment by spodermenpls** [comment]
@kkapsner I noticed when looking through the descriptions, that the RNG ones are very cluttered, they could use an empty line in between each of them (all locales):

![cb](https://user-images.githubusercontent.com/23747593/45455011-fd67bb80-b6e5-11e8-8558-f61fcb29bae9.JPG)

I also think the description of the "logging level / Aufzeichnungslevel" could use a hint that the logging happens in the Browser Console (not in a file, like an user here thought some time ago). I would replace the current text with:
"To find the cause of an error, detailed logging of the addon activities is helpful. This parameter controls the level of detail of the logging, which can be viewed in the Browser Console." and
"Für eine Fehlersuche ist eine detaillierte Aufzeichnung der Addon-Aktivitäten hilfreich. Mit diesem Parameter kann der Grad der Detailliertheit dieser Aufzeichnung eingestellt werden, diese kann in der Browser-Konsole eingesehen werden."

**Comment by kkapsner** [comment]
Accepted your merge request.
I would change the text for the logging level a little bit:
`To find the cause of an error, detailed logging of the addon activities is helpful. This parameter controls the level of detail of the logging.
The logging can be viewed in the Browser Console (F12 resp. Ctrl-Shift-C).`
and 
`Für eine Fehlersuche ist eine detaillierte Aufzeichnung der Addon-Aktivitäten hilfreich. Mit diesem Parameter kann der Grad der Detailliertheit dieser Aufzeichnung eingestellt werden.
Die Aufzeichnung kann in der Browser-Konsole eingesehen werden kann (F12 bzw. Strg+Shift+C).`

**Comment by spodermenpls** [comment]
I would change your text for the logging level a little bit:

`To find the cause of an error, detailed logging of the addon activities is helpful. This parameter controls the level of detail of the logging. The logging can be viewed in the Browser Console (Ctrl+Shift+J).`

`Für eine Fehlersuche ist eine detaillierte Aufzeichnung der Addon-Aktivitäten hilfreich. Mit diesem Parameter kann der Grad der Detailliertheit dieser Aufzeichnung eingestellt werden. Die Aufzeichnung kann in der Browser-Konsole eingesehen werden (Strg+Umschalt+J).`

Your command opens the Web Console and not the Browser Console, which is better for this task.

**Comment by kkapsner** [comment]
Actually I had the Browser Console in mind... but I would include both as some things cannot be seen in the Browser Console (e.g. logged objects are only displayed as `<unavailable>` in the Browser Console).

So the Text will be:

To find the cause of an error, detailed logging of the addon activities is helpful. This parameter controls the level of detail of the logging.
The logging can be viewed in the Browser Console (Ctrl+Shift+J) and the Web Console (Ctrl-Shift-C).

Für eine Fehlersuche ist eine detaillierte Aufzeichnung der Addon-Aktivitäten hilfreich. Mit diesem Parameter kann der Grad der Detailliertheit dieser Aufzeichnung eingestellt werden.
Die Aufzeichnung kann in der Browser-Konsole (Strg+Umschalt+J) bzw. der Web-Konsole (Strg+Umschalt+C) eingesehen werden.

**Comment by spodermenpls** [comment]
"(Ctrl-Shift-C)" -> "(Ctrl+Shift+C)" und das "bzw." könnte auch wie im Englischen ein "und" sein.. ansonsten passt alles.

**Comment by spodermenpls** [comment]
@kkapsner Good job, again.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-RC1

**Comment by kkapsner** [comment]
0.5.4 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4
