### ISSUE TITLE
Reorder the block mode dropdown menu

### ISSUE THREAD

**Issue by CopperEyeWall** [kkapsner/CanvasBlocker#25]
The block mode dropdown menu is currently a bit confusing because the readout API entries are sandwiched between entries that apply to all canvas. Reorder the list to put the readout API entries at the bottom so that the all-canvas entries are together.

Suggested order (arranged from block -> allow for both the canvas and readout entries groups):
* block everything
* block only black list
* ask for permission
* allow only white list
* allow everything
  * [separator line]
* block readout API
* ask for readout API permission
* fake readout API

If possible, it'd be nice to add a separator line to the menu between the all-canvas and readout API sections to make clear the separation between them

Note that this would also include reordering the entries on the AMO descriptions pages for all languages.

**Comment by kkapsner** [comment]
I like the idea to separate the "readout-API" and the other stuff. But I put the readout on top. It's the better choice to use.

The separator is not possible with the normal SDK but I tweaked it a little bit (and filed a bug to include this in the official version) - check out my fork of the addon-sdk if you're interested.

The order of the other entries is in that way by purpose. At the beginning are the most restrictive ones and the further down it goes the more is allowed. So I will not change that order.

**Comment by CopperEyeWall** [comment]
The block mode menu entries order looked good and the separator appeared correctly when I tested v0.1.6-Development this evening. Thanks!
