### ISSUE TITLE
a few suggestions for reorganizing preferences

### ISSUE THREAD

**Issue by practik** [kkapsner/CanvasBlocker#251]
Now that CanvasBlocker has grown to include other APIs, the preferences could be a bit more logically organized:

1. Change the name of the Faking section to Canvas API.
2. Move the settings “Block mode” and “Store image for inspection” into the Canvas API section.
3. Move the three other API sections up so that all four API sections are together.
4. Two options for the “API whitelist” settings (aka “Protected API features”):
  a. Move them into a new section between Window API and Notifications.
  b. Break them up and move each API’s features into the appropriate API section. Building on the suggestion at https://github.com/kkapsner/CanvasBlocker/issues/245#issuecomment-419511152, that might look something like this:
````
Protect audio API
    Block audio fingerprinting on all websites              ☑︎
    Block/allow on specific websites (click arrow to add)   ▼
        example1.com                                        ☐
        example2.com                                        ☐
        [          ] +
    Block/allow specific API features on all websites       ▼
        getFloatFrequencyData                               ☑︎
        getByteFrequencyData                                ☑︎
        getFloatTimeDomainData                              ☑︎
        getByteTimeDomainData                               ☑︎
        getChannelData                                      ☑︎
        copyFromChannel                                     ☑︎
        getFrequencyResponse                                ☑︎
````
5. One last little thing: In the API Whitelist / Protected API Features section, there should not be any hyphens in the API names – e.g. “Canvas API,” not “Canvas-API."

**Comment by spodermenpls** [comment]
> "One last little thing: In the API Whitelist / Protected API Features section, there should not be any hyphens in the API names – e.g. “Canvas API,” not “Canvas-API.""

Are you using the German version? With commit eed3e670ce2beee6d748edf711f31ac9295fbea1 in effect next release, there should be not much hyphens left in the English locale..

**Comment by spodermenpls** [comment]
The mentioned API titles in the whitelist aren't part of the locale template, so they're "Germanized" for all languages - your turn, @kkapsner..

**Comment by practik** [comment]
Of course, if idea 4b is accepted, then 5 won't matter anymore :-)

**Comment by spodermenpls** [comment]
That is true indeed..

**Comment by kkapsner** [comment]
Very good input.

To 1.:
The faking section will stay there (the rng settings are API independent) but a separate canvas section makes totally sense.

To 2.: The block mode is also for all APIs. But the "store image..:" will go to canvas

To 3.: I would rather move the canvas section down. So the order will be:
* (empty section for the first three settings)
* asking
* faking
* notifications
* lists
* canvas API
* audio API
* history API
* window API
* DOMRect API
* misc
* settings

To 4.: b:
![grafik](https://user-images.githubusercontent.com/1105157/45392432-9edc0800-b627-11e8-8d25-6937d2b67617.png)

To 5.: obsolete due to 4b

**Comment by spodermenpls** [comment]
@kkapsner Your modified idea 4b is a good too, but could still use my descriptions then. #247 is no longer needed then, though.

**Comment by spodermenpls** [comment]
> the "arrow menus" should stay open when you left them open, when you close and re-open the CB tab.

@kkapsner Is this implementable, at least with an optional switch? This would make editing the site specifics a lot more convenient, re-opening menus (and finding the right one..) gets annoying after doing it for the 99th time..

**Comment by practik** [comment]
Ah, I didn't realize that block mode and RNG settings were for all APIs.  But I think these changes will make that clearer.

**Comment by kkapsner** [comment]
Saving the arrow state is possible and should not be too hard.

**Comment by kkapsner** [comment]
Please check https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-Alpha3 (the arrow thing is not yet in).

**Comment by spodermenpls** [comment]
The new setting page looks very neat, much better than before!

**Comment by spodermenpls** [comment]
@kkapsner By the way, when do you plan to lift the version count up to 1.0? Wouldn't the next release be a good candidate?

**Comment by practik** [comment]
I agree with spodermenpls, the new preferences look great. Thank you kkapsner for all the work!

**Comment by kkapsner** [comment]
Hm... I think CB is ready for 1.0 but I'm not sure if I am ;)

**Comment by spodermenpls** [comment]
Do you need help with replacing "0.5.4" with "1.0"? 😉

**Comment by kkapsner** [comment]
I will decide short before the release.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4-RC1

**Comment by practik** [comment]
I'm testing 0.5.4. RC2. All looks good in the prefs, but I notice that when I click on the page action icon, the "more" option is missing.

**Comment by practik** [comment]
And wow, there is a LOT of DOMRect faking happening on some webpages.

**Comment by spodermenpls** [comment]
@practik Take a look at the release notes: "notification details are not stored by default".. set a checkmark in the menu if you need the request details (needs potentially lots of RAM though, that's why it's disabled now by default).

**Comment by practik** [comment]
> notification details are not stored by default

Ah, that's what that means – I saw that preference but I thought it was just a reworded version of "Store image for inspection." Thank you.

> DOMRect

Yep, YouTube seems a prime offender here. Just loading an ordinary YouTube video page triggers 80–90 requests, and scrolling to the bottom and back to the top again adds about 400 more.

**Comment by kkapsner** [comment]
> And wow, there is a LOT of DOMRect faking happening on some webpages.

That's why I disabled notifications for DOMRect on my machine...

**Comment by kkapsner** [comment]
0.5.4 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4
