### ISSUE TITLE
Plugin stopped working - Not changing the value (No matter which option is chosen )

### ISSUE THREAD

**Issue by Sarah-ra** [kkapsner/CanvasBlocker#252]
## Description

Hey,

The plugin stopped working. I was relaxed that it was protecting but now it's been many days it's not working, I thought you were working to fix the bug but now it seems you're not even aware of this issue so updating you:

FYI: I set Random Number Generator: Non Persistence
but values don't change

I'm using:
Ver: Firefox Quantum 62.0 (also I checked with ver 58.1 by installing current ver and installing this old version)
Win 10 64 bit

I checked here https://canvasblocker.kkapsner.de/test/test.html and values don't change and above all I checked https://browserleaks.com/canvas here it always show me same Signature whether I refresh the browser or I close the browser and reopen it again or I check the link via another Firefox profile. It doesn't change the value and it always shows same the value (Signature). I bit worried about that it starting revealing my PC hardware id which isn't expecting after using your extension.

Any idea how it can be fixed?

Q) Do you have the firefox setting privacy.resistFingerprinting activated?
A) Yes

## Expected Behavior

It seems like a bug because it used to work and now it stopped working

## Current Behavior

As I explained above in detail, plugin always shows the same signature. I tested in many ways.

## Possible Solution

I don't know how to fix it. Looking for your suggestion to fix it.

## Steps to Reproduce (for bugs)

1. On Windows 10 (64 bit), either install Firefox 58.0.1 (32-bit) or 62.0 (32-bit)
2. Set the setting: Non Persistence 
3. Go to https://browserleaks.com/canvas Under signature: you will find a value. Now close the browser and visit the site again you will see the same value under signature whereas it should be changed.
4.

## Context

I was wondering my hardware id is secure and not revealed to anyone as plugin is installed (most trusted one) but not sure why this plugin stopped working.

## Your Environment

* CanvasBlocker Version used: 0.5.3
* Firefox version incl. 32- or 64-bit: 32 bit
* Operating System and version (desktop or mobile): Win 10 (64 bit)
* Installed addons: List of all plugins screenshot: https://s8.postimg.cc/netpmtixh/add.jpg

## Your Settings

{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "persistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1536613832643,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "blink",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "13",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}

**Comment by kkapsner** [comment]
With privacy.resistFingerprinting Firefox will not even allow CB to see the real content of the canvas. It will always return a white canvas. That's why you always get the same hash value (it shoult be `e5d9fd78536844cc8a4144ddb7a03eb9628f12c7c8b7828f942cadf6efb79ac0 / 03fedeb80c3f8ebf2ed864024e9967256468d64dbe847f202ad06a60f2b3d9b3` on https://canvasblocker.kkapsner.de/test/test.html )

Only if you grant the page access to the canvas content you will see different values for each reload.
![grafik](https://user-images.githubusercontent.com/1105157/45358045-78d34b00-b5c8-11e8-9ecf-e98ac83d7d2a.png)

**Comment by Sarah-ra** [comment]
Thanks it works. I'm going to change the rating from 3 to 5 Star as you helped me run the plugin and also for giving good support.

FYI: I didn't change the permission for the specific page (as you mentioned above) rather I disabled the setting in firefox about:config so that it works for all sites. Is it a right approach?

**Comment by kkapsner** [comment]
You can leave the setting in about:config. It's a privacy setting that is also used in the Tor Browser and it also does other things than protecting canvas data. 
The steps above are just to explain you how you can check if the addon is working properly and you can use it with RFP enabled.

PS: thanks for upgrading your rating.

**Comment by Sarah-ra** [comment]
Thanks, I just updated the rating to 5 and also added below note their so that people see you care about the users who use the plugin:

"UPDATE: I got the solution from developer on github, they are fast and impressed me with well descriptive answer and with screenshot. Now plugin is working just fine as it was."

You can cross check on review page it's 2nd review if you want. Thanks again 👍

**Comment by kkapsner** [comment]
You're welcome.
