### ISSUE TITLE
Create "sanitize settings" button

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#254]
As mentioned in #247 a button to check for weird/contrary/bad settings would be good.

Things to check:
* block mode vs protected APIs (e.g. fake input mode does nothing with window api)
* site specific value equal to general setting
* API protection enabled but all features disabled

Bonus: autoresolve (possible?)

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-RC1

**Comment by spodermenpls** [comment]
I like it, turned out very well. Good work.

**Comment by kkapsner** [comment]
Will do it tomorrow. Thanks for testing.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-RC2

**Comment by spodermenpls** [comment]
OK, the new toolbar search field is now just a shortcut to open the settings panel. That's definitely better than trying to squeeze the whole menu into the narrow toolbar, like in the first 0.5.4 Alphas.

**Comment by kkapsner** [comment]
I first thought about showing the result in the toolbar popup but this way is sufficient enough and was way easier to implement.

**Comment by kkapsner** [comment]
Version 0.5.5 is out and ready to use.
