### ISSUE TITLE
Silence intermittent failure to access "window" object

### ISSUE THREAD

**Issue by ssokolow** [kkapsner/CanvasBlocker#256]
CanvasBlocker sometimes assumes it can access the `window` object when that's not the case.

![screenshot17](https://user-images.githubusercontent.com/46915/45460222-2e39f780-b6ca-11e8-9048-47b24ecb78ac.png)

The error traces back to this line in `lib/require.js`:

```js
	window.scope = {};
```

## Expected Behavior

If the browser gives the extension unexpected/undesired input and the extension bails out early, that's sane... but it should do so without contributing to the flood of spurious error messages on the browser console.

## Current Behavior

CanvasBlocker is one of the many raindrops that leads to a flood of garbage making diagnostics difficult.

## Possible Solution

Wrap it in a try/catch so the browser knows that the behaviour in question is desired.

## Context

I've been going through my Browser Console, trying to clear out all the spurious cruft to make it easier to troubleshoot actual bugs and CanvasBlocker is currently contributing to the problem.

## Your Environment

* CanvasBlocker Version used: 0.5.3
* Firefox version incl. 32- or 64-bit: 63.0b4 (64-bit)
* Operating System and version (desktop or mobile): Kubuntu 14.04.5 LTS
* Installed addons:

```
Auto Tab Discard	0.2.8	true	{c2c003ee-bd69-42a2-b0e9-6f34222cb046}
Awesome RSS	1.3.4	true	{97d566da-42c5-4ef4-a03b-5a2e5f7cbcb2}
Behind The Overlay Revival	0.1.8	true	{c0e1baea-b4cb-4b62-97f0-278392ff8c37}
Bloody Vikings!	0.9.4	true	bloodyvikings@ffs.bplaced.net
CanvasBlocker	0.5.3	true	CanvasBlocker@kkapsner.de
Carefree Tumblr	0.1.0	true	{bb54be14-8b70-48a2-929b-2b26fa8bcca0}
Cookie AutoDelete	2.2.0	true	CookieAutoDelete@kennydo.com
cookies.txt	0.1	true	{12cf650b-1822-40aa-bff0-996df6948878}
Copy PlainText	1.8	true	copyplaintext@eros.man
Decentraleyes	2.0.7	true	jid1-BoFifL9Vbdl2zQ@jetpack
Disable HTML5 Autoplay	2017.12.20	true	disable-html5-autoplay@afnankhan
Download Star	2.0.2	true	{8cc0b007-e40b-46e8-9e50-e3bf021c94ab}
File Backups	0.3.5	true	file-backups@pmario.github.io
Google search link fix	1.6.7	true	jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@jetpack
Greasemonkey	4.7	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
HistoryBlock	2.0	true	historyblock@kain
HTTPS Everywhere	2018.8.22	true	https-everywhere@eff.org
In-Page Pop-up Reporter	1.6	true	{feb799e2-29e2-4e35-b862-cc4e1842b6f5}
InlineDisposition Reloaded	2.0.1	true	{914d3a0b-6982-4e58-9a60-2e5d6cf6b09b}
Link Cleaner	1.5	true	{6d85dea2-0fb4-4de3-9f8c-264bce9a2296}
Multiple Tab Handler	2.1.4	true	multipletab@piro.sakura.ne.jp
No Transition	1.1.8	true	{8b5fde66-c64d-4a33-99f1-c7c94138d67e}
Open in Sidebar	2018.7.26	true	open-link-in-sidebar@afnankhan
PinPatrol	0.4	true	@PinPatrol
Pure URL	1.3.0a	true	pure-url@jetpack
Random User-Agent	2.2.6	true	{b43b974b-1d3a-4232-b226-eaa2ac6ebb69}
Reload in address bar	1.3	true	{e1ed7a80-7c11-4f7e-968b-79b551a0067f}
Resurrect Pages	7	true	{0c8fbd76-bdeb-4c52-9b24-d587ce7b9dc3}
Select Link Text	2017.3.26	true	select-link-text@afnankhan
Session Boss	1.5	true	sessionboss@william.wong
Stylus	1.4.21	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
SuperStop	0.3	true	superstop@gavinsharp.com
Tab Count	1.0	true	tabcount@grepper.net
Tree Style Tab	2.5.4	true	treestyletab@piro.sakura.ne.jp
uBlock Origin	1.16.20	true	uBlock0@raymondhill.net
uMatrix	1.3.14	true	uMatrix@raymondhill.net
Unpaywall	3.77	true	{f209234a-76f0-4735-9920-eb62507a54cd}
Web ScrapBook	0.27.0	true	webscrapbook@danny0838.addons.mozilla.org
Aggregate Tabs to Main Window	1.3.0	false	aggregate-tabs-to-main-window@piro.sakura.ne.jp
cliget	2.0.0	false	cliget@zaidabdulla.com
Form History Control (II)	2.2.0.0	false	formhistory@yahoo.com
JSONovich	2.1.2	false	jsonovich@lackoftalent.org
Privacy Settings	0.3.4	false	jid1-CKHySAadH4nL6Q@jetpack
withExEditor	5.4.1	false	jid1-WiAigu4HIo0Tag@jetpack
YouTube Feeds	0.1.4	false	{e347026e-9666-402e-841e-20c9ec56c8ad}
```

(Sorry for the format. I just spent 15+ minutes waiting for Firefox to start responding after it seized up due to the bug in Form History Control that I was trying to diagnose when I encountered this error message and I don't have the patience to manually fix up the tab stops. Heck, I copy-pasted everything from "Your Environment" down from #255 since nothing has changed in the last few minutes.)

## Your Settings
```json
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1536791621802,
	"askOnlyOnce": "combined",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "16",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}
```

**Comment by kkapsner** [comment]
I never saw this error. And this is serious issue as it indicates that CanvasBlocker is not working at all. It seems to me that some other extension messes with the window object.

In such a case I have to inform the user somehow. In other cases I could use the CB internal error logging (which can be disabled) but at this fundamental stage even that system is not working. So there is little I can do for you.

**Comment by ssokolow** [comment]
According to the developer of Stylus (the source of the other `Permission denied to access property "window"` message, this is an assert("this should never happen") sort of thing and the inability to access the window object represents a violation of Firefox's API contract. (I suspect it to be some kind of race condition within Firefox itself, given the circumstances which managed to produce it.)

Unfortunately, because I only saw the error in hindsight, I have no idea when it was produced.

If you're willing to help, I'd suggest surfacing it in a way that would help me notice in time to narrow down some Steps To Reproduce if it happens again.

**Comment by kkapsner** [comment]
Sure I'm willing to help. Not sure what kind of notification you mean. An alert()?

**Comment by ssokolow** [comment]
I was imagining a checkbox under "Expert mode" which would request the WebExtensions `notifications` permission when checked and then emit whatever "Logging level" filters for as desktop notifications so they wouldn't potentially get missed if, for example, they get emitted by a browser window that's covered up by something else.

(My window manager has its "focus-stealing prevention" option raised above the default level and I tend to watch videos set "Always On Top" on my left-hand monitor, which covers up two of my four Firefox windows.)

**Comment by kkapsner** [comment]
I thought about it and I am not able to ship something as with such errors the settings system is not even working.

As for the Debug-Beta: I'm sorry but I have no time for it.

But from the screenshot I got a hint that the problem occured when you opened the about:addons page. So I hope you are (or were) able to find your culprit that's the root of the problem.
