### ISSUE TITLE
Audio Context Not Spoofed  When "Protect Audio API" Checked

### ISSUE THREAD

**Issue by Kraxys** [kkapsner/CanvasBlocker#258]
I checked  "Expert Mode" and "Protect Audio API". The entries below "Protect Audio API" let me think that CB was going to fake audio context, as it fakes canvas.

It tried to test this audio faking feature on https://audiofingerprint.openwpm.com. But the test failed,  because no results appeared. It was much more like the "Protect Audio API" had blocked, not spoofed, the Audio fingerprint. 

Without "Protect Audio API" checked, the results on https://audiofingerprint.openwpm.com clearly shows my browser is fingerprinted (same values from a session to an other).

The extension [Audiocontext-Fingerprint-Defender](https://addons.mozilla.org/en-US/firefox/addon/audioctx-fingerprint-defender) is able to fake results on the previous test page. So I think it's possible to  improve CB concerning Audion Context Spoofing. 

I used CB v 0.5.3 on a fresh portable profile of FF (60 ESR 64 bit) on Windows 7, with no other addons.

My CB Settings:
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1537043917489,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "4",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}

**Comment by kkapsner** [comment]
This test page is written very poorly. That's why it takes very long to compute with CB enabled. You can disable the audio cache to speed things up (not recommended for regular use). Or you can use my test page: https://canvasblocker.kkapsner.de/test/audioTest.html
