### ISSUE TITLE
Suggested changes to the English translation

### ISSUE THREAD

**Issue by CopperEyeWall** [kkapsner/CanvasBlocker#26]
Suggested changes to fix misc. typos (missing commas, "separate", "commas", "nevertheless") and clarify a few descriptions in the English translation (/locale/en-US.json):
* "whiteList_description": "Domains or URLs where the <canvas> API should not be blocked. To add multiple entries, separate them by commas."
* "blackList_description": "Domains or URLs where the <canvas> API should always be blocked. To add multiple entries, separate them by commas."
* "ignoreList_description": "Domains or URLs where no notification will be shown. To add multiple entries, separate them by commas."
* "askOnlyOnce_description": "When Canvas Blocker's Block mode is set to 'ask permission' or 'ask permission for readout API', a confirm message will appear every time a page tries to access the <canvas> API or readout API. This setting tries to display the confirm message only once for each page regardless of how many times the page tries to access the API. Nevertheless, multiple confirm messages may still be displayed on some pages."
* "allowPDFCanvas_description": "Firefox's native PDF reader uses the <canvas> API to display PDF content. If this setting is unchecked when viewing a PDF, Canvas Blocker may display multiple ask dialogs or the PDF reader may not work at all."

No idea if the same typos are in other translations.

**Comment by kkapsner** [comment]
To be honest, I once wrote the English translation and did not look at it further... I use the German one.

Thank you for your finding. Hopefully I removed all typos.
