### ISSUE TITLE
Is that normal?

### ISSUE THREAD

**Issue by BugFeedback** [kkapsner/CanvasBlocker#260]
## Description

https://passport.taobao.com/ac/password_find.htm?from_site=0
This website's Verify image, scrape the two chicks will cause CanvasBlocker make hundreds stuff (931). 

## Your Environment

* CanvasBlocker Version used:0.5.3
* Firefox 62 64-bit
* Win10 and desktop
* Installed addons:
CanvasBlocker alone addon tested

## Your Settings

Default settings

**Comment by kkapsner** [comment]
I would say that's not normal and the website should improve their script to be more performant.
The next version of CB will have a better performance in such cases when hundreds of calls are made, but it still will be noticeable.
