### ISSUE TITLE
CanvasBlocker cause firefox slow down in a website

### ISSUE THREAD

**Issue by BugFeedback** [kkapsner/CanvasBlocker#261]
## Description

CanvasBlocker cause firefox slow down in a website

## Steps to Reproduce (for bugs)

1.https://mailchimp.com/
sign up
2.https://us19.admin.mailchimp.com/signup/new-user/welcome/
when complete mail verification,go to that step website, CanvasBlocker will cause slow down firefox.
![bug](https://user-images.githubusercontent.com/41504474/45605676-46669980-ba71-11e8-813a-b97340e540cc.png)

## Your Environment

* CanvasBlocker Version used:0.5.3
* Firefox 62 64-bit
* Win10 and desktop
* Installed addons:
CanvasBlocker alone addon tested

## Your Settings

Default settings

**Comment by kkapsner** [comment]
Well... they are using a very badly written audio fingerprinting script:
![grafik](https://user-images.githubusercontent.com/1105157/45652234-421f9800-bad4-11e8-956a-e55d4b037997.png)
(I think they just copied the bad code from https://audiofingerprint.openwpm.com/ - see also https://github.com/kkapsner/CanvasBlocker/issues/71#issuecomment-401638063, #216, #235, #258)

You can disable the audio cache if you want to... but I do not recommend it. (Well I think I should make the audio cache a setting that can also be set on a page by page basis.)

**Comment by kkapsner** [comment]
0.5.4 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4

With this version you can disable the audio cache for specific pages.

**Comment by BugFeedback** [comment]
> 
> 
> 0.5.4 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4
> 
> With this version you can disable the audio cache for specific pages.

find another website are same causing firefox slow down in 0.5.4.
http://www.youku.com/
add in exclude specific list seems still slow down.

**Comment by kkapsner** [comment]
This time it's the DOMRect API... I have no clue what they are doing but I guess that it's just poorly written (e.g.YouTube uses DOMRect also very extensively and faces no slowdown).
You can disable the DOMRect API for this specific domain.

**Comment by BugFeedback** [comment]
> 
> 
> It's the audio API for sure (if you disable the audio cache it's a little bit faster - but I do not recommend doing that).
> If you look at the filename that calls the audio API you know what they are trying to do there: https://j1.58cdn.com.cn/resource/xxzl/tracker/nfp.js
> The code is highly obfuscated but I would bet they just use the bad code from https://audiofingerprint.openwpm.com/

Yes, you are right.
Now that I block this link in ublock, works smooth and normal.
`||58cdn.com.cn/resource/xxzl/tracker/*`
