### ISSUE TITLE
Strange errors surrounding "require" in blank new tabs

### ISSUE THREAD

**Issue by ssokolow** [kkapsner/CanvasBlocker#265]
## Description

A fresh Nightly profile with new tabs set to open as blank pages triggers odd errors about `require` from CanvasBlocker in the browser console.

## Expected Behavior

I should see no error message in the browser console.

## Current Behavior

I see this message at the browser console every time I click New Tab under the test profile:

```
[CanvasBlocker] invalid content scripts: require not defined at about:blank aa1843e1-adea-4214-8266-894f177b9cb5:13:9
    <anonymous> blob:moz-extension://bf5304fa-a342-47a8-a165-1b6c8fbbb190/aa1843e1-adea-4214-8266-894f177b9cb5:13:9
    <anonymous> blob:moz-extension://bf5304fa-a342-47a8-a165-1b6c8fbbb190/aa1843e1-adea-4214-8266-894f177b9cb5:1:2
SyntaxError: redeclaration of const require require.js:1:1 
```

## Steps to Reproduce (for bugs)

1. Create a new Firefox Nightly profile
2. Install CanvasBlocker
3. Open the Browser Console
4. Go to Preferences > Home and set "New tabs: Blank Page"
5. Click the New Tab Button

## Context

I was trying to reproduce another spurious error involving CanvasBlocker and blank new tabs but the fresh Nightly profile produced this instead of "Dynamic content script was too late to provide settings."

## Your Environment

* CanvasBlocker Version used: 0.5.3
* Firefox version incl. 32- or 64-bit: 64.0a1 (2018-09-16) (64-bit)
* Operating System and version (desktop or mobile): Kubuntu Linux 14.04.5 LTS
* Installed addons:

   ```
   CanvasBlocker		0.5.3	true	CanvasBlocker@kkapsner.de
   ```

## Your Settings
```
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"apiWhiteList": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1537209658164,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeImageForInspection": false,
	"notificationDisplayTime": 30,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "6",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.3
}
```

I'm assuming that `"isStillDefault": false,` was caused by my having to enable expert mode to access the settings export. The steps to reproduce are **exactly** what I did.

**Comment by ssokolow** [comment]
I know the feeling. I've filed roughly a dozen bugs on Firefox in the last week now that I don't have 52 ESR to cling to.

**Comment by kkapsner** [comment]
Done: https://bugzilla.mozilla.org/show_bug.cgi?id=1491994

As this does not really affect CBs behaviour I will close this issue.

**Comment by kkapsner** [comment]
Kind of "funny": if I replace the "const" with a "var" is works...
But the first message still appears - have to file a separate bug for that.

**Comment by kkapsner** [comment]
Hm... they changed the title to "Content scripts sometimes run twice for about:blank" which makes sense and also explains the first message.

**Comment by kkapsner** [comment]
I was able to confirm the double execution.
