### ISSUE TITLE
Microsoft Exchange Admin Center does not work with 0.5.4. RC2

### ISSUE THREAD

**Issue by crssi** [kkapsner/CanvasBlocker#267]
Unfortunately I cannot provide access to company control panel.
I tried to disable all protections, add to whitelist..., and still no joy, the only thing that work is to completely disable addon.

This is not critical at all, I can still use some other browser to use that page, but if I can help you to make your addon more perfect with some error logs, let me know/give instructions.

Cheers

**Comment by crssi** [comment]
Another MS page: [https://docs.microsoft.com/en-us/iis/manage/powershell/powershell-snap-in-run-time-data](https://docs.microsoft.com/en-us/iis/manage/powershell/powershell-snap-in-run-time-data)

Scroll page and observe the left tree control menu.

**Comment by crssi** [comment]
Images are missing on the page: [https://www.had.si/blog/2014/02/24/kam-na-najboljsi-hamburger-v-ljubljani/](https://www.had.si/blog/2014/02/24/kam-na-najboljsi-hamburger-v-ljubljani/)

**Comment by kkapsner** [comment]
I'm not able to reproduce any of your problems... please make a screenshot of what is wrong - maybe I miss it.

Can you please test with a fresh profile with only CB installed.

**Comment by crssi** [comment]
I am sorry to false alarm you, feel like a total noob now. :smile: 

The problem was in my user.js:

``` js
user_pref("dom.IntersectionObserver.enabled", false);
```

The FF default value is `true`, returning to default resolves the problem.

With value of `false` the CB 0.5.3 is working fine, but 0.5.4 RC2 not anymore.

**Comment by kkapsner** [comment]
Thanks for the explanation. This is not a false alarm and I know how to fix it.

**Comment by kkapsner** [comment]
0.5.4 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.4
