### ISSUE TITLE
Iridium by ParticleCore breaks with CanvasBlocker 0.5.4

### ISSUE THREAD

**Issue by Forsaked** [kkapsner/CanvasBlocker#269]
## Description
[Iridium](https://github.com/ParticleCore/Iridium) by @ParticleCore breaks after installation of Canvas Blocker 0.5.4 while using the [gHacks User.js](https://github.com/ghacksuserjs/ghacks-user.js).

## Expected Behavior
Whitelisting of the [Settings Page](https://www.youtube.com/iridium-settings) of Iridium should let it work.

## Current Behavior
Whitelisting of the [Settings Page](https://www.youtube.com/iridium-settings) of Iridium doesn't work, it's still gets an `404 Not Found` Error.
Disabling every option in Canvas Blocker also doesn't change anything.
Only disabling Canvas Blocker let it work again.

## Possible Solution
I have no Idea.

## Steps to Reproduce (for bugs)
1. create a fresh Firefox Profile
2. insert [gHacks User.js](https://github.com/ghacksuserjs/ghacks-user.js) into Profile folder
3. restart Firefox with new Profile
4. install Iridium
5. check if it works
6. install Canvas Blocker 0.5.4
7. check if Iridium still works
8. it should be broken now

## Context
Everything worked with Canvas Blocker 0.5.3 in combination with the [gHacks User.js](https://github.com/ghacksuserjs/ghacks-user.js) and [Iridium](https://github.com/ParticleCore/Iridium).
It also works without the [gHacks User.js](https://github.com/ghacksuserjs/ghacks-user.js) and with Canvas Blocker 0.5.4.
After the installation of Canvas Blocker 0.5.4 while using the [gHacks User.js](https://github.com/ghacksuserjs/ghacks-user.js), the Browser Console start putting out following Errors when i try to access the [Settings Page](https://www.youtube.com/iridium-settings) of Iridium:

`
Error: WebExtension context not found! ExtensionParent.jsm:1014:13
too much recursion check.js:22:3
TypeError: window.IntersectionObserverEntry is undefined modifiedDOMRectAPI.js:347:22
Error: WebExtension context not found! ExtensionParent.jsm:1014:13
TypeError: window.IntersectionObserverEntry is undefined modifiedDOMRectAPI.js:347:22 
 `

## Your Environment
* CanvasBlocker Version: 0.5.4
* Firefox Version: 62.0.2 x64
* Operating System: Windows 10 Pro 1803
* Installed addons: Iridium, Canvas Blocker
* Custom Stuff: gHacks User.js

## Your Settings
It doesn't make any difference if i use the standard settings or custom settings.

**Comment by Forsaked** [comment]
This was fast, with the RC-Version this happend, with the release of the Final-Version it is solved.

**Comment by kkapsner** [comment]
This looks similar to #267 - I thought I fixed that... well I have a look and see what I can do about it.

**Comment by kkapsner** [comment]
Ah... great when it's solved with the final version.
