### ISSUE TITLE
Slight display issue with toolbar badge

### ISSUE THREAD

**Issue by spodermenpls** [kkapsner/CanvasBlocker#271]
## Description

This issue only affects the CanvasBlocker badge when you put it in the "toolbox" door-hanger menu (my preferred location).

## Current Behavior

When there are 3 or more affected APIs, that get displayed while surfing the web, the toolbar gets wider accordingly to make room for more API names, but the space in the title bar doesn't get used, it always gets cut off after two API names.

Example with 3 APIs:
![cb1](https://user-images.githubusercontent.com/23747593/45992618-28a9bd80-c08b-11e8-957f-8555f58b6da3.JPG)
![cb2](https://user-images.githubusercontent.com/23747593/45992619-2c3d4480-c08b-11e8-9cad-153bbd398979.JPG)

Example with 4 APIs:
![cb3](https://user-images.githubusercontent.com/23747593/45992621-2e9f9e80-c08b-11e8-972a-08e73f2a0071.JPG)

## Possible Solution

The "adaptive widening" of the badge menu should be either removed, or the toolbar menu should be adjusted in a way that it's able to display 3, 4 or more API names by using the added width.

## Steps to Reproduce (for bugs)

1. Put the toolbar badge in FF's "More tools.." menu
2. Visit a website that affects 3 or more APIs (e.g. facebook.com with 3 APIs in use and the CB test page with 4 APIs, as used for my screenshots)
3. watch the menu adjust its width, but not using the new space

## Context

_"What are you trying to accomplish?"_ Enjoying an aesthetically pleasing toolbar menu.

## Your Environment

* CanvasBlocker Version used: 0.5.4
* Firefox version: 62.0.2 - 64 bit
* Operating System and version (desktop or mobile): Windows 10 Pro
* Installed addons: lots..

**Comment by kkapsner** [comment]
Unfortunately I cannot do anything about that as this whole width adapting and the wrong display are managed by Firefox itself and not the extension. You can see the same behaviour in NoScript for example.

Please open a bug for firefox (http://bugzilla.mozilla.org/)

**Comment by spodermenpls** [comment]
You're right, the issue seems to be a Firefox regression from either the 62.0 or 62.0.2 update, the issue is the same with the first Alpha, which definitely didn't have this width adaption thing going on (I think I would've noticed, I opened that menu about 800 times during the development phase of 0.5.4..).

**Comment by spodermenpls** [comment]
@kkapsner New trouble with the menu (tested with 0.5.9.1 and 0.5.10. RC3):
![cbrc3](https://user-images.githubusercontent.com/23747593/58640025-73ee2d00-82f8-11e9-9338-e8c648c0be5d.JPG)

![cb](https://user-images.githubusercontent.com/23747593/58640684-e6134180-82f9-11e9-995d-a562c2dcf372.JPG)

After clicking the empty Window API checkbox, everything gets unresponsive, and the "OK"/"Cancel" buttons appear at the very end of the menu.

**Comment by kkapsner** [comment]
Great - they did not fix that... and creating a good position for a dialog is quite a challenge.

Funny enough this problem is fixed in the nightly built.

**Comment by kkapsner** [comment]
It's even fixed in beta. But I think I like the dialog I built:
![image](https://user-images.githubusercontent.com/1105157/58670429-52646400-833f-11e9-944a-ff6e8fcc6fbf.png)

**Comment by spodermenpls** [comment]
Good job!

**Comment by spodermenpls** [comment]
@kkapsner And more trouble, this time adequate to this issue's title - of the four toolbar menu options (Settings, Testing, Rating, Reporting) only "Settings" works, the other three are not opening the intended sites. Are those working with Beta and Nightly again?

**Comment by kkapsner** [comment]
It's working for me in beta, nightly and normal (67.0). Are they opening wrong sites or do they do nothing?

**Comment by spodermenpls** [comment]
They didn't do anything - after a restart they're working again now, though.. still weird, that one worked (internal link) and three didn't (external links), maybe there's more to it than just a Firefox hiccup.

**Comment by kkapsner** [comment]
Your Firefox is weird sometimes... ;)
But without further information I cannot investigate more. If it happens again you should look at the browser console (Ctrl+Shift+J) if there is something related.

**Comment by spodermenpls** [comment]
Your extension is weird.
I guessed so, I will continue to have a close look on the menus, and will check the consoles in case of malfunctions.

**Comment by spodermenpls** [comment]
@kkapsner I've got another one for you: when I hover over the second URL (in case there is a second line) in the page action toolbar, the text starts bouncing up and down like crazy, making it impossible to access the whitelist options:
![Unbenannt](https://user-images.githubusercontent.com/23747593/59142188-6a308d80-89ba-11e9-86c0-a7e28136dbdb.JPG)
Do you reproduce?

**Comment by kkapsner** [comment]
No - I do not reproduce, but it looks bad:
![image](https://user-images.githubusercontent.com/1105157/59146031-6453a000-89ec-11e9-84c8-076890e2225d.png)

**Comment by kkapsner** [comment]
You can check the new alpha: https://canvasblocker.kkapsner.de/versions/

**Comment by spodermenpls** [comment]
@kkapsner Yes, that solved it, thanks.

**Comment by spodermenpls** [comment]
@kkapsner While checking my site-specific values to see what sites need to be whitelisted to work, I noticed that my existing two entries no longer are shown, inspite of still being active:
![cb](https://user-images.githubusercontent.com/23747593/61130800-d6217c80-a4b7-11e9-8860-3484abbc789c.JPG)
![cb2](https://user-images.githubusercontent.com/23747593/61130837-ea657980-a4b7-11e9-82c6-257ba8cf0670.JPG)
![cb3](https://user-images.githubusercontent.com/23747593/61130840-ed606a00-a4b7-11e9-9f7f-955644fd6da6.JPG)
![cb4](https://user-images.githubusercontent.com/23747593/61130846-f05b5a80-a4b7-11e9-886f-90e043b7f457.JPG)

**Comment by kkapsner** [comment]
Please give me your settings to check. Which version are you currently on?

**Comment by spodermenpls** [comment]
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "slither.io",
			"blockMode": "allowEverything"
		},
		{
			"url": "^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$",
			"protectWindow": false
		}
	],
	"hiddenSettings": {
		"displayAdvancedSettings": false,
		"displayDescriptions": false,
		"displayBadge": false
	},
	"expandStatus": {
		"blockMode": false,
		"useAudioCache": false,
		"protectedCanvasPart": false,
		"protectWindow": false,
		"protectAudio": false,
		"protectNavigator": false,
		"protectDOMRect": false
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 1000000,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {
		"name": true,
		"opener": true
	},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1562700453860,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {
		"history": false,
		"window": false
	},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "29",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}


I am on Firefox 68.0 and CB 0.5.12.

**Comment by kkapsner** [comment]
OK - found the issue.

**Comment by spodermenpls** [comment]
I've ran into another display issue concerning the settings menu - when making changes (adding / deleting URL entries, enabling the view of previously hidden settings) requires an individual reload of the page to be visible. I've wanted to delete an item from the "Data URL"-specific list, and pressing the "X" had no effect, so I de- and re-enabled CB, reset the settings, then restarted FF and finally de- and re-installed CB altogether, to no avail, until I noticed that the culprit is really only the lack of "instant refresh" of the settings page, which for some odd reason doesn't work anymore. Do you reproduce, and / or maybe have an idea what it could stem from?

**Comment by kkapsner** [comment]
Well... the new settings management of Firefox for web-extensions was not very reliable from the get go. (And also in Thunderbird.)

So everything is working now?

**Comment by spodermenpls** [comment]
Yes, it works normally again, so far.
