### ISSUE TITLE
Bug on google image

### ISSUE THREAD

**Issue by grysor** [kkapsner/CanvasBlocker#272]
Hello, I have canvasblocker version 0.5.4
i have a pc desktop with windows10 pro up to date
-I am under firefox quantum 62.0

There is a bug :
On google image for example here :
https://www.google.fr/search?biw=1450&bih=744&tbm=isch&sa=1&ei=UMOqW5_YLoTMrgTRpICgAg&q=fleurs&oq=fleurs&gs_l=img.3..0l10.179788.181940.0.182218.6.5.0.1.1.0.99.487.5.5.0....0...1c.1.64.img..0.6.490...0i67k1.0.q-qybWHb8Dc
when I click on images, very often nothing happens! While normally the thumbnail of the image should appear with next write: consult - share
And when I disable canvasblocker, then reload the page, this time all the images are again clickable and thumbnails with consult-share are re-displayed.

can you fix this problem please?thank you

**Comment by Reeywhaar** [comment]
Hello! Same for me on images.google.com. I have attached settings (github doesn't allow .json uploads so I changed extension to .txt) [CanvasBlocker-settings.txt](https://github.com/kkapsner/CanvasBlocker/files/2424609/CanvasBlocker-settings.txt)

I see in console, that every time I click on any image message "TypeError: a is undefined, can't access property "nextElementSibling" of it" shows up.

Also in the console there is an error message somehow related to content security policy [error-msg.txt](https://github.com/kkapsner/CanvasBlocker/files/2424624/error-msg.txt). So it maybe that extension denies execution of some inline scripts which breaks service.

Thank you!

**Comment by kkapsner** [comment]
Weird... still not able to reproduce the problem. Even with your settings.

Please try with disabled "Block data URL pages":
![grafik](https://user-images.githubusercontent.com/1105157/46161352-9f120f80-c285-11e8-9627-50c5f54b2b4b.png)

Which other addons do you have installed?
Still a test with a fresh profile could help.

**Comment by Reeywhaar** [comment]
No luck. By the way, I forgot the browser version I use: FF63b.5 (64bit) @ osx 10.13.6

**Comment by kkapsner** [comment]
I had a closer look at the csr message. "d2630e41-b004-4080-9716-5724fdbcdc2b" looks like an extension internal uuid. Please check which this is (on about:debugging#addons you can see the Internal UUIDs).

**Comment by Reeywhaar** [comment]
I found that problem caused by `Protect DomRectApi` being on.

**Comment by kkapsner** [comment]
Yes.. but why? I have no problems with it. There has to be something else which breaks in combination with that.

**Comment by Reeywhaar** [comment]
But that narrowed the problem.

As for uuid they are random on every load, and no extension with such uuid exists, I don't think they related. Also, I tried to disable every other extension to check is there any interference.

**Comment by kkapsner** [comment]
Yes it narrows the problem down. But actually I already had it in mind as it's the big change for 0.5.4

Any luck finding the interfering extension?

PS: the uuid should be random but should stay constant across browser restarts. At least they are on my limited tests.

**Comment by Reeywhaar** [comment]
I meant that uuid in error-msg.txt you said is random on every google images page reload.

There is no interfering exception as long as I can see. With only Canvas Blocked being enabled problem still present.

What I can't understand is that message in error-msg.txt is just that some script saw reported for csp violation, not blocked. But it obvious that some scripts were blocked in fact :-/

**Comment by kkapsner** [comment]
That's very weird. Does the error-msg also appear when CB is disabled?

Have you tried with a fresh Firefox profile?

**Comment by Reeywhaar** [comment]
No, there is no message with addon disabled.
Yes, problem is present with fresh FF profile with only canvas blocked installed. Really weird.

**Comment by Reeywhaar** [comment]
As a workaround for now adding "google.com" disabled to site specific values helps.
![screen](https://user-images.githubusercontent.com/884649/46165694-f28e5880-c299-11e8-834d-868c7ea11421.png)

**Comment by kkapsner** [comment]
So the scenario is:
* create a fresh firefox profile
* install CB
* go to images.google.com -> the csr message appears and the display is broken

Correct?

**Comment by Reeywhaar** [comment]
Yes, [my test link](https://www.google.com/search?rls=ig&hl=en&biw=1066&bih=661&gbv=2&tbm=isch&sa=1&q=linus+windows&btnG=&oq=&gs_l=#imgrc=olQlqFmrYAi_XM:)

**Comment by kkapsner** [comment]
Seems simple enough... but still no luck on my site... I will try on Windows...

**Comment by Reeywhaar** [comment]
I narrowed down even more. While in expert mode, disabling "getBoundingClientRect" in DomRect api removes bug.

**Comment by kkapsner** [comment]
Good to know. But as I'm still not able to reproduce the problem I still do not know how to fix this.

Also on Windows 10 no luck. Everything works for me.

**Comment by Reeywhaar** [comment]
Oh, about the error msg that I told earlier, it appears that it doesn't correlate with addon in any way, it just sometimes appears, and sometimes not, sometimes immediately, sometimes after delay. So don't bother with it. Sorry for misinformation.

**Comment by Reeywhaar** [comment]
I'm on Mac myself. Did you try with Firefox Beta?

**Comment by kkapsner** [comment]
No - I try with 62.0.2 and the nightly. I will try beta.

**Comment by kkapsner** [comment]
Regarding the error msg: it might be an ad...

**Comment by grysor** [comment]
> 
> 
> Hm... please give me you CanvasBlocker Settings (you may want to delete the persistent storage and some private informations:
> ![grafik](https://user-images.githubusercontent.com/1105157/46126465-aa395100-c22d-11e8-87a0-d9d40381a584.png)
> 
Hello :) 
here are my canvasblocker settings, but I have not changed much because I'm a novice ...  :
[CanvasBlocker-settings.txt](https://github.com/kkapsner/CanvasBlocker/files/2425428/CanvasBlocker-settings.txt)


> I did not mean you should reset your Firefox but to create a new profile (open the command line prompt and start Firefox with the --no-remote and -p flag: `{path to firefox}\firefox.exe --no-remote -p`)

for this, I will not know how to do it I'm a novice, sorry :(

**Comment by Reeywhaar** [comment]
I'm digging it. Replacing `registerDOMRect` in `modifiedDOMRectAPI.js` with noop solves the problem, I think at least I could found the problem myself, maybe it will give you a hint later. I understand that it's hard to find the problem on site such as Google, there may be tons of regional specific settings.

**Comment by grysor** [comment]
> So, I have found where the problem is, and for sure, the best solution is just to add google.com to exceptions.

Hello 
that is true? if i put google.com to exceptions, this will fix the problem and the pics on google images will be clickable again? :)  I will try, thanks to you if it works I will make a return then :)

**Comment by grysor** [comment]
I have whitelisted googgle.com and it still does not work, just the first 3 pics in google image are clickable. For all the others, nothing happens when I click on it :(

**Comment by Reeywhaar** [comment]
@grysor there are many solutions. [see my comment](https://github.com/kkapsner/CanvasBlocker/issues/272#issuecomment-425191083) for first solution. The second is to change random number generator to `persistent`

![screen shot 2018-09-28 at 00 40 47](https://user-images.githubusercontent.com/884649/46176193-36438b00-c2b7-11e8-900b-956b3bd6e4b9.png)

**Comment by grysor** [comment]
@Reeywhaar 
this solution that you posted?  :

> As a workaround for now adding "google.com" disabled to site specific values helps.
> ![screen](https://user-images.githubusercontent.com/884649/46165694-f28e5880-c299-11e8-834d-868c7ea11421.png)

**Comment by Reeywhaar** [comment]
Yeah, doesn't it work?

**Comment by grysor** [comment]
Or does your other solution seem the best? :)
thank you in any case for your help and your solutions :) 

> ![screen shot 2018-09-28 at 00 40 47](https://user-images.githubusercontent.com/884649/46176193-36438b00-c2b7-11e8-900b-956b3bd6e4b9.png)

**Comment by Reeywhaar** [comment]
I think `persistent` solution more fail proof because, I'm not sure, but I think I saw the same problem on other websites.

**Comment by grysor** [comment]
Thank you for your answer
I'm going to add google.com in "protect DOMRect API" so, great, thank you :)

**Comment by grysor** [comment]
I'm disgusted, after doing it, I tried again and it still does not work for me, I can not click on any pic :(

**Comment by grysor** [comment]
by contrariwise, your second solution works like a charm, she ! :) 
all the pics are again clickable in google image!
> ![screen shot 2018-09-28 at 00 40 47](https://user-images.githubusercontent.com/884649/46176193-36438b00-c2b7-11e8-900b-956b3bd6e4b9.png)

**Comment by Reeywhaar** [comment]
Well, that great! As I said, maybe you're using regional google domain so adding just `google.com` will not work, that why solution above is more concrete.

**Comment by kkapsner** [comment]
@Reeywhaar thanks for the great analysis. I could change the cache to work on a property/value basis and not on the entire DOMRect. This would provide the same value for the rows. I will make an alpha version that you can test.

@grysor If you disable the DOMRect protection entirely the other settings are useless. That's why they disappear.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-Alpha1 (disable normal CB before).

**Comment by grysor** [comment]
> 
> 
> Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-Alpha1 (disable normal CB before).

Hello ,thank you for your message
I installed your new beta version by your link, and i confirm that the photos on google image are again all clickable! great, thank you :)

**Comment by grysor** [comment]
i use google translate in french because I live in France :) thank you

**Comment by Reeywhaar** [comment]
Works great for me! Thank you very much for openness. Hope it also resolves other similar bugs!

**Comment by spodermenpls** [comment]
Thumbs up from me too, the new faking method also seems to have sped up some DOMRect-heavy websites a little bit (e.g. Youtube, of course). 
I used to have similar "non-reactive thumbnails" on Google Images, but not for the longest time, so I wouldn't have been able to provide intel on that one. Thanks to @Reeywhaar for dropping some of his expertise. 👍

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-RC1

**Comment by Reeywhaar** [comment]
It works for me. Clean firefox, default settings, CanvaBlocker's icon show that it protects domRect. Google images works fine if you asking me.

**Comment by kkapsner** [comment]
Version 0.5.5 is out and ready to use.
 @grysor consider updating your review on AMO

**Comment by grysor** [comment]
Hello kkapsner
I'm sorry for my late response
Thank you very much for your work and this update in 0.5.5 :) I installed it more than 12 days ago and it works very well no bugs :) thanks to Reeywhaar for his expertise and his precious help :)

**Comment by kkapsner** [comment]
You're welcome.
