### ISSUE TITLE
stops local page from loading

### ISSUE THREAD

**Issue by horusra** [kkapsner/CanvasBlocker#273]
I'm using: https://luke-baker.github.io/ (specifically: https://luke-baker.github.io/chrome/NewTab_custom-page.uc.js ) to have firefox open my own local html file as "new tab".
Once in a while, the new tab page (my local file) gets stuck on a white page, endlessly "loading", and when I open the console, I see:
`[CanvasBlocker] invalid content scripts: require not defined at file:///C:/Users/Mohsen/Documents/Web/Start%20Page/startpage_rwrt/index.html`
[Screenshot](https://my.mixtape.moe/qxqyuz.jpg)
When I click on the random stuff to the right of the error "9e4fb717-8bb1-40d0-b983-7c777ea49434:13:9" (in the console) it opens: [this](https://pastebin.com/pdzvLftG) and selects `                                console.error(`

The local file I've set as the new-tab page is from: https://github.com/crshd/startpage.rwrt

I'm running Windows 10 Enterprise (Build 1803), running the latest Firefox version, and the only CanvasBlocker setting I've change was setting it to "Persistent". My Firefox install is fresh, other addons: umatrix, ublock origin, privacy badger. But seeing how the console shows it's canvasblocker preventing the page from loading, I'd say there is no issue with the other addons (because when I disable canvasblocker, the new tab always loads instantly).

ps. I realize there's a whitelist functions, but that's for domains, and I'm using "file:///C:/Users/...../index.html" so there's no domain to whitelist.

**Comment by kkapsner** [comment]
You can whitelist by using a RegExp but I think this will not help.

But I'm not able to reproduce your problem. Can you please try on a fresh profile with only CB installed?

**Comment by horusra** [comment]
oke I just went through all of my different addons, disabling them all, restarting my browser (ctrl-shift-q) and then opening firefox and opening a new tab. The issue only occurs when both CanvasBlocker and PrivacyBadger are enabled. I can now reliably recreate the issue every time. It may take about 2 or 3 open-close tabs to recreate it, but it always happens within a few tries when both of these addons are running. It's weird because privacy badger detects nothing on the page, and seems to not be blocking anything at all, but the combination with canvasblocker stops the page from loading.

**Comment by kkapsner** [comment]
OK - I was able to see the problem once. But in the other hundreds of times everything worked fine.

What happens if you deactivate PrivacyBadger and reactivate it? Can you still reproduce the problem?

**Comment by horusra** [comment]
> What happens if you deactivate PrivacyBadger and reactivate it? Can you still reproduce the problem?
yes, I can reliably recreate it.

**Comment by kkapsner** [comment]
This is getting really weird.

Have you tried on a fresh Firefox profile?

**Comment by horusra** [comment]
yes, I wiped every profile, setting and reninstalled firefox, same issue. but the problem arises mostly after firefox has been launched.

>start firefox
>open new tab, if it opens, close it and open another
>within 3 newtab attempts the issue arrises
>after this the issue gets less frequent
>until firefox is closed entirely and relaunched

**Comment by kkapsner** [comment]
What is the exact Firefox version?

**Comment by horusra** [comment]
62.02 64bit

**Comment by kkapsner** [comment]
How do you open the new tab? Ctrl+T or with the plus icon?

**Comment by horusra** [comment]
I use the + button, and I close firefox with the menu in top right and choose Exit.
![image](https://user-images.githubusercontent.com/17074394/46207287-1fd51800-c327-11e8-935d-e4185b78c98e.png)

**Comment by kkapsner** [comment]
Did the same happen with CB 0.5.3? Does the problem persist when you disable the different protections (window, history, audio, DOMRect)?

**Comment by horusra** [comment]
I don't know about CB version as I've only recently started using it.
![image](https://user-images.githubusercontent.com/17074394/46221871-f29c6000-c34e-11e8-8ac3-86ce94c6adf7.png)
Problem persists even after unchecking this and restarting browser. I will continue disabling options in CB to see if the problem is solved by them.

**Comment by horusra** [comment]
![image](https://user-images.githubusercontent.com/17074394/46222420-828ed980-c350-11e8-8ebb-5576647dbffd.png)
![image](https://user-images.githubusercontent.com/17074394/46222429-8c184180-c350-11e8-93a9-2f7d43399663.png)
Even with these settings (pretty much everything unchecked) the issue persists. I think it's about CB trying to read something but not being able to?

**Comment by horusra** [comment]
![image](https://user-images.githubusercontent.com/17074394/46222502-d4cffa80-c350-11e8-8fb2-baebd9e7fa8b.png)
Same error message with the options in my previous post.

**Comment by kkapsner** [comment]
And this error message is always present when the page does not load?

**Comment by horusra** [comment]
yes, always.

**Comment by kkapsner** [comment]
Hm... I might have an idea of what causes the load problem. Can you please compare with CB 0.5.2a and 0.5.2b?

But still only a vague idea what's the root of all this.

**Comment by horusra** [comment]
2a does not have the loading issue, but 2b does.

**Comment by kkapsner** [comment]
Does the error message still pop up with 2a?

**Comment by horusra** [comment]
Yes, the error message shows up, but the page loads just fine.
![image](https://user-images.githubusercontent.com/17074394/46342321-ba409e80-c63a-11e8-9e0d-61b4422949de.png)

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-Alpha2

**Comment by horusra** [comment]
> Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-Alpha2

that seems to have fixed it! a different error shows up but the page always loads just fine.
![image](https://user-images.githubusercontent.com/17074394/46381706-b6973100-c6a7-11e8-9b4e-4fddc5e6d57d.png)

**Comment by kkapsner** [comment]
Yes - i changed the message to indicate that Firefox is behaving weirdly. But now CB can handle that.

**Comment by horusra** [comment]
oh no! it's back. (but different)

![image](https://user-images.githubusercontent.com/17074394/46548222-b0cf6480-c8ce-11e8-955f-df8349fd68b3.png)

**Comment by kkapsner** [comment]
That's weird... but does the page load?

**Comment by horusra** [comment]
no that time the page was again blank and stuck on loading.

**Comment by kkapsner** [comment]
Your Firefox is weird... have you updated to 62.0.3 yet?

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-RC1

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-RC2

**Comment by horusra** [comment]
> Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.5-RC2
Okay, I've installed it, will test it and get back to you.

**Comment by horusra** [comment]
Same issue, and yes I'm on 62.0.3

![image](https://user-images.githubusercontent.com/17074394/46752766-595e3980-ccbe-11e8-90da-a0446477c475.png)

**Comment by kkapsner** [comment]
Hm... still the same configuration that it's only reproducible when privacy badger and CB are both active?
Can activate them in different orders and check if the not loading persists?
Does it still only occur on local files?

Can you increase the logging level to verbose and post the entries?

**Comment by kkapsner** [comment]
Please try the latest release 0.5.5
