### ISSUE TITLE
Any jQuery UI website trigger the domRect warning

### ISSUE THREAD

**Issue by Clodo76** [kkapsner/CanvasBlocker#275]
I host several websites with jQuery UI, and all trigger the domRect warning.

## Steps to Reproduce (for bugs)
Go to https://jqueryui.com/dialog/ .

## Your Environment

* CanvasBlocker Version used: 0.5.4
* Firefox version incl. 32- or 64-bit: 61.0.2 (64 bit)
* Operating System and version (desktop or mobile): Windows 10 Desktop
* Installed addons: None

## Your Settings
Default, just installed for testing.

Anyone can at least help me to understand how to avoid the warning?
I honestly can't remove jQuery UI only for this.
Thanks.

**Comment by kkapsner** [comment]
If you enable the detail storage and the display of the complete calling stack you can inspect the calling stack that led to the notification:
![grafik](https://user-images.githubusercontent.com/1105157/46104916-f1472800-c1d4-11e8-8080-17da45e14904.png)
-> 
![grafik](https://user-images.githubusercontent.com/1105157/46105019-33706980-c1d5-11e8-9488-cfc8f47e3e88.png)
->
![grafik](https://user-images.githubusercontent.com/1105157/46105032-3bc8a480-c1d5-11e8-8fdd-32cc449fd3f6.png)

So in this case the opening of the dialog leads to a domRect API read call. This is completely fine and legit. The notification only tells you that something was faked - not that a fingerprinting was attempted (I'm not able to detect this).
