### ISSUE TITLE
Add-on breaks many websites since upgrade to macOS 10.14

### ISSUE THREAD

**Issue by colacastell** [kkapsner/CanvasBlocker#277]
Since I have updated my MacBook Pro and iMac to macOS 10.14 Mojave, this Add-on breaks many websites in Firefox to the point of not being usable anymore.

## Description
Right after upgrading the OS, I used Firefox (my main Browser), and noticed, that many websites are broken. Startpage.com did not show any results anymore, Facebook was broken in too many places to describe in detail but mostly pages only loaded partly, and many images were simply not displayed troughout the entire web.

I launched Firefox in savemode without add-ins and the issues were gone. After this, I manually deactivated all my add-ins and enabled one after another to see, which was causing the issues. With this method, I was able to figure that CanvasBlocker is the only add-in that causes this issue when activated. Currently, I have CanvasBlocker disabled and everything works normally.

## Your Environment

* CanvasBlocker Version used: 0.5.4
* Firefox version incl. 32- or 64-bit: Firefox 62.0.2 64-bit
* Operating System and version (desktop or mobile): macOS 10.14 Mojave

**Comment by colacastell** [comment]
This solves the issue!

**Comment by kkapsner** [comment]
Hm... which blocking mode are you using? Or better: post your complete settings (you might want to remove sensitive data beforehand).

**Comment by colacastell** [comment]
`{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "blockReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {
		"domRect": false
	},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "24",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": false,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.4
}`

**Comment by kkapsner** [comment]
Ah... "blockReadout" is a mode that very likely breaks pages (especially with the DOMRect API being used very often in a legitimate way). I suggest using "fakeReadout" which is less detectable and protects you equaly good.
