### ISSUE TITLE
 stops local page from loading #273 (again)

### ISSUE THREAD

**Issue by horusra** [kkapsner/CanvasBlocker#280]
The same issue from here:
https://github.com/kkapsner/CanvasBlocker/issues/273

happened again, but with a different error this time. Since the last one is closed, I figured I needed to open a new issue.
Error:
![46548222-b0cf6480-c8ce-11e8-955f-df8349fd68b3 1](https://user-images.githubusercontent.com/17074394/46548425-5551a680-c8cf-11e8-899a-6d66c473cc9e.png)
Version:
![46548254-c9d81580-c8ce-11e8-9164-45b78c104592 1](https://user-images.githubusercontent.com/17074394/46548436-5be01e00-c8cf-11e8-9350-293b3abbe8ba.png)

**Comment by kkapsner** [comment]
I reopened the other issue.
