### ISSUE TITLE
hide the app!

### ISSUE THREAD

**Issue by dking1330** [kkapsner/CanvasBlocker#281]
Hello, I use the addon on the phone. Please make an option in the settings hiding the use of canvas. You can make a random name of the canvas, and other methods that block the detection of a plug-in. I cannot use Ebay.com as this site knows that I use Canvas !!

**Comment by kkapsner** [comment]
Can you please elaborate more on how you cannot use ebay?

Actually I do not quite know what you exactly want me to do.

**Comment by kkapsner** [comment]
I need more information to help you with your problem.

**Comment by kkapsner** [comment]
I'm able to use ebay with CanvasBlocker enabled.

Do you see any output in the browser console (Ctrl+Shift+K)?
What are your Canvasblocker settings?

**Comment by dking1330** [comment]
I use the mobile version. I tried different settings. But starting the page does not open, payments do not pass! How to hide the use of your plugin? I tried to rewrite the name of your plug-in, it turned out, but the store still notices the use!

Sent: Friday, October 19, 2018 at 7:59 PM

**Comment by kkapsner** [comment]
Without the information I cannot help. I will close this.

If you provide the information I can reopen the issue if necessary.
