### ISSUE TITLE
Firefox extension warning at amiunique.org/fp

### ISSUE THREAD

**Issue by Cespen** [kkapsner/CanvasBlocker#283]
I get a warning message from Firefox at https://amiunique.org/fp

"A script of the Extension 'CanvasBlocker' is slowing down Firefox"

And it does slow it down. You have to wait a few minutes before the site is rendered. Not a big issue, just wanted to report it.

**Comment by kkapsner** [comment]
This is again a page that uses that bad audio fingerprinting script from http://audiofingerprint.openwpm.com/:
![grafik](https://user-images.githubusercontent.com/1105157/46688264-2c961d80-cbfd-11e8-800d-908ad6709c47.png)

So there is nothing I can do about it.

You can make it faster by disabling the audio cache - but I do not recommend it.

Nevertheless: thanks for the report.

**Comment by kkapsner** [comment]
PS: do not worry if they tell you that you are unique - that's the point of using the fake modes: be even different between different page loads.
