### ISSUE TITLE
[feature request] UI to toggle the whitelist for the current domain/URL

### ISSUE THREAD

**Issue by dkasak** [kkapsner/CanvasBlocker#285]
This would be so much more usable if there was a whitelist toggle for the current domain/URL available in the popup menu that appears when you click the extension's icon. Manually editing the whitelist string is a hassle and error-prone, particularly with the new domRect blocking which seems to break many things.

Ideally, there would also be some way to whitelist only specific fingerprinting APIs, but I could also live with an on/off toggle.

**Comment by kkapsner** [comment]
When you click on the icon in the address bar (when something is faked on the page) there is a direct button to whitelist the domain or the url:
![grafik](https://user-images.githubusercontent.com/1105157/46904541-efc07400-cee5-11e8-9da3-157ea8e1b9e0.png)
![grafik](https://user-images.githubusercontent.com/1105157/46904543-f6e78200-cee5-11e8-9c11-14d6ae279f90.png)

You can also allow specific fingerprinting APIs for a domain by using the url specific values:
![grafik](https://user-images.githubusercontent.com/1105157/46904548-1f6f7c00-cee6-11e8-946a-95cf9788798c.png)

In fact the whitelist button does not change the whitelist string but adds a url specific value for the block mode.

**Comment by dkasak** [comment]
Oh, sorry, I missed this because I'm using Tridactyl so I'm not used to paying attention to the address bar much (and it is hidden most of the time).
