### ISSUE TITLE
Canvas Blocker Legacy

### ISSUE THREAD

**Issue by SampeiNihira** [kkapsner/CanvasBlocker#286]
Hi.
I use Pale Moon version 28 as a browser.
You can develop a recent Legacy version of Canvas Blocker that adds the recent protection for DOMRect (getClientRects) of version 0.5.4.?
Using an old Legacy version is useless,for internal setting Canvas.PoisonData set to true.
TH

**Comment by kkapsner** [comment]
Unfortunately I do not have the time to create (and maintain) a new legacy version of CB. The changes I would have to make are just too big.

Sorry.
