### ISSUE TITLE
Fake Canvas and Fake WebGL Detected

### ISSUE THREAD

**Issue by Kraxys** [kkapsner/CanvasBlocker#287]
Fake WebGL and Fake Canvas are detected on test site [FakeVision](http://f.vision/) ("Advanced Tests"). With the same CB settings, Kkapsner's detection test is detecting nothing but _API tempered_ via "_known pixel value test 10_"

Also I have had to deactivate Audio API Protection on FakeVision because with Audio API protected, FakeVision's tests took too long to be performed (even when unchecking Audio Cache Usage), so that CB's Audio API Protection has not been tested on this site.

EDIT:
In CB, after switching from "Fake Readout" mode to "Fake at Input", Kkapsner's Detection Tests are detecting nothing, while FakeVision/Advanced Tests is still detecting Fake WebGL (but no more Fake Canvas).

## Your Environment

* CanvasBlocker Version used: 0.5.5
* Firefox version incl. 32- or 64-bit: 64-bit
* Operating System and version (desktop or mobile): Desktop - Windows 7
* Installed addons: Only CB

## Your Settings

{
	"logLevel": 1,
	"urlSettings": [
		
		
		{
			"url": "^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$",
			"protectWindow": false
		},
		{
			"url": "f.vision/",
			"protectAudio": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {
		"protectAudio": true,
		"protectWindow": true
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": ,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "11",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.4
}

**Comment by kkapsner** [comment]
As you already found out the "fake input" mode prevents the detection of normal canvas. For WebGL I'm not aware of any (reasonable) way to prevent the detection there (actually I also have a detection page for webGL: https://canvasblocker.kkapsner.de/test/webGL-Test.html)

Unfortunately the "fake input" mode does not play well with the other protected APIs. I have to change that.

**Comment by kkapsner** [comment]
I'm quite confident they just took my tests... so passing the WebGL test can be achieved by setting the "min fake color" to at least 1. My WebGL-test is not a detection test but a support test...

PS: audio test works fine for me when disabling the cache. They also use the bad code from https://audiofingerprint.openwpm.com/
