### ISSUE TITLE
Request: Option to prevent all dialogs about Faked readout

### ISSUE THREAD

**Issue by tancrackers** [kkapsner/CanvasBlocker#29]
For the Fake readout API option, can we have an option to prevent the notification dialog for all sites?
That way, the readout API is faked, and we are not constantly hit with the notification that it was faked.
This, or a wildcard such as * for the ignore list.

EDIT: I see that putting "http*" in the ignore list does this. Perhaps a note should be made somewhere?

**Comment by kkapsner** [comment]
You can just uncheck the "Show notifications" checkbox to disable all notifications.
