### ISSUE TITLE
Need a new feature in the Faking

### ISSUE THREAD

**Issue by waltepull** [kkapsner/CanvasBlocker#290]
Hi thanks for your addon
You can add, please, to change the random number once for all domains and not for each separately?

**Comment by kkapsner** [comment]
Why do you want that? This makes you highly trackable.

**Comment by waltepull** [comment]
Me for internet marketing
when you want to change your identifiers, but in a mild form, as if you are not using anything...

By the way, this refers to the site [FakeVision](https://ls.tenebris.cc/about) and their [browser](https://ls.tenebris.cc/about) (read what it is for, and it will become clear how this function will be useful in your addon)

**Comment by kkapsner** [comment]
Hm... so your point is not privacy but having a different "disguises".

Technically this is simple BUT I'm not yet convinced to put it in... it really makes you 100% trackable across the whole internet.

**Comment by waltepull** [comment]
I understand that this goes against your initial vision and I also understand that from the technical side it is not difficult to add this function, but you will receive respect over time from people working in certain areas.

Please do it, if make not difficult for you. Ultimately, this function which the user himself chooses to turn on or off.

**Comment by kkapsner** [comment]
My point is the following: how do I protect a user that is not completely sure what they are doing from spoiling their privacy?

Maybe I add an additional confirmation dialog...

**Comment by kkapsner** [comment]
![grafik](https://user-images.githubusercontent.com/1105157/47456809-c18c3f80-d7d5-11e8-9189-ef01ec71ae13.png)
@spodermenpls what are your thoughts?

**Comment by waltepull** [comment]
This function will fit perfectly into a random number generator, for this you need expert mode

**Comment by spodermenpls** [comment]
@kkapsner I think the confirmation window is a good solution to prevent misunderstandings.

**Comment by kkapsner** [comment]
Version 0.5.6 is finally out and you should see this feature.
