### ISSUE TITLE
Asking to publish patched old version

### ISSUE THREAD

**Issue by Feodor2** [kkapsner/CanvasBlocker#292]
Hello , i found this addon very good. And i use old firefox browsers where new version of the addon can't install. I had discovered that you developed new things, and wanted to patch old 3.5 version with them, made success with the fake domrect, going to do others.

Also i would like to publish the addon, i can put inside it the note that it not related to you and do not go for help to you, anyway i shall publish howto patch.

**Comment by kkapsner** [comment]
Good that you managed to patch 3.5 with the DOMRect faking. But what is your question now?

**Comment by kkapsner** [comment]
You can do so. But you will not be able to publish it on AMO as they do not accept legacy addons any more, I think.
Not sure if you can sign it... but I think the browsers you are aiming at still run unsigned addons???

**Comment by Feodor2** [comment]
Yes. And i don't need to sign.
