### ISSUE TITLE
Can add all checkboxes?

### ISSUE THREAD

**Issue by rndlinker37** [kkapsner/CanvasBlocker#293]
`https://notabug.org/desktopd/no-resource-uri-leak`

**Comment by kkapsner** [comment]
What checkboxes do you mean?

**Comment by rndlinker37** [comment]
"Block access to resource:// URIs from Web"
"Block Web-exposed subset of chrome:// URIs"
"Uniformly filter disallowed redirects"
"This eliminates one known source of an information leak"
"Exposed resource:// domains"
"Exposed chrome:// domains"
"Restrict about: pages by default (for paranoids)"

And etc.

**Comment by kkapsner** [comment]
CanvasBlocker only uses `moz-extension://` URLs and these are not necessary for functionality. So I think you can enable these checkboxes.
