### ISSUE TITLE
is causing Firefox to slow down on Github.com, Pull requests, Review changes page

### ISSUE THREAD

**Issue by ProBackup-nl** [kkapsner/CanvasBlocker#296]
## Description
bug: because the browser tab comes to a stop, despite choosing: 

 1. "Temporarily Disabling Extension on Page"
 2. "Stop it"
 3. "Wait"

the page does not fully render.

## Expected Behavior
No Firefox warning "A script in the extensions CanvasBlocker is causing Firefox to slow down". 

## Current Behavior
The slow down.

## Steps to Reproduce (for bugs)
1. https://github.com/PrestaShop/PrestaShop/pull/6875/files

## Your Environment
* CanvasBlocker Version used: 0.5.5
* Firefox 60.3.0esr 64-bit:
* Operating System: Mac OS X 10.9.5
* Installed addons: Noscript, Ghostery, uBlock Decentraleyes, Web Developer, Textarea cache

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "github.com",
			"blockMode": "block"
		},
		{
			"url": "marktplaats.nl",
			"blockMode": "allow"
		},
		{
			"url": "tindie.com",
			"blockMode": "allow"
		}
	],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1542229187916,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": false,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "12",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": true,
	"isStillDefault": false,
	"storageVersion": 0.4
}

**Comment by kkapsner** [comment]
It's the "block"-mode for github. I can reproduce the problem (on 0.5.6 dev) and I think I know what's the problem.

**Comment by kkapsner** [comment]
Wrong button...

**Comment by kkapsner** [comment]
This is a weird but. It seems that github just keeps on calling the DOMRect-API despite it failing. So you would be better of using the fake mode on github. Why did you chose "block" for github?

**Comment by ProBackup-nl** [comment]
I just choose something at random, trying to get the annoying message away and try to view the pull files.

**Comment by kkapsner** [comment]
Hm.. so you also see the message when you use the "readFakeout" block mode?
Can you please try the latest alpha (you should disable the normal CB first): https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.6-Alpha1

**Comment by ProBackup-nl** [comment]
With 0.5.5 disabled and 0.5.6-Alpha1 in "fake" mode, the https://github.com/PrestaShop/PrestaShop/pull/6875/files url loads without messages from Firefox.

**Comment by kkapsner** [comment]
Great.
The problem with the "block" mode is unfortunately nothing I can change... it's Github's "fault".
