### ISSUE TITLE
[Question only] CanvasBlocker impact on UBO hostname-lookup data structures benchmark

### ISSUE THREAD

**Issue by StanGets** [kkapsner/CanvasBlocker#297]
Hi,

CanvasBlocker 0.5.5 / Firefox 63.0.3 (x64) / Windows 7 (x64)

I've ran uBlock Origin's [Benchmark of hostname-lookup data structures: Set, RegExp, HNTrie](https://raw.githack.com/gorhill/uBlock/master/docs/tests/hnset-benchmark.html) with CanvasBlocker enabled then disabled and the Trie-based WASM results are some 30% higher in the latter case.

I have optimal settings for CB except the option `Misc > Block data URL pages` unchecked because of UBO.

I'm just wondering why CB has such an impact on WASM as it seems.

My results:

![ubo bechmark - me-1](https://user-images.githubusercontent.com/42912760/49405748-a3f6b200-f753-11e8-8709-4f0f958a26f4.jpg)

No CanvasBlocker issue, performing well. Only this incidence. Thanks!

**Comment by kkapsner** [comment]
There should be not interference with WASM as I do not use it/interact with it in CB.

I get very varying results from run to run. No matter if CB is enabled or not. And for WASM the first run is always the slowest (makes kind of sense as it has to be compiled and optimised).
