### ISSUE TITLE
[Request] Start accepting Monero

### ISSUE THREAD

**Issue by iamtheoneaboveall** [kkapsner/CanvasBlocker#298]
Bitcoin is not private nor untraceable, please consider accepting Monero for donations. 
https://ww.getmonero.org/

**Comment by kkapsner** [comment]
It's on my todo list.

**Comment by iamtheoneaboveall** [comment]
any update on this? shouldnt take more than few minutes of downloading a wallet or using one for android (Monerujo) if you need help feel free to ask on /r/Monero or on irc. https://mymonero.com/#/
or https://www.getmonero.org/downloads/

**Comment by kkapsner** [comment]
Finally...

482QYZaagALWtPmwbptwBaexDYmcVsJrhJp2VVjTgjYA3Kk1YyMdSg9Wz2qz1Gh31E843PFVCDWS4hR4Bjf6ipWuB9iz2cs
