### ISSUE TITLE
getByteFrequencyData & Features detected

### ISSUE THREAD

**Issue by PentaBoB** [kkapsner/CanvasBlocker#299]
Thank you for this great addon.

Every thing works great but I have one issue.
When I use Protected API features==> getByteFrequencyData   https://www.gamingmasters.org/ website is not loading shout box. If I disable that it works fine, but  https://browserleaks.com/features  detected with full details. Is there any solution for that (Disabling Web Browser Features Detection).

Thank you

**Comment by kkapsner** [comment]
Which version of CB and Firefox are you using?

On this page I do not see a shout box - just a "Slothbox"... do you mean that? This box is loaded for me with both settings.

**Comment by kkapsner** [comment]
Please provide the requested information. Otherwise I cannot help you.
