### ISSUE TITLE
Request: HTTP Authenticaion Data ID...

### ISSUE THREAD

**Issue by Geyup** [kkapsner/CanvasBlocker#30]
Hi,

This is a really nice addon you made for Firefox, I like how you are into Fingerprinting protection.

I want to ask if you might consider another idea to add into CanvasBlocker to protect the browser from sending HTTP Authenticaion Data ID to 3rd party requests...

If you go to JonDONYM's site to check IP you will see they have a section for 'Authentication'

http://ip-check.info/?lang=en

Thank you for your consideration to add this feature to your addon.

**Comment by kkapsner** [comment]
Hi,

thank you for your interest in the addon. This HTTP Auth problem is definatelly worth to take care of. But it's way outside the scope of the CanvasBlocker. This would be a separate Addon.

**Comment by Geyup** [comment]
Hi,

Ahh no worries, after asking this I found the Random Agent Spoofer;

https://github.com/dillbyrne/random-agent-spoofer/

If you have't seen this you should.

I also don't get why NoScript isn't adding in this Canvas Blocking too? Not that I'd like to see anything taken away from you, but it makes sense to do so? No? hmm

**Comment by kkapsner** [comment]
I would be proud if parts of my work will fuse into NoScript.

**Comment by Geyup** [comment]
You need to approach them...
