### ISSUE TITLE
Contradictory test result between Panopticklick & Browserleaks

### ISSUE THREAD

**Issue by macgeekpro** [kkapsner/CanvasBlocker#300]
Hi guys, I run the tests at both sites with the default configs but they both have different results; Panopticlick said  my browser has a unique fingerprint [{screenshot}](https://imgur.com/rq2qhoy) But Browsercanvas said  my browser's uniqueness has false value [{screenshot}](https://imgur.com/ONVUcQi) Am I being protected correctly? Any setting I need to change from the default so that I can pass the tests correctly at both sites?

Spec:
Canvasblocker 0.5.5
Firefox 64.0
Additional Addons: UBO, Privacy Badger,  HTTPS Everywhere, Google&Facebook Containers, Decentraleyes, Dark Reader, Bitwarden

**Comment by kkapsner** [comment]
Do you have privacy.resistFinterprinting enabled? Otherwise I cannot explain the "(Tor browser signature)" with the default settings of CB.

**Comment by kkapsner** [comment]
If I enable RFP I get exactly your result. With this setting you are fine.

**Comment by macgeekpro** [comment]
> Do you have privacy.resistFinterprinting enabled? Otherwise I cannot explain the "(Tor browser signature)" with the default settings of CB.

Yes. I have it set to true in the browser's config.

> If I enable RFP I get exactly your result. With this setting you are fine.

Noted. I leave the setting as it is when I opened this issue. Thanks.
