### ISSUE TITLE
Show information on clicking the addon icon

### ISSUE THREAD

**Issue by zorbakus** [kkapsner/CanvasBlocker#303]
Currently you have to hover over the addon's icon to show what was blocked, and even then it doesn't show you how many requests. It would be more convenient and more in-line with other privacy addons to show some stats on left-clicking the icon.

**Comment by kkapsner** [comment]
The information you are searching is displayed when clicking on the icon in the task bar:
![grafik](https://user-images.githubusercontent.com/1105157/50575126-a2261a00-0df7-11e9-8ba0-c4dec648d7f0.png)

If you want more details you can enable that:
![grafik](https://user-images.githubusercontent.com/1105157/50575136-d994c680-0df7-11e9-9cca-fe963ce7cb01.png)
But keep in mind that this reduces the performance of the addon.

I'm not planning to move this information to the toolbar icon.
