### ISSUE TITLE
Hide icon in address bar

### ISSUE THREAD

**Issue by shizunge** [kkapsner/CanvasBlocker#304]
We need a switch to turn off icon in the address bar

## Description
On Firefox Android the icon in the toolbar seems not very helpful, but take a space.

Could you provide a switch to turn off the icon in the address bar? Because unlike on the PC, there is no option to remove a icon from address bar on Android. 

It is better if we could merge the address bar icon and the toolbar icon into a single toolbar icon for the Firefox Android.

## Your Environment
* Firefox version: 64
* Operating System and version (desktop or mobile): Android

**Comment by shizunge** [comment]
I found the option "turn off notification" will turn off the icon in the address bar.
I feel the word is not intuitive on Firefox Android.

**Comment by kkapsner** [comment]
What would you rather have it called then?
The term "notification" came from when CB was not a WebExtension and Firefox notifications (the big yellow bars) could be triggered by addons. So I do not mind changing it to something better.

**Comment by shizunge** [comment]
I don't have a better name either.
I just called it "address bar icon" . There could be a better one.
