### ISSUE TITLE
Settings Reset button

### ISSUE THREAD

**Issue by birdie-github** [kkapsner/CanvasBlocker#307]
Could you please add a button to reset all CanvasBlocker settings to defaults?

**Comment by kkapsner** [comment]
There is already a button, but it's only available when activating the expert mode (maybe I should change that...):
![grafik](https://user-images.githubusercontent.com/1105157/51930166-32a54980-23fa-11e9-8e0e-87a3db3808a5.png)

**Comment by birdie-github** [comment]
@kkapsner 

> There is already a button, but it's only available when activating the expert mode (maybe I should change that...):

Please do. A reset button shouldn't be hidden behind "Expert" mode. It's not really expert to want to have your settings reset.

**Comment by kkapsner** [comment]
Actually I do not remember why it was behind expert mode...
