### ISSUE TITLE
0.5.6 removal of existing block modes

### ISSUE THREAD

**Issue by hubbathegit** [kkapsner/CanvasBlocker#308]
[quote]Release notes for 0.5.6

- removed *Readout and *Input block modes (use protectedCanvasPart instead)[/quote]

More options = good. 
Less options = bad.

That's it.

**Comment by kkapsner** [comment]
Actually by separating the blocking mode from the protectedCanvasPart the number of options increased.

All the removed modes are still achievable with the new modes and the protectedCanvasParts (e.g. for fakeReadout you chose the "fake" mode and protect the "readout" part).

But there are now new combinations that were not possible before.
