### ISSUE TITLE
fake session history no work! CanwasBlocker v-0.5.6 release. OS android Browser Firefox.

### ISSUE THREAD

**Issue by SomeOneTorento** [kkapsner/CanvasBlocker#309]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CanvasBlocker Version used:
* Firefox version incl. 32- or 64-bit:
* Operating System and version (desktop or mobile):
* Installed addons:

**Comment by SomeOneTorento** [comment]
Settigs:



{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$",
			"protectWindow": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fakeReadout",
	"minFakeSize": 1,
	"maxFakeSize": 10000000,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": false,
	"ignoreFrequentColors": 0,
	"minColors": 3,
	"fakeAlphaChannel": true,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1549090487000,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "color",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": true,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": true,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "1000",
	"audioNoiseLevel": "minimal",
	"useAudioCache": false,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "21",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "dark",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.4
}

**Comment by BananaMangoFestival** [comment]
I have the same issue on Windows and initially I thought it was because of the new firefox version but it's not.
And I confirm it worked in 0.5.5

**Comment by kkapsner** [comment]
My bad - found the bug.

**Comment by kkapsner** [comment]
New release fixes this issue.
