### ISSUE TITLE
Bypass CanvasBlocker using iframe

### ISSUE THREAD

**Issue by DocumentRoot** [kkapsner/CanvasBlocker#31]
Hi

Firstly i want to say i'm helping make this demo:

https://www.browserleaks.com/canvas

And recently updated it, so now everyone can see more detailed whats going on when you "block readout API", or when you "fake readout API" with CanvasBlocker.

I have also reviewed the some extensions for blocking Canvas (two of them for Chrome, and also CanvasBlocker), and found that all they can be bypassed through creating canvas element inside iframe:
```
<iframe id="iframe" sandbox="allow-same-origin" style="display:none"></iframe>
<script>
var canvas = document.createElement('canvas');
console.log(typeof canvas.toDataURL)
canvas = document.getElementById("iframe").contentDocument.createElement('canvas')
console.log(typeof canvas.toDataURL)
</script>
```
When you do anything with canvas inside this iframe, extensions notices nothing.

But there is also a "good" news, why my demo still cant bypass CanvasBlocker, is this bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=941146

Firefox crash js with NS_ERROR_FAILURE if i try to set ctx.font or ctx.fillText inside iframed canvas :))))

For now i put temporary fallback for this bug, when crash happens it returns to non-iframe canvas,

But i hope you fix CanvasBlocker before they fix FF :)

**Comment by DocumentRoot** [comment]
Hi again

It's even possible to bypass blocker right now, with no waiting FF bugfix.
By cloning image from normal canvas to iframed canvas:

- we create normal  canvas
- draw image with any functions (FF dont crash because we still in normal canvas)
- but before readout, we copy image from normal canvas to iframed canvas
- then just export image from iframed canvas - and it will not be filtered by extension

```html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<iframe id="iframe" sandbox="allow-same-origin" style="display:none"></iframe>

<script>

(function(){

	console.log('before: '+before());
	console.log('after : '+after());

})();


function before()
{
	try{

		var fp_text = "BrowserLeaks,com <canvas> 1.0";
		var canvas = document.createElement('canvas');

		canvas.setAttribute("width", 220);
		canvas.setAttribute("height", 30);

		var ctx = canvas.getContext('2d');
		ctx.textBaseline = "top";
		ctx.font = "14px 'Arial'";
		ctx.textBaseline = "alphabetic";
		ctx.fillStyle = "#f60";
		ctx.fillRect(125, 1, 62, 20);
		ctx.fillStyle = "#069";
		ctx.fillText(fp_text, 2, 15);
		ctx.fillStyle = "rgba(102, 204, 0, 0.7)";
		ctx.fillText(fp_text, 4, 17);

		// export signature from iframe canvas
		var b64 = canvas.toDataURL().substring(22);
		var bin = atob(b64);
		var crc = bin2hex(bin.slice(-16,-12));

		return crc;

	}catch(e){
		return e;
	}
}


function after()
{
	var fp_text = "BrowserLeaks,com <canvas> 1.0";

	// create window canvas
	var canvas = document.createElement('canvas');
	canvas.setAttribute("width", 220);
	canvas.setAttribute("height", 30);

	// draw image in window canvas
	var ctx = canvas.getContext('2d');
	ctx.textBaseline = "top";
	ctx.font = "14px 'Arial'";
	ctx.textBaseline = "alphabetic";
	ctx.fillStyle = "#f60";
	ctx.fillRect(125, 1, 62, 20);
	ctx.fillStyle = "#069";
	ctx.fillText(fp_text, 2, 15);
	ctx.fillStyle = "rgba(102, 204, 0, 0.7)";
	ctx.fillText(fp_text, 4, 17);

	// create iframe canvas and ctx
	var iframe_canvas = document.getElementById("iframe").contentDocument.createElement('canvas');
	iframe_canvas.setAttribute("width", 220);
	iframe_canvas.setAttribute("height", 30);
	var iframe_ctx = iframe_canvas.getContext('2d');

	// copy image from window canvas to iframe ctx
	iframe_ctx.drawImage(canvas, 0, 0);

	// export signature from iframe canvas
	var b64 = iframe_canvas.toDataURL().substring(22);
	var bin = atob(b64);
	var crc = bin2hex(bin.slice(-16,-12));

	return crc;
}

function bin2hex(a){var b,c,d="",e;a+="";b=0;for(c=a.length;b<c;b++)e=a.charCodeAt(b).toString(16),d+=2>e.length?"0"+e:e;return d}

</script>
```

**Comment by kkapsner** [comment]
Hi

sorry for the delay - was busy doing other projects.

Thank you for the efford you put into browserleaks and for the finding of this bug.
I created a new version (0.1.7 - currently under review at Mozilla) that does not have that issue. It now reports that canvas are not supported when the iframe technique is used.

**Comment by kkapsner** [comment]
Version 0.2.0 (https://github.com/kkapsner/CanvasBlocker/blob/withoutPageMod/canvasblocker.xpi ) now changed a lot of things. The iframe bypass still does not work but the canvas support is now correctly displayed (and even a valid PNG...).

Please keep on trying to break my AddOn - it helps a lot.
