### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by uragan60** [kkapsner/CanvasBlocker#310]
new version is not working correct now 8(       
http://f.vision/ and not only ((((  did work good before 0.5.7

**Comment by kkapsner** [comment]
If you disable the audio cache it kind of works. BUT this page uses a very poorly written audio caching: 
![grafik](https://user-images.githubusercontent.com/1105157/52223981-3415bc80-28a7-11e9-9499-5fee84cde275.png)

The author should change that!

In 0.5.7 I changed nothing with the audio protection. But in 0.5.6 I changed some things - maybe the audio was not protected in a former version with your settings... I would have to know your settings.

Which other sites do not work properly?

**Comment by kkapsner** [comment]
What exactly do you mean with "not work correct"?
I do not speak Russian so I have no clue what should happen on this site.

**Comment by ysrn** [comment]
The TransferWise help pages (e.g. https://transferwise.com/help/article/2811598/borderless-account/what-type-of-payments-can-i-receive-into-my-borderless-account) are inflicted with the same issue. Disabling audio-cache helps, but there's still noticeable CPU churn and micro-hangs. Disabling audio protection entirely works well. 

It seems that many, if not most, users of the audio API use it in a way that the blocker just can't handle. It doesn't matter whether it is the result of bad coding practices, the reality is that it's there and it's common.

**Comment by kkapsner** [comment]
The TransferWise page should not use a tracker (js.navigator.io) that is poorly written (in fact I think that they just copied the bad code from https://audiofingerprint.openwpm.com/)

So there are two ways for you to solve your problem at the moment: either you use some decent tracking/add blocker (like NoScript or uBlock origin) that simply removes the slow scripts or you disable the audio protection.

I could offer you a setting that blocks the audio API for certain pages or a setting that blocks the API if it is called too often.

**Comment by ysrn** [comment]
A setting that blocks the API if it's called too often sounds like a good approach to me, if there's no other feasible perf/throttling solution.

I commented because that kind of behavior by sites is not that uncommon, and the resulting experience might be a deterrent in adopting CB unfortunately (FF very blatantly blames CB when this happens, with a top yellow bar). I wasn't looking for solutions to a specific problem, I can get TransferWise sorted. I was hoping for a solution within CB that would account for all such future TransferWises somehow. 

(As a side note, I do use both uBO and NoScript, but I disable the former when dealing with personal banks/fintech sites, and the latter wasn't blocking the tracker by default, which is how I encountered it)

**Comment by kkapsner** [comment]
Which old version of CB do you want to use? I think all versions that protect the audio API will have the same problem.

**Comment by uragan60** [comment]
0.5.5 work perfectly !!!
i tell you more it working amazing with AudioContext fingerprint Defender

**Comment by kkapsner** [comment]
That's weird - 0.5.5 should have the same issues with the audio protection than 0.5.7. Maybe the protection was disabled for you (I changed how the blocking modes work) or it was completely broken (quite unlikely as I think I tested it).

I know at least two ways to get the real audio fingerprint when using the defender.

@ysrn: I think there is a simpler way to solve these performance issues without blocking the API when called too often.

**Comment by kkapsner** [comment]
0.5.8 is out - please recheck.

**Comment by kkapsner** [comment]
@uragan60 please check my audio testing page with AudioContext fingerprint defender: http://canvasblocker.local/test/audioTest.html
There you can see what I mean that it's not a good protection.

**Comment by crssi** [comment]
I believe upper URL is not good and the right would be [https://canvasblocker.kkapsner.de/test/audioTest.html](https://canvasblocker.kkapsner.de/test/audioTest.html) :wink: 

Cheers

**Comment by kkapsner** [comment]
Oh... you're totally right - I corrected it.
