### ISSUE TITLE
Unclear: How to restore options that were hidden?

### ISSUE THREAD

**Issue by powyncify** [kkapsner/CanvasBlocker#314]
## Description
After clicking on an eye icon to hide an option, it should be clear how to restore ("unhide") the option.

## Expected Behavior
Click on the first eye icon to see hidden option.

## Current Behavior
1. Clicking on the first eye icon to does NOT restore hidden options
2. "Reset Settings" does not restore hidden options
3. Reinstall does not restore hidden options 

## Possible Solution
Make it easy to restore hidden options (or eliminate the possibility of hiding options)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CanvasBlocker Version used: 0.57
* Firefox version incl. 32- or 64-bit: 65 64-bit
* Operating System and version (desktop or mobile): Windows 10 desktop
![canvasblocker bug](https://user-images.githubusercontent.com/17192121/52306583-fe7fda80-295d-11e9-84fa-f4d065aa887d.jpg)
![canvasblocker bug](https://user-images.githubusercontent.com/17192121/52306709-4999ed80-295e-11e9-9a98-877378853058.jpg)

* Installed addons:

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"blockMode": false
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 0,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "16",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5

**Comment by kkapsner** [comment]
If you click on the first eye the hidden settings are displayed (with a crossed eye) and you can then click the eye again to unhide them:
![grafik](https://user-images.githubusercontent.com/1105157/52309682-33f9e780-29a1-11e9-99af-5f0c3c40ccb4.png)

"Reset settings" does restore the hidden settings, but there is a bug that you have to reload the settings page (F5) - I will address that.

Reinstalling does not change any settings as Firefox keeps them on your drive.

**Comment by powyncify** [comment]
First, thanks for your work on this important extension. I'm glad if I can contribute something.

So, I know that clicking on the eye _should_ reveal hidden options. But it doesn't on my version. Also, reset doesn't restore the hidden options.

I even created a completely new profile with no other extensions, just Canvas Blocker. Oddly, Canvas Blocker still doesn't show the hidden options, although they were hidden in a different profile.

1. Short-term: Is there a way to restore a hidden option by editing the setting files directly? I need the whitelist option urgently.
2. Long-term: Let me know if I can help in solving this.

Thanks again for your work!

**Comment by kkapsner** [comment]
The whitelist is not hidden by the eye but because you have to enable the expert mode to see it.
But you should be able to accomplish the same result by adding a URL-specific block mode.

**Comment by powyncify** [comment]
I understand. 

I'd suggest that the white list is a very important function. In some sites, I want to allow fingerprinting. Here's why: For account security, many sites (banks, Amazon) rely on fingerprinting to prevent unauthorized access. Because Canvas Blocker hinders fingerprinting, these sites respond by blocking access. So, I hope for an easy way to exclude some sites.

Thanks a lot for your work on this plugin. It is incredibly important!

**Comment by kkapsner** [comment]
The white list is just for legacy and backward compability there. The way to go is to use URL specific settings. If you want to allow a website you can simply click on the icon in the address bar:
![grafik](https://user-images.githubusercontent.com/1105157/52381170-c3220080-2a70-11e9-8ac7-226c2c377ce8.png)

**Comment by powyncify** [comment]
Thanks for clarifying. I mistakenly assumed that the options are what is visible when clicking on the green/red icon. I didn't realize that both icons are clickable.

Thanks for your patience. I hope that you can make it clearer, so you can spend more time on development and less time explaining to users like me...

**Comment by kkapsner** [comment]
Actually the address bar icon was introduced before the tool bar icon.

I have a screenshot of the dialog of the address bar icon on the page of the addon on AMO. If you know an additional/better place to show it please tell me.

**Comment by MaliusArth** [comment]
It is NOT clear that the eye in front of the search bar makes all hidden settings visible.
It should be distinguishable from the other eyes since its effect is different from the others.
Especially due to the search bar and the eye being part of the settings table it looks like the search bar itself can be hidden with this eye icon.
I suggest to put the visibility toggle beside the "Settings" title (<h1>) or add a separate checkbox (not the eye icon) underneath "Settings" with "Show hidden settings" written beside it.
The reasoning behind explicitly using a checkbox is that everyone who has ever used the internet before will know what behavior to expect from interacting with it - it is a toggle to switch between two states.
Everyone who sees the eye icons for the first time or who returns back to the settings after a long time will click on an eye to see what it does and then find themselves googling to get the settings back without having to reset all the settings, like I had to just now.

**Comment by kkapsner** [comment]
The settings title is not visible if you go to the settings via about:addons.

I think the separate checkbox with a label would be the most intuitive solution. And it should not be too hard to implement.

**Comment by kkapsner** [comment]
![image](https://user-images.githubusercontent.com/1105157/58089473-202b6780-7bc5-11e9-8980-139c734ffa4e.png)

**Comment by kkapsner** [comment]
Check out https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC2

**Comment by kkapsner** [comment]
Release 0.5.9 is published.
