### ISSUE TITLE
Protecting getImageData fails detection test

### ISSUE THREAD

**Issue by bugrepo** [kkapsner/CanvasBlocker#316]
## Description

Protecting **getImageData** function fails detection test:

known pixel value test 10: API tampering detected

https://canvasblocker.kkapsner.de/test/detectionTest.html

## Expected Behavior

Expected 220, got 221.
Expected 117, got 118.

etc.
 
## Steps to Reproduce (for bugs)

1. Disable all addons.
2. Install CanvasBlocker.
3. Go here: https://canvasblocker.kkapsner.de/test/detectionTest.html
4. If the test fails, disable getImageData protection and see the difference.

## Your Environment

* CanvasBlocker Version used: 0.5.7
* Firefox version incl. 32- or 64-bit: Firefox 65, 32-bit
* Operating System and version (desktop or mobile): Win 7 32-bit
* Installed addons: CanvasBlocker

**Comment by kkapsner** [comment]
You can protect the "input" part of canvas or increase the minimum size for a faked canvas to get rid of the detection.

But as mentioned in #114 there will always be a way to detect CB as it alters the content of the canvas (or the other APIs).

**Comment by bugrepo** [comment]
The "input" part works perfect! No detection at all! Thanks!
