### ISSUE TITLE
Script error 

### ISSUE THREAD

**Issue by reeslo** [kkapsner/CanvasBlocker#317]
Lastest version Firefox, Oneplus 3, Android 8.0.0

Go here : 
https://amiunique.org/fp

Screenshot : 
https://drive.google.com/file/d/1TmbLR7PjOoULpMu8JsX_nM20by7EtGHO/view?usp=drivesdk

**Comment by kkapsner** [comment]
I'm not allowed to see your screenshot.

What is the error?
Or is it the message that CanvasBlocker is slowing down Firefox? This is actually a problem of bad code in the website (e.g. #310). But the next version will have a solution for it.

**Comment by reeslo** [comment]
I've set share option to screenshot, message is similar Yep :)

**Comment by kkapsner** [comment]
My French is quite bad but exactly this behaviour should be solved with the next release (hopefully released today).

**Comment by kkapsner** [comment]
0.5.8 is out - please recheck.

**Comment by reeslo** [comment]
It's same :(

**Comment by kkapsner** [comment]
Hm... does it work if you disable the audio cache?

**Comment by reeslo** [comment]
Same : https://drive.google.com/file/d/1oEJ99i7kpMKmsgZUnsBAQ23efTV9r6e4/view?usp=drivesdk

**Comment by kkapsner** [comment]
Which API is the problem? Audio API?

**Comment by kkapsner** [comment]
Please disable all APIs and reenable them one by one until you get the script timeout. With this method we can find which API it is.

Without this information I'm not able to help you.

**Comment by kkapsner** [comment]
If you still see the problem and want to share the necessary information with me please post it and I will reopen this issue.
