### ISSUE TITLE
"Settings loading" test fails on "input" and "everything" parts

### ISSUE THREAD

**Issue by bugrepo** [kkapsner/CanvasBlocker#318]
If using "input" or "everything" part, then "Settings loading" test fails (red background).

If using "readout", then OK (green background). It it normal?

https://canvasblocker.kkapsner.de/test/settingsLoading.php

## Your Environment

* CanvasBlocker Version used: 0.5.7
* Firefox version incl. 32- or 64-bit: Firefox 65, 32-bit
* Operating System and version (desktop or mobile): Win 7 32-bit
* Installed addons: CanvasBlocker

**Comment by kkapsner** [comment]
It's normal because the canvas cache cannot work with "input". You can either use the persistent or constant random number generator to solve this issue.

**Comment by bugrepo** [comment]
Thanx for your help!

I tried to change values, but nothing happened until I guessed to restart the addon. After restart works fine!

**Comment by kkapsner** [comment]
That's weird. Maybe the browser was in the process of upgrading (0.5.8 came out today)...

**Comment by bugrepo** [comment]
I thought the same when I saw, that addon was updated :)
