### ISSUE TITLE
Audio issue with Protect DOMrect API enabled

### ISSUE THREAD

**Issue by SeriousHoax** [kkapsner/CanvasBlocker#319]
Audio breaks on this twitter video, https://twitter.com/ATP_Tour/status/1097164274072469504

As well as another website but you won't be able to access this site, 
http://172.16.29.29/

Disabling DOMRect API protection fix the audio.

* CanvasBlocker Version used: 0.5.8 with default settings
* Firefox Beta 66
* Operating System: Windows 10 & Manjaro Linux

**Comment by crssi** [comment]
Audio does not work at your twitter URL even when CB is not installed... but funny the audio does work when you click on time/progress bar. And it works in that case even when CB is installed.
So, I don't think that CB has anything to do with the audio in this case.

The second URL, that is `http://172.16.29.29/`, is local area IP address, which is not available over Internet.

Cheers

**Comment by kkapsner** [comment]
I see the same as crssi. Even without CB the audio is not there.

For the local site I have no idea what is the issue. I need more information there.

And why the DOM-Rect protection would interfere with any audio issues is extremely weird.

**Comment by SeriousHoax** [comment]
Well that's weird. My assumption was wrong I guess. But I can clearly listen to the audio after clicking the play button on the the official site and tweetdeck. By default, often the video plays mute, you have to unmute it so maybe that's what happened in your case. I just checked that the audio is fine on Tweetdeck but not on Twitter. I'm not being able to reproduce the issue I mentioned above. So, seems like not the issue of Canvas Blocker. 
I'm so sorry for wasting your time guys.

**Comment by kkapsner** [comment]
No problem.
