### ISSUE TITLE
fails at browserleaks

### ISSUE THREAD

**Issue by siliconic001** [kkapsner/CanvasBlocker#32]
Could you fix it so that it looks like its coming from a normal functioning but different computer every time?  From the test at browserleaks it fails to show a png and that could be used to identify and seperate you from normal users.  so this does not work at all.
![screen shot 2015-07-30 at 10 18 50 am](https://cloud.githubusercontent.com/assets/8810714/8985513/d2ee3212-36a5-11e5-81b7-0e3d42243009.png)

**Comment by kkapsner** [comment]
Sorry - but this is nearly impossible to do. The only think I can do is to make the PNG valid...

I am aware that it's possible to detect if the addon is running.
