### ISSUE TITLE
Navigation arrows are blocked on Yandex Maps.

### ISSUE THREAD

**Issue by RJ2k6** [kkapsner/CanvasBlocker#324]
https://i110.fastpic.ru/big/2019/0307/3d/5e946c44acd4684554da5e10cb1f423d.jpg
These arrows are blocked. So, it's not impossible to use it.
## Steps to Reproduce (for bugs)

1. https://yandex.ru/maps/213/moscow/?l=stv%2Csta&ll=37.622024%2C55.750482&panorama[direction]=347.397518%2C8.599813&panorama[point]=37.612414%2C55.746830&panorama[span]=120.000000%2C68.175332&source=wizbiz_new_map_single&z=14
2.
3.
4.

## Your Environment

* CanvasBlocker Version used: 0.5.8
* Firefox version: 64-bit:
* Operating System and version (desktop or mobile): windows 7 x64
* Installed addons: I switched off all addons. The problem with CanvasBlocker/

## Your Settings

CanvasBlocker settings are default.

**Comment by kkapsner** [comment]
There is little I can do about that. They draw the arrows in the canvas and then determine over the pixel data (they use webGL and readPixeldata) where these arrows are by the color... seems like a Hack to me - especially as they check for it (nearly) every time you move your mouse.

On my screen it starts to work when I go into full screen as I have the maximum faking size set to 1000000 and then the canvas is bigger than that.

The only thing I could offer is a "color whitelist" where you can enter a color definition and this color is then not faked...

**Comment by crssi** [comment]
It looks like that the "street view" on this site doesn't like anything advanced against figerprinting.

In a plain vanilla + just one pref breaks the "street view":
``` js
user_pref("privacy.resistFingerprinting", true);
```

**Comment by RJ2k6** [comment]
Ok. Thanks.

**Comment by kkapsner** [comment]
The color whitelist does not work... so it is not compatible with CB. So I'm sorry but there are only three options: either allow canvas on this page, disable the readPixel protection or set the max canvas size to something you are comfortable with and which is lower than the street view.

So unfortunately there is nothing else I can do for you. I'm sorry.
