### ISSUE TITLE
Totally unique fingerprint readout

### ISSUE THREAD

**Issue by AMihail1** [kkapsner/CanvasBlocker#326]
https://browserleaks.com/canvas spitting out a totally unique fingerprint - aren't we trying blend in, not have a totally trackable fingerprint? Is there any option to implement something like "blend" rather than "fake" ?

**Comment by kkapsner** [comment]
#154, #81

You can use privacy.resistFinterprinting to blend in with the TorBrowser users and have CB as a secondary line of defence.

**Comment by AMihail1** [comment]
Unfortunately resist.Fingerprinting breaks Captchas beyond use, I've sat thru one 5-10 times before it'll complete.

**Comment by kkapsner** [comment]
Yes - Google does not encourage you to protect you privacy.
