### ISSUE TITLE
WebGL Always show original value

### ISSUE THREAD

**Issue by Renan19** [kkapsner/CanvasBlocker#329]
Its simple, go to https://browserleaks.com/webgl
"WebGL Report Hash" is the same, no matter settings.
and "https://canvasblocker.kkapsner.de/test/webGL-Test.html" ever show "faked"
can change to "not faked" seting min value to "1000" but in browserleaks repost hash still the same.
and fake vision detect fake webgl in all cases.

I am attaching a probably solution, code attached.
Thanks for great work.

[solution.txt](https://github.com/kkapsner/CanvasBlocker/files/3050246/solution.txt)

**Comment by kkapsner** [comment]
For me the WebGL Image hash changes with every refresh.
The report hash is not touched by CB.

After having a look at the code I see several issues with it. The major being that I think it's a very bad idea to pretend that you are using a different browser. There are too many things that give away which browser you are using. So when the fingerprinter gets inconsistent data there you are easier to track.

But having a look at the getParameter function should be worth a shot. Maybe there is enough entropy that's worth fiddling with.

**Comment by Renan19** [comment]
First, thank you for responding. your work is amazing.

On the different browser, these WebGL results may vary, and I do not know if they could be used to identify your browser, but I'm not sure of that, here are a few examples.

===Chrome in Original Pc
ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
===Chrome in VM1
Google SwiftShader

===Firefox in Original Pc
ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
===Firefox in VM1
ANGLE (Software Adpter Direct3D11 vs_4_1_ps_1_1)

You see? same browser versions and differenta adapters, because hardware's change to a software Adpter.

The Code that I passed you passes the test and results as "not faked" since it generates an image with identifiable pixels, and can bypass fvision every time, probably for the same reason.

In contrast, it can not generate a hash of the image, which your CB code does perfectly.

If we could join the two solutions and select what to emulate, it would be perfect.

Thank you again.

**Comment by testomesto** [comment]
I don´t know why but since 1-2 days, CanvasBlocker gets detected to fake WebGL. I installed a new VM with Win7 x64 and a fresh Firefox + CB but if I activate it it gets detected.

Maybe you could check that and confirm or negate it ?

**Comment by kkapsner** [comment]
Please try release 0.5.9

If you still get detected please tell me exactly where you get detected and how you realized.

**Comment by testomesto** [comment]
Okey so i updated to 0.5.9.1 and i encountered a problem with the audio api

So WebGL still shows fake in persistent and non-persitent mode. I need to set minimal colors to 1 to get "not faked"

But now the Audio Api wont work in persistent mode. It gives the empty hash but 10kHz and 20kHz and the Sum are empty

**Comment by kkapsner** [comment]
Are you talking about https://canvasblocker.kkapsner.de/test/webGL-Test.html with the WebGL? Getting a "faked" is kind of fine - this is just a test if CB handles WebGL. Setting the minimal colours to 1 is a totally fine setting to prevent the detection there.

The audio issue should be fixed with 97e08d874a782d920a627e0b55891b1cf7527d33

**Comment by ChthonVII** [comment]
I'd like to also request faking the WebGL Report Hash parameters. In addition to Renan's approach, you might take a look at the way [this extension](https://addons.mozilla.org/en-US/firefox/addon/webgl-fingerprint-defender/?src=search) does it.

**Comment by kkapsner** [comment]
I had a look at getParameter and the other extension (quality is as expected: suboptimal) and think that there should be something in CB. But I'm not yet sure of the best way to fake something there. The shown methods do not convince me.

**Comment by andersonoliveira111** [comment]
software to inspiration about webgl and other things.
https://multilogin.com
https://kameleo.io
https://www.ivanovation.ro

**Comment by kkapsner** [comment]
Please check the latest beta version: https://canvasblocker.kkapsner.de/versions/

**Comment by spodermenpls** [comment]
Looks good to me. 👍

**Comment by kkapsner** [comment]
Version 0.5.14 is published.

**Comment by crssi** [comment]
Cool. Thank you.

Does this mean that `WebGL` is "protected", or there are any additional actions required (by current knowledge)?

Cheers

**Comment by kkapsner** [comment]
For the webGL hash nothing has to be done. If you want your (unmasked) vendor/renderer changed you have to set it in the settings. I have too few data points to give a full randomized faking option for these.
