### ISSUE TITLE
'Faked readout' notification on very long URLs causes window to extend beyond chrome with no scrollbar

### ISSUE THREAD

**Issue by rootwork** [kkapsner/CanvasBlocker#33]
Great add-on! Recently I've been noticing that with sites that generate long URLs, CanvasBlocker causes an unfortunate bug. The "Faked readout..." notification attempts to display the entire URL, which extends to the right beyond the chrome of the window.

Most problematically, it does not generate a scrollbar in Firefox, which means the controls for dismissing that notification (along with part of the content of the website, and the right side of Firefox's own toolbars and tabs) are beyond the edge of the window, and there's no way to reach them.

The only way to correct the problem is to close the tab. Firefox will continue operating in this enlarged-but-not-visible state, even on other tabs, until you close the tab with the problematic notification.

Here's an illustration:

![screen shot 2015-08-08 at 10 08 07 am 2](https://cloud.githubusercontent.com/assets/79733/9151383/c6dd9e56-3db5-11e5-826b-f430581da91d.png)

This is the test URL, a search on Google for lorem ipsum text:
https://www.google.com/search?safe=off&site=&source=hp&q=Lorem+ipsum+dolor+sit+amet%2C+consectetur+adipiscing+elit.+Vestibulum+lacinia+ante+non+dolor+viverra+iaculis.+Class+aptent+taciti+sociosqu+ad+litora+torquent+per+conubia+nostra%2C+per+inceptos+himenaeos.+In+adipiscing+pulvinar+eros%2C+vitae+dictum+elit+cursus+a.+Praesent+a+hendrerit+urna.+Maecenas+neque+libero%2C+viverra+in+neque+at%2C+posuere+tempor+metus.+Vestibulum+neque+nisi%2C+malesuada+sed+ipsum+varius%2C+bibendum+ornare+nisl.+Aliquam+adipiscing+vehicula+varius.+Morbi+a+interdum+lacus.+Integer+luctus+lobortis+magna%2C+nec+vulputate+augue+blandit+ac.&oq=Lorem+ipsum+dolor+sit+amet%2C+consectetur+adipiscing+elit.+Vestibulum+lacinia+ante+non+dolor+viverra+iaculis.+Class+aptent+taciti+sociosqu+ad+litora+torquent+per+conubia+nostra%2C+per+inceptos+himenaeos.+In+adipiscing+pulvinar+eros%2C+vitae+dictum+elit+cursus+a.+Praesent+a+hendrerit+urna.+Maecenas+neque+libero%2C+viverra+in+neque+at%2C+posuere+tempor+metus.+Vestibulum+neque+nisi%2C+malesuada+sed+ipsum+varius%2C+bibendum+ornare+nisl.+Aliquam+adipiscing+vehicula+varius.+Morbi+a+interdum+lacus.+Integer+luctus+lobortis+magna%2C+nec+vulputate+augue+blandit+ac.

But to be clear, this happens on all kinds of websites, including ones that don't have long URLs of their own, because sometimes they have embedded components that do have long URLs.

I think the notification needs to either enforce some kind of wrapping on the URLs at whatever the existing window size is, regardless of what the characters in the URL are, or display the first X characters of the URL, with an ellipsis or something to see the full URL if you want to see it.

**Comment by kkapsner** [comment]
Thank you for that finding - weirdly I never saw something like this. But I am able to reproduce it.

I have two ideas to solve this problem:
* I will no longer show the full URL but only the domain and add a button to show the full URL
* to arrange the buttons in one dropdown action button is on my agenda quite a time - this will reduce the needed space

But to be honest I think this is also an issue that Mozilla should address...

**Comment by rootwork** [comment]
Either of those seem like good solutions (naturally I defer to you to
decide which!) -- but I agree, it's a weird situation Mozilla should fix
since it seems like other plugins could trigger it.


kkapsner wrote:

**Comment by kkapsner** [comment]
I think I will go with the first - it's easier...

... but the second still remains on the agenda.
