### ISSUE TITLE
Add a whitelist to allow certain domains to use default javascript

### ISSUE THREAD

**Issue by lolcocks123** [kkapsner/CanvasBlocker#330]
I would like to use the default JavaScript APIs on some domains.

There should be a whitelist feature for CanvasBlocker.

Or is there one but I missed one?

**Comment by kkapsner** [comment]
If you click on the icon in the address bar you can whitelist there:
![image](https://user-images.githubusercontent.com/1105157/55682597-13fd8a80-5936-11e9-9cf4-f0faaa27f400.png)

You can also whitelist only certain APIs. I can provide more insights if you tell me what you want to achieve (and why).
