### ISSUE TITLE
[Feature Request] Per website settings

### ISSUE THREAD

**Issue by Aq32** [kkapsner/CanvasBlocker#331]
As the title suggests I'd like to request a feature where you could block and allow certain APIs for certain websites from the addon-icon on the toolbar.

eg.
Website/url: reddit.com
canvas ☒
audio ☒
history ☒
window ☒
domRect 🗹

Website/url: google.com
canvas ☒
audio ☒
history ☒
window ☒
domRect ☒

**Comment by kkapsner** [comment]
This is already possible for most of the APIs (but not from the addon-icon - just in the settings):
![image](https://user-images.githubusercontent.com/1105157/55687060-f0076c80-5968-11e9-9784-331f1a4badcd.png)

I do not plan to make this available in the addon-icon popup. Maybe I will add it to the url bar icon. At the moment you can only completely whitelist there:
![image](https://user-images.githubusercontent.com/1105157/55687101-52f90380-5969-11e9-869c-7e934300f993.png)
I could imagine to make this API specific.

**Comment by Aq32** [comment]
I did notice the url bar icon after making this request so this could be helpful for some people. More options are always better and we could learn more about which sites are worthy of trust.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC1

**Comment by kkapsner** [comment]
Release 0.5.9 is published.
