### ISSUE TITLE
Prevents CSV export from Google Contacts

### ISSUE THREAD

**Issue by nbeaver** [kkapsner/CanvasBlocker#333]
## Description

Attempt to export Google Contacts fails silently regardless of the format or number of contacts.

## Expected Behavior

Google Contacts produces a CSV or vCard file of contacts for download.

## Current Behavior

Pressing the final "Export" button silently fails.

## Steps to Reproduce (for bugs)

Export Google Contacts [as described on support page](https://support.google.com/contacts/answer/7199294?hl=en&ref_topic=6154204).

1. Open <https://contacts.google.com/>
2. Log in.
3. Click "More"
4. Click "Export"
5. Select one or more contacts and format.
6. Click "Export"

## Context

Reproduced on  for Ubuntu 18.04 in a clean profile with CanvasBlocker as the only installed add-on.

## Your Environment

* CanvasBlocker Version used: 0.5.8

* Firefox 66.0.2 (64-bit)

* Ubuntu 18.04 (Bionic Beaver)

* Installed addons: only CanvasBlocker

## Your Settings

    {
            "logLevel": 1,
            "urlSettings": [],
            "hiddenSettings": {},
            "expandStatus": {},
            "displayHiddenSettings": false,
            "whiteList": "",
            "sessionWhiteList": "",
            "blackList": "",
            "blockMode": "fake",
            "protectedCanvasPart": "readout",
            "minFakeSize": 1,
            "maxFakeSize": 0,
            "rng": "nonPersistent",
            "protectedAPIFeatures": {},
            "useCanvasCache": true,
            "ignoreFrequentColors": 0,
            "minColors": 0,
            "fakeAlphaChannel": false,
            "persistentRndStorage": "",
            "persistentIncognitoRndStorage": "",
            "storePersistentRnd": false,
            "persistentRndClearIntervalValue": 0,
            "persistentRndClearIntervalUnit": "days",
            "lastPersistentRndClearing": 1554832710231,
            "sharePersistentRndBetweenDomains": false,
            "askOnlyOnce": "individual",
            "askDenyMode": "block",
            "showCanvasWhileAsking": true,
            "showNotifications": true,
            "highlightPageAction": "none",
            "highlightBrowserAction": "color",
            "displayBadge": true,
            "storeNotificationData": false,
            "storeImageForInspection": false,
            "ignoreList": "",
            "ignoredAPIs": {},
            "showCallingFile": false,
            "showCompleteCallingStack": false,
            "enableStackList": false,
            "stackList": "",
            "protectAudio": true,
            "audioFakeRate": "100",
            "audioNoiseLevel": "minimal",
            "useAudioCache": true,
            "audioUseFixedIndices": true,
            "audioFixedIndices": "15",
            "historyLengthThreshold": 2,
            "protectWindow": false,
            "protectDOMRect": true,
            "domRectIntegerFactor": 4,
            "blockDataURLs": true,
            "displayAdvancedSettings": true,
            "displayDescriptions": false,
            "theme": "default",
            "dontShowOptionsOnUpdate": false,
            "isStillDefault": false,
            "storageVersion": 0.5
    }

**Comment by kkapsner** [comment]
It's the blockDataURLs setting. If you set this to false it should work.

But you set yourself to some risk as there is then a vector to extract your fingerprint (see #208 for further details). As Mozilla apparently is not focusing on the underlying problem I may should try to make this setting url specific so you can allow data-URLs for specific sites...

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC1

**Comment by kkapsner** [comment]
Release 0.5.9 is published.
