### ISSUE TITLE
reCAPTCHA

### ISSUE THREAD

**Issue by ghost** [kkapsner/CanvasBlocker#335]
Is there any particular URLs we can whitelist or settings we can tweak to make reCAPTCHAs a bit shorter? With all the default settings on I'm getting the one that makes you click the pictures and they're loading as if we're back on dialup internet ...

**Comment by kkapsner** [comment]
And they are fast if you disable CB?

If I test https://www.google.com/recaptcha/api2/demo it seems fine for me. On which page do you have the slow loading?

So to answer your question: there might be one but I do not know which ;)

**Comment by AMihail1** [comment]
I think it might be a canvasblocker + ghacks user.js problem ... I'm having to solve at least 5 loops to get thru.

**Comment by kkapsner** [comment]
I also have to solve some loops.  But with only CB installed (and nothing else) I only have to do one loop.

**Comment by kkapsner** [comment]
You could try to disable all protection in CB and the reenabling then one by one.

**Comment by AMihail1** [comment]
Today I learned:

window.name/opener play a big part for the reCAPTCHA errors. With it enabled in CB and the whitelists on sometimes I can't get the reCAPTCHA window to load at all, sometimes spits out the "automated traffic" error ... perhaps you could take a look into it?

about:config settings:
`user_pref("privacy.firstparty.isolate", false);` - "automated traffic" error loop if `true`
`user_pref("dom.targetBlankNoOpener.enabled", false);` - opener/name seem to play a big role here
`user_pref("privacy.firstparty.isolate.restrict_opener_access", false);` - same as above
`user_pref("dom.webaudio.enabled", true);` - this is for the Buster addon that solves them using text to speech API

**Comment by AMihail1** [comment]
I'm not sure the automatic whitelist entry for reCAPTCHA under Window API is actually doing anything - can you confirm its still working?

**Comment by kkapsner** [comment]
Yes I can confirm that it still works. Without it the captchas do not work at all.

**Comment by AMihail1** [comment]
I'm getting a strange bug where they don't load at all with Window API protected and the whitelist enabled - perhaps some ghacks user.js setting is interfering?

**Comment by AMihail1** [comment]
Also - is it possible to add reCAPTCHA to the Audio API whitelist?

**Comment by kkapsner** [comment]
Please send me your settings when you get the strange bug behaviour.

You also be able to disable the audio protection for the reCAPTCHA url:
![image](https://user-images.githubusercontent.com/1105157/56691873-3edf3100-66e1-11e9-92ea-7a1822f8adf3.png) -> 
![image](https://user-images.githubusercontent.com/1105157/56691897-47376c00-66e1-11e9-817c-46c00a295dfc.png)

**Comment by AMihail1** [comment]
Ahh, I didn't see those extra little black arrows!

Are we 100% sure on the syntax of the whitelist entry? Some other addons are expecting a ? after https like this: ^https**?**://www\.google\.com/recaptcha/api2/(?:b?frame|anchor).*$ - is it possible to remove **(?:b?frame|anchor)** to just allow everything after /recaptcha/ ?

**Comment by kkapsner** [comment]
You can add the "?" if you want to. I think Google uses https everywhere so it should not make a difference.

Yes, you can remove the frame|anchor part. I just want to be as specific as possible.

PS: the easiest way to modify these URL RegExp is with the settings inspection.

**Comment by AMihail1** [comment]
Can you confirm this is the correct syntax to whitelist?  

`^https://www\.google\.com/js/bg.*$`

**Comment by kkapsner** [comment]
Syntax is correct.

**Comment by kkapsner** [comment]
Do you still have the weird issue or can we close this?

**Comment by kkapsner** [comment]
3 weeks no reply: I will close this. If you still have the issue I can reopen this.
