### ISSUE TITLE
"Show notifications" option - what it actually does?

### ISSUE THREAD

**Issue by ReporterX** [kkapsner/CanvasBlocker#336]
I wonder what it actually does. Does it simply hide the icon in the address bar, or completely disable notification anywhere plus hiding the icon?

If it is just the former, I would suggest renaming as "Show notification icon in address bar".

Thank you.

**Comment by kkapsner** [comment]
It only hides the icon in the address bar. But instead of renaming I think it would be better when it would also disable the notification via the toolbar icon.

**Comment by kkapsner** [comment]
I changed my mind. The toolbar icon and the badge can be removed independently. So I will just change the description in the options page.

**Comment by kkapsner** [comment]
(The actual name will stay the same as it would be too long.)

**Comment by ReporterX** [comment]
Well you may change it into **Show notification icon**.

**Comment by kkapsner** [comment]
That sound reasonable.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC1

**Comment by kkapsner** [comment]
Release 0.5.9 is published.
