### ISSUE TITLE
[BUG] Protect Window API broken Google Captcha

### ISSUE THREAD

**Issue by Renan19** [kkapsner/CanvasBlocker#337]
If you protect "name" in "Window API" its broken google captcha
If tou deactive this protection, captcha works.

**Comment by crssi** [comment]
@Renan19 can you provide URL to your captcha test page?

**Comment by Renan19** [comment]
@crssi Yes, you can test here

`https://patrickhlauke.github.io/recaptcha/`

Open the page and click in checkbox to open captcha window.

**Comment by spodermenpls** [comment]
@Renan19 Did you whitelist this URL `^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$` in your site-specific settings for the Window API?

**Comment by Renan19** [comment]
> 
> 
> @Renan19 Did you whitelist this URL `^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$` in your site-specific settings for the Window API?

This regex dont work for me, work only if a put the url in whitelist ( `https://www.google.com/recaptcha/api2/` )
But it will broken secure if recaptcha fingerprint users.

**Comment by AMihail1** [comment]
Confirmed same bug for me - captcha won't work with window name protected and with it off I still get a 5-10 captcha loop ... there must be a way to fix this while maintaining privacy?

**Comment by kkapsner** [comment]
If you enable the window protection you are prompted if you want to add an exception for reCaptcha:
![grafik](https://user-images.githubusercontent.com/1105157/56345253-8fc1c780-61bf-11e9-994c-65b570e6adf8.png)
This will then add the suggested URL specific setting:
![grafik](https://user-images.githubusercontent.com/1105157/56345327-c4ce1a00-61bf-11e9-90cb-19787c0008fe.png)

The multiple loops are reproducible with my normal profile but not with a plain CB profile. So I think it is a mix between different addons/settings.

**Comment by crssi** [comment]
@kkapsner 
I get the warning like [this](https://send.firefox.com/download/ffc8fd5fde27c5f8/#QcrIVWZmaFIrCZ60L6zEwQ)
The is no window and the buttons are also missing.

**Comment by kkapsner** [comment]
This message is broken in the current Firefox but it works if you open the settings page in a separate tab or in the nightly build.
So there is little I can do about it.

**Comment by kkapsner** [comment]
So to close this issue:
* open the settings in a separate tab: ![grafik](https://user-images.githubusercontent.com/1105157/56369665-13000f00-61fa-11e9-9d30-3607176bb569.png)
* disable the window protection and reenable it
* add the exception when prompted
