### ISSUE TITLE
Settings gone after deactivate

### ISSUE THREAD

**Issue by Daisenki** [kkapsner/CanvasBlocker#338]
Settings are complete gone if you deactivate the add-on and reactivate it. Why does the add-on not save setting and restore it? Sometimes I need to deactivate it to get the fucking captchas to work.

Any news for a new version btw?

* CanvasBlocker Version used: 0.5.9 Alpha20190227
* Firefox version incl. 32- or 64-bit: 66.0.3 (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Home 1809 - 17763.437
* Installed addons: ClearURLs, Cookie AutoDelete, CSS Exfil Protection, Decentraleyes, Don't track me Google, FrankerFaceZ, HTTPS Everywhere, Iridium for YouTube, LastPass, Live Stream Notifier, Local CDN, MyJDownloader, NoScript, Privacy Possum, Smart Referer, Tampermonkey, uBlock Origin, Zoom Page WE

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$",
			"protectWindow": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 0,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "maximal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "19",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": true,
	"navigatorDetails": {},
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}

**Comment by kkapsner** [comment]
The settings should be restored on reactivating CB. And for me I cannot reproduce the problem. Can you please try with a fresh profile?

I do not do something special with the settings - I just use the provided storage API.

So I guess if the settings are cleared is a Firefox thing. You could use the settings export and import to solve the issue but this sounds kind of annoying.

PS: Next version will be released soon - I hope.

**Comment by kkapsner** [comment]
Did you reproduce with a fresh profile?

**Comment by Daisenki** [comment]
It did not happens anymore, I don't know why, maybe it was any setting I change, I close the ticket.

**Comment by kkapsner** [comment]
Thanks for checking.
