### ISSUE TITLE
Open CanvasBlocker, WebGL Image Hash has been changing, how to solve?

### ISSUE THREAD

**Issue by andychiu555** [kkapsner/CanvasBlocker#339]
In the environment where CanvasBlocker (the default mode) is turned on, whenever I refresh the website: https://browserleaks.com/webgl, (WebGL Image Hash) each time has different data.
So there is a problem: when you open a website, the website may be obtained multiple times (WebGL Image Hash), then the website will get different data (WebGL Image Hash).
However, if you close CanvasBlocker, the site gets multiple acquisitions (ebGL Image Hash) and always gets fixed data.
According to this phenomenon, in the environment where we open CanvasBlocker, the website can determine whether we use CanvasBlocker according to each data change. This seems to be a BUG?

**Comment by kkapsner** [comment]
The canvas cache prevents that a website that obtains the image data several times will get different data (you can see that at https://canvasblocker.kkapsner.de/test/test.html if you click on refesh the data obtained again).

If you want to have the same have between different page loads you can switch to the persistent random number generator.
