### ISSUE TITLE
xhamster

### ISSUE THREAD

**Issue by bagell** [kkapsner/CanvasBlocker#34]
hello, since the last update yesterday i cant login on xhamster.com :(
btw. there is no changelog on addons.mozilla.org for the 0.1.8-Release

**Comment by kkapsner** [comment]
Can you please post the error messages that appear in the developer console.

PS: There is a changelog, but it's not displayed... weird. But here on github you can easily see what is changed.

**Comment by bagell** [comment]
developer console?

**Comment by kkapsner** [comment]
Press F12 and select the console-tab in the occuring window/browser field.

**Comment by kkapsner** [comment]
You should check if the new version in the withoutPageMod-branch (https://github.com/kkapsner/CanvasBlocker/blob/withoutPageMod/canvasblocker.xpi ) works for you.

**Comment by bagell** [comment]
i checked the new Version and it works not
the message is

TypeError: 'getImageData' called on an object that does not implement interface CanvasRenderingContext2D. modifiedAPI.js:9:18
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented. jquery-1.9.1.o.min.js:1:0

**Comment by kkapsner** [comment]
Can you please tell me your FF version and the used OS.

**Comment by bagell** [comment]
windows 8.1 64 bit with Firefox 40.0.3

**Comment by kkapsner** [comment]
Can you please use https://github.com/kkapsner/CanvasBlocker/blob/moreDebuggingInfo/canvasblocker.xpi and make sure the "Display complete calling stack" preference is checked. This should show more infomation in the error message.

**Comment by bagell** [comment]
Error: 

Aufrufende Datei: 
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://canvasblocker-at-kkapsner-dot-de/canvasblocker/lib/modifiedAPI.js Zeile 61 Spalte 63
	https://eu-st.xhcdn.com/js/fingerprintjs2/fingerprint2.js Zeile 549 Spalte 42
	https://eu-st.xhcdn.com/js/fingerprintjs2/fingerprint2.js Zeile 174 Spalte 19
	https://eu-st.xhcdn.com/js/fingerprintjs2/fingerprint2.js Zeile 67 Spalte 14
	https://eu-st.xhcdn.com/js/main2.js?241 Zeile 1434 Spalte 1
	https://eu-st.xhcdn.com/js/jquery-1.9.1.o.min.js Zeile 1 Spalte 19248
	https://eu-st.xhcdn.com/js/jquery-1.9.1.o.min.js Zeile 1 Spalte 20141
	https://eu-st.xhcdn.com/js/jquery-1.9.1.o.min.js Zeile 1 Spalte 14658
	https://eu-st.xhcdn.com/js/jquery-1.9.1.o.min.js Zeile 1 Spalte 11905

original: [object HTMLCanvasElement]
context: null

**Comment by kkapsner** [comment]
Thank you for the trace. I am now able to reproduce the problem with some simle code

```JS
var canvas = document.createElement("canvas");
var context = canvas.getContext("webgl");
console.log(canvas.toDataURL());
```

It should now work with the latest version of the withoutPageMode-branch.

PS: This is a real fingerprinting script that breaks here.

**Comment by bagell** [comment]
It Works now and i likes when the real fingerprinting breaks here and now :)
Thanks for the rapid Support.
