### ISSUE TITLE
 White List of Domain Names

### ISSUE THREAD

**Issue by Machou** [kkapsner/CanvasBlocker#340]
## Description

Could you expand the area for the white list of domain names. If we add 2 or 3, that's fine, but now I have about 30 of them and it's not at all intuitive and annoying enough to manage this list.

Add a little button to whitelist the site would be quite nice too;)

## Your Environment
* CanvasBlocker Version used: latest (0.5.8)
* Firefox version: 63.0.3 - 64-bit
* Operating System and version (desktop or mobile): Windows 7 64-bit

**Comment by kkapsner** [comment]
The idea is that you should not use it at all. It's legacy from previous versions (and people complained when I hid it).

Instead you should use the url specific settings (indicated by the black arrow at the very right that you can click). With this you can manage url specific settings much better and more granular.

There is already a little button to whitelist a site: 
![image](https://user-images.githubusercontent.com/1105157/56613992-2ce58b80-6618-11e9-86a1-a6c9e2027300.png)

**Comment by Machou** [comment]
Yes, I know, but I don't think we're talking about the same thing.

I'm talking about changing the <input /> to <textarea>, for example, at this location :

![image](https://i.imgur.com/RWmHnQb.jpg)

Regards

**Comment by kkapsner** [comment]
OK - that I can do.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC1

**Comment by kkapsner** [comment]
Release 0.5.9 is published.

**Comment by Machou** [comment]
I think the textarea is still small, but it's already much better.

You should use bootstrap to style your fields:)

Thank you for your work anyway!

**Comment by kkapsner** [comment]
You can drag the textarea bigger:
![image](https://user-images.githubusercontent.com/1105157/58387077-9dae0800-8009-11e9-9a8c-8ae4d42c6c17.png)

**Comment by Machou** [comment]
I know i know :)

**Comment by Machou** [comment]
Why not add a button to the list to put a site on the white list? like adblock or ublock for example?

**Comment by kkapsner** [comment]
If you get the browser address bar icon (indicating that something was blocked or faked on that page) you can click it and whitelist the page there.

I also think that the url specific settings (particularly the blocking mode) are a much better way to allow certain things for a domani or url. There you have a simple input and a button do add something.

The old and simple white list is actually just legacy code and at some point in the future I will get rid of it.

**Comment by Machou** [comment]
Sorry, but when I click on it, I end up with a list of options like this: https://i.imgur.com/1II3lGV.jpg

**Comment by kkapsner** [comment]
This is the wrong icon. You have to click the one in the address bar:
![image](https://user-images.githubusercontent.com/1105157/59145953-3752bd80-89eb-11e9-97ee-d2b641f5a099.png)

It only appears if CB did something on the page.

**Comment by Machou** [comment]
I can see the icon but it's still grayed out, and I can't move it from the "page action bar"

**Comment by kkapsner** [comment]
Did you disable the notifications? It should automatically appear in the address bar when CB does something and you do not have to move it there.

**Comment by Machou** [comment]
no, my notification is enabled

**Comment by kkapsner** [comment]
OK. Good that it works now.

**Comment by Synetech** [comment]
> 
> 
> This is the wrong icon. You have to click the one in the address bar:
> ![image](https://user-images.githubusercontent.com/1105157/59145953-3752bd80-89eb-11e9-97ee-d2b641f5a099.png)
> 
> It only appears if CB did something on the page.

- It doesn't show those buttons unless you hover the mouse over the URL, which people might not do and thus not see it.
- It asks for a regex for the URL, which most people won't understand
- It wraps the URL in **$…^** so for example, **^example.com$** won't whitelist it for **^example.com/foobar$**.
- When it asks which APIs to whitelist, it seems to do the opposite (eg if you select only canvas, it selects everything _except_ canvas)

**Comment by kkapsner** [comment]
I think I commented on all points [here](https://github.com/kkapsner/CanvasBlocker/issues/501#issuecomment-709991698).
