### ISSUE TITLE
Firefox Nightlies settings dark mode

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#341]
I've discovered a big CSS problem in my add-on and checked some other add-ons, to see you are also affected.

In Firefox 68 (Nightly), the system' dark mode is governed by `prefers-color-scheme` is also applied to `about:addons`.

That includes add-on options page (presumably only if they use `browserStyle`?).

This is how your add-on looks like then:
![image](https://user-images.githubusercontent.com/11966684/56851516-6a942e00-6910-11e9-9a10-848d403222e3.png)

### See https://github.com/rugk/offline-qr-code/issues/190 for details.

I am still figuring out when that may come to stable or what it is about that feature… AFAIK it's not yet included in the beta/stable channel.

----

This could be related to https://github.com/kkapsner/CanvasBlocker/issues/181. (commented there for details)

**Comment by rugk** [comment]
BTW, asked some questions about that change: https://discourse.mozilla.org/t/firefox-68-added-dark-version-to-about-addons-breaking-many-add-ons/38716

**Comment by kkapsner** [comment]
Setting "browser_style" to false does not change anything. So I will have to provide a complete theme myself.

**Comment by rugk** [comment]
Yeah, but **remember** it's still Nightly! Nobody knows when/how it will ship and stuff can still be changed then. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1544212

**Comment by kkapsner** [comment]
I know. But if I offer a theme option I can also apply it on the options page.

**Comment by rugk** [comment]
Possibly, but remember `prefers-color-scheme` will later control Firefox Nightly's behaviour and thus always follow the system' design. (https://developer.mozilla.org/docs/Web/CSS/@media/prefers-color-scheme) You can obviously do the same (in FF >=67=).

**Comment by kkapsner** [comment]
Interesting. I could change the "default" theme to match what comes with this scheme. So you could force any theme you like but in the default it uses the system design.

**Comment by kkapsner** [comment]
Please check out the latest alpha: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-Alpha2

Especially the theme "automatic" and "dark".

**Comment by kkapsner** [comment]
I was not happy with all the layout. Please check https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-Alpha3

**Comment by rugk** [comment]
I trust you there. :smile:

**Comment by kkapsner** [comment]
OK - then I will close this issue as it looks fine on my machine.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC1

**Comment by kkapsner** [comment]
Release 0.5.9 is published.
