### ISSUE TITLE
Firefox 66.0.3 Canvas Blocker "could not be verified for use in Firefox and has been disabled."

### ISSUE THREAD

**Issue by JustFloyd** [kkapsner/CanvasBlocker#343]
## Description
Firefox 66.0.3 has blocked all of my addons saying they could not be verified even though they are available from firefox

## Expected Behavior
Addons Disabled

## Current Behavior
Not Functioning/diabled by Mozilla
## Steps to Reproduce (for bugs)
Opened firefox and a pop up told me they were disabled

## Your Environment

* CanvasBlocker Version used:
* Firefox version 32 bit:
* Win 10 Desktop
* Canvas Blocker, Ublock Origin, Facebook Purity

## Your Settings
Can't Access

**Comment by Daisenki** [comment]
It seems to be a on going issue from uBlock Origin https://github.com/uBlockOrigin/uBlock-issues/issues/558

**Comment by hugoncosta** [comment]
A ton of add-ons have been broken, mine have all literally died. Thanks Mozilla.

**Comment by hugoncosta** [comment]
https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/14

They've released a hotfix and it should be applied in the next couple of hours. Issue can be closed.

**Comment by kkapsner** [comment]
Thanks for letting me know (Mozilla did not...).

I will close this as it's a (hopefully) temporary Firefox bug.
