### ISSUE TITLE
0.5.9 Alpha3 corrupted xpi?

### ISSUE THREAD

**Issue by Daisenki** [kkapsner/CanvasBlocker#344]
Can't install 0.5.9 Alpha3, Firefox 66.0.3 (64-bit) report back:
"The add-on downloaded from this site could not be installed because it appears to be corrupt."

I also download the xpi, but a file installation didn't work too: 
"This add-on could not be installed because it appears to be corrupt."

Edit: Maybe that's the problem here: https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

The stabil version on https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/ has the same problem, I get the same error message

**Comment by kkapsner** [comment]
I managed to install it yesterday:
![grafik](https://user-images.githubusercontent.com/1105157/57178603-5ea9ee00-6e73-11e9-96ca-9871cc9e22e3.png)

But now I get the same error.

**Comment by Daisenki** [comment]
Yeah, it's also affected from the current issue https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 without a new certificate at Firefox there is no way to install it right now. Seems we need to wait.

**Comment by kkapsner** [comment]
Yes - seems so. But it seems as they are working on it:
![grafik](https://user-images.githubusercontent.com/1105157/57178715-05db5500-6e75-11e9-8e97-991212a4f493.png)

**Comment by kkapsner** [comment]
A notification to the authors of the affected extension would have been good...

**Comment by Daisenki** [comment]
Mozilla pushed out a fix with the studies feature, I enable it and got a new certificate. The installation of 0.5.9 Alpha3 was no problem now.

https://bugzilla.mozilla.org/show_bug.cgi?id=1548973#c60
"For everyone's info: we don't need to so anything if ""studies" is enabled (Firefox Preferences -> Privacy & Security -> Allow Firefox to install and run studies)."

**Comment by Daisenki** [comment]
![12345](https://user-images.githubusercontent.com/22057956/57179518-35d32a00-6e6e-11e9-9b12-8e7994b23a48.JPG)

**Comment by spodermenpls** [comment]
A restart of Firefox might speed up the process, after you enabled "allow to install studies". I've got my new certificate here too, now.

**Comment by kkapsner** [comment]
I had studies enable (do not know why... and did not remember to activate it) that why I did not notice the problem.

But with this hotfix we can close this issue.

**Comment by kkapsner** [comment]
Well... I have enabled studies but my Firefox decided not to download the studies and now *all* my addons are gone.

Mozilla fucked this up royally. Especially after they were criticised so much for introducing the signing system.

**Comment by kkapsner** [comment]
Even the language pack is disabled.

**Comment by spodermenpls** [comment]
@kkapsner Did you try a restart to trigger the study download?

**Comment by kkapsner** [comment]
I did restart several time. Even switched to beta and nightly. This then resulted in all extension being deleted... great!

Fortunately I had a backup and now it installed the XPI which solves the issue and everything is OK again.

(The study page did not show anything for me - not even some sort of header)

**Comment by spodermenpls** [comment]
@kkapsner Do you want to release another Alpha (with the improved DOMRect faking, which I would like to test), or is the official 0.5.9 next (the 1.0 is still a thing, I hope? 😅)?

**Comment by kkapsner** [comment]
Yes I want to release another Alpha. Yesterday also the creation of new version did not work. I will check later again.

PS: Yes, 1.0 is still a thing.

**Comment by kkapsner** [comment]
Nope... cannot create a new version: 
![grafik](https://user-images.githubusercontent.com/1105157/57198861-3b1c9b80-6f78-11e9-8183-eb0b6a9219eb.png)

**Comment by spodermenpls** [comment]
At least 66.0.4 for Desktops and Android has been released now.. hopefully updates on AMO etc will be opened soon again too.

**Comment by Daisenki** [comment]
Firefox really fucked up with all that add-on problem right now and only because a expired certificate.

**Comment by spodermenpls** [comment]
@kkapsner How far away is Alpha4 from being published?

**Comment by kkapsner** [comment]
I think the next will be RC1 - I feel confident about it. (There will be even further performance improvements). I hope do publish it this evening

**Comment by kkapsner** [comment]
OK - I just went for it: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC1

**Comment by spodermenpls** [comment]
Very good, testing it right now. Would it be possible to separate "test fingerprinting" and "test big random image" from one another on your perfomance test page? The second test slows down the first considerably, and thus distorts the results..

**Comment by kkapsner** [comment]
Sure I can separate them.
