### ISSUE TITLE
CanvasBlocker disabled in Firefox 66

### ISSUE THREAD

**Issue by RaySolomon** [kkapsner/CanvasBlocker#345]
Today mozilla firefox for android 8 mobile disabled this addon and provided this url as to why. I think only the addon author/publisher can fix this because it needs to be a signed addon.

https://support.mozilla.org/en-US/kb/add-signing-firefox-android?redirectlocale=en-US&as=u&redirectslug=unsigned-addons&utm_source=inproduct

* CanvasBlocker Version used: 0.5.8
* Firefox version incl. 32- or 64-bit: 64
* Operating System and version (desktop or mobile): mobile

Mozilla/5.0 (Android 8.0.0; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0

**Comment by kkapsner** [comment]
CB is signed. There is a massive problem at Mozilla with their verification system: https://bugzilla.mozilla.org/show_bug.cgi?id=1548973
