### ISSUE TITLE
Message System on Ebay not editable with enabled Canvas Blocker

### ISSUE THREAD

**Issue by manyplay** [kkapsner/CanvasBlocker#346]
If you try to answer a message on ebay the text field is not reachable using Firefox latest Build.
Only with disabled addon you can write into the textfield.

**Comment by spodermenpls** [comment]
Did you try the latest Alpha version? I can't confirm that issue, as far as I can see..

**Comment by kkapsner** [comment]
Please tell me your settings and if the issue is reproducible with https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC1 (you should export the settings from your normal CB, deactivate it, install the Beta and import the settings).

**Comment by kkapsner** [comment]
No response for two weeks: I will close this. If you provide the information and the problem still persists I can reopen it.
