### ISSUE TITLE
Could not register on freshprep.ca without disabling canvasblocker

### ISSUE THREAD

**Issue by wilbowma** [kkapsner/CanvasBlocker#348]
## Description

I tried registering on freshprep.ca several times. Registration failed until I disabled CanvasBlocker, after which it succeeded.

## Expected Behavior

I should be able to complete the registration process on freshprep.ca

## Current Behavior

I could not complete the registration process on freshprep.ca

## Possible Solution

My guess would be the payment processor is using fingerprinting for security purposes?

## Steps to Reproduce (for bugs)

1. Try to register on freshprep.ca
2. It does not work.
3. Disable CanvasBlocker
4. It works

## Your Environment

* CanvasBlocker Version used: 0.5.8
* Firefox version incl. 32- or 64-bit: 64 bit 66.0.5
* Operating System and version (desktop or mobile): macOS 10.14.2
* Installed addons:

## Your Settings

{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$",
			"protectWindow": false
		}
	],
	"hiddenSettings": {
		"displayDescriptions": true
	},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1558139347464,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": false,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "textnow.com",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "16",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}

**Comment by kkapsner** [comment]
On which stage of the registration did it fail?
Did you check with the different APIs unprotected? (If I would guess I would say the window API...)

**Comment by wilbowma** [comment]
Registration failed at the final step after entering payment information (which I wager will make reproducing this annoying). 

The page simply hung after pressing the final submit button.

I did not check disabling different APIs.

**Comment by kkapsner** [comment]
That's true. I contacted the people there - they should be able to tell me what's the problem there.

**Comment by kkapsner** [comment]
No answer yet - I sent another mail.

**Comment by kkapsner** [comment]
Still silence... so no way for the to investigate. The latest alpha may solve the problem (or not - I have no idea...) but as I cannot test...

@wilbowma can you as a paying customer contact them regarding this issue?

**Comment by wilbowma** [comment]
I'll give it a shot.

--

**Comment by wilbowma** [comment]
Support tells me "We have passed this over to our IT team and developers. They are currently working on this and seeing what they can do for you."

**Comment by kkapsner** [comment]
I got an answer from a dev: 

> I tried to reproduce the issue with our staging environment, and was not able to reproduce using this issue.

So either they changed something at their side or the newer versions of CB solved the problem. But either way the problem seems solved. Are you fine with closing it?

**Comment by wilbowma** [comment]
Well I suppose there's nothing to be done, so sure.

--

**Comment by kkapsner** [comment]
Thanks
