### ISSUE TITLE
Is CanvasBlocker still useful with Firefox 67 (with its new fingerprint proctection) ?

### ISSUE THREAD

**Issue by usercase** [kkapsner/CanvasBlocker#349]
Hi,

First, thank you for your great work ! I have a simple question : 

Is CanvasBlocker still useful with Firefox 67 (with its new fingerprint proctection feature) ?

### FYI
When i go [here](https://browserleaks.com/canvas) with my shiny new install of Firefox 67 and after multiple refresh my signature doesn't change. And my uniqueness is 100%.

**Comment by kkapsner** [comment]
It still has it's purpose.
The new FF feature is great but as far as I understand it, it works with a blocking list. So it will not protect against fresh fingerprinting scripts which CB does.

PS: I get different signatures on my FF 68 Beta... what are your settings?

**Comment by usercase** [comment]
Sorry do you mean my settings on FF 67 ? 

I also have an install of FF dev edition 68.0b3, and on browserleaks, i also get the same signature while my unqueness is 99,999%

Where did you get the documentation of FF 67 FP protection ? Because from what I understand they implemented the TOR anti-FP feature, and I can't imagine that TOR is limited by a simple blocking list. What do you think ?

**Comment by kkapsner** [comment]
No - I mean the CB settings.

If you mean privacy.resistFingerprinting which is already some time time in FF the approach is completely different. They just report a complete white canvas which creates the same fingerprint for all users. With this enabled CB still has a place to be helpful: sometimes you have to allow the site to read the canvas to work. In that case CB can still protect.

**Comment by usercase** [comment]
**My CB settings / FF 67.0**
```
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"protectWindow": true,
		"protectAudio": true,
		"protectedCanvasPart": true
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1558617477163,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": false,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "12",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}
```

**> If you mean privacy.resistFingerprinting**
I was talking about the new anti-FP feature that came with FF 67.

**FF 67 Anti-FP**
I looked around to gather some informations, it could be useful for anyone : 

Seems @kkapsner you re right, the blocking list is delivered by Disconnect : 
https://blog.mozilla.org/futurereleases/2019/04/09/protections-against-fingerprinting-and-cryptocurrency-mining-available-in-firefox-nightly-and-beta/

Those are probably the blocking list of Disconnect : 
- https://github.com/disconnectme/disconnect-tracking-protection/blob/master/entities.json
- https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json

So I would say FF has a limited approach when CB works on any website.

**Comment by kkapsner** [comment]
Yes - I was talking about that in the first place.

Regarding your non changing signature: please try with https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC3 (export your settings, disable normal CB, install the Beta, import your settings)

**Comment by Thorin-Oakenpants** [comment]
> Where did you get the documentation of FF 67 FP protection ? Because from what I understand they implemented the TOR anti-FP feature, and I can't imagine that TOR is limited by a simple blocking list.

Firefox's **`Content Blocking`** has lots of flavours. Trackers, Cryptominers, etc, including one called Fingerprinting. These have NOTHING to do with the Tor Uplift. These are lists/rules to block **CONTENT**

Do not confuse it with **RFP** (privacy.resistFingerprinting) from the Tor Uplift. This is about spoofing, blocking, randomizing **actual** fingerprint metrics

**Comment by usercase** [comment]
@Thorin-Oakenpants I start to see more clearly, thanks

@kkapsner My signature is non changing on a **shniny new install of FF 67 (=no addon)**.
It's why I was surprised and came here for answsers : to know why the anti-FP feature "wasn't working" :thinking:. With FF 67, I was expecting to see a changing signtaure and maybe stop to use CB. Now I understand that this new feature doesn't have the CB behaviour.

**Comment by kkapsner** [comment]
OK - good we clarified that.
