### ISSUE TITLE
Failure at http://games.washingtonpost.com/games/daily-crossword/

### ISSUE THREAD

**Issue by Al-Majhoul** [kkapsner/CanvasBlocker#35]
Further to discussions at addons.mozilla.org:

I run Firefox 38.2.1ESR under Win7x64.  I installed a separate portable version of this with no other addons and all default settings. CB 0.1.6 worked without whitelisting site. Page failed to load completely under CB 0.1.8, with or without whitelisting.  I then installed a portable version of FF 40.0.3, installed most of the addons I normally use and tried again: CB 0.1.8 worked OK.
This suggests either an incompatibility with the ESR version I use, or a CB dependence on some specific feature in FF versions >38.

**Comment by kkapsner** [comment]
Hi,

thank you for filing the issue.

I can reproduce the problem with FF 38.2.1ESR and found the problematic part. Can you please check out the XPI-file in the withoutPageMod branch (https://github.com/kkapsner/CanvasBlocker/blob/withoutPageMod/canvasblocker.xpi - there are also some major code changes that should make the addon more reliable and save).

**Comment by Al-Majhoul** [comment]
This version work even without whitelisting.  Many thanks for the fix.

**Comment by kkapsner** [comment]
You're welcome.
