### ISSUE TITLE
[Feature request] Support for unique RNG between containers and domains

### ISSUE THREAD

**Issue by Felicity-Samwell** [kkapsner/CanvasBlocker#350]
Firstly thanks for the great addon.
I love the persistent RNG feature for each domain.  But if I want to run two separate google accounts using the firefox containers, even with a VPN I will still be given away by the RNG being the same for both containers as it is the same domain.  Is there anyway around this and if not would you consider adding support to log different persistent RNG for each domain inside each container?  

In the mean time "constant" RNG is fine although I do wonder if changing RNG every webpage would make it obvious that you are using spoofing software.

**Comment by kkapsner** [comment]
With containers you mean this: https://blog.mozilla.org/firefox/introducing-firefox-multi-account-containers/ ?

I'm not sure if I can detect which container the tab is in. But I can look into it when I have time.

**Comment by Felicity-Samwell** [comment]
Thanks for reply. 

Yes they are also known as contextual identities in the javascript API.  Each tab object from the JS API also has a cookieStoreId value already which is unique to the container.  
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab

Not sure if this is helpful but it's what I've been using.  Thanks again

**Comment by kkapsner** [comment]
Looks doable.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.10-RC1

**Comment by kkapsner** [comment]
Version 0.5.10 is published and available on AMO

**Comment by openffchrome** [comment]
thanks alot awesome

**Comment by openffchrome** [comment]
it would be nice to have a "Store persistent data" setting per container.
i mean i would like for example to always have the same RNG for X container but only for this one.

**Comment by kkapsner** [comment]
Actually I already thought about something like container specific settings (similar to the url specific settings). This could be one candidate. Please open a new issue with this feature request.

And you are right: the "store persistent data" is storing everything.
