### ISSUE TITLE
Breaks startpage proxy since  FF 67

### ISSUE THREAD

**Issue by xalloc** [kkapsner/CanvasBlocker#351]
I'm on Firefox 67, since this release CB breaks startpage.com "Anonymous View" feature. The page loads indefinitely and In FF console I see many errors.
Whitelisting the whole startpage.com domain doesn't fix, I need to disable CB addon entirely to make it work again.

**Comment by kkapsner** [comment]
It even breaks harder with the RC2 of 0.5.9. But I know how to address this.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.9-RC3
(first export you CB settings, disable normal CB, install the Beta version and import your settings)

**Comment by kkapsner** [comment]
Release 0.5.9 is published.

**Comment by xalloc** [comment]
Sorry I had no time to test unitil now... version 0.5.9 fixes it, thank you!
