### ISSUE TITLE
Add time to backup file name

### ISSUE THREAD

**Issue by grenzor** [kkapsner/CanvasBlocker#352]
Can the time/date to the filename? It can also useful for sorting and identifying specific backups.
Example: CanvasBlocker_2019-05-30_12.00.00.json

**Comment by kkapsner** [comment]
Good idea.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.10-RC1

**Comment by kkapsner** [comment]
Version 0.5.10 is published and available on AMO
