### ISSUE TITLE
Prestashop 1.6 backend don't work with version 0.5.9

### ISSUE THREAD

**Issue by juanjointera5** [kkapsner/CanvasBlocker#354]
When I enter my Prestashop's backend, the page is unusable. Yesterday was working.

## Description
The spinning animation in the upper left corner never end and a lot of content is not loaded. The backend is unusable. Reloading the page a lot times, makes the spinning animation finally disappears and the page works. Disabling the CanvasBlocker makes the page works again. Adding the domain to whitelist don't work.

I don't know if this is only with MY backend, or maybe fails to other installations.

Reverting to 0.5.7 version makes the backend works again.

## Expected Behavior
The backend should work as yesterday.

## Current Behavior
The backend seems to use the canvas API for some operations. The 0.5.9 version is making the backend to don't work. CUrrently with version 0.5.7 and works.

## Possible Solution
I don't know. Reverting to 0.5.7 version or disabling the extension (not desirable) makes the backend works again.

## Steps to Reproduce (for bugs)
Just use the backend.

## Context
Use the backend of my shop.

## Your Environment
* CanvasBlocker Version used: 0.5.9
* Firefox version incl. 32- or 64-bit: 67.0 (64-bit)
* Operating System and version (desktop or mobile): Windows 10
* Installed addons: Not relevant, already tried to disable all extensions except CanvasBlocker and still fail

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"protectWindow": false,
		"blockMode": true
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1558978895235,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "17",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}

**Comment by kkapsner** [comment]
Please try version 0.5.9.1

**Comment by juanjointera5** [comment]
Yes! It's now working!

Thanks.

**Comment by juanjointera5** [comment]
Yes! It's now working!

Thanks.

**Comment by juanjointera5** [comment]
Sorry, false alarm. It seems that the new version solve the problem in some parts, but it's still broke.

Reverting back to 0.5.7 again. (Can't find xpi for 0.5.8).

**Comment by kkapsner** [comment]
I fixed https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.8 (the file was corrupt in some way...)

Are there error messages in the console (Shift+Ctrl+K)? What is the reproduction scenario on http://demo.prestashop.com ?

I need a way to narrow it down.

**Comment by kkapsner** [comment]
Please report back soon or it will not be fixed in 0.9.10 (I want to release it within the next days).

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.10-RC1

**Comment by juanjointera5** [comment]
Ok, just upgraded to 0.5.9.1 to do the tests.

First, checked again with my Prestashop installation and is broken. Then, tested on Prestashop demo site, and works correctly. But, note that the demo shop is using version 1.7. My Prestashop version is 1.6.

This is on the console while using my installation:
`TypeError: Argument 1 of MutationObserver.observe is not an object.` File: iframeProtection.js:127:15.

Hope this is usefull for you.

Thanks for your work.

**Comment by juanjointera5** [comment]
Tried 0.5.10-RC1 and don't work, sorry. Same error on console:

TypeError: Argument 1 of MutationObserver.observe is not an object. File: iframeProtection.js:127:15.

**Comment by kkapsner** [comment]
Thanks for testing.

This error message helps to find the problem. Not quite sure what causes it, but I think I can work with that.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.10-RC2

**Comment by juanjointera5** [comment]
Great! Now it's working all sections on backend!

Thanks!

**Comment by kkapsner** [comment]
Good - the final 0.5.10 will be released within the next days.

**Comment by kkapsner** [comment]
Version 0.5.10 is published and available on AMO
