### ISSUE TITLE
Catalogs hosted by https://view.publitas.com won't load in 0.5.9

### ISSUE THREAD

**Issue by Pilford** [kkapsner/CanvasBlocker#355]
After I updated CanvasBlocker to 0.5.9 all online catalogs hosted by https://view.publitas.com won't load anymore. When I disable CanvasBlocker it works again.

**Comment by kkapsner** [comment]
This is bad...
I found the place that causes the problem but I do not understand it. But I think I can fix it.

**Comment by kkapsner** [comment]
Please try version 0.5.9.1

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.10-RC1

**Comment by kkapsner** [comment]
Version 0.5.10 is published and available on AMO
