### ISSUE TITLE
Version 0.5.9 broke google.docs on latest waterfox (56.2.10)

### ISSUE THREAD

**Issue by rlesch** [kkapsner/CanvasBlocker#356]
![image](https://user-images.githubusercontent.com/45274733/58494972-8d676b80-8176-11e9-9774-dcd85048bbc4.png)

Obviously deleting cache & reloading doesnt solve it.
Neither Custom settings nor default settings work. 

only solution so far: 

a) disabling canvas blocker 
or
b) setting chrome as useragent (in an useragent tool, not in the canvas blocker navigator options)*

Any changes under options -> navigator settings, even resetting them and diasabling the navigator 
protection,  breaks the site again, despite the changed useragent. 
Only total reset of Canvas Blocker options, browser reload and reset to e.g
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3350.0 Iron Safari/537.36"
works.

**Comment by rlesch** [comment]
youtobe broke too. So i guess more or less any google related service. went back to 0.5.8.

**Comment by spodermenpls** [comment]
Youtube doesn't break on Firefox 67 though, so this might be some Waterfox specific issue.

**Comment by kkapsner** [comment]
Please try version 0.5.9.1

**Comment by kkapsner** [comment]
Youtube is working with my Waterfox.56.2.10

... and I just realized that you cannot install 0.5.9.1 - you will be able to install 0.5.10

**Comment by kkapsner** [comment]
Now you should be able to install 0.5.9.1 - please check

**Comment by kkapsner** [comment]
Well... my quick test with a sheet failed. I did not get your error but a different one.

**Comment by rlesch** [comment]
Tried 0.5.9.1, - Got same error on google.docs. 
But at least Youtube works again, seems its getting in the right direction .

p.s thx for the fast reply!

**Comment by kkapsner** [comment]
Waterfox behaves very strange there. But I can implement a fix specific for the google docs problem.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.10-RC2

**Comment by kkapsner** [comment]
Version 0.5.10 is published and available on AMO
