### ISSUE TITLE
Version 0.5.9.1 breaks multiple sites in Firefox Nightly 69.0a1 (2019-05-28) (64-bit)

### ISSUE THREAD

**Issue by Caspy7** [kkapsner/CanvasBlocker#358]
Running Firefox Nightly 69.0a1 (2019-05-28) (64-bit) (Windows 10) and CanvasBlocker 0.5.9.1

Started up browser and found that multiple sites weren't working right. On Twitter, tweets weren't live loading (when you scroll to the bottom), retweeting/liking broken and more. On Wire many entries weren't displaying and were giving errors.
There may have been other sites, but those were some of my go-tos.
Determined CanvasBlocker was the cause, reproduced in a fresh profile with only CanvasBlocker enabled.
Tested on Firefox Beta 68.0b5 (fresh profile + CanvasBlocker) and the issues were not present.

Certainly can't tell who's technically at fault, but thought it should be on the radar.

**Comment by kkapsner** [comment]
I think it's same issue as #357. So it should be fixed with 0.5.10

... and I don't care who's fault it is. (Background: within the last few days Mozilla changed some class inheritances CB relies on.)

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.10-RC1

**Comment by kkapsner** [comment]
Version 0.5.10 is published and available on AMO
