### ISSUE TITLE
Canvas Blocker 0.1.7 & 0.1.8: Break sites & Firefox's PDF viewer

### ISSUE THREAD

**Issue by hairycactus** [kkapsner/CanvasBlocker#36]
I found that Canvas Blocker 0.1.7 & 0.1.8 (updated from v 0.1.6 via AMO) break:
* **Mapping sites**
— maps (or even complete webpages on mapping sites) do not render, despite domain white-listing; below are 2 non-exhaustive examples (note: I haven't tested most mapping sites, before downgrading to v 0.1.6)
  * Sample 1: <a href="https://worldview.earthdata.nasa.gov/?p=geographic&l=MODIS_Aqua_CorrectedReflectance_TrueColor%28hidden%29,MODIS_Terra_CorrectedReflectance_TrueColor,Reference_Labels%28hidden%29,Reference_Features%28hidden%29,Coastlines&t=2015-09-05&v=79.43044598687308,-46.53227532085682,175.47732098687308,-0.7588378208568187">NASA Worldview</a>
  * Sample 2: <a href="http://www.arcgis.com/home/webmap/viewer.html">ArcGIS WebMap</a>

* **Firefox's inbuilt PDF viewer**
— PDF file from *any* website will not load (only shows blank page with spinning icon), despite ticking Canvas Blocker's <code>Allow canvas in PDFs</code> (default in 0.1.7 & 0.1.8: unticked)
  * Sample: <a href="http://www.nas.gov.sg/archivesonline/data/pdfdoc/20150428003/gis_media_release_on_psoriasis_%2820150423%29_embargoed_final.pdf">PDF page</a>

The only way to avoid the above breakages is to disable Canvas Blocker, or uninstall it. Disabling all other add-ons (except Canvas Blocker) does not solve the breakages.

Last working version is **v 0.1.6** (reinstalled from AMO), for which the aforementioned sites work perfectly, without any need for white-listing. Firefox's PDF viewer also works fine (note: v 0.1.6's <code>Allow canvas in PDFs</code> is ticked by default).

I'd tested **v 0.2.0 devt** (06 Sep 2015) referenced at <a title="Failure at http://games.washingtonpost.com/games/daily-crossword" class="issue-link" href="https://github.com/kkapsner/CanvasBlocker/issues/35#issuecomment-138086568">Issue #35</a>, but all of the above problems persist. I note that 0.2.0 devt does not have any PDF-related preference for user to tick or untick. Meanwhile, Firefox's PDF viewer remains broken.

Specs: Firefox 33.1.1, Win 7 SP1 (x64)

**Comment by kkapsner** [comment]
Why are you using an outdated Firefox? Everything works find in FF 40.

PS: the PDF-related preference was removed because it opened a potential bypass.
