### ISSUE TITLE
[Latest Firefox Nightly update] CanvasBlocker 0.5.9.1 breaks Youtube and Reddit commenting

### ISSUE THREAD

**Issue by Valmar33** [kkapsner/CanvasBlocker#360]
With the latest Firefox Nightly update, CanvasBlocker breaks Youtube video controls, Reddit videos and commenting. These are what I've noticed prominently.

Expected behaviour should be that it blocks canvas-fingerprinting without breaking Youtube or Reddit in various ways.

To reproduce, create a new Firefox Nightly profile, install CanvasBlocker, and play around with Youtube video controls, Reddit videos, or trying to reply to comments on a post. Basically, anything related to canvases.

Default settings are enough to break stuff.

**Comment by kkapsner** [comment]
This is a duplicate to #357 and #358 - will be fixed in 0.5.10

**Comment by Valmar33** [comment]
Ah, sorry. Should have checked closed issues, but that probably wasn't the obvious option. :P

**Comment by kkapsner** [comment]
No problem.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.10-RC1

**Comment by kkapsner** [comment]
Version 0.5.10 is published and available on AMO
