### ISSUE TITLE
Navigator API protection issue with netflix.com

### ISSUE THREAD

**Issue by 10bass** [kkapsner/CanvasBlocker#362]
Attempting to stream video on Netflix while using Navigator API protection results in a Streaming Error and video cannot be played.

## Description
Browsing with Firefox 67.0 on MacOS 10.14, with Navigator API set to the "Windows" and "Firefox" presets. Trying to play video with Netflix results in a "Streaming Error" message, and "Error Code: F7121-1331". Disabling "Protect Navigator API" resolves the issue, as does leaving protection enabled but changing the operating system to "Mac OS X". I have tried whitelisting the base domains that Netflix loads content from (netflix.com, nflxso.net, nflxvideo.net, nflxext.com) both within the "Lists" section and in the Navigator-specific section, being sure to uncheck the box. I have tried adding various subdomains as well (assets.nflxext.com, codex.nflxext.com, www.netflix.com, etc...) but have not seen any change.

If I keep the OS preset at "Mac OS X", Netflix will play if I change the browser preset to Chrome or Opera. Selecting "Safari" results in Netflix automatically redirecting me to a system requirements page (https://help.netflix.com/en/node/23742). Selecting "Edge" results in an endless loading animation. The "Safari" and "Edge" presents give the same result regardless of the OS preset, for whatever that's worth.

Perhaps I am using the whitelist incorrectly, but if so, I do not see how.

## Expected Behavior
Netflix should play videos when the domains it loads resources from are whitelisted.

## Current Behavior
A streaming error is encountered unless the OS matches or protection is disabled completely.

## Possible Solution
Unknown, aside from giving up on using a non-native OS preset. Unfortunately I do not currently have access to a Windows or Linux instance to test their behavior.

## Steps to Reproduce (for bugs)
1. Login into Netflix with Navigator API protection enabled and the OS set to a different OS than the native OS.
2. Attempt to stream a video.
3. Disable Navigator API protection, or select the same OS prefix as your actual OS
4. Stream a video.

## Context
Inability to watch video while Navigator API protection is enabled and a cross-OS preset is selected.

## Your Environment
* CanvasBlocker Version used: 0.5.9.1 (latest available from addons.mozilla.org)
* Firefox version incl. 32- or 64-bit: 67.0, 64-bit
* Operating System and version (desktop or mobile): MacOS 10.14.5
* Installed addons: Multiple, but no others that affect the useragent or fingerprinting. Edit: disabling other addons did not affect behavior, issue can be reliably replicated by enabling CanvasBlocker.

## Your Settings
{
	"logLevel": 0,
	"urlSettings": [
		{
			"url": "netflix.com",
			"protectNavigator": false
		},
		{
			"url": "nflxso.net",
			"protectNavigator": false
		},
		{
			"url": "nflxvideo.net",
			"protectNavigator": false
		},
		{
			"url": "nflxext.com",
			"protectNavigator": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {
		"protectNavigator": true
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "about:blank",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": true,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": ,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": false,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": true,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "16",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": true,
	"navigatorDetails": {
		"windowManager": "Windows",
		"platform": "Win32",
		"platformDetails": "Windows NT 10.0; Win64; x64",
		"oscpu": "{platformDetails}",
		"appVersion": "5.0 ({windowManager})",
		"buildID": "20181001000000",
		"productSub": "20100101",
		"userAgent": "Mozilla/5.0 ({platformDetails}; rv:{firefoxVersion}) Gecko/20100101 Firefox/{firefoxVersion}",
		"firefoxVersion": "{real Firefox version}"
	},
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}

**Comment by kkapsner** [comment]
Unfortunately I neither have a Mac nor a Netflix account... but looking in the details I see that serversite navigator protection does not respect any whitelisting. I have to change that.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.10-RC3

**Comment by 10bass** [comment]
That resolves the problem, thank you (if anyone reading this later runs into the same error, the only required setting is Navigator whitelist of netflix.com, the other domains from my config aren't needed).

**Comment by kkapsner** [comment]
Version 0.5.10 is published and available on AMO
