### ISSUE TITLE
canvasblocker breaks some sites that previously worked 

### ISSUE THREAD

**Issue by jahnson** [kkapsner/CanvasBlocker#364]
I noticed others reporting some sites that were broken by canvasblocker so I held off to see if the repairs would fix this too -- but alas thus far not.  

## Description
eg. tennis24.com 

## Expected Behavior
tennis scores should display 

## Current Behavior
tennis scores do not display 

## Possible Solution
disable canvasblocker, tennis scores display again 

## Steps to Reproduce (for bugs)
1. enable canvasblocker, scores do not display on tennis24.com 
2. disable canvasblocker, scores do display on tennis24.com 
3. enjoy life 
4. better to go out and play some tennis yourself though 

## Context
canvasblocker with tennis24.com worked together harmoniously until 1-2 weeks ago 

## Your Environment
* CanvasBlocker Version used: 0.5.10 
* Firefox version incl. 32- or 64-bit: 32b, 66.0.4 
* Operating System and version (desktop or mobile): W7-64
* Installed addons: ublock origin, decentraleyes, chameleon (you need to decorate firefox like a Christmas tree full of addons to get even a little bit of privacy these days)

**Comment by kkapsner** [comment]
This is weird. I only could reproduce the problem once. Now it works completely fine.

So some question to you to sort this problem out:
Can you update you Firefox to the latest version?
Does the problem also appear if you use a new profile with only CB added to it?
Do you see any error messages in the console (Ctrl + Shift + K) that are not present when CB is disabled?
What are the other pages that do not work?

**Comment by kkapsner** [comment]
OK - it's the Firefox version. I'm able to reproduce the problem in Firefox ESR (60.7).

**Comment by bug** [comment]
Same problem here with our organisation webmail platform (Zimbra), which does no longer load when CB is loaded in Firefox 67.0.

**Comment by kkapsner** [comment]
@bug: since you face the problem in FF 67 it's most likely something different. But you may check the next alpha version.

**Comment by jahnson** [comment]
The close of this issue was a bit rushed but now I have been able to update FF and the tennis scores are appearing again.  It's raining in Paris.

**Comment by kkapsner** [comment]
The issue was automatically close by the fix. So With the next version it should also work with older versions.
