### ISSUE TITLE
Ajax webmail (Zimbra) broken since 0.5.9

### ISSUE THREAD

**Issue by LogicaBorealis** [kkapsner/CanvasBlocker#365]
Hi!

First of all, thanks a lot for this nice add-on I'm using for a few years now! Here is the description of the problem I encounter.

## Description
I cannot use the following webmail platform since 0.5.9: [webmail.ntymail.com](https://webmail.ntymail.com) 
After logging in, you get indefinitely stuck at the "Loading..." page (splash screen).
Whitelisting the domain doesn’t help and the fingerprint icon does not appear, as if CanvasBlocker wasn't doing anything.
Given the problem occurs with CanvasBlocker alone, other addons I use that may interact with it (uMatrix/uBlockO, NoScript...) shouldn’t be involved.
FYI, the webmail platform is an Ajax version of Zimbra.

## Expected Behavior
The splash screen should disappear after a few seconds to show the webmail interface.

## Current Behavior
See "Description" section.

## Possible Solution
No solution to propose (it anyway goes beyond my technical abilities).
A temporary workaround I found is to disable CanvasBlocker in private windows and use this webmail in a private window.

## Steps to Reproduce (for bugs)
Unfortunately you won't be able to reproduce the bug without an account and it seems you currently cannot create a new one.

## Your Environment
* CanvasBlocker Version used: 0.5.10
* Firefox version incl. 32- or 64-bit: 64-bit 67.0
* Operating System and version (desktop or mobile): Mac OS X 10.11.6
* Installed addons: the problem occurs with other addons deactivated.

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "ntymail.com",
			"protectedCanvasPart": "nothing",
			"protectDOMRect": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {
		"protectedCanvasPart": true,
		"protectDOMRect": true
	},
	"displayHiddenSettings": false,
	"whiteList": "<other domains…>,ntymail.com",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 4,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1559491960000,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "12",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": false,
	"protectNavigator": false,
	"navigatorDetails": {},
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}

**Comment by kkapsner** [comment]
Do you see any CB related entries in the console (Ctrl + Shift + K)?
Do you have a Windows or Linux system to see if it happens there as well?

**Comment by LogicaBorealis** [comment]
No CB entry in the console.

I won't be able to test other OS before next tuesday. I'll let you know if the problem occurs on Windows as well.

**Comment by kkapsner** [comment]
OK - I think this issue has to be investigated with the ability to add debug outputs. So is there a way that I can get an account to test this?

**Comment by LogicaBorealis** [comment]
Well, it looks difficult. As I wrote before, account creation is now suspended. They say it should "come back soon" for several weeks...
A new platform is announced. Hopefully it will solve my problem "on its own".

**Comment by kkapsner** [comment]
OK - let's see.

**Comment by derritter88** [comment]
same issue for me - Zimbra does not work while Canvas Blocker is enabled

**Comment by kkapsner** [comment]
Anyone of you able to debug a WebExtension? (Or willing to lend their credentials for me to debug?) I have a suspicion.

**Comment by derritter88** [comment]
I can create you a temporary account for my mail server so you'd be able to log in and do some trouble shooting.

Could you please share your email address / GPG pubkey with me?

**Comment by kkapsner** [comment]
Sent a mail with my informations.

**Comment by kkapsner** [comment]
Thanks derritter88. I'm able to reproduce the problem and think that I can fix it (zimbra uses a non documented feature of HTML).

**Comment by kkapsner** [comment]
Please try the latest alpha: https://canvasblocker.kkapsner.de/versions/

**Comment by LogicaBorealis** [comment]
I tested Alpha20190612 and can confirm the issue is solved.
Thank you!

**Comment by kkapsner** [comment]
Great. I'm not quite sure when the final 0.5.11 will launch. But it may be within the next week.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.11-RC1

**Comment by derritter88** [comment]
New beta versions works for me - thanks!

**Comment by kkapsner** [comment]
Normal 0.5.11 is released.

**Comment by derritter88** [comment]
Thanks - updated and still works!

**Comment by kkapsner** [comment]
Great. Thanks again for the support and the quick feedback.
