### ISSUE TITLE
The recent version caused one webpage's buttons not work

### ISSUE THREAD

**Issue by BugFeedback** [kkapsner/CanvasBlocker#366]
## Description

In the inbox interface of this mailbox https://en.mail.qq.com, click many buttons are not available, including email and other buttons.
![sample](https://user-images.githubusercontent.com/41504474/59076128-000ae080-8907-11e9-9734-b586b5568ffd.jpg)

## Current Behavior

Bug appear in 0.5.9-0.5.10(lastest), 0.5.8 and before is normal.

## Possible Solution

Only disable the entire extension of CanvasBlocker to be normal.

## Steps to Reproduce (for bugs)

1.Need to register to have a QQ account
2.Log in https://en.mail.qq.com
3.Send myself a email

## Your Environment

* CanvasBlocker Version used:0.5.10(lastest)
* Firefox version incl. 32- or 64-bit:64-bit
* Operating System and version (desktop or mobile):desktop
* Installed addons:CanvasBlocker

## Your Settings

Only CanvasBlocker extension with a new clean Firefox 67 profile environment to test.
CanvasBlockerwith Default setting.

**Comment by kkapsner** [comment]
Do I really have to give them my phone number to register? Actually I'm not willing to do that...

Do you see any error messages in the console (Ctrl + Shift + K) that are not present when CB is disabled?
Did you try to disable the data-URL protection?

**Comment by BugFeedback** [comment]
Your are right, no one willing to. You can imagine that China is what a invasion of privacy dictatorship nation.

I have tried to disable the data-URL protection still not work.

I found these error messages that only appear when CB is enabled:

> ReferenceError: gbIsFF is not defined
frame_html:191:13
TypeError: _oTop.setOnlineAttachInfo is not a function
frame_html:207:11
TypeError: getTop(...).setGlobalVarValue is not a function
frame_html:213:10
TypeError: _oTop.S is not a function
frame_html:218:19
ReferenceError: Scale is not defined
frame_html:265:1
ReferenceError: S is not defined
frame_html:290:1
ReferenceError: addEvent is not defined
frame_html:354:1
ReferenceError: ossLogForSetFrame is not defined
frame_html:367:5
TypeError: getTop(...).JS is undefined
today:34:1
TypeError: getTop(...).setTagUnread is not a function
today:98:11
TypeError: getTop(...).updateFolderByRecur is not a function
today:98:10
TypeError: getTop(...).JS is undefined
today:123:1
ReferenceError: hasClass is not defined
frame_html:273:1
ReferenceError: JS is not defined
frame_html:324:1

I hope this helps you.

**Comment by kkapsner** [comment]
Nothing sticks out... but it seems the window-API protection might be active (should not be in default settings). Please try disabling the window-API.

Does whitelisting of the page work?

**Comment by kkapsner** [comment]
Please try the latest alpha: https://canvasblocker.kkapsner.de/versions/

**Comment by BugFeedback** [comment]
> 
> 
> Nothing sticks out... but it seems the window-API protection might be active (should not be in default settings). Please try disabling the window-API.
> 
> Does whitelisting of the page work?

No enable window-API.  I also have already tried it with whitelist is not working.

**Comment by BugFeedback** [comment]
> 
> 
> Please try the latest alpha: https://canvasblocker.kkapsner.de/versions/

Now tested 0.5.11Alpha20190612 works fine again.

**Comment by kkapsner** [comment]
Great to hear that. Not sure when the final 0.5.11 will be released. But it may be within the next week.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.11-RC1

**Comment by kkapsner** [comment]
Normal 0.5.11 is released.
