### ISSUE TITLE
How can avoid function name: API tampering detected？

### ISSUE THREAD

**Issue by sunnyafree** [kkapsner/CanvasBlocker#367]
## Description

When I test on https://canvasblocker.kkapsner.de/test/detectionTest.html with canvas readout mode, all test show no API tampering detected,but the function name show API tampering detected,is there anyone can tell me how to solve this problem.

## Your Environment

* CanvasBlocker Version used: Version 0.5.10
* Firefox version incl. r:64-bit firefox67
* Operating System and version (desktop or mobile):desktop with Windows10
* Installed addons:only CB

**Comment by kkapsner** [comment]
The next version of CB will solve this issue (see c3d4a1901c910077f74ee7c175c119e32492f242).

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.11-RC1

**Comment by kkapsner** [comment]
Normal 0.5.11 is released.
