### ISSUE TITLE
Store persistent data containers whitelist.

### ISSUE THREAD

**Issue by openffchrome** [kkapsner/CanvasBlocker#368]
hello i miss a feature to be able to store persistent rng per container, eg alway use the same fake rng for facebook container1, another one for facebook container2, and random rng when using facebook in other containers (using temporary containers), what do you think about it? 

thanks!

**Comment by openffchrome** [comment]
i found out that while using temporary container and the feature to create  a new name for each new container and the store persistent data feature of canvasblocker it should do the job for what i want to do but it still store a lot of unneeded data (the data of the temporary containers)

**Comment by kkapsner** [comment]
So you suggest to delete the persistent data for the temporary containers? I'm not sure if I can distinguish between temporary and permanent containers. I could provide a tool to delete the data only for a specific container.

**Comment by grenzor** [comment]
I think it makes sense to have a whitelist/custom option under rng settings where users can type a specific domain name or container name and next to it an option to select a specific rng type for only that container name or domain name.

**Comment by kkapsner** [comment]
I can react if a contextual identity is removed which should cover the temporary containers.
I will also include a "clear container" button where you can clear the persistent data for a specific container.

@grenzor: domain specific settings are already implemented but not enabled for the rng type. And I don't think this is useful. But you can already whitelist certain domains.
Making settings depending on the container is tricky. I see the benefit of having it, but with the technical limitations of web extensions I don't want to do it.

**Comment by openffchrome** [comment]
awesome, thanks!

**Comment by kkapsner** [comment]
Please try the latest alpha: https://canvasblocker.kkapsner.de/versions/

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.11-RC1

**Comment by openffchrome** [comment]
seems ok thanks!

**Comment by kkapsner** [comment]
Normal 0.5.11 is released.
