### ISSUE TITLE
Canvas Blocker breaks whitelisted sites or all sites in Allow Everything mode

### ISSUE THREAD

**Issue by djasa** [kkapsner/CanvasBlocker#37]
Recently, Canvas Blocker started breaking all sites that use canvas in any way:
  * mapy.cz: no map shown (but loads ok when you click "Letecká" at top left corner and back)
  * google maps: full version doesn't work at all
  * video.aktualne.cz - any video stops at "loading ad" stage

Whitelisting sites doesn't help, switching Canvas Blocker to Allow Everything block mode doesn't help either, the sites start working like charm when Canvas Blocker is disabled. All of these happen on clean profile + Canvas Blocker, no other add-on or preference make any difference

versions:
Firefox ESR 38.2.1
Canvas Blocker 0.1.8-Release

**Comment by kkapsner** [comment]
Seems like the same issue as #35.

This should be fixed in the withoutPageMod branch: https://github.com/kkapsner/CanvasBlocker/blob/withoutPageMod/canvasblocker.xpi

I'm currently testing and will release version 0.2.0 soon.
