### ISSUE TITLE
Page broken when CB enabled

### ISSUE THREAD

**Issue by crssi** [kkapsner/CanvasBlocker#371]
## Description
When CB extension is enabled, then `https://www.triglav.si/` is broken.

## Your Environment
* CanvasBlocker Version used: 0.5.10
* Firefox version incl. 32- or 64-bit: 64
* Operating System and version (desktop or mobile): Desktop
* Installed addons:

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"blockDataURLs": false,
		"protectNavigator": false
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {
		"length": true
	},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1561016008200,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "26",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": false,
	"protectNavigator": false,
	"navigatorDetails": {},
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}

**Comment by kkapsner** [comment]
In my tests the problem is solved with the latest alpha version: https://canvasblocker.kkapsner.de/versions/

Please verify.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.11-RC1

**Comment by crssi** [comment]
With 0.5.11-RC1 works perfectly. :smile: 

You are best. :heart: 

Fell free to close this issue, when it is appropriate for you.

Thank you and cheers

**Comment by spodermenpls** [comment]
@kkapsner Is it intended that CB doesn't update from the latest Alpha to the new RC automatically?

**Comment by kkapsner** [comment]
No, it's not. Now it will. Had a mistake in the update URL.

**Comment by kkapsner** [comment]
Normal 0.5.11 is released.
