### ISSUE TITLE
No whitelist option for local html

### ISSUE THREAD

**Issue by AeliusSaionji** [kkapsner/CanvasBlocker#373]
This page performs poorly while CB is enabled, yet CB does not claim to be running for the page- it does not offer me the ability to whitelist anything.

https://aelius.keybase.pub/Blur%20Reduction%20C32HG7x%20%231%202019-06-24%2021-56%200.3127x%200.329y%20Rec.%201886%20M-S%20XYZLUT%2BMTX%20%5BA%5D%20vs%20sRGB%20%5BA%5D.x3d.html

**Comment by AeliusSaionji** [comment]
Update:
When viewing the file locally, no whitelist options appear. Now that I've hosted it, the option to whitelist is there.

**Comment by kkapsner** [comment]
The page works fine on my machine. But I will include a way to whitelist local files.

**Comment by kkapsner** [comment]
https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.12 is out
