### ISSUE TITLE
Feature request: WebGL Unmasked Renderer spoofing

### ISSUE THREAD

**Issue by dnminh11** [kkapsner/CanvasBlocker#375]
This is not a big deal if you are on your real PC. The problem is that if you are using CB on a Windows 7 VMWare machine, the attribute `Unmasked Renderer` will always be `ANGLE (Software Adapter Direct3D11 vs_4_1 ps_4_1)` and the same thing applies to other OSes. You can check it at [https://browserleaks.com/webgl](url)

CB has already changed the `WebGL Image Hash` but in my opinion, if we have a variety of `Unmasked Renderer` values, it'll be a bit harder to trace us.

**Comment by kkapsner** [comment]
I think this is the same as #329. Correct me if I'm wron.

**Comment by kkapsner** [comment]
Please check the latest beta version: https://canvasblocker.kkapsner.de/versions/

The vendor/renderer (also unmasked) can be changed by an expert setting.
