### ISSUE TITLE
Create setting presets

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#376]
Options displayed upon installation.
Presets can also be applied later.

presets:
* default (no changes)
* casual (add some performance tweaks but that might reduce security - could also include some url-specific settings)
* sneaky (hard to detect CB but might slow down pages and the browser)
* high security (YOU SHALL NOT GET MY FINGERPRINT)

Details of the presets have to be specified with some user input.

**Comment by kkapsner** [comment]
```
{
	"default": {},
	"convenience": {
		"maxFakeSize": 1000000,
		"protectDOMRect": {
			"onedrive.live.com": false
		}
	},
	"stealth": {
		"minFakeSize": 10,
		"protectedCanvasPart": "input",
		"rng": "persistent",
		"ignoreFrequentColors": 3,
		"minColors": 3,
		"storePersistentRnd": true
	},
	"max_protection": {
		"minFakeSize": 0,
		"audioFakeRate": "0.1%",
		"audioNoiseLevel": "low",
		"protectWindow": true
	}
}
```

This is my current list of settings for the presets. @spodermenpls anything that you would add to one of the presets?

**Comment by spodermenpls** [comment]
CanvasBlocker is compatible with almost every site that I visit, I only have "agar.io" and "slither.io" whitelisted, I don't know if those two games are worth an entry in the factory settings. 😅

**Comment by kkapsner** [comment]
I think every browser game that uses canvas will struggle with CB... and I will not include all. Although they are quite popular I think we can leave them out.
