### ISSUE TITLE
Crash OneDrive Gallery Page

### ISSUE THREAD

**Issue by Riajyuu** [kkapsner/CanvasBlocker#377]
## Description
upload enough photons to OneDrive, open onedrive.live.com and select photos at the left panel.

## Current Behavior
Firefox says, a webpage is slowing down Firefox

## Possible Solution
Close tab or stop webpage.

## Your Environment

* CanvasBlocker Version used: 0.5.11
* Firefox version incl. 32- or 64-bit: 67.0.4 (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Pro lastest
* Installed addons: N/A

## Your Settings
All defaults

**Comment by kkapsner** [comment]
I have no OneDrive account. I would assume that the DOMRect-API is causing the issue.

Please check if the problem disappears if you disable the DOMRect API protection.

**Comment by Riajyuu** [comment]
@kkapsner  yes it does.

**Comment by kkapsner** [comment]
So you should be able to disable the DOMRect for this domain only (please tell me which domain exactly - it might be useful for #376).

Unfortunately I think there is nothing else I can do about this.

**Comment by Riajyuu** [comment]
@kkapsner 

the link is https://onedrive.live.com/?id=root&cid={UUID}#v=photos&id=root&cid={UUID}&qt=allmyphotos

So you will have to disable it on all OneDrive. Maybe I can provide you an OneDrive account so that you can investigate further?

**Comment by kkapsner** [comment]
With an account I could look into it. But I am not sure if I can improve the situation.

**Comment by Riajyuu** [comment]
@kkapsner so how can I reach you? I can't see any email, phone or sth like that on your profile page.

**Comment by kkapsner** [comment]
I added my email address to the profile as it is already visible in github if you know where to look (e.g. https://api.github.com/users/kkapsner/events/public)
