### ISSUE TITLE
"getClientRects()" fingerprinting is blocked instead of being spoofed/faked

### ISSUE THREAD

**Issue by panderlad** [kkapsner/CanvasBlocker#379]
## Description
Testing https://browserleaks.com/rects it get's just "?" as result, meaning the "getClientRects()" are not getting faked but just blocked.

This create a big problem for some website, where it's not possible to log it, because the log in page just doesn't show up: account.booking.com/sign-in

Tested with the Bloking Mode to "Ask for permission", and it works after I grant the DOMRect API permission and History API.

Can you solve it faking the DOMRect API, not just blocking it?

**Comment by kkapsner** [comment]
It works for me.

Please tell me your settings and used version (Browser and Canvasblocker) so I can check what your problem is exactly.

**Comment by kkapsner** [comment]
Without your input I'm not able to find the issue.

**Comment by kkapsner** [comment]
If the problem still exists and you provide the needed information I can reopen this issue.
