### ISSUE TITLE
Seamonkey support

### ISSUE THREAD

**Issue by nazir-cz** [kkapsner/CanvasBlocker#38]
Can you please add support for the SeaMonkey (formerly Mozilla Suite)?
You only need to add SeaMonkey to list of supported applications in install.rdf as http://addonconverter.fotokraina.com do...

```
  <em:targetApplication> 
    <em:Description> 
    <em:id>{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}</em:id> 
    <em:minVersion>2.0</em:minVersion>
    <em:maxVersion>2.*</em:maxVersion> 
  </em:Description> 
  </em:targetApplication>
```

No further adjustments are needed...

**Comment by kkapsner** [comment]
Release https://github.com/kkapsner/CanvasBlocker/releases/tag/0.2.2.1-OtherRelease should work in Seemonkey - but no warranty.
