### ISSUE TITLE
Shows "scripts not responding" on Android

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#383]
## Description

When you use this on Firefox for Android, it very often shows a "Not responsive" script warning on web pages, which points to CanvasBlockers JS. :smile: 

## Expected Behavior

Work.

## Current Behavior

Shows a big message and I can block the script.

I guess whatever it is doing is stressing the CPU architecture too much. :smiley: 

## Steps to Reproduce (for bugs)

1. Install and open some sites.

## Your Environment

* CanvasBlocker Version used: N/A
* Firefox version incl. 32- or 64-bit: N/A
* Operating System and version (desktop or mobile): LineageOS 14.1

## Your Settings

default settings AFAIK

**Comment by kkapsner** [comment]
Can you please compare with 0.5.8. (I do not have an android device to test this)

**Comment by spodermenpls** [comment]
What if you limit the maximum faking size? I've set it to 30000, to suit my old hardware of my phone.

**Comment by TriMoon** [comment]
Same happen on `Linux (Kubuntu 19.04)` with FF `70.0a1` while browsing this issue page (for example), and the preview of comments is non-functional (cause you need to select "stop") with these settings:
```json
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"blockMode": false,
		"highlightPageAction": false,
		"protectWindow": false
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "ask",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1563781088092,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "blink",
	"highlightBrowserAction": "none",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": true,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "24",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}
```

**Comment by kkapsner** [comment]
I have no problems in Linux (Manjaro) with 70.0a1 an these settings. Can you please run the innerHTML test on https://canvasblocker.kkapsner.de/test/performanceTest.html with and without CB?

**Comment by TriMoon** [comment]
On that page i didn't get a popup asking me for permission, but anyway here the results:
  - CB enabled: 
`finished run 300 from 300 -> average: 15.26(±1.33) ms (min: 13.00ms, max: 23.00ms)`
  - CB disabled: 
`finished run 300 from 300 -> average: 10.48(±1.03) ms (min: 9.00ms, max: 17.00ms)`

**Comment by kkapsner** [comment]
Your times are much better than what I get on my machine... still github is fine for me.
That's really weird.

This test is for a general hook I had to do to protect a new attack vector. If you have general problems with pages this could have been the issue.
There is nothing faked so no notification.

Github highly uses the DOMRect-API. Does disabling this protection help?

Can you please also test with default settings? And then reverting to your step by step?

Thanks for you help so far.

**Comment by TriMoon** [comment]
I might comeback to this issue someday in the future because of other duties, but for now i keep it disabled...
The weird part of your test page is that it **didn't ask for any permissions**, so maybe your test page needs improvement....

**Comment by kkapsner** [comment]
That's totally fine that it did not ask for permission. Nothing is faked there - it tests some background operations.
The "test fingerprint" should ask for permissions.

**Comment by kkapsner** [comment]
@rugk can you please provide a screenshot of the "not responding" message?

**Comment by rugk** [comment]
AFAIK the previous workarounds or so did fix the problem. I'm not sure, however.

**Comment by kkapsner** [comment]
OK - so at the current situation there is nothing I can do. So I will close this issue and it can be reopened when we have more information about this problem.
