### ISSUE TITLE
Do we need this add-on in Firefox 68?

### ISSUE THREAD

**Issue by sphh** [kkapsner/CanvasBlocker#384]
The new Firefox 68.0 has the possibility to block finger printing: https://support.mozilla.org/en-US/kb/content-blocking

Could you please explain if (and why) we still need the CanvasBlocker add-on. Thanks!

When I disable CanvasBlocker, https://browserleaks.com/canvas shows me the same fingerprint id with an uniqueness of "99.98% (91 of 474678 user agents have the same signature)". With the add-on enabled I get "100% (0 of 474678 user agents have the same signature)"

**Comment by kkapsner** [comment]
This was introduced with Firefox 67 and discussed here #349 

Having a uniqueness of 100% is fine as long as it changes every time (if you reload you see that the signature changes).

**Comment by sphh** [comment]
Looks like I have missed both: The new feature in Firefox 67 and the thread #349. Thanks for the reference.

Maybe it is worth to put this answer somewhere more prominent (e.g. the readme or the description on Mozilla's add-on page)?
