### ISSUE TITLE
Captcha 

### ISSUE THREAD

**Issue by jorg35** [kkapsner/CanvasBlocker#385]
Captcha does not work in v 0.5.13 RC1.

**Comment by kkapsner** [comment]
Which captcha? reCAPTCHA is not working when the window API is protected. That's why you are prompted with the choice to whitelist it when you enable the window API.

With this it works fine at my end.

**Comment by jorg35** [comment]
Canvasblocker beta-0.5.13 Alpha 20190716 is good,on the same settings.

**Comment by kkapsner** [comment]
That's very weird. Between these two only some GUI was changed.
Where did you test?

**Comment by jorg35** [comment]
Tested on Waterfox 56.2.12. Win10.

**Comment by kkapsner** [comment]
Also there everything works fine for me.

Which test page for the captcha are you using?
What are your settings?

**Comment by jorg35** [comment]
Too much interference in my privacy.

**Comment by kkapsner** [comment]
You can remove everything from the settings that you do not want to share. But I need to reproduce your problem to solve this issue.

**Comment by jorg35** [comment]
Works, I did reset settings. Sorry for the inconvenience.

**Comment by kkapsner** [comment]
OK - no problem.
