### ISSUE TITLE
Site specific values not shown in UI

### ISSUE THREAD

**Issue by TriMoon** [kkapsner/CanvasBlocker#386]
## Description
When you are able to actually add a "Site specific value" the current values are **not** listed at all in the UI of the settings page.
No matter if you close and reopen it, no matter if it's in a separate tab or not.

## Expected Behavior
All values that are currently configured for the respective "Site specific value" should be listed.

## Current Behavior
No list is shown at all, just a single blank input box with the '+' on right.

## Possible Solution
No idea at all because i didn't code this :wink:

## Steps to Reproduce (for bugs)
1. While on any webpage click the fingerprint icon in the URL-bar and select the gear icon to open the settings page of this extension.
(Or use any other method to get to the same settings page.)
2. As an example we will add an entry to "Block mode".
Click the black arrow on right side of the "Block mode" setting.
3. Type any text fe, `local.` and click the `+` symbol on right of the input box.
4. This value is now actually in the config, but not shown.
5. Close the settings page tab and open the settings page in a fresh tab.
It is **still not shown**.
6. Check it was actually added to the config by clicking the "Inspect" button in the "Export settings" section.

## Context
I was trying to use this feature and was baffled by the lack of info feedback.

## Your Environment
* CanvasBlocker Version used: `0.5.12`
* Firefox version incl. 32- or 64-bit: `Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0 ID:20190721215935`
* Operating System and version (desktop or mobile): `Desktop Linux` `Kubuntu 19.04`
* Installed addons:
```
Amazon.com 1.1
Awesome RSS 1.3.5
Bing 1.0
CanvasBlocker 0.5.12
Certainly Something (Certificate Viewer) 1.2.3
Compat Report 0.1.0
Containers theme 1.0.3
Context Plus 0.6.0
Debian queries 2.3
Decentraleyes 2.0.12
DuckDuckGo 1.0
DuckDuckGo Privacy Essentials 2019.7.2
Emoji Cheatsheet for GitHub, Basecamp etc. 2.0.1
Enterprise Policy Generator 4.4.0 [DISABLED]
Facebook Container 2.0.1
Feedbro 3.42.8
Firefox Lightbeam 2.1.0
Firefox Multi-Account Containers 6.1.0
FoxyProxy Standard 6.6.2
Google 1.0
Greasemonkey 4.9
HTTP/2 Indicator 3.0
IPFS Companion 2.8.3 [DISABLED]
Laboratory 3.0.5 [DISABLED]
MathML Font Settings 0.3.2 [DISABLED]
Native MathML 1.9.4 [DISABLED]
Nightly Tester Tools 4.0
Notes by Firefox 4.3.5 [DISABLED]
Offline QR Code Generator 1.6
PassFF 1.9 [DISABLED]
Plasma Integration 1.5
React Developer Tools 3.6.0 [DISABLED]
Session Sync 3.1.12
Snooze Tabs 1.1.1
Tab Session Manager 4.5.2 [DISABLED]
To Google Translate 3.10
Tree Style Tab 3.1.5
True Sight 1.7.1
Twitter 1.0
Vue.js devtools 5.1.1
Wikipedia (en) 1.0
Yandex 1.0
YouTube Container 1.3.0
eBay 1.0
uMatrix 1.3.16
```

## Your Settings
Fresh config after "Reset"

**Comment by TriMoon** [comment]
Due to #383 im now disabling this addon...

**Comment by kkapsner** [comment]
Already fixed in https://github.com/kkapsner/CanvasBlocker/commit/6fb0f946af989d67ebe68cf60c0c501689f6f75b - version 0.5.13 will be published soon.
