### ISSUE TITLE
issue with login (Coursera)

### ISSUE THREAD

**Issue by 88-percent** [kkapsner/CanvasBlocker#389]
## Description
Login fails on Coursera 

## Expected Behavior
Clicking "Log in" should log in to site.

## Current Behavior
Clicking "Log in" results in no action.

## Steps to Reproduce (for bugs)
1. visit https://www.coursera.org/?authMode=login
2. enter email and password
3.click "log in"

## Your Environment

* CanvasBlocker Version used: 0.5.13
* Firefox version incl. 32- or 64-bit: 64
* Operating System and version (desktop or mobile): MacOS 10.13
* Installed addons:

**Comment by kkapsner** [comment]
Please tell me your settings.
Please also test with the Data-URL protection disabled.

**Comment by 88-percent** [comment]
Sure thing! What other personal data other than "persistentRndStorage" should I remove before sending the settings?

Where  do I disable Data-URL protection? I can't seem to find it in the settings.

**Comment by kkapsner** [comment]
You should also have a look at the urlSettings and remove entries that are not related to this issue. Also the lists (white, black, ignore) can be cleared.

The Data-URL protection can only be disabled when you are in expert mode. So activate the expert mode and just search for "data".

**Comment by 88-percent** [comment]
after enabling Expert Mode I tried disabling both:
1) APIs > Canvas API > toDataURL
2) Misc > Misc > Block data URL pages
but neither worked.

I'm attaching my settings.

Be sure to let me know if I can be of any further help.

[CanvasBlocker Export Settings.txt](https://github.com/kkapsner/CanvasBlocker/files/3526540/CanvasBlocker.Export.Settings.txt)

**Comment by kkapsner** [comment]
This page uses reCaptcha which does not work with the window API protection enabled (see #337).

Please disable and reenable the window API protection. You will then be prompted if you want to add an exception for reCaptcha. Add the exception and the login page should work.

**Comment by 88-percent** [comment]
great that we know what the issue is. I think I must be doing something wrong then, as it's still not working for me. I only used the default catcha - was I supposed to get my own value from somewhere?

I'm attaching a screenshot.

![screenshot](https://user-images.githubusercontent.com/41041011/63859825-8deee880-c997-11e9-9cc8-7faa597f1bb7.png)

**Comment by kkapsner** [comment]
You have to remove the check mark for the captcha url.

**Comment by 88-percent** [comment]
Thanks!

I thought the tickmark represented an exception. 

Sorry for the trouble.

**Comment by kkapsner** [comment]
No, the tickmark represents the state for that setting for that URL. You're not the first one to get this wrong. If you hover your mouse over the circle with the "i" you should get a description of the setting and some more information of how the url exceptions work.

No problem.
