### ISSUE TITLE
Trouble understanding testing pages

### ISSUE THREAD

**Issue by arelkin** [kkapsner/CanvasBlocker#390]
https://canvasblocker.kkapsner.de/test/

Thanks for your plug-in. Just found it and have begun using it. I went to your test page, but I am having trouble understanding the results of the test results.

For example, on the https://canvasblocker.kkapsner.de/test/navigatorTest.php page, both sets of data seem to be accurate and the same. I don't understand if that means the the Canvas Blocker is working or not working.

Other test pages return a lot of information, but don't specify "yes, Canvas Blocker anonymized or blocked your profile."

Any help understanding, appreciated.

**Comment by kkapsner** [comment]
The navigator test page does nothing interesting in the default settings of CB. If you enable the navigator protection you can check there that it took your settings correctly and that it fakes the values consistently (you can also check other userAgent spoofing addons and see how inconsistent they are sometimes).

Also a simple "Yes, ..." is not possible as this highly depends on your settings. But as I already did on some pages (e.g. https://canvasblocker.kkapsner.de/test/iframeTest.html) I should include a "how to read the results" section in every test page.

**Comment by kkapsner** [comment]
I updated the pages. Please have a look and give feedback.

**Comment by kkapsner** [comment]
@spodermenpls can you please have a look?

**Comment by spodermenpls** [comment]
I already had a look at it shortly after your edit, everything looks fine to me (no typos). I didn't comment since I viewed the the existing descriptions as sufficient (after you added those for the iFrame test), but a little bit of finetuning can't hurt.

**Comment by kkapsner** [comment]
Thanks for checking.

I think I will close this issue. If @arelkin thinks something is not clear I will reopen it.
