### ISSUE TITLE
Question about protection on sites originating from localhost and local files

### ISSUE THREAD

**Issue by Paba22** [kkapsner/CanvasBlocker#391]
Recently I observed that CanvasBlocker is active on Syncthing web GUI and local files.
Is there a point in protecting from fingerprinting when sites originate from the local machine? Doesn't that mean that they are trusted?
I guess it could help some users in testing, but still wouldn't it make more sense if it was opt-in instead of the default behavior?
I would appreciate if someone could explain to me, why protection is on even when viewing local files or sites originating from localhost.

**Comment by kkapsner** [comment]
People download the weirdest things from the internet and store them local. So I would not assume that these are trusted.
Also malicious files that are sent by mail and then opened are stored as local files. As the negative impact is really low and I see an actual attack vector I will not change the default behaviour.

The reason why the protection is on is simply that it's the way the web extension APIs work and I have no reason to change it. If you want these file to be not protection you should be able to whitelist it (localhost is easy as it's a domain and the file-protocol should be doable with a RegExp).
