### ISSUE TITLE
Signature not changing on https://browserleaks.com/canvas

### ISSUE THREAD

**Issue by rugabunda** [kkapsner/CanvasBlocker#392]
I've been testing canvasblocker on stealth + RFP, I get the same canvas signature on https://browserleaks.com/canvas whether it is disabled or enabled, for days now. Uniqueness says tor browser signature. Is this to be expected?

**Comment by kkapsner** [comment]
Yes, this is to be expected with RFP. It wins over CB.
But your setup is still useful. If you grant a page access to the canvas CB will still protect your fingerprint.

I think you cannot allow the canvas on browserleaks as it uses a background canvas.
