### ISSUE TITLE
Console errors (causing lag perhaps?)

### ISSUE THREAD

**Issue by privacyguy123** [kkapsner/CanvasBlocker#394]
My console is getting blasted with "NOT intercepting window due to SOP" on sites like YouTube and Investing.com which is actually causing my browser to lag a little - have I got something set wrong here?

**Comment by kkapsner** [comment]
These entries go away if you set your log level to error. But actually this message should not be a warning but a notice. I will change that.

**Comment by kkapsner** [comment]
Version 0.5.14 is published.
