### ISSUE TITLE
webgl is not change hash

### ISSUE THREAD

**Issue by andersonoliveira111** [kkapsner/CanvasBlocker#395]
the webgl is not change the hash did you remove the api webgl ? beacause on the extension is say 
Protected "fingerprinting" APIs:
canvas 2d
  webGL
  audio
  history
  window (disabled by default)
  DOMRect
  navigator (disabled by default)

but the webgl is not working and is not showing on the extension can you explain that?

**Comment by kkapsner** [comment]
The webGL was not changed. Within the settings it's part of the "canvas" API.

The webGL image hash is changing for me on https://browserleaks.com/webgl (not the report hash - see #329). Where did you check?

**Comment by andersonoliveira111** [comment]
have the same report hash is not delectable?  
![Captura de tela de 2019-09-05 14-50-18](https://user-images.githubusercontent.com/54554812/64366442-9d4fe080-cfec-11e9-9fce-d18e29b03ae5.png)

look this extension https://chrome.google.com/webstore/detail/browser-plugs-fingerprint/gpgbpgdfipppcelfbdlbkhmibofknppj 

change the webgl the only thing is that is random and to persistent and also change the fonts api will be good if you put this on your extension.

**Comment by crssi** [comment]
Here, `WebGL Image Hash` is changing, but `WebGL Report Hash` is allways the same... why is that so?

Cheers

**Comment by kkapsner** [comment]
The webGL report hash is based on webGL meta data which is not covered yet by CB. But it's planned.

So this is a duplicate to #329 and therefore will be closed.

**Comment by kkapsner** [comment]
Please check the latest beta version: https://canvasblocker.kkapsner.de/versions/
