### ISSUE TITLE
Google reCAPTCHA - Not Working - Android - PC

### ISSUE THREAD

**Issue by desmonk** [kkapsner/CanvasBlocker#398]
Google reCAPTCHA not wokring on Android and PC.

## Description
Google reCAPTCHA not working on PC and Android.
Breaks many websites which rely this service by Google.

## Expected Behavior
Should be able to work with Google reCAPTCHA.
Should be able to work as usual like before it had.

## Current Behavior
Google reCAPTCHA box never appears.
Many websites get stuck due to the nature of the case.

## Steps to Reproduce (for bugs)
Both Firefox Android and on PC suffers the same fate.
1. Install the Extension.
2. Either use Android or Windows 7/10
3. Visit a site that uses Google reCAPTCHA service.
4. No prompt by Google to enter into the reCAPTCHA box to pass the test.

## Your Environment
* CanvasBlocker Version: Latest Version: 0.5.3Alpha20180821
* Firefox Latest Version ESR 64-bit 68.1.0
* Windows 7/10, Firefox Android 9 Pie
* Installed addons: uBlock, HTTPS Everywhere, NoScript

## Your Settings
Due to the nature of my work I can not do that. Hope you understand.

**Comment by kkapsner** [comment]
It works fine for me on https://www.google.com/recaptcha/api2/demo
I guess it's the same issue as #337 and #358. Without your settings (you might remove some private data) I cannot tell.

**Comment by desmonk** [comment]
Thank you for getting back so quickly. Passes the demo page, yes but fails randomly especially on Firefox for Android. I came across on Twitter.

**Comment by kkapsner** [comment]
Do you have the window API protection activated?

**Comment by kkapsner** [comment]
I need some more details about your settings. Without them I cannot reproduce and therefore resolve this issue.

**Comment by kkapsner** [comment]
No response for more than three weeks. I will close this. If you provide the needed information I can reopen this issue.

**Comment by desmonk** [comment]
So sorry for the delay. What I found out is with Firefox's Content Blocking on, reCAPTCHA won't even load. Firefox does not enable Content Blocking for test page so it works. I guess the conflict is between this function of Firefox. Not with this extension.

But on Android the problem is there. With or without Content Blocking option, extension does block reCAPTCHA.

**Comment by kkapsner** [comment]
What are your settings on Android?

**Comment by desmonk** [comment]
I really am surprised but on Android too it is working. Okay so this is what I had before. While I was at Twitter getting Help, had to enter Google CAPTCHA form, and here where I had to disable extension. I have now only one question. What is "red cross on gear icon (Settings)" over Google DOMRect? While Twitter does not have that red cross.

I have to admit I feel so embarrassed now as both platforms now do not have the issue. I again apologies.

**Comment by kkapsner** [comment]
No problem. Maybe it was a reCAPTCHA problem...

I do not quite know what you mean by "red cross on gear icon (Settings)". Which icon from here: https://github.com/kkapsner/CanvasBlocker/tree/master/icons

**Comment by desmonk** [comment]
This gear icon with a red cross on Google:
https://ibb.co/kHq4SJb

**Comment by kkapsner** [comment]
Ah... this is not a gear but a fingerprint icon. These two icons on the right are not dedicated to the entries left to them but global actions you can perform (you should see a tool tip if you hover with the mouse over them). The gear opens the settings and the fingerprint with the cross disables notifications.

**Comment by kekukui** [comment]
The issue persists - Recaptcha window is visible but images do not appear, using the default CanvasBlocker settings.  "Protect Window API" is the problem.  https://github.com/kkapsner/CanvasBlocker/issues/337

Exception for recaptcha works -- but how would the average user know about this ?

**Recaptcha test tool**
https://patrickhlauke.github.io/recaptcha/

**Note:**
If you enable/disable CanvasBocker or change any setting, you must reload the page for the change to effect recaptcha

**Comment by kkapsner** [comment]
> The issue persists

I know and there is nothing I can do about it as reCAPTCHA relies on `window.name`.

> Exception for recaptcha works -- but how would the average user know about this ?

The window API protection is not active by default and if it's activated a prompt is shown that asks if the exception should be added.

**Comment by kekukui** [comment]
> **The window API protection is not active by default and if it's activated a prompt is shown that asks if the exception should be added.**

On Firefox, where it says _"Presets: Thanks for installing CanvasBlocker"_, the word "google" or "recaptcha" does not appear.  Under "Maximum protection", it does say "`Protect window API`" is enabled, but _the user will not know this blocks_ **recaptcha**.  When I choose "Maximum protection" preset and then perform the Recaptcha test, it does not work and _there is no prompt to add exception_.

**Comment by kkapsner** [comment]
You're right. But the "Maximum protection" preset states: 

> This settings will break some pages

What do you think is a better. Simply state that this preset breaks reCAPTCHA or add the prompt there as well?

**Comment by kkapsner** [comment]
I would actually prefer to not show the prompt there. Having a "Maximum protection" and then add an exception in the same action is kind of weird...

I think I will just add some text there and the steps to be performed to get it working.

**Comment by kekukui** [comment]
I have a couple ideas:

**1.**  - Display a prompt if the browser attempts to access a reCAPTCHA domain while
"Protect Window API" = enabled.  Something like this:

> **reCAPTCHA disallowed by CanvasBlocker.**
> **Want to unblock/whitelist reCAPTCHA domains?**
> `[Yes]` `[No]` `[Help]`
> ☑️ `Remember my choice`
____________________

**2.** - Display a control for ☑️  "**Whitelist Google ReCAPTCHA**" in the presets menu

**Comment by kkapsner** [comment]
I went with the second route and added a reCAPTCHA preset.

**Comment by kekukui** [comment]
Thats fine, anything like this will help.  But it should probably be in bold/colored text so the control is easily noticed.  I disabled half of my extensions while trying to determine which extension was blocking reCAPTCHA before I realized it was CanvasBlocker.  I know you cant make a control for every possible thing that CanvasBlocker might break, but reCAPTCHA is used on millions of web sites, so a lot of people will surely be confused when they find that it does not work.

**Comment by kkapsner** [comment]
I will release a beta with that soon where you can have a look.

**Comment by kkapsner** [comment]
Version 1.0 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.0

**Comment by boistordu** [comment]
Sorry to reopen this subject but I have the same issue. 
I don't think it's a firefox problem honestly. The problem goes away when I deactivate your extension. 
So,

it is not happening everywhere, I didn't change anything in the settings of your extension at the moment, it's pretty much vanilla. 
It doesn't not work everywhere, So I guess it depends of the domain and which script is actually called but I can confirm from the developper tab that the script is coming to my host without problem, there are not blocked by any js blocker. 
what's happening is that the round gets circling and circling over and over next to I'm not a robot. 
the website in question is suicideproject.org  maybe you can try yourself, use a vpn by the way to make the test more accurate.
So if there are any settings, because I don't find your UI very intuitive so I'm kinda lost at the moment in all the presentation of the settings of your extension, to exclude maybe domain where captcha could be embedded to avoid those kind of problems could you make a wiki page about it? 
Thanks in advance

**Comment by kkapsner** [comment]
For me the reCaptcha at https://suicideproject.org/wp-login.php?action=register works fine with completely vanilla settings.

If you have the window-API protection enabled you also want to enable "Allow window.name in frames". (If you enter "recaptcha" in the search bar of the options page you should also find it:
![grafik](https://user-images.githubusercontent.com/1105157/75463706-77493e80-5986-11ea-9858-1428a45e5f28.png))

I added a section about reCAPTCHA in the FAQs: https://canvasblocker.kkapsner.de/faq/

PS: I know that the options UI needs some improvements...

**Comment by boistordu** [comment]
ow okey and this case should be enabled by default?

**Comment by kekukui** [comment]
> maybe you can try yourself, use a vpn by the way to make the test more accurate.

I just added CanvasBlocker to a new install of Firefox.  When the presets menu appeared, I applied "convenient settings" and then "recaptcha".  I then proceeded to the indicated site, using a VPN as suggested.  The captcha worked.

> PS: I know that the options UI needs some improvements...

It's much better already 🙂  and I like the blinking effect

**Comment by kkapsner** [comment]
> ow okey and this case should be enabled by default?

No. This is not enabled by default. But if you enable the window API protection you are prompted if you want to enable this. (Not if you are using enabling the stealth preset, but in the description it clearly states you should also consider enabling the reCAPTCHA preset.)
