### ISSUE TITLE
Tab Crash with CanvasBlocker on a fresh profile

### ISSUE THREAD

**Issue by allo-** [kkapsner/CanvasBlocker#399]
## Description
When creating a new profile with CanvasBlocker preinstalled, every tab crashes and the addons do not work either. When I remove CanvasBlocker from the preinstalled extensions, it works for me.
For more details about the preconfigured profiles, see:
https://github.com/allo-/firefox-profilemaker/issues/173

I consider this a Firefox bug, but maybe you know what the actual issue is, or can add a workaround in the addon, so the crash can be avoided.

## Steps to Reproduce (for bugs)

Easiest way:

1. Visit ffprofile.com and create a profile, that contains CanvasBlocker on the Addons-Tab of the site.
2. Create a new Firefox profile and unzip the created profile into the profile folder (see instructions at the final page of the generator

The minimal way seems to be to put the CanvasBlocker XPI into the "extensions" folder and set ``extensions.autoDisableScopes=14`` (Allow to preinstall addons) in ``prefs.js``.

## Context
My project allows users to generate new profiles with privacy friendly defaults. I like to add your addon to the profile, but it crashes Firefox. This is probably some Firefox bug, but you may be able to help debugging, file a bug against Firefox yourself or add a workaround to your addon.

## Your Environment

* CanvasBlocker Version used: 0.5.13
* Firefox version incl. 32- or 64-bit: 64 Bit
* Operating System and version (desktop or mobile): Desktop, Linux
* Installed addons: CanvasBlocker

## Your Settings
No settings, that Canvasblocker does not autogenerate itself on the first start.

**Comment by kkapsner** [comment]
Unfortunately I'm not able to reproduce this issue. Can you please just give a zip file of a profile that is broken and a reproduction scenario how a tab crashes?

**Comment by allo-** [comment]
Sorry I removed the option to add CanvasBlocker at the moment, so people do not generate crashing profiles.

Here is an example profile.
https://ffprofile.com/static/example_profile.zip

I am looking into it, it seems that it depends on some of the other preferences, only with CanvasBlocker and ``autoDisableScopes`` I do not run into the issue.

Maybe it is related to some of the other APIs like indexedDB or similar storage that can be restricted in the generator.

**Comment by allo-** [comment]
Indeed, enabling all the storage apis worked and it seems that indexedDB is the problem here. I am not sure if extensions should be able to use it, when it is disabled for website (I would think they should be able to do it, but I do not know the Mozilla policy on that), but at least it should not crash.

**Comment by allo-** [comment]
It seems to be still the same bug, like Firefox with no settings but indexeddb disabled crashing on youtube.com.

I am not sure about the extension api and how it is or should be excluded from the setting, but I guess there is not much for you to do.

**Comment by allo-** [comment]
FYI: I reported it in the Mozilla Bugtracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1581384
We'll see if they can identify the problem there.

**Comment by wesaphzt** [comment]
With CanvasBlocker extension, extensions are still broken and I get the crashed tab messages.
Removing CanvasBlocker and using only the other extensions they're still broken but I don't seem to get the crashed tab messages anymore.

For reference, these are the terminal errors I get. Might be worth adding them onto the Mozilla bug report.
[Parent 7, Gecko_IOThread] WARNING: pipe error (80): Connection reset by peer: file /build/firefox/src/firefox-69.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
[Parent 7, Gecko_IOThread] WARNING: pipe error (77): Connection reset by peer: file /build/firefox/src/firefox-69.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358

###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x360020,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x36011A,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

**Comment by kkapsner** [comment]
With the indexedDB disabled I'm able to reproduce the problem. I can also pinpoint the exact line of code that triggers the problem (https://github.com/kkapsner/CanvasBlocker/blob/master/lib/settings.js#L435). It's the loading of the settings. So it's a little bit tricky to solve this problem...

**Comment by wesaphzt** [comment]
Just noticed I commented on the wrong issue (sorry).
FYI those errors aren't specific to CanvasBlocker, but Firefox 69-specific errors for various extensions and issues that come about with indexedDB disabled. 68 worked fine.
