### ISSUE TITLE
[feature request] addon icon and/or window to edit entry before adding to ignore/whitelist

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [kkapsner/CanvasBlocker#40]
an addon icon for the addon/status bar would be useful as its kind of a pain to go into the addons page and find canvas blocker and click on settings. maybe it could bring up a window when clicked to quickly change options.

another thing that might be nice would be a popup when clicking on ignore or whitelist for a domain when readout is faked. that way the domain can be edited before it is added e.g. to add/remove subdomain or something

**Comment by kkapsner** [comment]
I like the idea of a prompt where you can edit the values that are added to the lists and changed the code accordingly.

But I'm not sure if an icon that only links to the preference panel is worth the space it requires in the toolbar.

**Comment by berrythesoftwarecodeprogrammar** [comment]
thats true
thanks :)
