### ISSUE TITLE
DOMRect faking

### ISSUE THREAD

**Issue by privacyguy123** [kkapsner/CanvasBlocker#400]
What exactly are we being protected against with this protection on? I've noticed allowing it for sites I trust speeds up page loading tenfold - is it worth slowing down my web experience with this option on?

**Comment by kkapsner** [comment]
Please check #236 for further information.

I know that it slows down some pages significantly (already improved: #253). If you trust the page you can whitelist this API for it (I would not disable the protection entirely).

Also ignoring this API in the notifications improves the performance.
