### ISSUE TITLE
CanvasBlocker is not working

### ISSUE THREAD

**Issue by molitar** [kkapsner/CanvasBlocker#403]
Installed latest CanvasBlocker from Mozilla extensions. 3 different browser identification sites and they all identified everything 100% correct.  It is not working.

## Description
Not blocking fingerprint

## Expected Behavior
Expect it to block my real information

## Your Environment

* CanvasBlocker Version used: 0.5.14
* Firefox version incl. 32- or 64-bit: Firefox DE 70.0b14 64-bit
* Operating System and version (desktop or mobile): Windows 10

## Your Settings
Selected the second option to apply.

**Comment by kkapsner** [comment]
Which identification sites are you using?

What do you exactly mean by "browser identification"?

**Comment by molitar** [comment]
I went to many sites like doileak and others that test for fingerprints.  The values did not seem to change at all.

**Comment by kkapsner** [comment]
Which value at doileak would you expect to change?
On https://browserleaks.com/canvas you can see the signature change.

**Comment by molitar** [comment]
From various sites I was expecting false reports maybe of the desktop size, plugins installed but the values seem to be the same with it on and off.. 

sites tested: 
https://amiunique.org/
https://panopticlick.eff.org/results?aat=1&dnt=1&t=1#fingerprintTable

But than again I am using the Firefox Developer Edition 70 so that maybe causing problems and making it now work.  I found another plugin not working properly and going to downgrade back to version 69 because of it.

**Comment by kkapsner** [comment]
For most of the protected APIs I created my own test pages: https://canvasblocker.kkapsner.de/test
There you should be able to tell if the extension is working.

As far as I know Firefox 70 is not a problem for CB. Please run the tests above with it (with the stealth preset you might not get the expected result but you should see differences when disabling DB).

**Comment by kkapsner** [comment]
The data-URL test works fine for me. Can you please give me a screenshot (blur any displayed hashes).

You can whitelist sites with the icon in the address bar: 
![grafik](https://user-images.githubusercontent.com/1105157/67157257-0f288300-f32a-11e9-89b3-eb793a1dcc20.png)

Within the settings you can inspect your whitelistings:
![grafik](https://user-images.githubusercontent.com/1105157/67157263-2a938e00-f32a-11e9-8ef4-80e9084fb052.png)

**Comment by molitar** [comment]
Well not sure maybe something about Firefox security in version 69.  I can open it in Chrome but when I try Firefox I get unable to connect URL.  I disabled uBlock Origin and even my VPN.. still same results.

**Comment by kkapsner** [comment]
Weird.. it works fine for me in FF 70. Did you try with a fresh profile?

**Comment by kkapsner** [comment]
Since I did no get an answer I expect that everything is working now. If the problem still exists I can reopen the issue.
