### ISSUE TITLE
Screen size spoofing

### ISSUE THREAD

**Issue by privacyguy123** [kkapsner/CanvasBlocker#404]
https://addons.mozilla.org/en-GB/firefox/addon/chameleon-ext/

It feels like this addon does everything CanvasBlocker does, just a little worse ... except screen size spoofing - do you think you could add it in?

**Comment by crssi** [comment]
Screen size cannot be spoofed without getting busted.
The only way is using RFP (`privacy.resistFingerprinting`)

**Comment by kkapsner** [comment]
This is a duplicate of #220
