### ISSUE TITLE
AmIUnique FIngerprint Test

### ISSUE THREAD

**Issue by privacyguy123** [kkapsner/CanvasBlocker#405]
Amiunique HTML5 canvas showing as the same on every refresh - is this working as intended?

**Comment by kkapsner** [comment]
Unfortunatelly Amiunique does not show the computed hash to determine if you are unique. CB changes the image very slightly which is not detectable by the human eye. You test if the canvas protection is working on https://canvasblocker.kkapsner.de/test/test.html or https://browserleaks.com/canvas - there you can see that the hash/signature changes.

**Comment by privacyguy123** [comment]
Hmm - yes I do see it working there.
