### ISSUE TITLE
Fingerprinting test - hashes do not change upon reload

### ISSUE THREAD

**Issue by 3r233fff** [kkapsner/CanvasBlocker#406]
Using windows 7 and firefox the "fingerprinting test" (https://canvasblocker.kkapsner.de/test/test.html) and "settings loading" (https://canvasblocker.kkapsner.de/test/settingsLoading.php) passes everything mentioned except that the hashes don't change upon reloading the tab.

All other tests perform as expected.

I would greatly appreciate some support with this.

**Comment by kkapsner** [comment]
Please give me your settings so I can try to reproduce this.

**Comment by 3r233fff** [comment]
"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {
		"length": true
	},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": true,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{}",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": ****************,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "13",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": true,
	"navigatorDetails": {},
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}

**Comment by kkapsner** [comment]
No as you are using  the "nonPersistent" rng. With these settings the hash changes for me.

Which Firefox Version are you using? Have you tried with a fresh profile?

**Comment by kkapsner** [comment]
You do not have to remove your existing profile. You can have multiple ones - so testing with a fresh profile should not reset your complete browser.

There is one setting that comes to mind: privacy.resistFingerprinting. With this enabled the canvas test page will not show the content of the canvas and the hash will always stay the same.

**Comment by 3r233fff** [comment]
Yes, I have that setting enabled. I assumed the hashes were not merely a calculation of just the HTML5 canvas, but also drew on other sources.

I guess it's solved then! :)
