### ISSUE TITLE
Any way to block IP numbers?

### ISSUE THREAD

**Issue by arelkin** [kkapsner/CanvasBlocker#408]
Go to https://www.dailymail.co.uk/, specifically 
https://www.dailymail.co.uk/ushome/index.html

pull open the source code and see your IP number right there as a Javascript variable:
PageCriteria.clientIP = '1.1.1.1';

Is there any mechanism in Canvas Blocker to block that?

**Comment by crssi** [comment]
Why would you need to block that?

Cheers

**Comment by Daisenki** [comment]
IP 1.1.1.1 is the DNS from Cloudflare, blocking that IP can break many websites, there is absolute no point to block it

**Comment by crssi** [comment]
@Daisenki 
I believe that the @arelkin has replaced his internet facing IP with `1.1.1.1` in the first post just as a sample. 😉

**Comment by arelkin** [comment]
@crssi - Isn't part of the point of this plugin to protect our privacy? Would not anonomyzing, obscuring or blocking our IPs be part of that?

@Daisenki - yes, 1.1.1.1 is just an example IP number.

**Comment by crssi** [comment]
Well yes, but your outgoing IP is already revealed, so it doesn't matter and tampering with would just make you more identifiable.
It is like I would call you over a phone where my CalledID would be shown on your screen and I would lie to you that I am calling from some another phone number. It is more than a useless since it also reveals to you that I am a liar.

**Comment by kkapsner** [comment]
If you want to hide your IP you have to use a VPN or TOR. The IP is a so basic part of the communication between your computer and the server that a web extension cannot do anything about it. It way out of the scope of it.

You need additional hardware infrastructure to be able to communicate with a server without the server obtaining your ip. BUT someone (the VPN provider or the entrance node of TOR) will know you IP. And usually (at least in IPv4 land - IPv6 is a different story, but as far as I know most traffic in the browser is v4...) an IP is not static as well. Your ISP simply controls if you have the same all the time or if it changes on a regular basis. Usually having a static IP is more expensive...

And actually it's debatable if an IP is private data.

PS: there is actually no JS functionality to obtain your public IP.
