### ISSUE TITLE
clicking 'ignore domain' replaces whitelist with ignorelist

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [kkapsner/CanvasBlocker#41]
when the canvas api is blocked on a page and i click 'ignore domain', it adds the website to the ignore list and then also replaces my whitelist with the ignore list. so i lose all my whitelist entries and both lists are now the same as each other

firefox 41.0.1
canvasblocker 0.2.0

**Comment by kkapsner** [comment]
Oh... I'm very sorry for this bug. I ran into it myself.

**Comment by berrythesoftwarecodeprogrammar** [comment]
thats fine :)
thanks for addressing both of my issues. new release is great
