### ISSUE TITLE
fingerprintjs still seems to get a constant fingerprint

### ISSUE THREAD

**Issue by ilikenwf** [kkapsner/CanvasBlocker#410]
I'm using canvasblocker, resistFingerprinting, and some other even more paranoid settings from the ghacks user.js file...

Despite this, fingerprintjs seems to be able to get a constant or near constant fingerprint from my browser.

https://fingerprintjs.com/demo

I'm not entirely sure if it is the canvas, but I would expect that with various configurations this hash should change every page load if I've not got "constant" set, correct?

**Comment by kkapsner** [comment]
If you use resistFingerprinting the canvas fingerprint will not change. But it will be the same to all TOR users and all other users that enabled it. See https://github.com/kkapsner/CanvasBlocker/issues/158 and https://github.com/ghacksuserjs/ghacks-user.js/issues/767 for further reading.

But I'm quite sure this page uses some sort of persistent storage to keep the ID. It does not change for me upon reload but if I use a private window it does (closing the private window and opening another one also changes it).

What do you get when you open the page in a private window?

**Comment by ilikenwf** [comment]
I get the same result all around...

I'm using some other addons but none of them should be affecting the canvas.

**Comment by ilikenwf** [comment]
...disabling resistFingerprinting has fixed the randomnness.

On the upshot I have most of the bases that resistFingerprinting covered between my user.js and other addons, as well as canvasblocker.

**Comment by Thorin-Oakenpants** [comment]
> I have most of the bases that resistFingerprinting covered

Not true :)  Firefox core code can (bugs aside) properly protect you, whereas extensions are limited. For example, you can bypass script injection via timing

**Comment by Thorin-Oakenpants** [comment]
OT: @kkapsner I haven't had time to test it, but see [here](https://webbrowsertools.com/) .. if you take the `UA` test and try methods `ii` and `v`

> ii `[aggressive] navigator.userAgent`: This method clones the "navigator" object exactly when page is about to render to prevent any external scripts from altering it later. It is pretty hard to bypass this method as the spoofer does not have enough time to asynchronously get the faked user-agent string at this point.

> v `[aggressive] iframe navigator.userAgent`: Same as method 2, however, uses a newly created sandboxed iframe to prevent any script from being able to manipulate the "navigator" object.

No idea what JS creating a "sandboxed" iframe means

**Comment by ilikenwf** [comment]
Having the master switch disabled seems to only affect a handful of
options not otherwise exposed to granular control - the script timing
mitigations are broken out in their own options it seems.

privacy.resistFingerprinting.reduceTimerPrecision.jitter

privacy.resistFingerprinting.reduceTimerPrecision.microseconds

I would argue the proof is in the pudding - having the option on, I have
a consistent fingerprint. Off with canvasblocker and my options, and
addons as they are, they can't get a consistent hash on me.

**Comment by Thorin-Oakenpants** [comment]
I don't think so. AFAIK for timing fingerprinting mitigations the RFP master switch must be on. Those prefs you're looking at were built in by tom as safeguards and for testing. I wouldn't play with them if I were you.

**Comment by ilikenwf** [comment]
I'm not playing with them, but they're on and have default values despite the main resistFingerprinting option being turned off...unless it disables the entire class of mitigations I'd argue there's little to worry about.

Considering that most fingerprinting is done using something like fingerprint.js, I would argue it is more important to avoid a consistent fingerprint than it is to do things the correct way until this issue is worked around and canvasblocker can randomize and coeexist with the resistFingerprinting option.

Most of what you see here is me spoofing, and I have RFP off... the canvas fingerprint is as it is because I'm spoofing it randomly instead of using an all white alpha channel, which if I recall is what the tor project does?

![image](https://user-images.githubusercontent.com/414778/69897214-f8545380-130d-11ea-9b9e-c9bc750dad7c.png)

**Comment by Thorin-Oakenpants** [comment]
but **they exist** and have (default) **values** <-- that's how prefs work

**Comment by kkapsner** [comment]
@ilikenwf great - then we found the source of the constant fingerprint. In that case all users of RFP should share the same fingerprint as you and you are harder to track within that crowd. My point in that discussion is that both approaches (having the fingerprint change all the time and sharing a fingerprint with a lot of other people - an analogy for the first would be to identify real people by the number of mouths they have and for the second one to do that by the number of seconds they are alive) are valid and will both protect you. I decided to go in CB with the "change always" way as it's easier to do and maintain.

You two can continue to discuss but as CB is out of the picture I will close the issue.

@Thorin-Oakenpants the UA test page reports exactly the same result for all methods for me (I have the UA changed via CB). As far as I know the methods are similar to the ones in https://canvasblocker.kkapsner.de/test/test.html - just something else was read.

A sandboxed iFrame is kind of protected agains changes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox

**Comment by Thorin-Oakenpants** [comment]
Ahh OK ... well, the dev of that page says "sandboxed iframe to prevent any script from being able to manipulate the navigator object" - but that's not the case then, is it?

And the other one, grabbing the properties as soon as possible seems plausible? I have the situation on android when grabbing screen metrics: the very first js file loaded, listed in the document head, which runs before the document has fully loaded, I am able to get the native droid screen measurements (i.e of an empty page). I might mod that to grab the ua string and output it to console, and see if CB can catch it.

**Comment by Thorin-Oakenpants** [comment]
> I might mod that to grab the ua string and output it to console, and see if CB can catch it.

Nah, doesn't work: but I was only testing file:// ... so maybe it's the internet latency?

**Comment by Thorin-Oakenpants** [comment]
Ahh .. yes, I can bypass it

**Comment by ilikenwf** [comment]
Most of my fingerprinting mitigations revolve around emulating tor browser, including the spoofed UA.

As such I can at best suggest that using "none - completely white" for the canvas with RFP enabled and spoofing a common resolution is the best option. Despite the results I'm still unique within 51,000 visitors, so I wonder if any of this is worth it or if some of my settings need to be further tuned.

Suggestions welcome:
![image](https://user-images.githubusercontent.com/414778/69904981-c5f63500-13a5-11ea-96bf-7c1dcf9bcd9d.png)
