### ISSUE TITLE
window.open attack vector

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#412]
Thanks @Thorin-Oakenpants for keeping me busy...

Vector can be seen in the fingerprinting test page when it's solved.

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/0.5.15-RC1

**Comment by Thorin-Oakenpants** [comment]
Yeah, that seems to work: obviously you're covering all the properties, not just the one I output for a test, right? Also, oscpu/buildID show undefined for the single test I did mimicking chrome browser

**Comment by kkapsner** [comment]
Sure. My test actually does not involve navigator but the canvas API (https://canvasblocker.kkapsner.de/test/test.html at the bottom).

**Comment by Thorin-Oakenpants** [comment]
Oh! :)

**Comment by kkapsner** [comment]
Yes - every protection was effected. That's why I want to release 0.5.15 as fast as possible.

**Comment by Thorin-Oakenpants** [comment]
I knew it affected nav.* and window.* ... but damn .. that's why I said "Oh!" ... I wonder how many extensions have expected things break this way

**Comment by kkapsner** [comment]
> I wonder how many extensions have expected things break this way

I haven't checked, but I guess not many.

But as the vector requires the user to click somewhere I think it's not that widely used.

**Comment by kkapsner** [comment]
Version 1.0 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.0
