### ISSUE TITLE
Have Gmail as a pinned tab, after restarting the browser, the page shows an error message

### ISSUE THREAD

**Issue by afgks** [kkapsner/CanvasBlocker#413]
To reproduce the problem: 
1. Login to Google, go to Gmail inbox or open [this](https://mail.google.com/mail/u/0/#inbox) link
2. Pin the tab or switch to the tab when you close Firefox (When you restart FF and restore session, Gmail will be the first tab to be loaded.)
3. The page won't load. An error message will be shown: "_We're sorry, but your Gmail account is temporarily unavailable. We apologise for the inconvenience and suggest trying again in a few minutes. You can view the G Suite Status Dashboard for the current status of the service._"

I have tested with a new Firefox profile with only CanvasBlocker installed. Same behaviour.

At the moment, you have to either reload the page every time you restart the browser, or whitelist the domain. 

## Your Environment
* CanvasBlocker Version used: 0.5.14
* Firefox version 72.0b1 64-bit (I can't remember if this bug started appearing in Firefox 70 or 71, but it wasn't new, I only realised today that it was the addon causing this error)
* Operating System and version: Windows 10 Pro
* Installed addons: None

## Your Settings
Default setting, untouched.

```
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "onedrive.live.com",
			"protectDOMRect": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {
		"blockMode": true
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 1000000,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{}",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1575431957302,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "12",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "dark",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5
}
```

**Comment by kkapsner** [comment]
Weird behaviour. If I only have this one tab pinned I can reproduce the issue. If I have a second tab then not.

Also I do not reproduce if I completely reset the CB settings. Really weird.

Please try if it helps to allow the domRect API for mail.google.com:
![image](https://user-images.githubusercontent.com/1105157/70184077-5fe01980-16e7-11ea-997c-3fe0e5fbc0ed.png)

**Comment by afgks** [comment]
Yes, allowing domRect API for mail.google.com solved the problem. 

It is strange that you don't encounter this bug with two pinned tabs, because I have more than two pinned tabs but I still encounter this bug.

**Comment by kkapsner** [comment]
My second tab was not pinned. When I pin it I can also reproduce it.

I think it's a weird thing that Firefox does when restoring the tabs. I see some weird logging there. At the moment I do not even have a starting point to solve the issue on the CB side.

But as google already knows who you are (you are logged in to gmail...) there is no benefit of protecting the DOMRect anyway. So I think I will simply add an exception for mail.google.com as well to the "convenience" preset (as it is for onedrive) and call this issue solved.
