### ISSUE TITLE
Add-on is detected in test

### ISSUE THREAD

**Issue by deonin** [kkapsner/CanvasBlocker#414]
Hey!
I dont remember but somewhere found website f.vision for test fingerprint. Im not sure in reliability of that but still. When i checked browser with your plugin i got next "Detected some salt in canvas output". Its happening only if i using "readout" protection but not with others. And in 1 of 10 cases website dont see any salt. Is it mean that sometimes your plugin generate good clean hash? If i set "minimal size of spoof" less than 70000 (but its not safe for expansion said in description) i get clean test without any errors.
Is it really bad? Can website add me in blacklist because of this issue?
And if yes can you do something with that?
Thanks.

**Comment by kkapsner** [comment]
The probability that CB produces a clean hash is very slim (if you have a canvas with 10 pixels the probability is 1/2^10 = 1/1024 - and with 10 pixels a fingerprint is kind of useless). And if the threshold for getting a "clean" test is 70000 the used canvas has that many pixels.

As I do not quite know how they detect the "salt" (what every they really mean by that) I do not know why it has a 10% rate to fail.

I don't think this is that bad. It would be better if CB would not be detectable but as it does change some things it always will be. I do not know of any anti-FB technique that is not detectable somehow.

In theory sites can handle you differently based on that. But I did not encounter it.

If you want you can use the "stealth" preset (and adjust it even more). It is designed to be less detectable.
