### ISSUE TITLE
A web page is displayed incorrectly and the page content is missing

### ISSUE THREAD

**Issue by assistdebug** [kkapsner/CanvasBlocker#415]
## Description

CB makes this page unable to display the comment area,only whitelist or disable can display normally:
http://coral.qq.com/4608804024

## Your Environment

* CanvasBlocker Version used: 0.5.14
* Firefox version: 64-bit
* Operating System and version: desktop
* Installed addons: CanvasBlocker

## Your Settings

default

**Comment by kkapsner** [comment]
This web page uses weird techniques...

**Comment by kkapsner** [comment]
Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/1.0-RC3

**Comment by assistdebug** [comment]
1.0-RC3 Tested works fine,Thanks kkapsner.

**Comment by kkapsner** [comment]
Great - I hope version 1.0 will be released soon. There were bigger code changes that I want to test in my daily usage for some days.

**Comment by kkapsner** [comment]
Version 1.0 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.0
