### ISSUE TITLE
Presets vs Default settings?

### ISSUE THREAD

**Issue by bitpixl** [kkapsner/CanvasBlocker#416]
Hi kkapsner,

Can you tell me how each presets affect privacy/security vs the default settings?
I'm using the default settings, with only "Block data URL pages" turned off as per Ghacks recommendation.

Is Convienent preset worse and Stealth better (but more taxing on the system)?

Just curious :)

Keep up the great work!

**Comment by kkapsner** [comment]
I would not say that one is better or worse. They have different use cases.

"Convenient" is more for set and forget. It tries not to bother you.

"Stealth" will bother you with worse performance on some sites. If you think that some pages will do something different when they detect that you are using CB you should use that. But I think too few people use CB to make it worth while for the "fingerprintgers" to implement a detection for it. (But I may be wrong.)

But as the preset page states: you can also apply multiple presets.

PS: I use complete custom settings.

**Comment by bitpixl** [comment]
Well yes, I get that, but I'm wondering how the presets compare to the default settings if you just added the addon to firefox. Those settings are nog like any of the presets, so it made me wonder if the default settings give better protection compared to "convienent" and or "stealth". My guess is that it's somewhere in between, but it's nice to get a comfirmation from the master self ;)

(And do you care to share your settings? ;) )

**Comment by kkapsner** [comment]
Yes, the default settings are kind of in the middle. Less convenient and less stealthy.

My settings are based on the default settings. These are the meaningful changes:
```
	"logLevel": 25,
	"urlSettings": [
		{
			"url": "^https://www\\.google\\.com/recaptcha/api2/(?:b?frame|anchor).*$",
			"protectWindow": false
		}
	],
	"minFakeSize": 10,
	"maxFakeSize": 1000000,
	"ignoredAPIs": {
		"domRect": true
	},
	"showCallingFile": true,
	"showCompleteCallingStack": true,
	"audioNoiseLevel": "maximal",
	"protectWindow": true,
	"protectNavigator": true,
	"navigatorDetails": {
		"windowManager": "Windows",
		"platform": "Win32",
		"platformDetails": "Windows NT 10.0; Win64; x64",
		"oscpu": "{platformDetails}",
		"appVersion": "5.0 ({windowManager})",
		"buildID": "20181001000000",
		"productSub": "20100101",
		"userAgent": "Mozilla/5.0 ({platformDetails}; rv:{firefoxVersion}) Gecko/20100101 Firefox/{firefoxVersion}",
		"firefoxVersion": "{real Firefox version}"
	},
	"displayAdvancedSettings": true,
	"theme": "dark"
```

**Comment by bitpixl** [comment]
@kkapsner thank you for clarifying and sharing your own custom config 👍 

My knowledge on web privacy is limited and I try to learn more as I go along.
Canvas fingerprinting seems to be a beast on it's own and for alot of settings I don't even know what they mean or do. As I don't know how to troubleshoot this addon if something would break, I'm hesitant changing from the default config. Does "Stealth" preset actually also increase fingerprint protection or only detection?.

Also: I wish you all the best for 2020 ;)

**Comment by kkapsner** [comment]
Actually "Stealth" decreases the fingerprint protection slightly in favour of detection. But in a negligible way.

Troubleshooting CB is quite simple for you: if something does not work just open an issue here with a reproduction scenario. The tricky part is then on me ;) 

Also: dito
