### ISSUE TITLE
CanvasBlocker breaks Braintree hosted fields when window API protected

### ISSUE THREAD

**Issue by kyz** [kkapsner/CanvasBlocker#417]
## Description
CanvasBlocker breaks all [Braintree hosted fields](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v3). This breaks a lot of e-commerce sites.

Example: Go to https://archive.org/donate/ , ensure credit cards are selected as payment method, click "Donate" button. This pops up a form for address and card details.

With Firefox 71.0 on Ubuntu 18.04.3 (both 64-bit), with enhanced tracking protection on, and with _no addons enabled_, this works fine. With the same setup, and _only CanvasBlocker addon enabled_, this stops working. It also works fine with all my addons enabled _except_ CanvasBlocker. So the problem is definitely CanvasBlocker, and not another addon, nor interactions between addons.

With CanvasBlocker enabled, and "protect window API" turned off, it works fine again. So the problem is further pinpointed - Braintree hosted fields need window.opener or window.name to work.

## Expected Behavior
Expected behaviour  is that the hosted fields work normally - the three fields at the bottom are Card number, MM / YY and CVC. Their labels should appear and they should be editable.

## Current Behavior
Current behaviour is that the hosted fields don't initialise. Their labels don't appear, they can't be edited.

Correspondingly, the console shows the error "TypeError: c[e.field] is not a function" at line 1 column 26035 of https://js.braintreegateway.com/web/3.50.1/js/hosted-fields.min.js

Pretty-printed in the debugger, it is this code, where e.field is the blank string:

            this._bus.on(N.FRAME_READY, function (e, t) {
              c[e.field](t)
            }),

Putting a breakpoint at this line, disabling CanvasBlocker, and reloading the page and opening the popup again, reveals it should be called three times and e.field should be "expirationDate", "number" and "cvv".

I have not gone through all 4000 lines of Braintree's code, but somehow CanvasBlocker results in these field values being stripped out and breaking the functionality.

All three fields are not regular form fields, but iframes on a third party host, for example the card number field looks like this:

    <iframe style="border: medium none; width: 100%; height: 100%; float: left;"
     src="https://assets.braintreegateway.com/web/3.50.1/html/hosted-fields-frame.min.html#a459ddde-d370-4588-bd14-ff5a58e4c31a"
     allowtransparency="true"
     scrolling="no"
     type="number"
     name="braintree-hosted-field-number"
     title="Secure Credit Card Frame - Credit Card Number"
     id="braintree-hosted-field-number" frameborder="0"></iframe>

Adding in the understanding that turning off protection for window.opener and window.name makes this work again, suggests that Braintree's hosted fields rely on accessing the iframe name to determine which field they should be.

## Possible Solution

I'd suggest adding Braintree's iframe URLs to the whitelist to be allowed to see window.name, by default. Something like this:

    ^https://assets\.braintreegateway\.com/.+/hosted-fields-frame(?:\.min)?\.html

It would have a similar rationale for why the Google reCaptcha URL is added when enabling the window API protection - it's an embedded iframe that web users would regularly see, it needs access to the window API, and it takes quite some time to track down that this is the source of the problem.

## Steps to Reproduce (for bugs)
See above.

Another example:

1. Go to https://www.cineworld.co.uk/
2. Go through all steps of booking a ticket, up to payment step. Choose to pay by card.
3. Watch as payment card step just doesn't load. Note in the top-right it says "Braintree"
4. Disable Canvas Blocker's window API protection and reload the page (resubmitting form), now payment card details appear. In this case, the hosted fields iframe is https://assets.braintreegateway.com/hosted-fields/2.15.7/hosted-fields-frame.html

## Context
I would like to engage in e-commerce.

Quite a number of websites use third-party merchant services (for example archive.org are using Stripe), and sites can pass on the burden of making their entire website PCI compliant, if they use Braintree's hosted fields so they never see any credit card details.

 ## Your Environment
* CanvasBlocker Version used: 0.5.14
* Firefox version incl. 32- or 64-bit: 71.0 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 18.04.3 (desktop, 64-bit)
* Installed addons: no others, see above

## Your Settings
The default settings, with window API protection turned on and say "Yes" to "This breaks reCaptcha, do you want to add that to the whitelist?"

**Comment by kkapsner** [comment]
Thanks for the detailed report. I can reproduce the issue and agree that we have to address that somehow.

I could add this to the whitelist for the windows API on demand, but actually there might be others. A different approach would be to allow the readout of `window.name` (braintree is using that and not the opener) in embedded window objects. It works for reCAPTCHA and braintree.

@Thorin-Oakenpants I think this could be an OK compromise as he name can only be set by the embedding window and will be lost when this window navigates to something different.

**Comment by Thorin-Oakenpants** [comment]
> I think this could be an OK compromise...

IANAExpert .. but sounds right to me: i.e restriction of cross origin sub-resources ?

The only problem I have with this sort of thing (whitelisting), is the slippery slope: if everyone starts abusing it, then it becomes problematic. The real solution is FPI - but that ticket has been open for 2+ years and it's tricky AF :)

**Comment by kkapsner** [comment]
Yes, whitelisting is slippery. Especially when it's not done by the user but by the software itself. That's why I do not want to add another entry in the whitelist.

Sure, FPI would be the real solution, but it would also have to have some sort of mechanism for this scenario (and reCAPTCHA).

@kyz: Please test https://github.com/kkapsner/CanvasBlocker/releases/tag/1.0-RC4

**Comment by Thorin-Oakenpants** [comment]
> but it would also have to have some sort of mechanism for this scenario

FPI already has issues where third parties are involved in some sort of login/permission flow (e.g using alice.com to log into bob.com) etc. There's a thing called [Dynamic FPI](https://bugzilla.mozilla.org/show_bug.cgi?id=1549587) which aims to solve all of this

**Comment by kkapsner** [comment]
Version 1.0 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.0
