### ISSUE TITLE
It is not compatible ?

### ISSUE THREAD

**Issue by jorg35** [kkapsner/CanvasBlocker#418]
It is not compatible with Waterfox 56 why?
so hard to do?

**Comment by kkapsner** [comment]
It should work for the most part and it should install (both the beta version [1.0RC4](https://github.com/kkapsner/CanvasBlocker/releases/tag/1.0-RC4) and [0.5.14](https://addons.mozilla.org/de/firefox/addon/canvasblocker/versions/)). Some APIs are missing so the protection is not as good.

Why are you asking?
Isn't Waterfox 56 outdated? As far as I know the latest version is Waterfox Classic 2019.12

**Comment by ltGuillaume** [comment]
New versioning system, but it basically still is Waterfox v56.3. With CanvasBlocker v1 just installed, I see several scripts are failing to load. For example, I cannot see any results on StartPage.com.

Console output differences between with and without CanvasBlocker enabled:
```
too much recursion[Learn More]  search:84:11279
	doPreIntercept/</<.get< moz-extension://cc0f0f34-fb74-470f-ad21-82700845fff0/lib/intercept.js:158:28
	doPreIntercept/</<.get< moz-extension://cc0f0f34-fb74-470f-ad21-82700845fff0/lib/intercept.js:159:36
	(...)
TypeError: window.debounce is not a function[Learn More]  search:179:1408
	[1092] https://www.startpage.com/sp/search:179:1408
	n https://www.startpage.com/sp/search:179:117
	[1091] https://www.startpage.com/sp/search:179:959
	n https://www.startpage.com/sp/search:179:117
	<anonymous> https://www.startpage.com/sp/search:179:914
	<anonymous> https://www.startpage.com/sp/search:179:14too much recursion[Learn More]  intercept.js:159:36
too much recursion[Learn More]  intercept.js:152:1
too much recursion[Learn More]  search:1090:9545
	doPreIntercept/</<.get< moz-extension://cc0f0f34-fb74-470f-ad21-82700845fff0/lib/intercept.js:159:36
	doPreIntercept/</<.get< moz-extension://cc0f0f34-fb74-470f-ad21-82700845fff0/lib/intercept.js:159:36
	(...)
TypeError: window.csaInit is not a function[Learn More]  search:1094:21
	<anonymous>
TypeError: s1Csa is undefined[Learn More]  search:1100:9
	<anonymous>
too much recursion[Learn More]  intercept.js:158:28
	doPreIntercept/</<.get< moz-extension://cc0f0f34-fb74-470f-ad21-82700845fff0/lib/intercept.js:159:36
	doPreIntercept/</<.get< moz-extension://cc0f0f34-fb74-470f-ad21-82700845fff0/lib/intercept.js:159:36
	(...)
too much recursion[Learn More]  util.js:41:7
TypeError: window.debounce is not a function[Learn More]  search:441:2374
	[1086]/<
TypeError: window.debounce is not a function[Learn More]  search:477:2385
	[1084]/<
```

Similarly, I cannot click buttons like "Comment" here on GitHub
```
too much recursion[Learn More]  combobox-nav.esm.js:29:23
```

**Comment by kkapsner** [comment]
Yes - you should only enable CanvasBlocker or CanvasBlocker-Beta. Since Firefox removed the beta feature (https://blog.mozilla.org/addons/2018/02/28/discontinuing-support-for-beta-versions/) I have to use two different ids. 

But your problem is solved now?

**Comment by ltGuillaume** [comment]
Yes!
