### ISSUE TITLE
Add Ability to Spoof Navigator Settings persistently per Container

### ISSUE THREAD

**Issue by ImCowboySibs** [kkapsner/CanvasBlocker#424]
I believe it would be useful to implement the ability to assign and spoof navigator properties per Container Tab(s) rather then the current function of spoofing the navigator properties browser wise, the reason this would be ideal is because it would be in line with the extensions current behavior/functionality to spoof fingerprint values on a per container basis persistently.

Thank you for developing this extension.

**Comment by kkapsner** [comment]
Good point.

This is a bigger change but doable.

**Comment by kkapsner** [comment]
Done in cc8ca147b0be8f009e8e381807f1f946e437f322 - please check the latest alpha version: https://canvasblocker.kkapsner.de/versions/
