### ISSUE TITLE
Canvas hash does not change when page is refreshed

### ISSUE THREAD

**Issue by Glenta** [kkapsner/CanvasBlocker#425]
## Description

After freshly installing Firefox 72.0.1 and installing CB, the canvas hash stays the same even though it is supposed to change when the page is refreshed.

## Expected Behavior

As said in the fifth bullet on the [Canvas Test](https://canvasblocker.kkapsner.de/test/test.html)
> upon page reload the hash changes

## Current Behavior

The hash stays the same upon refresh

## Steps to Reproduce (for bugs)

1.Freshly install Firefox 72.0.1 x64
2.Set Browser Privacy to Standard
3.Set Do Not Track to Always
4.Install CB with Stealth Preset
5.Visit [Canvas Test](https://canvasblocker.kkapsner.de/test/test.html) record hash and refresh page

Screen Recording of issue https://i.vgy.me/0kBOgB.mp4

## Your Environment

* CanvasBlocker Version used: 0.5.14
* Firefox version incl. 32- or 64-bit: 72.0.1 x64
* Operating System and version (desktop or mobile): Windows 10 Pro x64 Desktop
* Installed addons: CanvasBlocker

## Your Settings

	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "input",
	"minFakeSize": 10,
	"maxFakeSize": 0,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 3,
	"minColors": 3,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{\VALUES}",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1578541600149,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "23",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 0.5

**Comment by kkapsner** [comment]
With the stealth preset these hashes do not change (it's the `"rng": "persistent",` setting). I added a note in the test pages for that.

But to be sure that CB works fine you can check that the hash is different when you have CB enabled or disabled. Also you can check if they are different on https://canvasblocker2.kkapsner.de/test/ (just a different subdomain).

**Comment by kkapsner** [comment]
To elaborate a little bit more: the persistent rng stores the randomness that it used to alter the fingerprints on a domain basis so that a page does always get the same hash but this hash cannot be used to track you across different domains. So you can be tracked within a domain (which is also possible with cookies and which is often wanted as you want to stay logged in a page with a login) but as you browser to somewhere else.
