### ISSUE TITLE
Regression after 1.0 release

### ISSUE THREAD

**Issue by goose3228** [kkapsner/CanvasBlocker#429]
After 1.0 release extension throws exception on website vk.com.

## Description
Here is call stack:
`TypeError: can't redefine non-configurable property "top" : extension.js:63:35
exportFunctionWithName moz-extension://a5b4f0aa-33bf-4413-ab34-a784ab0056cc/lib/extension.js:63
interceptGetters moz-extension://a5b4f0aa-33bf-4413-ab34-a784ab0056cc/lib/intercept.js:377
forEach self-hosted:235
interceptGetters moz-extension://a5b4f0aa-33bf-4413-ab34-a784ab0056cc/lib/intercept.js:363
forEach self-hosted:235
interceptGetters moz-extension://a5b4f0aa-33bf-4413-ab34-a784ab0056cc/lib/intercept.js:357
intercept moz-extension://a5b4f0aa-33bf-4413-ab34-a784ab0056cc/lib/intercept.js:433
preIntercept moz-extension://a5b4f0aa-33bf-4413-ab34-a784ab0056cc/lib/intercept.js:191
interceptWindow moz-extension://a5b4f0aa-33bf-4413-ab34-a784ab0056cc/lib/frame.js:153
interceptAllFrames moz-extension://a5b4f0aa-33bf-4413-ab34-a784ab0056cc/lib/frame.js:163
set innerHTML moz-extension://a5b4f0aa-33bf-4413-ab34-a784ab0056cc/lib/iframeProtection.js:161
Lt https://vk.com/js/cmodules/bundles/common.a9065b590f515c024d66.js?ee6952ffc592d0a7eb9d:1`

I understand that extension may break some sites, but throwing like this seems to be an internal error.
## Expected Behavior
No errors in console and interruptions in website scripts.

## Current Behavior
Exception

## Possible Solution
Add try/catch at lib/extension.js:63

## Steps to Reproduce (for bugs)
Navigate to vk.com, open a few pages. I was unable to reproduce it without logging in though.

## Your Environment
* CanvasBlocker Version used: 1.0
* Firefox Nightly 74.0a1 (2020-01-18) (64-bit)
* Operating System and version (desktop or mobile): Arch Linux
* Installed addons: Reproducable without any other addons

## Your Settings
`{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {
		"displayAdvancedSettings": false
	},
	"expandStatus": {},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1579388845700,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "28",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}`

**Comment by kkapsner** [comment]
This is not good... can you please test with Firefox 72.0.1? I will try to reproduce your problem.

**Comment by kkapsner** [comment]
Can you also please increase the logging level to "verbose" and give me the entry right before the error?

**Comment by kkapsner** [comment]
The return value of `DOMRectReadOnly.prototype.__lookupGetter__("top").name` would also be interesting. It should be "get top" but it seems your build returns "top"...?

**Comment by kkapsner** [comment]
Also `Object.getOwnPropertyDescriptor(window, "top")` tells the that `top` is configurable in Firefox Nightly but not in stable... the confusion increases.

**Comment by kkapsner** [comment]
Please try with the latest beta version at https://canvasblocker.kkapsner.de/versions/ (you have to disable the "normal" CanvasBlocker).

**Comment by goose3228** [comment]
Seems to be working now, thanks!

**Comment by goose3228** [comment]
There is one more thing though - now it throws `TypeError: can't access property "error", logging is undefined` in the same place. Error seems to be only when log level is greater than 0, but i'm not sure for now, will be able to provide more details tomorrow.

**Comment by kkapsner** [comment]
Crap... please try the latest beta.

**Comment by goose3228** [comment]
Thanks again, now all is fine!

**Comment by kkapsner** [comment]
What's your log level? You should get an error message... I did not fix the actual problem... (not sure if I can fix it...)

**Comment by goose3228** [comment]
Well, i get error messages like `Wrong name specified for x Error: ""` with `FireFox bug: Need to change name in exportFunction from <empty string> (originally correct) to get x` following, but they are not exceptions and do not interrupt site scripts, so at least site does not break.
As for the rest - for me it does not seem to be something critical, i think you and firefox devs have other things to do.
May be i could fix it myself some day. For now it seems that site is messing up some browser API's.
A few days ago __lookupGetter__("top").name returned "get top" everywhere, but just "top" on this particular website, and only after some actions on page. I can't reproduce it now though, may be because of extension update (2020-01-23 version).

**Comment by kkapsner** [comment]
OK - then this page just does weird things... then I will close this issue
