### ISSUE TITLE
Better "ask" message 

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#43]
Selected: "Asking when using read API"
Currently it's a JavaScript message.
In my opinion it would be nicer if the message box could be more nice and include a "temporarily allow" button to allow it only for the current visit.
It should also display the question like all other blocking questions in Firefox below the address bar in an infobar.

IMHO Tor Browser does it quite good. It shows exactly the message I would also like to see by this addon.

**Edit:** Also note that buttons like "block always" or something like this would be nice.

**Comment by kkapsner** [comment]
There is a technical issue with changing the way the addon asks for permission: the execution of the script has to stop until the user decides on it. So this address bar notifications will not work the same way. I would suggest that you use the "fake" options as it is way more flexible and has nicer notifications.

PS: The "ask" option is only there for backwards compatiblity. I quite willing to remove it entirely.
PPS: Does the page reload if you allow the API in the Tor Browser?

**Comment by rugk** [comment]
> There is a technical issue with changing the way the addon asks for permission: the execution of the script has to stop until the user decides on it. So this address bar notifications will not work the same way. I would suggest that you use the "fake" options as it is way more flexible and has nicer notifications.

Okay.

>PPS: Does the page reload if you allow the API in the Tor Browser?

No. Not automatically.
