### ISSUE TITLE
Unable to download from https://www.catalog.update.microsoft.com when Window API protection enable

### ISSUE THREAD

**Issue by MetalAlch** [kkapsner/CanvasBlocker#434]
## Description
When Window API protection enable it is impossible to download something from https://www.catalog.update.microsoft.com. Even if you add the site to exception in Window API settings, downloads still not work. Only a complete disabling Window API protection helps. 
## Expected Behavior

A page with a download link should open.

## Current Behavior

Open a page with internal site error number and text "The website has encountered a problem" 

## Possible Solution

Now I can only work around this problem by completely disabling Window API protection when try downloading something.

## Steps to Reproduce (for bugs)

1:Open Firefox and check in CanvasBlocker settings if Window API protection enabled.
2: Exclude (whitelisting) https://www.catalog.update.microsoft.com in Window API section.
3: Open https://www.catalog.update.microsoft.com
4: In search field enter KB4528760 or ANY other update.
5: Try to download
6: You should see "The website has encountered a problem" page.

## Context

I completely disabled automatic downloading Window updates and manually download and install them from this site. But with Window API protection enabled i can`t. I want to understand why whitelisting this site not work too. This is webextension bug or am I incorrectly creating an exclude rule for this site.

## Your Environment

* CanvasBlocker Version used: 1.0
* Firefox version incl. 32- or 64-bit: Firefox 72.0.2 x64
* Operating System and version (desktop or mobile): Windows 10 x64 (1607,1809), Debian 10
* Installed addons: uBlock Origin, uMatrix, Decentraleyes, HTTPS Everywhere

## Your Settings
 
[CanvasBlocker-settings_2020-01-27_14-29-30.zip](https://github.com/kkapsner/CanvasBlocker/files/4117549/CanvasBlocker-settings_2020-01-27_14-29-30.zip)

**Comment by kkapsner** [comment]
I think your whitelisting is wrong. You have to use `www.catalog.update.microsoft.com` without the `https://`:
![image](https://user-images.githubusercontent.com/1105157/73194539-a1f86b00-412c-11ea-85e7-902c73e805f1.png)

With that it works for me.

**Comment by MetalAlch** [comment]
Forgive me. I'm a little confused. It was necessary to uncheck after adding a new rule. That was the problem. :)
 But i found new bug when add exclude rule:
[canvas.zip](https://github.com/kkapsner/CanvasBlocker/files/4118503/canvas.zip)

**Comment by Thorin-Oakenpants** [comment]
heh, this is the one site earthlng said he found rel=no-opener had issues with
 - `https://github.com/ghacksuserjs/ghacks-user.js/issues/860#issuecomment-566132112`

**Comment by kkapsner** [comment]
> Forgive me. I'm a little confused. It was necessary to uncheck after adding a new rule. That was the problem. :)

Yes, you have to uncheck. You are not setting an exception but you are setting the value of the setting for that domain.



> But i found real bug when add exclude rule:

We should add a seizure warning to CanvasBlocker ;) 
Jokes aside: this is a problem with the way Firefox embeds the options page in the UI. You should not be able to reproduce this issue if you open the options in a separate tab.
To solve this I would have to change the layout of the options... well... I knew that I had to do it at some point as it's not that good.

**Comment by kkapsner** [comment]
I think the layout change will not happen soon... and if it happens the embedded options page will have to go as the layout is too restrictive.

So to solve this issue I will just simply always open the options page in a new tab.

**Comment by kkapsner** [comment]
Version 1.2 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.2
