### ISSUE TITLE
Cosmetic: Incorrect year in name of Alpha builds

### ISSUE THREAD

**Issue by geeknik** [kkapsner/CanvasBlocker#435]
Just a minor cosmetic issue, though I'm sure you've noticed your build system is naming Alpha builds at https://canvasblocker.kkapsner.de/versions/ with the wrong year:  `canvasblocker_beta-1.1Alpha20192601-an+fx.xpi`

**Comment by kkapsner** [comment]
Ups... thanks for pointing this out. Will fix it in upcomming alpha builds.
