### ISSUE TITLE
Need access to privacy settings?

### ISSUE THREAD

**Issue by forteller** [kkapsner/CanvasBlocker#438]
Hi. Not sure where else to ask this.

Was alerted by Firefox that the latest update required access to my privacy settings. The release notes does not help me understand why or what exactly this entails. Hope you can clarify for me.

Thanks! And thank you for making this important tool.

**Comment by kkapsner** [comment]
The access to the privacy setting is needed to display the notice for privacy.resistFingerprinting. So it's not that important but unfortunately I cannot make it optional.

CB only reads that and does not write any privacy settings: https://github.com/kkapsner/CanvasBlocker/search?q=%22browser.privacy%22&unscoped_q=%22browser.privacy%22
