### ISSUE TITLE
LGTM security scanner results

### ISSUE THREAD

**Issue by powerman** [kkapsner/CanvasBlocker#439]
May worth looking at https://lgtm.com/projects/g/kkapsner/CanvasBlocker/ - I'm not a JS dev so it's hard to say how critical are found issues.

**Comment by kkapsner** [comment]
Thanks for the link. They are not critical (the first one cannot be triggered by "user-defined" code). But I will fix some of them.

**Comment by kkapsner** [comment]
Actually I did not even know CB was there. Did you integrate it there?

**Comment by powerman** [comment]
Not sure - it was already in my dashboard (together with few other projects) right after I've logged into LGTM for the first time. Probably it somehow detected my interest to these projects, but I suppose they was added by someone else.

**Comment by kkapsner** [comment]
OK - I don't mind it being there. Just curious.
