### ISSUE TITLE
Fake read API: Alternative method with using common values

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#44]
IMHO it would be nice to have an alternative method of the "fake readout API" which does not use random values, but rather use common values.
Because one disadvantage of a completely random value is that it reveals the fact *that you're using this addon*. And if this is detected websites may try to use workarounds around the readout API.
Even if that's not possible or not detected it is still a kind of tracking factor if there are many complete  Canvas hashes from <add another tracking factor like IP here>.
So if you can combine the fact "random Canvas hash" with another one you may be able to track the user, just because this addon is not as widespread, which means already the fact that you're using this addon may be "suspicious".
On the other hand there may be other methods to detect whether a particular addon is installed. I won't deny this and - if this addon was also affected - you cannot fix this. It's just that you do not have to provide more identifying values by something like this.

So what I would suggest is: Adding another "block mode" in the settings which uses common values instead of random ones. To do this get a database of common Canvas values. However there are different approaches how this mode may work and I'm suggesting them here all and leave it up to discussion what to use: The mode should... (`RCOV` = *r*andomly *c*hoose *o*ne common *v*alue [out of a list of common values])
* RCOV and use one per Canvas access (even if it should read multiple times on a website)
* RCOV and use one per site visit
* RCOV and use them for a pre-defined time for all sites and switch it later (1h or so)
* RCOV and use it for the current browser session (maybe that's not such a good idea, because it is too much bound to a event which can occur at any time [a browser may be opened very long or very short] and you can possibly track whether the user closed the browser)
* RCOV at the first installation of the addon and use it until the addon is uninstalled (possibly provide a update to choose another value)
* hard-code one very common value and use it for all installations

PS:
1. it also breaks test like https://amiunique.org/ because obviously they report you're unique - which is true. It's just that this uniqueness is temporarily.
2. https://www.browserleaks.com/canvas has a database of common Canvas values.

**Comment by kkapsner** [comment]
This is not as simple as you might think:

First you have sightly different fingerprinting schemes/texts/etc. on different sites. So one should have to get a database of all these and then detect them.
And second: the code does not have to return the hashes (as browserleaks has a database of - but see first point) but the actual image. This is way too much data.
Lastly don't I see a way to implement the determination, which dataset to use, in a way that is not super slow.
