### ISSUE TITLE
Breaks login on id.sonyentertainmentnetwork.com while in Private Browsing mode

### ISSUE THREAD

**Issue by anden11** [kkapsner/CanvasBlocker#440]
Cannot sign in to my PSN account when CanvasBlocker is enabled

## Description
Having the plugin enabled gives an error like
"18.a60d655f.1580668003.xxxxxx" but when the plugin is disabled, sign-in works fine.

## Expected Behavior
Sign-in should work

## Current Behavior
Sign-in does not work

## Steps to Reproduce (for bugs)

1. Go to https://store.playstation.com
2. Press Sign In (button in the upper right corner of the site)
3. Enter user name/password
4. Press Sign In

If testing multiple times, make sure to restart the private browsing session before each sign-in.
I think the log-in page performs additional checks that CanvasBlocker breaks, but after one successful sign-in you seem to get a cookie that allows you to skip this check the next time, restarting private browsing should avoid confusion with that.

## Your Environment

* CanvasBlocker Version 1.1
* Firefox version 72.0.2 (64-bit)
* Ubuntu Desktop 16.04.6 LTS

## Your Settings
Settings should be default, didn't change anything.

**Comment by crssi** [comment]
Unckeck protect screen api and try again.

**Comment by kkapsner** [comment]
This page is completely broken for me on a fresh profile without any extension...

As far as I see they use screen and DOMRect API - please check if whitelisting these for this page helps

**Comment by anden11** [comment]
For whatever reason, this problem no longer happens to me, maybe something got updated/fixed?

**Comment by kkapsner** [comment]
OK - I guess they changed something. CB was not updated.

Thanks for letting me know.
