### ISSUE TITLE
New permissions requested - modify privacy settings

### ISSUE THREAD

**Issue by becarefulwithmath** [kkapsner/CanvasBlocker#442]
New permissions requested - to modify privacy settings. Is it necessary?

Environment
* CanvasBlocker Version used: 1.0
* Firefox version 72.0.2 (64-bit)
* Operating System and version (desktop Win 10):

**Comment by kkapsner** [comment]
Duplicate to #438 so I will just copy my answer from there (it's not necessary for the core functionality):
The access to the privacy setting is needed to display the notice for privacy.resistFingerprinting. So it's not that important but unfortunately I cannot make it optional.

CB only reads that and does not write any privacy settings: https://github.com/kkapsner/CanvasBlocker/search?q=%22browser.privacy%22&unscoped_q=%22browser.privacy%22
