### ISSUE TITLE
[Feature request] Always open settings on a new tab

### ISSUE THREAD

**Issue by dmlemos** [kkapsner/CanvasBlocker#447]
Provide an option to open settings on a separate tab.

## Description
Every time sites have to be whitelisted, it takes more time personally because I have to do one more click.
For people who prefer working with the settings on a separate tab, makes sense to do that by default.

## Expected Behavior
Settings to always open on a tab, as it is much easier to work with.

## Current Behavior
Settings always open on the small contained extension pre-defined screen.

## Possible Solution
Would prefer to open settings in a tab by default, but an option to do that is enough.

**Comment by kkapsner** [comment]
There is already a way to open the options page in a new tab:
![image](https://user-images.githubusercontent.com/1105157/75587855-b60af180-5a77-11ea-924c-04993b6f92d2.png)
Also if you search in the browser action it will open a new tab:
![image](https://user-images.githubusercontent.com/1105157/75587941-e81c5380-5a77-11ea-8173-9b85f5f21418.png)

BUUUUUT the embedded options page is very limited in space and therefore prevented me to experiment with better UI solutions for that page. Therefore in the next version CB will always open the options in a separate tab: 0f1aa1cc32c0d46d1707b9b49a3bac1de52e1fc3

**Comment by dmlemos** [comment]
Great. Thank you

**Comment by kkapsner** [comment]
Version 1.2 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.2
