### ISSUE TITLE
Protect measureText (TextMetrics)

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#448]
measureText (TextMetrics) can be used to validate DOMRect values. Therefore we must protect it as well.

**Comment by kkapsner** [comment]
@Thorin-Oakenpants: please check out the latest alpha version with your test.

**Comment by Thorin-Oakenpants** [comment]
you can test it yourself - it's all in TZP already

**Comment by kkapsner** [comment]
Great - did not know it was already there.

Weird that I get zero differences in TZP but 6 here: https://canvasblocker.kkapsner.de/test/textMetricsTest.html

**Comment by Thorin-Oakenpants** [comment]
OK, installed latest alpha

no CB (or both off)
- 5/31 diffs, hashes are stable

both on (textM + domR)
- counts = `5/31` as per previous tests as if CB wasn't enabled
   - the actual differences change per reload, but the counts are the same
- the hash for both textM and domR change with each page reload

one on, one off
- counts = `22/31` as per previous tests
- the applicable on protection hash changes

Seems pretty solid to me.

----

Weird that I get zero differences in TZP but 6 here

That sounds like one char x 6 styles. Are you using divs and spans? Look at my code. I know you're not measuring offset* - but dcf found that the span height didn't change wven when the div around it did, or something

As I added getBoundingClientRect, I found I had to use the reverse

And then, just to mess with my head, with getClientRects, I had to do the opposite to bounding

```
			// offset: w=span h=div
			// bounding: w=div h=span
			// client: w=span, h=div
```

**Comment by Thorin-Oakenpants** [comment]
**CB Tests**

no protection
- 20 of 258

both protected
- 15 of 258

one protected but not the other
- 169 of 258

hmmm 20 vs 15 - that's a weird diff. Is this diff metric the right way to analyze this (i.e your patch)

**Comment by kkapsner** [comment]
It's u+007F and measureText that is different - my <canvas> was not inserted in the DOM. When I insert it I also get 0 diffs - little bit weird but now this is fixed.

**Comment by Thorin-Oakenpants** [comment]
^^ so what was the issue? what stopped it being added? I'm confused. Also ...

you
```js
const char = String.fromCodePoint(charCodePoint);
```

but dcf wrote a function because... "String.fromCodePoint isn't supported"
```js
	// String.fromCharCode doesn't support code points outside the BMP (it treats them as mod 0x10000)
	// String.fromCodePoint isn't supported.
	// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode
	// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint

function get_str_from_codepoint(n) {
	if (n <= 0xffff) {
		return String.fromCharCode(n)
	} else {
		n -= 0x10000
		return String.fromCharCode(0xd800 + (n >> 10), 0xdc00 + (n % 0x400))
	}
}
```

but it probably doesn't matter for us (I'm using his function) - he was testing tens of thousands of these chars to find a small set that provided entropy, and IDK much about this stuff, but seems like we're not affected ??

**Comment by kkapsner** [comment]
The issue was that I created the canvas via script and did not insert it to the DOM - now it's inserted (dd6fbc6c1f2d7a945d7cc52395299fdccc4bf3ed) and it works fine.

`String.fromCodePoint` works fine for me and is supported in Firefox since FF 29 - it's not supported in IE but I do not care about that at all.

**Comment by Thorin-Oakenpants** [comment]
that makes sense - https://www.bamsoftware.com/talks/fc15-fontfp/fontfp.html is Jan 2015, so the work was done prior to that: first FF release in 2014 was 27, but I guess dcf was testing all browsers and his solution made it universal

I could probably clean my code up to remove that function, but I still wonder if the "outside the BMP" issue still exists (and down the track I may use stuff "outside the BMP")

**Comment by kkapsner** [comment]
The "outside the BMP" is still true for `String.fromCharCode`. That's the reason `String.fromCodePoint` exists.

**Comment by kkapsner** [comment]
Version 1.2 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.2
