### ISSUE TITLE
WebGL protection?

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#45]
According to [amiunique.org](https://amiunique.org/faq) you can also use WebGL similar to Canvas to track a user.

It would be great if this Blocker could also help to block such tracking attempts.

**Comment by kkapsner** [comment]
WebGL should already be dealt with.

**Comment by rugk** [comment]
Oh really?
So what about adding this information to the Readme/addons page description and so on so that users know this does not only block Canvas, but also WebGL?

**Comment by kkapsner** [comment]
WebGL is a part of the canvas-API. But you're right: a less technical user might not know that and get confused.
