### ISSUE TITLE
Conflict with  Privacy Badger

### ISSUE THREAD

**Issue by Shadow-of-Colossus** [kkapsner/CanvasBlocker#452]
I have a conflict between Privacy Badger and CanvasBlocker when starting FF or restarting with my restart_firefox.uc.js script, it stops at loading ex: google.com (home page), I press F5 then it loads. If I disable PB for that page loads normallly but if different page on restart, doesn't load normally 90% of the time.

## Current Behavior
Page should load on start up withourt F5 reload, 

## Steps to Reproduce (for bugs)
Try both addons together.

## Your Environment
CanvasBlocker 1.1 Firefox 72, Win 7 64bit

## Your Settings

{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1584484691789,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "color",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "4",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "colorful",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment]
I think it's the same issue than #388. I'm not able to reproduce this problem in FF 74 any more.

So please try the following things to solve this issue:
* update Firefox to the latest version
* disable CanvasBlocker and reenable it

**Comment by Shadow-of-Colossus** [comment]
I disabled PB's "Send websites the "Do Not Track" signal" and the instances of pages stalling on load dropped dramatically, like 10% of the time instead of the 90%

**Comment by kkapsner** [comment]
OK - if you have some indication that it's a CB bug please report back here and I will reopen this issue.
