### ISSUE TITLE
TextMetrics API problem

### ISSUE THREAD

**Issue by one-way-ticket** [kkapsner/CanvasBlocker#453]
## Description

I have problem with new feature "TextMetrics" in CB 1.2 (Firefox ESR 68.6 x32).
I check on here: https://canvasblocker.kkapsner.de/test/textMetricsTest.html
Result:
1. "the hashes are different to the hashes when CanvasBlocker is disabled" - ok, worked.
2. "the number of differences stays the same when CanvasBlocker is disabled" - ok, always "0 from 258". CB is disabled & CB is enabled.
3. "upon page reload the hashes change" - does not work. The hashes does not change after reload page (F5). Always the same value.

Also i checked here : https://browserleaks.com/fonts
Result:
Always "130 fonts and 114 unique metrics found in the list of 512 fonts"
Always the same value "Fingerprint". It does not change after reloading the page.

## Expected Behavior

After reloading page the hashes must be a changed.
## Current Behavior

After reloading page the hashes does not a changed.
## Steps to Reproduce (for bugs)

1. install latest FF ESR 68.6 x32 in Win7 Pro x32.
2. install CB 1.2.
3. Repeatedly reload page on https://canvasblocker.kkapsner.de/test/textMetricsTest.html
4. Repeatedly reload page on https://browserleaks.com/fonts

## Context

Fresh install Firefox. No other addons & plugins.

## Your Environment

* CanvasBlocker Version used: 1.2
* Firefox version incl. 32- or 64-bit: Firefox ESR 68.6 x32
* Operating System and version (desktop or mobile): desktop Win7 Pro x32.
* Installed addons: no other addons.
privacy.resistFingerprinting -  any value (is not important).
## Your Settings

{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"historyLengthThreshold": true,
		"protectTextMetrics": true,
		"fakeMinimalScreenSize": true,
		"protectScreen": true
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1584517151178,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "11",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "default",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment]
Thank you for testing. In Firefox ESR 68.6 the TextMetric does only report integer values. But CB only fakes in the decimal places and does not touch integers (it would make CB very detectable). So the hashes always stay the same.

But the integer values do not offer a great fingerprinting potential and therefore this FF 68 is less trackable than FF 74 in that regard. So the behaviour should be no problem.

I will update the text in the test page.

**Comment by kkapsner** [comment]
One additional word to font fingerprinting: CB does not protect from that (#200)

**Comment by reallyuniquename** [comment]
@kkapsner 
>Firefox ESR 68.6 the TextMetric does only report integer values. But CB only fakes in the decimal places and does not touch integers (it would make CB very detectable). So the hashes always stay the same.

How do I determine if TextMetric reports just integers on an arbitrary browser?

https://github.com/kkapsner/CanvasBlocker/blob/6f5cfc1080feca6d71bdf9931192569587188ebc/test/textMetricsTest.js#L88-L91
I can dump `propertyData[property]` here. If it's mostly integers and a few float values with two digits after decimal point, is this it? Not precise enough for fingerprinting?

**Comment by kkapsner** [comment]
The "DOMRect integer factor" determines what fraction of an integer is treated as an integer. By default a quarter of a pixel is not faked. This done to prevent the detection of CB.

So if you only have .25 .5 and .75 as the digits after the decimal point nothing should  be faked.

These values can be used for fingerprinting. But not very efficient and being detected can be fingerprinted very effective. So you should be fine.
