### ISSUE TITLE
Data URL pages workaround

### ISSUE THREAD

**Issue by corford** [kkapsner/CanvasBlocker#456]
If I've understood the bug referenced in the tooltip for blocking Data URL pages (https://bugzilla.mozilla.org/show_bug.cgi?id=1475831 ), would CanvasBlocker be able to successfully inject its content scripts into Data URL loaded iframes if I disable `security.data_uri.unique_opaque_origin` (in about:config)?

Just wondering if above is a viable alternative to blocking data URL pages completely.

**Comment by kkapsner** [comment]
As far as I see this is an alternative (according to my test page: https://canvasblocker.kkapsner.de/test/dataUrlTest.php). But actually I do not know if this flag opens a different security issue. The original bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1324406) is not very clear why this is in the specs.

... reading a little bit in https://github.com/whatwg/html/issues/1753 is seems that this flag can introduce XSS problems. So I would advice not to use it.
