### ISSUE TITLE
CanvasBlocker 1.2 won't install on Firefox 60.9.0

### ISSUE THREAD

**Issue by Just-me-ghacks** [kkapsner/CanvasBlocker#460]
> Version 1.2
> Released Mar 17, 2020 - 313.97 KB
> Works with firefox 56.0 and later

Is it just me or CanvasBlocker 1.2 can't be installed on Firefox 60.9.0?

**Comment by kkapsner** [comment]
It should work. Actually I only test three Firefox versions: Firefox ESR (currently 68.6.1), normal Firefox and Firefox nightly. I bump down the compatibility down to 56 to support Waterfox Classic (which is based on FF 56) and there it works fine.

What are the error messages when you try to install it?

PS: Why are you using such an outdated Firefox?

**Comment by Just-me-ghacks** [comment]
_Unplug the network cable / block Firefox with firewall_

**CanvasBlocker 1.2**

about:addons >> Install Add-on From File...

The error message is:
> CanvasBlocker could not be installed because it is not compatible with Firefox 60.9.0.

CanvasBlocker 0.5.14, 0.5.10, 0.5.8 install just fine.

CanvasBlocker 1.2 could be installed on Firefox 60.9.0 if you allow it to access Internet DURING the installation. Go figure... :)

Firefox 60.9.0 is the previous ESR and while it's potentially less secure than the latest version, I like it better (in terms of usability/performance/privacy)

Keep up the good work, **kkapsner**!

**Comment by kkapsner** [comment]
> CanvasBlocker 1.2 could be installed on Firefox 60.9.0 if you allow it to access Internet DURING the installation. Go figure... :)

Yes, this is to be expected. The manifest specifies a minimum version of what I tested: https://github.com/kkapsner/CanvasBlocker/blob/master/manifest.json#L103

Only at AMO the version is bumped down to 56. So the browser needs a connection to AMO to get this change.
