### ISSUE TITLE
Crash in pinterest web

### ISSUE THREAD

**Issue by Iquaridys** [kkapsner/CanvasBlocker#461]
hi 
cant you try it in pinterest web ?
when i try on CanvasBlocker Pinterest Web cant run well / crash even show blank or no image
when i try disable CanvasBLock Pinterest Web run normal

**Comment by Iquaridys** [comment]
when on pinterest homefeed, if it runs normally it should be able to load / display the image when it scrolls down, but if I turn on CanvasBlocker it can't display the image.

**Comment by kkapsner** [comment]
Unfortunately I cannot test this as the registration for pinterest is not working at the moment.

But we can still try to narrow it down:
First disable the data-URL protection (you have to enable the expert mode first) and see if that helps:
![grafik](https://user-images.githubusercontent.com/1105157/78424502-57d0c000-766e-11ea-91c3-baef3b73dac9.png)

Secondly please disable all the API protections and enable them back one after the other to see which causes the problem.

**Comment by kkapsner** [comment]
I'm not able to reproduce your problem. What are your settings?

**Comment by kkapsner** [comment]
Almost a month without an answer. So I will assume the problem is gone.

If it's still present please answer my question and I will reopen the issue.
