### ISSUE TITLE
TimeZone and time offset spoofing

### ISSUE THREAD

**Issue by hotx** [kkapsner/CanvasBlocker#464]
Is it possible to add Timezone and time offset spoofing?

**Comment by kkapsner** [comment]
It is possible but very complex to get everything consistent: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
Especially the string functions.

I'm not sure if it's worth the effort. What's your use case?

**Comment by hotx** [comment]
I see.

I'm testing client-server behavior with different TZ in my project so I'm working with -no-remote flag with few browsers running.

**Comment by kkapsner** [comment]
All the set.. and get... functions that only return numbers are quite straight forward. But something like `parse` is tough - I would have to build my own parser to know how to fake that correctly.
