### ISSUE TITLE
Canvasblocker preventing RFP/letterboxing from spoofing screen size

### ISSUE THREAD

**Issue by bapweb-gh** [kkapsner/CanvasBlocker#465]
## Description
Without CanvasBlocker installed, activating RFP/letterboxing means websites can't see your real screen resolution, but when CanvasBlocker is installed (and javascript is enabled) the real screen resolution is detected.

## Expected Behavior
Test sites such as browserleaks.com should report the screen size as the letterbox dimensions (e.g 1300x600) when firefox is configured accordingly. CanvasBlocker (as far as I know) should not interfere with that.

## Current Behavior
Test sites such as browserleaks.com reveal the true screen size (e.g 1366x768) with CanvasBlocker enabled, but report the spoofed size with it disabled (and no other changes).
One exception to this is with javascript disabled, where the expected behaviour is followed.

## Steps to Reproduce
1. Create a new firefox profile, open it maximised
    - [browserleaks.com](https://browserleaks.com/javascript) shows an accurate screen resolution
2. In about:config set to true:
privacy.resistFingerprinting
privacy.resistFingerprinting.letterboxing
    - [browserleaks.com](https://browserleaks.com/javascript) shows letterboxed resolution
3. Install CanvasBlocker from AMO
    - [browserleaks.com](https://browserleaks.com/javascript) shows an accurate screen resolution again

Extra info:
* A different test site, [deviceinfo.me](https://www.deviceinfo.me) can detect screen resolutions without javascript enabled.
  - With javascript disabled, it shows the spoofed resolution whether CanvasBlocker is installed or not
  - With javascript enabled, it behaves as browserleaks.com described above

## Your Environment
* CanvasBlocker Version used: 1.2 (maybe 1.1, I can't remember when I first noticed the problem before isolating it)
* Firefox version incl. 32- or 64-bit: 64-bit, v74 and v75
* Operating System and version (desktop or mobile): Arch Linux, but using firefox from mozilla.org, not a package
* Installed addons: only CanvasBlocker (see steps to reproduce)

## Your Settings
Settings are completely default (see steps to reproduce)

**Comment by kkapsner** [comment]
This is to be expected. CB takes the inner dimensions of the window and then reports the next bigger common screen resolution (https://github.com/kkapsner/CanvasBlocker/blob/master/lib/modifiedScreenAPI.js#L42) that it fits in. If you want the letterboxing to apply (actually I'm kind of sceptical if it helps against fingerprinting) you have to disable the screen API protection or "Fake minimal screen size"
![Uploading image.png…]()

PS: screen protection was introduced in 1.0
