### ISSUE TITLE
Pale Moon Support ver. Legacy 0.2

### ISSUE THREAD

**Issue by moceletsor** [kkapsner/CanvasBlocker#466]
There are only **persistent** and **not persistent** random number generator options on CanvasBlocker Legacy 0.2 for Pale Moon. Would you add the **constant** random number generator option as you did for FireFox addon, please. Thank you.

**Comment by kkapsner** [comment]
You are talking to the wrong person. I do not maintain CanvasBlocker Legacy. @Feodor2 does.

I did not find their repository so I cannot link directly to it.

But as far as I see the code for the constant random number generator is already included (also the white one) and only the setting definition in package.json (and the locale) has to be updated.
