### ISSUE TITLE
Add protection for offscreen canvas

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#467]
## Description
As far as I see the conversation in https://bugzilla.mozilla.org/show_bug.cgi?id=1390089 OffscreenCanvas will not be behind a preference flag in the near future.

## Expected Behavior
CanvasBlocker should protect it to prevent fingerprint leaks.

## Current Behavior
Not jest tested (to create the test is part of this issue), but I think there are some leaks.

**Comment by Thorin-Oakenpants** [comment]
well, the current pref is `gfx.offscreencanvas.enabled` .. so when that goes, you'll know for sure :)

PS: don't forget TZP when you update the tests
