### ISSUE TITLE
Privacy Badger compatibility

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#47]
After using [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker) a bit I discovered that it also reported Canvas reads (also readouts) on Firefox error pages. Looking at the stack trace I saw this was caused by [PrivacyBadger](https://github.com/EFForg/privacybadgerfirefox).

I do not know who can fix this better, but it would be nice to have some solution here.

```
about:certerror?e=nssBadCert&u=https%3A//self-signed.badssl.com/&c=windows-1252&f=regular&d=self-signed.badssl.com%20verwendet%20ein%20ung%C3%BCltiges%20Sicherheitszertifikat.%0A%0ADem%20Zertifikat%20wird%20nicht%20vertraut%2C%20weil%20es%20vom%20Aussteller%20selbst%20signiert%20wurde.%0A%0A%28Fehlercode%3A%20sec_error_unknown_issuer%29%0A Zeile 131 Spalte 1
	about:certerror?e=nssBadCert&u=https%3A//self-signed.badssl.com/&c=windows-1252&f=regular&d=self-signed.badssl.com%20verwendet%20ein%20ung%C3%BCltiges%20Sicherheitszertifikat.%0A%0ADem%20Zertifikat%20wird%20nicht%20vertraut%2C%20weil%20es%20vom%20Aussteller%20selbst%20signiert%20wurde.%0A%0A%28Fehlercode%3A%20sec_error_unknown_issuer%29%0A Zeile 187 Spalte 5
	about:certerror?e=nssBadCert&u=https%3A//self-signed.badssl.com/&c=windows-1252&f=regular&d=self-signed.badssl.com%20verwendet%20ein%20ung%C3%BCltiges%20Sicherheitszertifikat.%0A%0ADem%20Zertifikat%20wird%20nicht%20vertraut%2C%20weil%20es%20vom%20Aussteller%20selbst%20signiert%20wurde.%0A%0A%28Fehlercode%3A%20sec_error_unknown_issuer%29%0A Zeile 1 Spalte 2
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-mnnxcxisbpnsxq-at-jetpack/privacybadger/data/fingerprinting.js Zeile 231 Spalte 3
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-mnnxcxisbpnsxq-at-jetpack/privacybadger/data/fingerprinting.js Zeile 243 Spalte 1
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js Zeile 66 Spalte 12
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/sandbox.js Zeile 320 Spalte 9
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/sandbox.js Zeile 281 Spalte 1
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/heritage.js Zeile 146 Spalte 23
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker-child.js Zeile 52 Spalte 20
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/heritage.js Zeile 146 Spalte 23
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/page-mod.js Zeile 157 Spalte 16
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/page-mod.js Zeile 190 Spalte 5
	resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/page-mod.js Zeile 122 Spalte 7
```

Test site: https://self-signed.badssl.com
Firefox 42.0
CanvasBlocker 0.2.1
Privacy Badger 1.0.3

Also reported on PrivacyBadger: https://github.com/EFForg/privacybadgerfirefox/issues/462

**Comment by orzechow** [comment]
How about the performance impact of this issue? Is it noteworthy actually?

EFF won't fix the issue on their side, so you it looks like we can only hope for CanvasBlocker to ignore PrivacyBadgers injection.

**Comment by rugk** [comment]
> EFF won't fix the issue on their side, so you it looks like we can only hope for CanvasBlocker to ignore PrivacyBadgers injection.

Yes, a exclusion in this extension would be nice.
I think the most bad consequence of this issue is not a performance impact, but rather that you get questions for every site you visit when you've selected to ask for Canvas.

**Comment by kkapsner** [comment]
Hm... to be honest I think this issue would be easier to solve on the other side.
The only thing I could offer would be a white list that works on the calling stack and not on the url...

**Comment by rugk** [comment]
No matter how it works an exclusion/exception would be nice... :wink: 

But if you have an idea how they can fix it please [comment in the issue](https://github.com/EFForg/privacybadgerfirefox/issues/462) - at least if your suggestion is not "remove this canvas!" (:wink:) as they have reasons to do this.

**Comment by kkapsner** [comment]
The new branch https://github.com/kkapsner/CanvasBlocker/tree/stackList has now a option to enable a white list that operates on the calling stack. The content of this list has to be well formated JSON.

In this case you should enter something like
```
[{"url": "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-mnnxcxisbpnsxq-at-jetpack/privacybadger/data/fingerprinting.js", "line": 231, "column": 3}]
```
You can also omit the line and column if you want to allow the complete script...

Please download the xpi from this new branch and test if it works for you. (Since it's not signed you will have to disable xpinstall.signatures.required for the test.)

**Comment by orzechow** [comment]
Very nice! It works for me, but I had to change the filter rule to:

    [{"url": "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-mnnxcxisbpnsxq-eff-at-jetpack/data/fingerprinting.js"}]

No idea, why this `/privacybadger` path is missing in the resource url, but it seems that's the format for all my add-on scripts.
Thanks for the quick fix! Hoping for an official signed version ;)

**Comment by orzechow** [comment]
It would be nice to add a suggestion for this rule within the settings view - for less experienced users.

**Comment by rugk** [comment]
[**@orzechow**](https://github.com/orzechow) commented on [1. Jan. 2016, 04:05 MEZ](https://github.com/kkapsner/CanvasBlocker/issues/47#issuecomment-168279150 "2016-01-01T03:05:26Z - Replied by Github Comment Enhancer"):
> It would be nice to add a suggestion for this rule within the settings view - for less experienced users.

Indeed. Possibly the extension should display a note/warning if it detects that Privacy Badger is installed (if this is possible) and suggest this exclusion.

**Comment by kkapsner** [comment]
This new feature is in version 0.2.2

**Comment by rugk** [comment]
Thanks. @orzechow exclusion works.
However what about just excluding `resource://` generally? (As an option for not so techy users who don't want to look for such "complicated" JSON snippets as exclusions)

I mean if you have a local resource (such as an addon) installed which tracks you you already lost. This addon should only protect against tracking of websites/external scripts.
Or do you see any issues with such an approach?

**Comment by kkapsner** [comment]
The JSON is necessary because I wanted to be able to allow only specific functionality not only a complete JS-file. So if you use this whitelist on a real website that only provides one big JS-file that also does the fingerprinting you can allow only the parts you want.

To allow resources completely has two drapbacks:
1. It requires to enable the script whitelist which creates a big overhead.
2. An addon could offer some API for websites which is per se not malicous (does not have to be related in any way to canvas). Now a bad website could manage to get this API in the stack of the canvas-API call and it would be allowed.

**Comment by rugk** [comment]
> 2. An addon could offer some API for websites which is per se not malicous (does not have to be related in any way to canvas). Now a bad website could manage to get this API in the stack of the canvas-API call and it would be allowed.

Okay this is a good reason for not allowing `resource://` generally.
