### ISSUE TITLE
Please add new protection Font Fingerprint

### ISSUE THREAD

**Issue by mookuk** [kkapsner/CanvasBlocker#470]
Please add new protection Font Fingerprint on CanvasBlocker.
example:
https://addons.mozilla.org/ru/firefox/addon/font-fingerprint-defender/
Only persistent session and not  "renews" it every time you visit a website or reload a page.
If that's all right.

**Comment by kkapsner** [comment]
Find my opinion of this addon in https://github.com/kkapsner/CanvasBlocker/issues/200#issuecomment-578158039
This older issue shows my decision (and how I came to it) on protection font fingerprinting.

TLDR: it will not be implemented because I do not see a good way to do it.
