### ISSUE TITLE
sendRemoveListener error in console

### ISSUE THREAD

**Issue by gitdine** [kkapsner/CanvasBlocker#471]
When I look at the console, the message "**sendRemoveListener on closed conduit CanvasBlocker@kkapsner.de.[number]**" appears frequently as an error.
This doesn't seem to effect functionality, but it's worth investigating. I think it might have something to do with Fission?
![image](https://user-images.githubusercontent.com/55441362/80575061-723e5500-89f2-11ea-961f-9252f5029876.png)

**Comment by kkapsner** [comment]
I think it's https://bugzilla.mozilla.org/show_bug.cgi?id=1633315 and I think this is a Firefox Bug.

**Comment by gitdine** [comment]
I'm using FF 75 stable and CB 1.2 with default settings. I have a lot of experimental about:config prefs set so that might have something to do with it.

**Comment by kkapsner** [comment]
The discussion and scenarios in the Firefox bug strongly suggest that it's not the WebExtensions fault. Therefore I will close this issue.

But nevertheless thanks for reporting.
