### ISSUE TITLE
how do i undo my oopsie

### ISSUE THREAD

**Issue by gitHu6-newb** [kkapsner/CanvasBlocker#472]
## Description

I'm in ver 1.2 of the Settings and I clicked on the "hide" button of an option. ( i think the block options)
how do i get it back?

**Comment by kkapsner** [comment]
Simply check the "Display hidden settings" checkbox:
![image](https://user-images.githubusercontent.com/1105157/81509864-ebe91380-930d-11ea-8148-83e2df529c00.png)
