### ISSUE TITLE
Navigator spoofing fails

### ISSUE THREAD

**Issue by littleRichard2020** [kkapsner/CanvasBlocker#474]
## Description
hey first of all thanks a lot for your great work, it's a great plugin! 
unfortunately the navigator spoofing seems to not work properly. In your Navigator Test you will see real appVersion, platform and real useragent next to the faked ones.

I was able to reproduce this on Windows 10 firefox versions 72 and 76 (both 64bit), as well as webdeveloper version77.0b6 (64-bit) and on my Android phone (v68).

## Steps to Reproduce (for bugs)

1.  choose stealth settings 
2. CanvasBlocker navigator settings -> choose Linux and Firefox presets
3. make Navigator test
4. see : 
- appVersion: 5.0 (X11) | 5.0 (Windows)
- platform: Linux x86_64 | Win32
- userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0 | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0

## Your Environment

* CanvasBlocker Version used: Version 1.2:
* Firefox version incl. 32- or 64-bit: 77.0b6 (64-bit) | 76.0.1 (64-Bit) | v68
* Operating System and version (desktop or mobile): windows (Desktop), Android(Mobile)
* Installed addons: just Canvasblocker

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "input",
	"minFakeSize": 10,
	"maxFakeSize": 0,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 3,
	"minColors": 3,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{\"www.google.com\":[226,229,75,46,50,54,202,167,86,55,158,24,194,235,199,177,254,132,163,131,188,44,158,81,132,232,169,20,144,203,82,71,106,226,52,180,174,228,251,23,151,1,156,197,138,230,87,231,113,178,109,141,215,167,11,82,22,31,119,94,135,169,122,178,130,141,86,189,183,170,64,2,157,92,116,110,58,218,149,254,97,179,206,160,89,190,87,18,211,232,93,77,14,144,141,188,144,125,131,238,191,1,65,205,194,103,15,110,23,23,185,229,242,57,237,85,220,13,16,13,151,207,201,214,11,174,111,142],\"canvasblocker.kkapsner.de\":[205,225,177,9,141,168,167,184,147,236,114,79,246,154,101,199,224,12,221,157,156,26,70,179,25,57,6,218,206,11,224,42,68,48,233,136,190,24,63,139,0,184,78,246,157,176,79,213,111,174,183,126,49,222,66,40,246,121,66,190,166,216,248,11,131,146,89,38,33,238,225,158,72,25,157,213,211,245,165,41,120,235,32,24,75,58,79,138,186,56,73,253,156,45,20,97,247,16,28,165,187,164,73,129,148,223,184,237,148,246,228,163,93,82,212,135,2,230,52,121,181,86,168,91,172,53,70,53]}",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1589706167336,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "2",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": true,
	"navigatorDetails": {
		"osPreset": "Linux",
		"windowManager": "X11",
		"platform": "Linux x86_64",
		"platformDetails": "X11; Linux x86_64",
		"oscpu": "{platform}",
		"browserPreset": "Firefox",
		"firefoxVersion": "{real Firefox version}",
		"appVersion": "5.0 ({windowManager})",
		"buildID": "20181001000000",
		"productSub": "20100101",
		"userAgent": "Mozilla/5.0 ({platformDetails}; rv:{firefoxVersion}) Gecko/20100101 Firefox/{firefoxVersion}"
	},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": false,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment]
Thanks for reporting. I already know of this issue and it's tracked in #473. At the moment there is little I can do about it (as far as I know).
