### ISSUE TITLE
Screen size spoofing seems to not work in Waterfox 2020.05

### ISSUE THREAD

**Issue by ilikenwf** [kkapsner/CanvasBlocker#475]
With the settings below, the screen size is not spoofed on panopticlick...Chameleon succeeds, but I'd rather not use that addon:

![image](https://user-images.githubusercontent.com/414778/82511917-0a18f580-9afe-11ea-830b-c69c07c4c501.png)

**Comment by kkapsner** [comment]
I'm not able to reproduce your problem:
![image](https://user-images.githubusercontent.com/1105157/82552741-fce22200-9b62-11ea-9ea7-ba80913810d4.png)

Which version of Waterfox and CB are you using? What are your exact settings?

**Comment by ilikenwf** [comment]
I'm using the newest build of waterfox-current, and the 1.3 alpha build
of CB.

**Comment by kkapsner** [comment]
Still not able to reproduce with Waterfox current 2020.05 and CB 1.3 alpha.
Which OS are you on? Did you build it yourself?

**Comment by ilikenwf** [comment]
I'm running Linux, and while I did build Waterfox, I did not build the
addon.

I'm also using ghacks user.js with RFP on but have patched my build to
allow CB to manipulate the canvas...

Interestingly using a userscript to spoof screen size is working for me.

**Comment by kkapsner** [comment]
Please try a fresh profile and a default build of Waterfox (with and without RFP) - also with RFP I'm not able to reproduce.

**Comment by kkapsner** [comment]
Any results?

**Comment by ilikenwf** [comment]
Sorry I've been tied up, I'll attempt to test tonight.

**Comment by kkapsner** [comment]
What are the test results?

**Comment by kkapsner** [comment]
Almost 4 weeks without response... if you still have the problem and did the test I can reopen this issue.
