### ISSUE TITLE
Canvas is Spoofed

### ISSUE THREAD

**Issue by zerrom** [kkapsner/CanvasBlocker#476]
## Description
CanvasBlocker detected at https://www.deviceinfo.me/

## Expected Behavior
CanvasBlocker shouldn't be detected at https://www.deviceinfo.me/

## Steps to Reproduce (for bugs)
1. I have Firefox 68.8.0 with privacy.resistFingerprinting=false
2. CanvasBlocker 1.2 is with the default settings
3. When I visit https://www.deviceinfo.me/ about Canvas I have Allowed-Spoofed. It's that normal? In my understanding with the above settings and CanvasBlocker I should have Supported-Allowed?

## Your Environment
* CanvasBlocker Version used: 1.2
* Firefox version incl. 32- or 64-bit: 68.8.0 64bit
* Operating System and version (desktop or mobile): Windows 10

**Comment by kkapsner** [comment]
As CanvasBlocker changes the way canvas behave there will always be a way to detect it somehow. In this case you can use the stealth preset or set the canvas protected part to "input" or set the minimal canvas fake size to 36.
