### ISSUE TITLE
Pref that breaks CB

### ISSUE THREAD

**Issue by crssi** [kkapsner/CanvasBlocker#477]
FYI: https://github.com/ghacksuserjs/ghacks-user.js/issues/951

Close at will and cheers

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/issues/923 has more detail and I updated the first post

> It is fixed in FF78 (supposedly). IF it happens to you, you have two options
> - set `dom.quotaManager.useDOSDevicePathSyntax` = `false`
> - set `network.file.disable_unc_paths` = `false`
> 
> I assume a restart is required

**Comment by kkapsner** [comment]
Thanks for the notification. I think there is nothing I can do about it as it's the settings storage.
