### ISSUE TITLE
Help with Navigator test

### ISSUE THREAD

**Issue by troubleword** [kkapsner/CanvasBlocker#482]
Navigator test: https://canvasblocker.kkapsner.de/test/navigatorTest.php
Whatever I do, the Navigator test reveals the following parameters (red lines):

- appVersion: 5.0 (X11) | 5.0 (Windows)
- platform: Linux x86_64 | Win32
- userAgent: Mozilla / 5.0 (X11; Linux x86_64; rv: 77.0) Gecko / 20100101 Firefox / 77.0 | Mozilla / 5.0 (Windows NT 10.0; Win64; x64; rv: 77.0) Gecko / 20100101 Firefox / 77.0

In the settings, I have the Navigator API enabled. It is configured on Linux / Firefox (due to the proxy server)

On whatleaks.com everything shows correctly (as configured):
- Passive OS Fingerprint: Linux
- Browser Useragent: Linux

I do not use third-party user-agents.

Can you tell me how to successfully pass Navigator test (at canvasblocker.kkapsner.de)?
Tell me in which direction to move?
![Print](https://user-images.githubusercontent.com/61377575/84603562-f7dd6d80-ae97-11ea-8bb3-9a5d7739f542.jpg)

**Comment by kkapsner** [comment]
This is a duplicate to #474. And the reason is #473. So there is nothing you can do (and as far as I know I cannot do anything at the moment either).

You might vote on the bugzilla entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1636977

**Comment by troubleword** [comment]
If you deal with this problem, perhaps the following can help:
After installing the plugin "Luminous: JavaScript events blocker", all the red marks disappeared and the parameters disappeared through the line. To do this, in the Luminous settings you need to enable the "message" lock in the "handleEvent".
However, this solution is more likely a baton than a scalpel: many sites work incorrectly.
![Print_2](https://user-images.githubusercontent.com/61377575/84688378-ec497f80-af47-11ea-92d7-98f7e17127ad.jpg)

**Comment by kkapsner** [comment]
Thanks for sharing this information. I can easily circumvent this "protection" by changing the script  slightly (changing the `addEventListener()` call to an assignment to `on...`).

PS: The usage of this addon is highly detectable and I would not recommend using it for anti-fingerprinting purposes.
