### ISSUE TITLE
Delete whitelisted websites. 

### ISSUE THREAD

**Issue by Renalrazi** [kkapsner/CanvasBlocker#483]
## Description
When I add a site using the pop up in the url bar to whitelist ALL API, I cannot remove this whitelisted website from the addon. The cross next to the url in one of the API settings resets to the API default instead of deleting the website.

## Expected Behavior
A way to delete websites that were whitelisted using the popup in the url bar. 

## Current Behavior
The cross next to the url has two different behaviors. 
1) If the site was added to the whitelist to whitelist ALL API using the popup in the url bar, the cross resets the settings to the API default. 
2) If the website was manually added to the API in the addon option page or set to only whitelist one API in the popup, the cross deletes the website. 

How's that not confusing?

Currently, to delete a website that was added to whitelist ALL API using the popup in the url bar from the addon, you need to export your settings, delete the site from the .json, reset the settings in the option page and import your edited json settings file. 

## Possible Solution
Add a button to remove a website from the whitelist in the "CanvasBlocker whitelist inspection" page. 

I read  #291 and while you explain how this cross work, you don't explain how to delete whitelisted website from your addon. If there's a simple way to delete whitelisted websites, please explain where it is because I couldn't find it after looking around the option page for an hour.

**Comment by kkapsner** [comment]
If you whitelist all APIs you have to delete the entry at the "Block mode" setting.

Also you can check in the settings inspection which `"urlSetting"` has been set for the URL.

Another way to remove a whitelisting is to use the mentioned "CanvasBlocker whitelist inspection" page and the run the "Setting sanitation" to remove any URL specific settings that are the same as the default value. Removing a website inside the "CanvasBlocker whitelist inspection" will result in the loss of all other URL specific settings for this website.

But the mentioned step above with the "Setting sanitation" should be removed. I will work on that.

**Comment by Renalrazi** [comment]
There is no option to delete a whitelisted website in the "Block mode" setting. The cross resets the website to the Block Mode default. There's an option to allow everything, but it's not what I want. I want to delete the url.

> Removing a website inside the "CanvasBlocker whitelist inspection" will result in the loss of all other URL specific settings for this website.

I don't think you understood what removing a website means. When I say I want to remove a website from the addon, I mean that I want to remove it **_completely_** from your addon. I don't want it to retain value, whatsoever, I just want it removed, gone, pouf, as if I had not added the website in the first place.

**Comment by kkapsner** [comment]
> There is no option to delete a whitelisted website in the "Block mode" setting. The cross resets the website to the Block Mode default.

Please post your settings then I can figure out which setting is keeping the URL.
If you delete all URL specific settings for this URL it will be removed completely.

> I just want it removed, gone, pouf, as if I had not added the website in the first place.

I know what you want. But there is currently no easy to use UI to do it (I plan to improve the options UI - let's see if I find a good way to include that). If you are familiar with the JSON setting export you can also change it in the "inspect" page. So no need to export/change/import.

**Comment by Renalrazi** [comment]
> Please post your settings then I can figure out which setting is keeping the URL.
If you delete all URL specific settings for this URL it will be removed completely.

I managed to remove the couple of websites I wanted to remove using the UI instead of editing the json. 

>
I know what you want. But there is currently no easy to use UI to do it (I plan to improve the options UI - let's see if I find a good way to include that).
Yes, please because it can be a giant headache to remove a whitelisted website from the addon. The simplest the better.
