### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by slinforced** [kkapsner/CanvasBlocker#485]
Hey love your tool it is very useful but i got two questions
1. is it possible to disable Html5 canvas protection because it was detected on multiple sites
2. could you uprgrade the tool to spoof the Ja3 hash too?

**Comment by kkapsner** [comment]
Short answers:
1. yes
2. no

long answers:
1. you can set the "Protected part of the canvas API" to "nothing" and the Canvas protection will be disabled.
2. Ja3 hashes are generated by the SSL communication. A web extension does not have the ability to change the way the browser handle SSL handshakes. It would be a huge security issue if that would be the case.

**Comment by slinforced** [comment]
Okay do you know how can i change ja3 hash

**Comment by geeknik** [comment]
> Okay do you know how can i change ja3 hash

Check out these articles:
https://medium.com/cu-cyber/impersonating-ja3-fingerprints-b9f555880e42
https://www.defensive-security.com/blog/hiding-behind-ja3-hash

Play around with this software:
https://github.com/cucyber/JA3Transport

Good luck!

**Comment by slinforced** [comment]
Thank you so much great team !!!
