### ISSUE TITLE
Providing config file?

### ISSUE THREAD

**Issue by freeze-out** [kkapsner/CanvasBlocker#486]
Hi.

I really like your extension.

Is there any way to provide some kind of configuration file to have my custom preset set? I have to manage several Firefox profiles and I want to install all of those with predefined settings for your extension.
All I could find so far ist the option to export the config in the settings of the addon and reload it in another file. Those steps would have to be done by hand. Any possibility to place the settings somewhere without those manually steps?

Thanks for your help.

**Comment by kkapsner** [comment]
WebExtensions do not have general access to the file system (only very limited to the downloads folder). So CanvasBlocker cannot read a config file. So the export/import is the only thing I can do to have such kind of functionality.

Firefox used to store the webExtension settings in a simply file in the profile but a while ago they switched to IDB. I think it's the sqlite file in `{profile}/storage/default/moz-extension+++{extension id}^userContextId={no idea what this number means}/idb/`. But I think the content is not trivial to read/modify. But it's the only "file" I can point you to.
