### ISSUE TITLE
TextMetrics test does not work on Linux

### ISSUE THREAD

**Issue by troubleword** [kkapsner/CanvasBlocker#488]
Good evening!

I have the latest version of Firefox and CanvasBlocker.

The problem arose on Linux Ubuntu (I have 2 different Linux Ubuntu systems, the problem has been identified on both).

The TextMetrics test page shows that the CanvasBlocker does not hide two lines (see screenshot):
- actualBoundingBoxAscent
- actualBoundingBoxDescent

![Screen-1](https://user-images.githubusercontent.com/61377575/85797760-ec662e00-b744-11ea-9915-c0fa521f7b89.jpg)

(On another version of Linux Ubuntu, the plugin also does not hide the line actualBoundingBoxLeft).

I did not change anything in the settings of CanvasBlocker, all check boxes are selected (see screenshot)

![Screen-2](https://user-images.githubusercontent.com/61377575/85797782-f720c300-b744-11ea-92bd-36ff0b44aac5.jpg)

When the CanvasBlocker is disabled, the specified lines have the same values ​​(i.e., the CanvasBlocker does not replace them).

Other plugins do not affect the test (disabled).

Interestingly, on a system with Windows 10, these lines change successfully.

Tell me, how important is this vulnerability? How can I protect my anonymity?

Thank!

**Comment by Thorin-Oakenpants** [comment]
That's because your values do not need to randomized, they're integers. Go [here](https://thorin-oakenpants.github.io/testing/textmetrics.html) and post a pic or paste some stats

**Comment by troubleword** [comment]
![Screen-3](https://user-images.githubusercontent.com/61377575/85849762-3d613b00-b7b4-11ea-8c8b-f670cafbcb7f.jpg)

**Comment by troubleword** [comment]
Thank you, you helped me figure it out.
As I understand it, the values of the integer are too insignificant to form a unique fingerprinting.
However, the unique Hash confuses me (in two lines). Is this a vulnerability of my anonymity?
Should I worry about this?
-----
I can also switch the line "dom.textMetrics.actualBoundingBox.enabled" to false in the Firefox settings (about: config). Would it make me more visible (stand out from the average user)?

**Comment by troubleword** [comment]
Thank you, you helped me figure it out.
As I understand it, the values of the integer are too insignificant to form a unique fingerprinting.
However, the unique Hash confuses me (in two lines). Is this a vulnerability of my anonymity?
Should I worry about this?
-----
I can also switch the line "dom.textMetrics.actualBoundingBox.enabled" to false in the Firefox settings (about: config). Would it make me more visible (stand out from the average user)?

**Comment by troubleword** [comment]
Thank you, you helped me figure it out.
As I understand it, the values of the integer are too insignificant to form a unique fingerprinting.
However, the unique Hash confuses me (in two lines). Is this a vulnerability of my anonymity?
Should I worry about this?
//------------------------------------
I can also switch the line "dom.textMetrics.actualBoundingBox.enabled" to false in the Firefox settings (about: config). Would it make me more visible (stand out from the average user)?

**Comment by Thorin-Oakenpants** [comment]
An integer is a whole number, like `23` or `41` - they have no decimal places. The test is using the same 43 characters as CB's test

On your two Linux setups, for `BoxAscent` and `BoxDescent`, all 43 measurements are integers: so there is nothing for CB to randomize. CB randomizes the decimal parts. This (a high percentage of integers) is common in Linux distros, but of course depends on your default font and the characters used in the test.

Do not change your textMetrics prefs in about:config from default - that can be detected and you'll stand out

**Comment by Thorin-Oakenpants** [comment]
Here's my windows with textmetric spoofing off
- the default font is the same as many other Latin languages on Windows = Times New Roman
- lots less integers, which means CB has something to randomize
![windows](https://user-images.githubusercontent.com/16656956/85909768-fd797280-b80a-11ea-9c6a-95742fc817a5.png)

**Comment by kkapsner** [comment]
> As I understand it, the values of the integer are too insignificant to form a unique fingerprinting.

Not only that. Also if I change the integer values it would be extremely easy to spot that something was faked.

> However, the unique Hash confuses me (in two lines). Is this a vulnerability of my anonymity?

I guess the Hash depends on your system fonts so you should share it with other Ubuntu users.

> Would it make me more visible (stand out from the average user)?

Yes. Almost no one will disable that and it's enabled by default in the new Firefox.

But what bothers me is the number of differences. This should be 0.

**Comment by Thorin-Oakenpants** [comment]
> But what bothers me is the number of differences. This should be 0.

Why would it be zero. Diffs is the change between domrect vs textmetric width, and width is more precise, right? I mean I get diffs from memory on my test when I randomize tm with CB - that was the whole point, the diffs is indicative of spoofing (except android where we discussed the devicePixelRatio probably being a factor: that is diffs is sky high when not spoofing which is wrong)

**Comment by kkapsner** [comment]
On all my machines I get 0 diffs. The two APIs use a shared cache to return the same values. If `width` is more precise it would also return a diff if nothing is faked.

**Comment by Thorin-Oakenpants** [comment]
I'm like you .. I need a quiet moment (or hours) .. in this case for me, to refresh and digest whats going on here. IIRC the number of diffs was a tell, so did you modify your code (I watch your commits and didn't see one AFAICT) ? Your is the only extension that spoofed tm. And it wasn't a windows thing, because we know the glyphs aren't integers (we blew them up to 22 gazillion pixels)

I'll have to retest, but I'm starting to feel like I need a break
- domrect=off, tm=off: 5/31 diffs
- domrect=on, tm=off: 22/31 diffs
- domrect=off, tm=on: 22/31 diffs
- both on: 5/31 diffs

Maybe in my earlier testing, I was only focused on enabling tm=on. By default CB has both enabled.

However - **diffs are not necessarily zero!** - see my example. You're doing six counts right? 6 x 43 = 258? I don't follow. There's the control (domrect) and then tm width to compare it to. What is being run six times?  Oooh, the six styles. Why aren't I counting those? Now I'll have to check. My output is different, but I'm sure I count all six styles. ToDo list here I come...

What does OP get with CB disabled on your test for diffs?

**Comment by kkapsner** [comment]
OK - I have to correct me: on all my Linux machines I get 0 diffs. On Windows I get some.

> What does OP get with CB disabled on your test for diffs?

That's a very good question.

**Comment by troubleword** [comment]
I retested on 2 Linux platforms the number of differences was 0.
![Screen-1](https://user-images.githubusercontent.com/61377575/85926383-d45aef80-b8a7-11ea-9db8-40c3733de071.jpg)
//---
With DOMRect or TextMetrics disabled, the number of differences changes to 164 (153 on the second Linux).
// ---
In a regular browser (Windows 10) without any plug-ins (including CB), the number of differences is 89. On another laptop (Windows 10) without protection, the value was also 89.
![Screen-2](https://user-images.githubusercontent.com/61377575/85926451-39164a00-b8a8-11ea-977a-b3c730781c10.jpg)
// ---
On Windows 10 with CB, I have 193.

**Comment by kkapsner** [comment]
> With DOMRect or TextMetrics disabled, the number of differences changes to 164 (153 on the second Linux).

OK - that's fine.

> On Windows 10 with CB, I have 193.

That's weird. The number does not change for me. Do you have both APIs enabled?

**Comment by Thorin-Oakenpants** [comment]
> My output is different, but I'm sure I count all six styles. ToDo list here I come...

Now that I've had a sleep, and a coffee ... I compare all 258 tm widths against two sets of 258 domrect measurements
- `getBoundingClientRect` = `diffsb`
- `getClientRects` = `diffsc`

But I also only count unique diffs in each array, and the total is out of unique tm widths as well. So I have three values
- unique tm widths
- unique getBoundingClientRect diffs vs tm
- unique getClientRect diffs vs tm

So the `31` is the number of unique tm widths. If the hashes for `getBounding` vs `getClientrects` are the same, I only output one line (and the counts will be the same cuz you know, the hash). But if you only spoof one of the two, i.e the hash is different, then a second line appears and labels are changed (and of course counts could be different)

Here's an example: domrect=on but only `getClientRect` (tm = off)
![example](https://user-images.githubusercontent.com/16656956/85940211-9cd15f00-b90a-11ea-9215-4b36bea42888.png)

FYI: Here's the same example: domrect=on but only `getClientRect` (**but this time tm = on**)
- which flips the results: but it's still two different hashes (and super likely but not guaranteed different counts)
![example2](https://user-images.githubusercontent.com/16656956/85940324-24b76900-b90b-11ea-8f33-e1d15b0bd2d2.png)

Phew, that took me a while to remember and work out what I did

**Comment by Thorin-Oakenpants** [comment]
windows 7 [CB test], each test is a new tab
- no protection: 20 diffs
- both protected: 20 diffs
- only one protected: 169 diffs
- you're only counting with `getBoundingClientRect`, so partial domRect protection tests don't make sense

So AFAICT it's working. OP maybe had tm width or `getBoundingClientRect` or one of the APIs disabled by mistake .. or needed to use a new tab

**Comment by kkapsner** [comment]
> So AFAICT it's working. OP maybe had tm width or `getBoundingClientRect` or one of the APIs disabled by mistake ..

That's my suspicion as well.

**Comment by troubleword** [comment]
> That's weird. The number does not change for me. Do you have both APIs enabled?
You are right, the value is too high due to another add-on that has changed Client Rects.
If I turn off all add-ons (except CB) the number of differences is 32.
In Linux this add-on does not affect the number of differences (equal 0).

**Comment by troubleword** [comment]
> That's weird. The number does not change for me. Do you have both APIs enabled?

You are right, the value is too high due to another add-on that has changed Client Rects.
If I turn off all add-ons (except CB) the number of differences is 32.
In Linux this add-on does not affect the number of differences (equal 0).

**Comment by troubleword** [comment]
> That's weird. The number does not change for me. Do you have both APIs enabled?

You are right, the value is too high due to another add-on that has changed Client Rects.
If I turn off all add-ons (except CB) the number of differences is 32.
In Linux this add-on does not affect the number of differences (equal 0).

> Do you have both APIs enabled?

Yes

**Comment by kkapsner** [comment]
OK - so everything works like intended.
