### ISSUE TITLE
What does "ignore domain" do?

### ISSUE THREAD

**Issue by mc0e** [kkapsner/CanvasBlocker#49]
OK, so I get a message like "Faked readout on github.com" with a bunch of buttons, including "ignore domain".  It's less than clear what happens though when a domain gets "ignored".  Does that just mean I don't get notified about this domain?  Does the canvas usage get blocked or not or not when I do this?

Given the presence of a "whitelist domain", I'm guessing that "ignore domain" doesn't do that, so it's more like "silently block domain in future".  Is that right?  Can we come up with a better way to express that?

**Comment by kkapsner** [comment]
You're completely right. The "ignore" button just adds the domain to the
list of domains that do not trigger a notification. I thought the label
in the preference panel for the ignore list is clear enough.

But if you come up with a better expression that does not occupy a lot
of space I can change that.

**Comment by kilobyte** [comment]
This issue puzzled me as well.
What about adding "*(don't display notifications)*" to the popup dialog text?

**Comment by kkapsner** [comment]
It would have to be "don't display notifications for domain" which is way too long... but does "silence domain" work for you?

PS: But I definitely have to change the text in the following dialog...

**Comment by kilobyte** [comment]
"silence" sounds less likely to cause confusion than "ignore", yes.
