### ISSUE TITLE
import fingerprints

### ISSUE THREAD

**Issue by salisbury-espinosa** [kkapsner/CanvasBlocker#490]
Is it possible to import fingerprints?
this is necessary for more reliable emulation.
so that the fingerprints are statistically related

**Comment by kkapsner** [comment]
Not really. If you use the persistent rng and store the persistent data you can export and import that. But the actual fingerprint is not completely determined by that alone. Also if you visit a new domain you have to resync your stored data (unless you use "Share persistent randomness between domains"). But all of that is a very bad idea if you are using CB for any privacy reasons.

PS: I do not quite get what you mean by "emulation".

**Comment by salisbury-espinosa** [comment]
> PS: I do not quite get what you mean by "emulation".

fingerprint emulation...

this is necessary in order not to fall under suspicious behavior - large companies collect fingerprints (

By the way, you probably have to expand the list of supported fingerprints: 
https://www.zdnet.com/article/apple-declined-to-implement-16-web-apis-in-safari-due-to-privacy-concerns/

**Comment by kkapsner** [comment]
As far as I see it only tow of these APIs are in Firefox: HDCP policy check and proximity. Both are behind a flag so not in a standard installation. As changing your browser flags that enable certain APIs increases your fingerprint I suggest not to enable it in the first place.
