### ISSUE TITLE
Detection, impossible to avoid?

### ISSUE THREAD

**Issue by digitalnature** [kkapsner/CanvasBlocker#491]
From what I understand this extension replaces some native functions with others that return modified data.
But doing a simple request for the function body will reveal if the function has native code or not.

Example:

`console.log(HTMLCanvasElement.prototype.toDataURL.toString())` outputs ` { [native code] }`
but after you override the prototype with a custom function you get the actual code of your function, so you know it has been tampered.

**Comment by kkapsner** [comment]
As CB uses `exportFunction` to get the function into the security context of the page to `toString` detection does not work for CB. See https://canvasblocker.localhost/test/detectionTest.html

But indeed it's impossible to avoid detection completely.
