### ISSUE TITLE
String.fromCharCode is not sufficient

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [kkapsner/CanvasBlocker#494]
- `textMetricsTest.js` uses String.fromCharCode for all the code points
- TZP uses this function

```js
function get_str_from_codepoint(n) {
	if (n <= 0xffff) {
		return String.fromCharCode(n)
	} else {
		n -= 0x10000
		return String.fromCharCode(0xd800 + (n >> 10), 0xdc00 + (n % 0x400))
	}
}
```

The list of 43 chars came from [David Fifield & Serge Egelman](https://www.bamsoftware.com/talks/fc15-fontfp/fontfp.html#demo) and was whittled down from gazillions to a small fast set for font fingeprinting

TZP uses the same chars in it's font detection enumeration, as it improved accuracy. So in the two font enumeration tests I combine fingerprintjs2 's string with the unicode glyphs and with arthur's set of unicode points.

I know this was mentioned by me once before, but you said it was OK. I added it to my ToDo list, to get rid of my extra function. That day has arrived. But it doesn't work. Here are the two strings being generated to add to the fallback font code

```js
		strTZP += "</span>\n<span>" + get_str_from_codepoint(fntCode[i])
		strCB += "</span>\n<span>" + String.fromCharCode(fntCode[i])
```

Here is a pic
![chars](https://user-images.githubusercontent.com/16656956/87862409-4e2e4800-c93f-11ea-9b68-4d6000405659.png)

Of all the 43 items in the charCodePoints array, the 31st is `0x1D790`. If you add a debug in the else statement, it's the only one to that uses the else condition.

Now admittedly, you're not using this to test font fingerprints per se, you're using it to make sure textMetrics width matches clientrects and that they are randomized .. and for the other textMetric stuff

But technically, it's not correct

`view-source:https://www.bamsoftware.com/talks/fc15-fontfp/fontfp.html#demo`
> // String.fromCharCode doesn't support code points outside the BMP (it
> // treats them as mod 0x10000). String.fromCodePoint isn't supported.
> // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode
> // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint

edit: that's from the source, which is of course **many** years old, so take it with a grain of salt

**Comment by Thorin-Oakenpants** [comment]
I'm always second guessing myself, so I snapped dcf's test as it hit the codepoint
![dcf](https://user-images.githubusercontent.com/16656956/87862651-e0cfe680-c941-11ea-9295-46a815381cef.png)

Anyway, I think our tests should be using the same chars

**Comment by kkapsner** [comment]
>     * `textMetricsTest.js` uses String.fromCharCode for all the code points

No - it uses `String.fromCodePoint`: https://github.com/kkapsner/CanvasBlocker/blob/master/test/textMetricsTest.js#L65

Did not do the test yet (have to go to bed...), but it should behave properly.

**Comment by Thorin-Oakenpants** [comment]
you're right. I just had a massive sleep and am already on my second coffee. I misread fromCharCode and fromCodePoint - the strings **are** the same

**Comment by kkapsner** [comment]
> the strings **are** the same

Great - thanks for testing again.
