### ISSUE TITLE
permanent hash spoof for android

### ISSUE THREAD

**Issue by thiagoroberio** [kkapsner/CanvasBlocker#496]
I tested the extension on firefox mobile, and everything seems to work fine. However, I cannot keep the screen hash constant, it changes whenever the page is updated, even if it is permanent in the settings. Is a stable mobile version possible?

**Comment by kkapsner** [comment]
I hope to be able to fix this. At the moment I have no clue why this is happening...

**Comment by kkapsner** [comment]
When #503 is fixed it seems this issue here has solved itself by the update to Fenix.

**Comment by kkapsner** [comment]
Works for me in Nightly fenix.
