### ISSUE TITLE
CanvasBlocker activates canvas protection even when PRF is on

### ISSUE THREAD

**Issue by EchoDev** [kkapsner/CanvasBlocker#499]
CanvasBlocker activates canvas protection even when PRF is on. Tested on Firefox 80, latest CB on AMO, Win 10 x64

## Description
There are multiple ways to block canvas fingerprinting in Firefox. privacy.resistFingerprinting (PRF) is one of those ways. From what I understand CB should not activate for canvas fingerprinting when PRF is on.

I have the follow settings enabled

privacy.resistFingerprinting true
privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts false (For testing this issue)
privacy.resistFingerprinting.randomDataOnCanvasExtract false (For testing this issue)

I use the following site to test this issue
https://browserleaks.com/canvas

Browserleaks outputs the following signature A4E1854E (Tor Browser signature). This mean PRF is working correctly. 

Weirdly enough it seems CB still activates itself even when it is not needed. The fingerprint icon shows up in the url bar with the following message
Faked at input on browserleaks.com (2) 

The icon on the addonbar also confirms CB is activated for canvas protection.

Why is this a problem?
Sometimes I use Google Sheets ([example sheet](https://docs.google.com/spreadsheets/d/1KDNGI76HoMNyYLL6RqWu4PqUbw-lI920tf7QTclnLLE)). Due to the aggressive settings chosen in CB this page locks up Firefox partially making it unresponsive untill I force stop CB.

Why not just whitelist Google Sheets in CB and let PRF do it's job?
CB doesn't only protect against canvas fingerprinting but also seems to protect against domRect and textMetrics on Google Sheets. I'm not sure how much protection PRF has for these APIs, but even if it does we shouldn't rely on a whitelist workaround?

## Expected Behavior
When PRF canvas protection is on, CB shouldn't activate its own canvas protection. Only when the user gives permission to read the canvas, CB should activate canvas protection

## Current Behavior
CB canvas protection activates even when PRF canvas protection is on. Even when CB activates PRF still has priority.

## Steps to Reproduce (for bugs)
1. Make sure PRF is on and disable returning random data on canvas extract
2. Go to https://browserleaks.com/canvas
3. Hover over CB icon

## Context

Not tested with a fresh profile

## Your Environment

* CanvasBlocker Version used: 1.3
* Firefox version incl. 32- or 64-bit: Firefox 80 x64
* Operating System and version (desktop or mobile): Windows 10 x64
* Installed addons: uBlock Origin, uMatrix, Decentraleyes

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"protectScreen": true
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "input",
	"minFakeSize": 0,
	"maxFakeSize": 0,
	"rng": "persistent",
	"protectedAPIFeatures": {
		"outerHeight @ screen": true,
		"outerWidth @ screen": true,
		"matches @ screen": true,
		"availLeft @ screen": true,
		"availTop @ screen": true,
		"availHeight @ screen": true,
		"availWidth @ screen": true,
		"height @ screen": true,
		"width @ screen": true,
		"name @ window": false,
		"opener @ window": false
	},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": ,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "0.1%",
	"audioNoiseLevel": "low",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "3",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": false,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment]
Unfortunately there is no good way to detect if you allowed the usage of the canvas when RFP is enable. So CB always has to step in.
So the expected behaviour

> Only when the user gives permission to read the canvas, CB should activate canvas protection

is not possible.

You problem with Google Sheets can be solved by only whitelisting the canvas API for Google sheets.
