### ISSUE TITLE
Ignore list not working (or not documented enough)

### ISSUE THREAD

**Issue by Synetech** [kkapsner/CanvasBlocker#501]
This add-on kills Google Maps and makes it constantly stall. I tried adding Google Maps to the ignore list, but CanvasBlocker still interferes with it.

I tried adding these permutations to the ignore list and the whitelist:

google.com/maps
www.google.com/maps
maps.google.com
google.com/maps/*
www.google.com/maps/*
maps.google.com/*

I tried restarting the add-on and reload the Google Maps pages, but nothing seems to work to prevent the add-on from messing up GM. 😕 How is it supposed to work? It needs better documentation (or input validation—it didn't notice or complain about or fix that I put them on separate lines instead of comma-separated, and I ended up just spamming every permutation, just in case because I can't determine if it needs an asterisk or what 🤷).

(An alternative issue would be that it causes Google Maps to keep stalling in the first place. 🤔)

**Comment by spodermenpls** [comment]
Google Maps and Street View work fine on my end (Win 10 and Firefox 81.0.1), and have been since I reported the issue #92 . The ignore list just hides notifications for the sites (or APIs) that are inserted/ticked there, so this is not the right tool for this. Delete all your entries, open Maps/Street View and click on the fingerprint icon in the address bar, there you can add the URLs by clicking on them and allowing them by a click on the green tick mark (as seen here: (as seen here: https://github.com/kkapsner/CanvasBlocker/issues/340#issuecomment-500114575)) and select either the long URL (may be sufficient for testing) or the shortened URL for a bigger scope.

**Comment by crssi** [comment]
@Synetech, you gave not enough info for anyone to be sufficient helpful.
Which browser and version of the browser?
Did you tried without extensions?
Do you have any additional changes (like user.js usage in firefox)? Which are those?

Cheers

**Comment by Synetech** [comment]
I know the problem is with CanvasBlocker because Firefox shows a yellow bar saying that it is taking too long and asks if I want to disable CanvasBlocker, and if I add Google Maps to the whitelist, it works fine.

> Google Maps and Street View work fine on my end (Win 10 and Firefox 81.0.1), and have been since I reported the issue #92 . 

That's great, but this is a different issue; I'm not talking about it not working at all, I'm talking about it using 100% CPU and causing the browser to freeze, then resume, then freeze, then resume, then… Moreover, I'm not talking about street-view, the map itself keeps freezing while CB is active.

> The ignore list just hides notifications for the sites (or APIs) that are inserted/ticked there, so this is not the right tool for this. Delete all your entries, open Maps/Street View and click on the fingerprint icon in the address bar, there you can add the URLs by clicking on them and allowing them by a click on the green tick mark (as seen here: [#340 (comment)](https://github.com/kkapsner/CanvasBlocker/issues/340#issuecomment-500114575))) and select either the long URL (may be sufficient for testing) or the shortened URL for a bigger scope.

The comment you linked to almost didn't help because I wasn't seeing the control icons in the address bar; they only show up when you hover over the URL (which was only by chance that I noticed). Then even after clicking on the whitelist icon, it asks for a regexp, which most people won't know. Then it asked to whitelist just the canvas API or all; I selected just the canvas, but when I checked the settings, all of the APIs _except_ canvas are check-marked.

This is what I'm talking about, the whitelisting is very confusing and user-unfriendly.

**Comment by kkapsner** [comment]
> I'm talking about it using 100% CPU and causing the browser to freeze, then resume, then freeze, then resume, then…

Please post your CB settings. Maybe you use a setting which is heavy on the CPU.

> Then even after clicking on the whitelist icon, it asks for a regexp, which most people won't know.

If you click the first option in the first dialog in the whitelisting process you will whitelist the whole domain.

> I selected just the canvas, but when I checked the settings, all of the APIs _except_ canvas are check-marked.

Please show me a screenshot of where you checked. Maybe some documentation at that place could help to make this more clear.

> This is what I'm talking about, the whitelisting is very confusing and user-unfriendly.

A redo of the options is on my todo list - unfortunately this list is not shrinking at the moment... if you have ideas of how to make this less confusing and more user-friendly you are welcome to share these. We then can discuss the pros and cons.

**Comment by kkapsner** [comment]
Version 1.6 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.6
