### ISSUE TITLE
User-agent manipulation with CanvasBlocker

### ISSUE THREAD

**Issue by KnoxZZ** [kkapsner/CanvasBlocker#502]
Have you thought about adding a possibility to manipulate the user-agent header? I know there are many extensions that do it already, but in my opinion it would be nice to have the feature baked in to CanvasBlocker so users could rely on single extension for their anti-fingerprinting needs.

**Comment by kkapsner** [comment]
CB already supports navigator changes which include the user-agent: #321 

Just enable the navigator API protection and open the navigator settings.
