### ISSUE TITLE
Addon not working in Fenix

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#503]
If you get CanvasBlocker installed on Fenix (currently only possible in Nightly: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) pages do not load when using the persistent rng.

## Description
When using persistent rng on Fenix Nightly the page https://canvasblocker.kkapsner.de/test/test.html does not load.

## Expected Behavior
Page should load and show the test results.

## Current Behavior
Page is stuck.

## Possible Solution
It seems cookieStoreId is not (yet) supported in Fenix. Make CB aware of that.

## Steps to Reproduce (for bugs)
1. Install CB on Fenix Nightly
2. Set RNG to persistent
3. load https://canvasblocker.kkapsner.de/test/test.html -> it does not load.

## Your Environment

* CanvasBlocker Version used: 1.3
* Firefox version incl. 32- or 64-bit: Fenix Android
* Operating System and version (desktop or mobile): Android 10
* Installed addons: CB

**Comment by sharbet** [comment]
I'd like to report another problem under this issue:

With CanvasBlocker installed in Nightly (Fenix), pages do not load properly or are put under infinite loading.

Problems with CanvasBlocker enabled:

- Sites such as https://browserleaks.com/canvas do not load properly.

Specific problems with DomRect API enabled:

-  Sites such as reddit.com, yahoo.com (mobile version) are put under infinite loading.

Your Environment

    CanvasBlocker Version used: 1.3
    Firefox version incl. 32- or 64-bit: Fenix Android
    Operating System and version (desktop or mobile): Android 9
    Installed addons: CB (Persistent RNG)


[CanvasBlocker-settings_2020-10-29_18-21-11.zip](https://github.com/kkapsner/CanvasBlocker/files/5457381/CanvasBlocker-settings_2020-10-29_18-21-11.zip)

**Comment by kkapsner** [comment]
I think it's the same problem.
