### ISSUE TITLE
Plan to put version 1.4 on AMO?

### ISSUE THREAD

**Issue by sharbet** [kkapsner/CanvasBlocker#505]
I am currently using version 1.3 on Fenix through AMO(addons.mozilla.org) collections.

Since you released version 1.4 which includes upgrades to DomRect API and fixes to Fenix, I want to try it out on Fenix.

However, AMO collections only allow addons that are posted on AMO to be included, and Fenix does not allow manual installation of .xpi files.

Is there a planned date for the release of v 1.4 on AMO?

**Comment by kkapsner** [comment]
[Version 1.4](https://github.com/kkapsner/CanvasBlocker/milestone/16) is planned to be released on AMO next sunday. It is currently in daily use on desktop for me to see if anything is broken.

Thanks for testing.

**Comment by spodermenpls** [comment]
I've also switched to the CB-beta build to test it in the real world (I can't test for Fenix unfortunately, since my Jolla Phone / Tablet emulate only Android 4.1/4.4 and not 5.0 - I will test it on Fennec 68.11.0 later), and had no complaints. Good work as always!
