### ISSUE TITLE
Problem with Navigator Protection

### ISSUE THREAD

**Issue by glenlivet23** [kkapsner/CanvasBlocker#507]
Navigator not spoof.

https://canvasblocker.kkapsner.de/test/navigatorTest.php
![scr](https://user-images.githubusercontent.com/74437591/99133551-acaac080-25d7-11eb-92b3-8a7c9202bce2.png)

OS: Linux Ubuntu 18.04 x64
Firefox 82.03 x64

Addons only CB

Settings:
//===========
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "everything",
	"minFakeSize": 10,
	"maxFakeSize": 0,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 3,
	"minColors": 3,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{}",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1605314512567,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "color",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "3",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": true,
	"navigatorDetails": {
		"osPreset": "Windows",
		"windowManager": "Windows",
		"platform": "Win32",
		"platformDetails": "Windows NT 10.0; Win64; x64",
		"oscpu": "{undefined}",
		"browserPreset": "Chrome",
		"appVersion": "5.0 ({platformDetails}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{chromeVersion} Safari/537.36",
		"buildID": "{undefined}",
		"productSub": "20030107",
		"userAgent": "Mozilla/{appVersion}",
		"chromeVersion": "86.0.4240.198",
		"vendor": "Google Inc."
	},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": false,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "light",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}
//===========

**Comment by kkapsner** [comment]
This is a known issue (#473) and a Firefox issue (https://bugzilla.mozilla.org/show_bug.cgi?id=1636977). I did not yet find a good way to solve it with the methods webExtensions offer me.
