### ISSUE TITLE
Allow Renderer and Vendor to return empty string

### ISSUE THREAD

**Issue by martini1992** [kkapsner/CanvasBlocker#508]
## Description
When testing the Tor browser using [https://coveryourtracks.eff.org/](https://coveryourtracks.eff.org/) Vendor and Render show "None" implying nothing was returned. Currently both of these fields have to return something, the ability to return nothing will increase anonymity.

## Expected Behavior
Ability to return empty strings for all Vendor and Renderer parameters.

## Current Behavior
Always returns something, either entered string or the browser default value.

## Possible Solution
Checkbox to return nothing for each parameter.

## Steps to Reproduce (for bugs)
1. Change "Reported webGL vendor", "Reported webGL renderer", "Reported webGL unmasked vendor" or "Reported webGL  unmaskedrenderer"
2. Observe exact string (or default if empty) is reported by [https://coveryourtracks.eff.org/](https://coveryourtracks.eff.org/)

**Comment by kkapsner** [comment]
Tor uses the Strings `Mozilla` for both vendor and renderer (see https://canvasblocker.kkapsner.de/test/webGL-Test.html). But the WEBGL_debug_renderer_info extension is disabled so the "unmasked" version is not available.
I think I can build something to support something like this.

**Comment by kkapsner** [comment]
Please check the latest alpha version: https://canvasblocker.kkapsner.de/versions/

You have to set unmasked vendor and renderer to `{disabled}`.

**Comment by crssi** [comment]
Cool.

What would be best option to use?

**Comment by kkapsner** [comment]
> What would be best option to use?

Depends on what you want to achieve. If you want to simulate what Tor does you should set it to `{disabled}`.

**Comment by zxpetrel** [comment]
Any chance to add this to the descriptions for Reported webGL unmasked vendor/renderer?  It may save some others time finding it here or messing with about:config (as I did before realising you'd implemented it).  This seems to me exactly what's required.  Although I'm yet to find out if it breaks anything that would be an issue for me.

**Comment by kkapsner** [comment]
Sure - suggestions for the actual wording?

**Comment by kkapsner** [comment]
@zxpetrel: created #607 to track the documentation.
