### ISSUE TITLE
no fake readout

### ISSUE THREAD

**Issue by monperrus** [kkapsner/CanvasBlocker#51]
I try this extension on amiunique.org. It detects the canvas fingerprinting and a notification pops-up, but it seems no to deliver a fake result, because the "view details" page still display the generated canvas.

**Comment by kkapsner** [comment]
The result is faked. The changes are too small to be seen by human eyes (you can see them if you look closer in the orange part - you see some speckles) but will change the produces hash.

**Comment by monperrus** [comment]
If I understand correctly, this means that the produced hash is unique
for every run?

**Comment by kkapsner** [comment]
Should be (if the picture is not complete black). If not your rng is broken.

**Comment by slrslr** [comment]
@kkapsner On each reload of the page https://amiunique.org/fingerprint it always shows the same HTML5 image canvas, value "6 - Canvas". I have enabled the CanvasBlocker (CB) and not restarted the browser yet. CB button shows a successful protection for: canvas, screen, history. CB is set to blocking mode "fake" and "readout". https://coveryourtracks.eff.org on other hand shows: "randomized by first party domain" and" Bits of identifying information: 1.67; One in x browsers have this value: 3.17". Any idea please?

**Comment by kkapsner** [comment]
@slrslr: the image will appear identical. CB tries to modify them in a way that is not perceptible to the human eye.
