### ISSUE TITLE
Screen spoofing potentially detectable

### ISSUE THREAD

**Issue by Maryse47** [kkapsner/CanvasBlocker#510]
Screen spoofing as used by CanvasBlocker may be vulnerable to detection by anti-fingerprinting.  Please see https://palant.info/2020/12/10/how-anti-fingerprinting-extensions-tend-to-make-fingerprinting-easier for details (I don't want to copy paste it to github).

**Comment by kkapsner** [comment]
The points in the linked article do not apply to CB (well - the last one of "The art of faking" kind of does apply but this is unavoidable). I already fixed them..

The "solutions" that are mentioned might also not be sufficient enough (the `bind` approch definitely is not).

But thanks for pointing me to the article.
