### ISSUE TITLE
Possible WebRTC options

### ISSUE THREAD

**Issue by CookingRoberta** [kkapsner/CanvasBlocker#511]
New feature :  fake WebRTC local IP address

## Description
I heard it is possible to use WebRTC to get the local IP address of the host.
Since the CB already has many features I thought adding this in the future may be smart.

## Expected Behavior
Random local IP address may be used. If my local is 192.168.1.11 it may be some different address from the /24 segment say 192.168.1.rnd and it may behave similar as canvas hash (persistent, constant, non persistent, none)

## Current Behavior
Currently WebRTC protection looks like not present.
Do you have any WebRTC plans for the future, or you relay on completely ignoring this feature?

**Comment by kkapsner** [comment]
I don't think it's still possible to extract the IP address with WebRTC any more. The test pages I found (e.g http://net.ipcalf.com/ or https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) did not show my local IP for me.

Please give me a page that reports your local IP.

I might see a way to fake something there but then your webRTC will not work properly. So why not just disabled webRTC in about:config? It will break webRTC as well.

**Comment by CookingRoberta** [comment]
No, I don't have the URL showcase for leaking local IP address. Since WebRTC had problems before with leaking public IP in case you are using browser addons, local IP in case you use ICE, I assumed this is still the case. There are some indicators https://www.ivanovation.ro/modules/ it is even smart to alter the MAC also in case you have WebRTC enabled.
After checking WebRTC https://www.youtube.com/watch?v=nRZePB4kzWo seams that ICE servers do not know the local IP address of the pear, and use credentials instead, that will translate to the local IP address on the pear side. However, WebRTC is very complex and complexity is a bad sign usually since unintentional failures may arise. WebRTC test https://test.webrtc.org/ is excellent testing website, the documentation is clear https://webrtc.org/getting-started/overview. Again WebRTC uses Canvas of it's own which opens the canvas fingerprinting pandora. This is why I think your advice is very smart. BTW, the about:webrtc is leaking the local IP address which in conjunction with ~~opening blitz popup bugs~~ in Firefox older versions may lead to leaking IP address. But I guess this is not the WebRTC leak anymore.
