### ISSUE TITLE
Script blocked by Firefox

### ISSUE THREAD

**Issue by InklingLove** [kkapsner/CanvasBlocker#515]
Hi,

When the script blocks because it requires resources from Firefox and we are already on the page in question, during the blocking of the script and therefore the extension, the site had access to our real data? Risk of leaks?

Thanks :)

**Comment by kkapsner** [comment]
No there is not risk of leak and the site has no access to the real data. JavaScript is single threaded in one tab and CB is blocking that. That's why Firefox is complaining.
