### ISSUE TITLE
Slow/lagging loading of sites (Warning of CB slowing Fx)

### ISSUE THREAD

**Issue by MysteryIII** [kkapsner/CanvasBlocker#517]
## Description

On some sites (I think sites with external data loaded) the loading time is very slow and you will only see a bit of data after the other like the loading itself is stuttering.
One of these sites is Github Insights -> Network, like [this](https://github.com/kkapsner/CanvasBlocker/network) or even more [here](https://github.com/topjohnwu/Magisk/network). Another site would be [this](https://www.radioessen.de/artikel/corona-in-essen-zahl-der-faelle-sinkt-548075.html) if you scroll down.

I also made the tests provided in FAQ and everything seems to be fine including all performance tests.

## Expected Behavior

Sites should load without lagging.

## Current Behavior

Sites are lagging, providing the data with lot stuttering.

## Steps to Reproduce (for bugs)

Load provided Links (and scroll down):
[Here](https://github.com/kkapsner/CanvasBlocker/network), [this](https://github.com/topjohnwu/Magisk/network), [there](https://www.radioessen.de/artikel/corona-in-essen-zahl-der-faelle-sinkt-548075.html) and [that](https://www.lidl.de/de/filialsuche/s940).

## Your Environment

* CanvasBlocker Version used: 1.4
* Firefox version incl. 32- or 64-bit: 84.0.1 (64-bit)
* Operating System and version (desktop or mobile): Windows 10
* Installed addons: 

1. Add to Searchbar
2. Canvas Blocker
3. ClearURLs
4. Firefox Multi-Account Containers
5. I don't care about Cookies
6. Linkificator
7. LocalCDN
8. Nano Defender
9. Smart Referrer
10. Stylus
11. uBlock
12. Violentmonkey

## Your Settings

<details>
<summary>Settings</summary>

{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "",
			"protectDOMRect": true,
			"fakeMinimalScreenSize": true
		}
	],
	"hiddenSettings": {
		"audioFakeRate": false,
		"webGLVendor": false,
		"enableStackList": false
	},
	"expandStatus": {
		"protectNavigator": true,
		"blockMode": true,
		"allowWindowNameInFrames": false,
		"protectDOMRect": true,
		"section_DOMRect-API": true,
		"protectScreen": false,
		"showNotifications": true,
		"section_History-API": true,
		"fakeMinimalScreenSize": true
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "input",
	"minFakeSize": 10,
	"maxFakeSize": 0,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 3,
	"minColors": 3,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{}",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1609234230106,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "0.1%",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "13",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {
		"windowManager": "Windows",
		"platform": "Win32",
		"platformDetails": "Windows NT 10.0; Win64; x64",
		"oscpu": "{platformDetails}"
	},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": false,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}

</details>

**Comment by kkapsner** [comment]
I'm not able to reproduce your problem with your settings and only CB installed. Please check with a clean profile and only CB added. Then add the other addons one by one until you see the problem.

**Comment by MysteryIII** [comment]
No sorry, this didn't help.
Just to make sure it's not caused by any weird settings or so, I created a new profile, installed only CB and imported my settings.
Then I opened this [site](https://www.lidl.de/de/filialsuche/s940) and just after some seconds it started to create freezing.
While it looked good on first impression, I couldn't even choose the cookie settings on the popup/layer of the site.

**Comment by kkapsner** [comment]
OK - my bad. Now I can reproduce.

The problem are very big canvas (in your example page the bing map) in combination with the "input" canvas protection mode. For the time being you can allow such big canvas to be not faked by setting the maxFakeSize parameter. But I may have an idea of how to speed this up...

**Comment by MysteryIII** [comment]
Thank you.
Which maximum would you recommend?
Also will your idea help for Github, too? This issue is the same for Insights -> Network. The more activity and participants the more it will lag, so if you look into a very "popular" project it won't stop stuttering and loading all results takes a very long time. But I guess also here the maxFakeSize might help.

**Comment by kkapsner** [comment]
I would recommend a value above 1 000 000 - depending on your PC performance. A faster PC can handle higher values.

Depending on the canvas size (related to screen size) this setting should also help at Github. But if my idea works it should be faster everywhere.

No, you do not need to restart the Browser when changing any CB setting.

**Comment by kkapsner** [comment]
Please check the latest alpha version with maxFakeSize set to 0: https://canvasblocker.kkapsner.de/versions/

**Comment by MysteryIII** [comment]
For the other sites it's working great, thanks! But for GitHub it didn't fix it. [Here](https://github.com/freeCodeCamp/freeCodeCamp/network) you have a very distinct example.

**Comment by kkapsner** [comment]
Github does weird things there: it draws text that is not visible in the canvas. Not sure if I can do anything about it.

**Comment by kkapsner** [comment]
I can make it better - but the performance will never be great on this particular network graph...

**Comment by MysteryIII** [comment]
It's a pity, but thanks for looking into it and your efforts to make it better.

**Comment by kkapsner** [comment]
Please test the latest alpha.

**Comment by MysteryIII** [comment]
There's no more freezing and I think the lag isn't that bad. Also this is one of the most active projects on GitHub (just for a distinct example) and on others there is no big impact.
