### ISSUE TITLE
Only change fingerprint when all tabs for domain are closed

### ISSUE THREAD

**Issue by vertigo220** [kkapsner/CanvasBlocker#518]
CB may already do this, but it's unclear after looking at the description, settings, and issues. Issues #123 and #102 seem to touch on it, but I can't tell if it can do it (and if so, how) or if the desired behavior has been declined by @kkapsner (in which case, I'm hopeful I can convince them).

Essentially, I'm wanting a random fingerprint to be generated for each individual site, as it already does, but I don't want it to change that fingerprint until all tabs for that domain are closed, at which point the next time one is opened it would create a new one. Basically, how Cookies Exterminator works but for FP instead of cookies. This reduces the chances of standing out by having one's fingerprint change constantly within a domain.

It appears the persistent setting is the closest to this, but that sounds like it keeps the FP the same across sessions, whereas I would like it to change each time a domain is freshly opened, whether as part of a new session or by opening it in a tab when it's not opened in any other tabs.

It seems the best approach for handling this would be to have a whitelist for not faking FP info for a domain ever, a blacklist for changing it every time it's freshly loaded, and a grey list for using the same fake FP always, across sessions.

And assuming this can already be done, and that's what the persistent (or some other) setting does, then my suggestion would be to improve the explanation(s) to make that clearer.

**Comment by kkapsner** [comment]
The persistent random number generator is the right place to do something like this. We have the option to clear the persistent data on a regular interval. This might serve you.

Can you specify what your use case is and where you face problems? Fingerprinting data is different to cookies as cookies have a regular use case but fingerprinting not really except tracking.

**Comment by vertigo220** [comment]
I'm not having problems, I just don't think that fingerprints should be constantly changed, as I agree this only makes you stand out more. If a site is tracking you through fingerprinting, there are three scenarios:

- Your fingerprint never changes, and it knows who you are across sessions through the fingerprint
- Your fingerprint constantly changes throughout a session, so even though it can't track you by the fingerprint, it can narrow you down _significantly_ as being one of very few users, if not the only user, that's doing this, so the constantly changing fingerprint essentially acts as its own fingerprint
- Your fingerprint remains the same during a session, so the site doesn't see anything suspicious or "special" about you and thinks it's tracking you, but then when all tabs are closed for that domain, the fingerprint is changed, so next time you visit the site, you appear to be someone different and it thinks it's tracking you (but it thinks you're someone different) again, so you're fooling it into thinking it's working, but it's not, whereas constantly changing the fingerprint you're the one who's actually being fooled

Doing it at a regular interval wouldn't accomplish this. It would have to change when and only when all tabs for the domain are closed. I know fingerprinting isn't the same as cookies, I simply mentioned Cookies Exterminator because that's how fingerprinting _should be_ dealt with, not because they're the same.

**Comment by kkapsner** [comment]
I think I get your point. The fastest way to implement would be to change the regular clearing so it does not clear if a tab/iframe with that domain is still loaded - I guess.

**Comment by vertigo220** [comment]
Sounds like it would work. Thanks!

**Comment by kkapsner** [comment]
Version 1.6 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.6
