### ISSUE TITLE
faked readout on github.com

### ISSUE THREAD

**Issue by monperrus** [kkapsner/CanvasBlocker#52]
I'm really surprised to see "faked readout on github.com".

     Calling file: https://assets-cdn.github.com/assets/frameworks-7d180c2bb5779ecb7ab5d04ce8af999e73836dcf0df1a8c44b69c62a1de0732f.js line 1 column 1776

Does it mean that github does canvas fingerprinting?

**Comment by kkapsner** [comment]
No, this means that github does some sort of canvas readout (the last time I checked it was a kind of emoji support detection).

**Comment by monperrus** [comment]
It is possible to filter real canvas fingerprinting from acceptable
usage such as this one?

For instance, as what was done in the excellent experiments of The web
never forgets
<https://securehomes.esat.kuleuven.be/%7Egacar/persistent/> (function
is_canvas_false_positive
<https://gist.github.com/gunesacar/0c1344bf04667e031574>).

**Comment by kkapsner** [comment]
This filter is a little bit too easy to bypass... and a more complex filter would increase the code base and the CPU load by a huge amount.

So: No.
