### ISSUE TITLE
Firefox Android support

### ISSUE THREAD

**Issue by FlorianJSa** [kkapsner/CanvasBlocker#521]
Currently there is no canvas fingerprint protector for Firefox on Android how about making this Adon available for Firefox on Android

**Comment by kkapsner** [comment]
Unfortunately there is currently no way for me to make it available for (normal) Firefox on Android. You can follow the instructions [here](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) to get it running on Firefox nightly.
