### ISSUE TITLE
Detection prevention and protection at "webbrowsertools.com"

### ISSUE THREAD

**Issue by kurikokata** [kkapsner/CanvasBlocker#526]
Hello.
My environment is firefox 84.0.2 and CanvasBlocker 1.4.
On the following page, is there a setting to enable detection prevention and protection for CanvasBlocker?

Detect Canvas Fingerprint :: WebBrowserTools
https://webbrowsertools.com/canvas-fingerprint/

**Comment by kkapsner** [comment]
You can use the "Stealth" preset to be undetected at that page.

**Comment by kurikokata** [comment]
Thank you for your advice.
I used the "Stealth" preset, but the "red solid box" is not spoofed.

**Comment by kkapsner** [comment]
It should not be spoofed as it is designed to be constant for everybody. It's just an image of a red box.
