### ISSUE TITLE
may be an issue, may be not - open readouts

### ISSUE THREAD

**Issue by ajay-gh** [kkapsner/CanvasBlocker#527]
Hi K.,
I am using github (issue) since it seems your preferred method. So please bear with me if I cannot provide all the data requested.
I've been using the site < ip-check.info > in order to see what they might be able to "learn about my FF browser and my system". Also played with parameters in the CanvasBl interface in order to see what happens.

All in all I saw the expected behavior with exception of two parameters. With jscript switched ON (for the purpose of testing), a custom user agent,  and webGL turned OFF, there engine was able to tell 
a) my browser type as none standard **and static** !  and 
b) the very system I am using (Intel Mac OS X 10.14 ...), also not so common and again static over many tests !

This surprised me a little. Shouldn't such "read-out" values be protected ? So I checked my CanvasBl settings, but couldn't find anything wrong. Can I ask you : aren't these read-outs protected by CanvasBl, and if so, are my settings wrong or incomplete ? My latest settings file is attached, in case you find the time to look it over.

Your help greatly appreciated.
Thanks for a great add-on !!

Ajay

[CanvasBlocker-settings_2021-02-06_10-25-20.json.zip](https://github.com/kkapsner/CanvasBlocker/files/5937075/CanvasBlocker-settings_2021-02-06_10-25-20.json.zip)

**Comment by kkapsner** [comment]
The browser type should change when you enable the navigator protection and set something useful. But userAgent spoofing is not really useful as there are indirect method to get the real OS, browser and build.

The system should also be changed when the navigator protection is used.

How did you set the "custom user agent"?

**Comment by ajay-gh** [comment]
I do agree with what you say, UA spoofing alone cannot do it. But I am using every possible means in FF and add-ons etc. to ensure that indirect methods to deduce my browser or system fingerprint won't work. 
Now back to CanvasBlocker, it did also enable / use the Navigator API, unfortunately with the same result. Making changes in other parts of CanvasBlocker has the expected results on the ip-check website. BUT the two values mentioned before (system and browser type) do not change and do not get spoofed. 
Can you see any reason or could this be a bug due to FF upgrades ?
Thanks again

**Comment by kkapsner** [comment]
Yes - it is container sensitive.

> Thanks for a real great add-on.

You're welcome.
