### ISSUE TITLE
Navigator and DOMRect

### ISSUE THREAD

**Issue by guga14** [kkapsner/CanvasBlocker#529]
As stated in the test page, I'm opening an issue to report test result that are not expected.

# Navigator test
## Expected Behavior
- no line is red or has multiple values (separated by a "|")

## Current Behavior
- appVersion: 5.0 (Windows) | 5.0 (X11)
- platform: Win32 | Linux x86_64
- userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0 | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0

# DOMRect test
## Expected Behavior
- all the hashes and numbers should be equal for the getClientRects and getBoundingClientRect tests

## Current Behavior
- hashes are different

## Your Environment
* CanvasBlocker Version used: 1.5
* Firefox version incl. 32- or 64-bit: 85.0.1 (64-bit)
* Operating System and version (desktop or mobile): Kubuntu 20.04
* Installed addons: ublock, decentraleyes, cookie autodelete and clear URLs

## Your Settings

{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"protectNavigator": false
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "constant",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{}",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": ...,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": false,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "18",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": true,
	"navigatorDetails": {
		"osPreset": "Windows",
		"windowManager": "Windows",
		"platform": "Win32",
		"platformDetails": "Windows NT 10.0; Win64; x64",
		"oscpu": "{platformDetails}",
		"browserPreset": "Firefox",
		"firefoxVersion": "{real Firefox version}",
		"appVersion": "5.0 ({windowManager})",
		"buildID": "20181001000000",
		"productSub": "20100101",
		"userAgent": "Mozilla/5.0 ({platformDetails}; rv:{firefoxVersion}) Gecko/20100101 Firefox/{firefoxVersion}"
	},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment]
The problem with the navigator is #473.

I cannot reproduce the problem with the DOMRect - can you please give me a screenshot?

**Comment by guga14** [comment]
![SS](https://user-images.githubusercontent.com/78984570/108770308-0ebd7f00-7552-11eb-874a-4851623f4448.png)

**Comment by kkapsner** [comment]
Looks fine to me. The "getClientRects" and "getBoundingClientRect" are all the same. The others are not meant to be the same. You can verify with CB disabled.
