### ISSUE TITLE
Browser hang for a few seconds on certain websites

### ISSUE THREAD

**Issue by thegoodthings** [kkapsner/CanvasBlocker#53]
On certain YouTube embed links (those forbidden from embedding, not allowed in certain countries, etc.) ([example link](https://www.youtube.com/embed/sPLEbAVjiLA)), when the page is opened and the play button is clicked, the browser hangs for a few seconds as the notification bar shows.  Disabling notifications lessens the length of the hang, and it only occurs in "fake readout API" mode.

This issue happens with versions 0.2.0 and 0.2.1 - it did not occur with 0.1.8.  I can reproduce this in clean profiles under both Windows 8.1 + Firefox 43beta7 and Debian sid + Iceweasel (Firefox ESR) 38.4.0, so probably not system/config related.

**Comment by kkapsner** [comment]
YouTube reads the content of a big canvas there and the appled faking to these can take some time. Why disabling the notifications reduces the hanging is kind of weird, but the general problem is the size of the canvas.

I am already thinking of an option to disable the faking for big canvas (greater than 1000 pixels) on some parts of the API (especially getImageData()).

**Comment by kkapsner** [comment]
In the next version will be a setting where a maximum area can be set. If a canvas is bigger than that the faking will be disabled for it.

**Comment by jay** [comment]
Will the changes you make allow users to be fingerprinted by way of large canvases?

**Comment by TPS** [comment]
I suppose that'd be correct, @jay, but I think that's why @kkapsner making it _optional_, right?

**Comment by kkapsner** [comment]
Yes, you are both right.

**Comment by kkapsner** [comment]
The new release 0.3.1 includes an option to set a maximum size.
