### ISSUE TITLE
new test see

### ISSUE THREAD

**Issue by xan2204** [kkapsner/CanvasBlocker#531]
hi
on new version CanvasBlocker

test link https://abrahamjuliot.github.io/creepjs/tests/iframes.html

off CanvasBlocker ✔ passed 

on error 
 ✖ expect valid error message in HTMLIFrameElement.prototype.contentWindow
✖ expect valid error message in Element.prototype.appendChild 

also https://abrahamjuliot.github.io/creepjs/

when checkbox on Screen API
Trash
gathered (1)

detalies
1: screen: [1920, 1080, 1920, 1080, 24, 24] does not match iframe

I haven't looked at the other tests, please take a look too.

**Comment by kkapsner** [comment]
I'm working on the first one. Have to dig deeper on the second one.
