### ISSUE TITLE
Can't delete item from "Site specific values"

### ISSUE THREAD

**Issue by moocan** [kkapsner/CanvasBlocker#533]
Hello,

I can't delete any previously added `specific websites` inside for example `API > Canvas API` or `General > Block mode`

## Description
I can add `specific websites` inside `Site specific values` by entering an expression or url and then click on `[+]` but I cannot delete any when I click on `[X]`.
When I click on `[X]`, it changes the value selected in the "Combo Box" (on the left of the "[X]") by the default setting I have chosen for `API> Canvas API` (when done in `API> Canvas API`) or `General> Block mode` (when done in `General> Block mode`) but the entry is not deleted. 

Screen capure of `API > Canvas API` but same behavior in `General > Block mode` attached bellow.

it might not be a bug but just misuse or a step i'm missing 

## Expected Behavior

Delete entry item when I click on `[X]`. 

## Current Behavior

`^ ĥ` in the expression field is because I tried to clear the value, hoping it gets deleted if it's empty.  
![canvas1](https://user-images.githubusercontent.com/21237706/110048222-b7888d00-7d4f-11eb-9627-7fea9658cf9b.png)
![canvas2](https://user-images.githubusercontent.com/21237706/110048232-bc4d4100-7d4f-11eb-91b4-5b0e007a6f13.png)

## Possible Solution

I had success twice with : 
Starting from  `Site specific values` expression field, `tab` to select `Combo Box`,  `tab` to select `[X]` and hit enter => worked once not twice
Zoom in and zoom out several times on the `CanvasBlocker Settings` page and try removing again by clicking` [X] `between zooming until the entry is removed. => worked once 

## Steps to Reproduce (for bugs)

1. see above

## Context

Tested on Firefox 84.0.2 x86_64 with my current profile and with same Firefox with a totaly new profile with only CanvasBlocker add-ons installed.

## Your Environment

* CanvasBlocker Version used: 1.5
* Firefox version incl. 32- or 64-bit: 84.0.2 x86_64
* Operating System and version (desktop or mobile): Linux Ubuntu 20.04 LTS x86_64 (13 inch 1366x768)
* Installed addons:

**Comment by kkapsner** [comment]
The URLs displayed there are a collection of all URLs you entered somewhere for a site specific value. When you delete the last value for that URL the entry disappears:
![Peek 2021-03-05 14-09](https://user-images.githubusercontent.com/1105157/110119926-b0e42f00-7dbc-11eb-904f-90de373014f0.gif)

As seen in your screenshot. The value also gets slightly grayed out which indicates that the "default" value is used.
