### ISSUE TITLE
Browser name LEAKS because of InstallTrigger

### ISSUE THREAD

**Issue by InstallTrigger** [kkapsner/CanvasBlocker#536]
please make these options to block InstallTrigger and fake window.chrome.webstore and other objects
because http://proxyleak.com can detect Firefox name

you can read about it on https://christopherdiehl.github.io/posts/browser-fingerprinting/

thank you

**Comment by kkapsner** [comment]
There are always ways to detect which browser you are using. All the implementation details and browser prefixes (e.g. CSS prefixes) just give it away. And faking all of them would make the browser very slow and it would consume too much time to develop and maintain than I have.
Even different versions can often be detected by feature testing.

I understand why you want to hide in the big pool of Chrome users (and I understand why you do not want to use Chrome) but you will simply only put yourself in the very small group of Firefox users that pretend to use Chrome.

So I'm sorry but this will to be implemented.
