### ISSUE TITLE
Add an option to fake the values for the whitelisted domain, instead of leaving them untouched

### ISSUE THREAD

**Issue by hjk789** [kkapsner/CanvasBlocker#538]
I'm using CanvasBlocker in block all mode, and I noticed that most sites require userAgent and getBoundingClientRect so they can work properly (otherwise they don't even load or the interactions stop working). To make them work again I have to whitelist the Navigator API and the DOMRect API to these sites. However by doing this, all the values from these APIs are left untouched. I would like to suggest an option to choose whether whitelisted APIs should have fake values instead of just the real values.

**Comment by kkapsner** [comment]
Using CanvasBlocker in the blocking mode is not ideal if you want to avoid being tracked/fingerprinted. You place yourself in the small group of people that have Javascript enabled but the APIs are not. I recommend to use the fake mode.

You could try the "ask for permission" mode but I think it will annoy you quite soon.

But I think having a separate blocking mode for each API or a dedicated whitelist mode will add too much complexity for the very small group of people who would use it.

**Comment by hjk789** [comment]
I think fingerprinting is irrelevant when it has too little info about you and when none of this info is connected to your personally identifiable data like full name, phone number, credit card number, social security number, email, house address, etc. Blocking would just make it harder to add entropy to the fingerprint. When it is connected, then it indeed is important.

This wouldn't add complexity as I'm not suggesting adding a dropdown to each API to choose if it will be blocked or faked. Instead what I'm suggesting is adding another item to the Block Mode section of the General tab, something like "Block by default, fake when allowed". It wouldn't need to hold an additional whitelist as it would use the same one, the difference would be in how the list is interpreted (instead of giving out the values untouched, fake them).

**Comment by kkapsner** [comment]
Since faking may also break some web pages I think another block mode is not the best way.
How do you whitelist domain? Do you use the (legacy) whitelist or the URL specific setting for the block mode? Or do you use the page action (menu that appears when you click on the fingerprint icon in the address bar)?

I think changing the page action could be a good way to implement you use case by asking the user if they want to completely allow the domain or only want to fake the values (when currently in block mode).

**Comment by kkapsner** [comment]
This would be the actions available:
![image](https://user-images.githubusercontent.com/1105157/121194926-74b6e380-c86f-11eb-9e3e-8a58b08eac4b.png)
![image](https://user-images.githubusercontent.com/1105157/121194949-7aacc480-c86f-11eb-9475-82c77b446b4a.png)
![image](https://user-images.githubusercontent.com/1105157/121195048-90ba8500-c86f-11eb-8d15-d239c8a2e939.png)
![image](https://user-images.githubusercontent.com/1105157/121195085-99ab5680-c86f-11eb-8085-01ae9c093192.png)
This then leads to this setting:
![image](https://user-images.githubusercontent.com/1105157/121195135-a2039180-c86f-11eb-8d96-b2721e69434e.png)

**Comment by kkapsner** [comment]
Version 1.6 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.6
