### ISSUE TITLE
Red icon

### ISSUE THREAD

**Issue by jakejakes2020** [kkapsner/CanvasBlocker#541]
Why does the icon turn red?
## Description

Does a red icon indicate that a website is fingerprinting me or something else? And "Protection Successful for" means what? That the site is fingerprinting me?

Thanks in advance! ;)

**Comment by kkapsner** [comment]
The icon turns red if CanvasBlocker did something on that page. It does not mean that the web page tried to fingerprint you - it most likely is a legitimate usage of the protected API. It's very hard to distinguish between a fingerprinting attempt and a regular API use.
