### ISSUE TITLE
Feature Request: Font Fingerprinting Negation

### ISSUE THREAD

**Issue by ilikenwf** [kkapsner/CanvasBlocker#542]
This addon does indeed work, and does so very simply:

https://addons.mozilla.org/en-US/firefox/addon/font-fingerprint-defender/

I ended up using it's javascript to do it through violentmonkey, but I could see this technique being useful in canvasblocker since it already handles so many other vectors.

I use Librefox, which already randomizes the canvas and webgl vendor out of the box, but I still use CanvasBlocker to cover the other aspects of the browser that aren't really done well by any other extension.

Thanks for the great work!

**Comment by ilikenwf** [comment]
The JS in the above addon:
```

var inject = function () {
  var rand = {
    "noise": function () {
      var SIGN = Math.random() < Math.random() ? -1 : 1;
      return Math.floor(Math.random() + SIGN * Math.random());
    },
    "sign": function () {
      const tmp = [-1, -1, -1, -1, -1, -1, +1, -1, -1, -1];
      const index = Math.floor(Math.random() * tmp.length);
      return tmp[index];
    }
  };
  //
  Object.defineProperty(HTMLElement.prototype, "offsetHeight", {
    get () {
      const height = Math.floor(this.getBoundingClientRect().height);
      const valid = height && rand.sign() === 1;
      const result = valid ? height + rand.noise() : height;
      //
      if (valid && result !== height) {
        window.top.postMessage("font-fingerprint-defender-alert", '*');
      }
      //
      return result;
    }
  });
  //
  Object.defineProperty(HTMLElement.prototype, "offsetWidth", {
    get () {
      const width = Math.floor(this.getBoundingClientRect().width);
      const valid = width && rand.sign() === 1;
      const result = valid ? width + rand.noise() : width;
      //
      if (valid && result !== width) {
        window.top.postMessage("font-fingerprint-defender-alert", '*');
      }
      //
      return result;
    }
  });
  //
  document.documentElement.dataset.fbscriptallow = true;
};

var script_1 = document.createElement("script");
script_1.textContent = "(" + inject + ")()";
document.documentElement.appendChild(script_1);
script_1.remove();

if (document.documentElement.dataset.fbscriptallow !== "true") {
  var script_2 = document.createElement("script");
  script_2.textContent = `{
    const iframes = [...window.top.document.querySelectorAll("iframe[sandbox]")];
    for (var i = 0; i < iframes.length; i++) {
      if (iframes[i].contentWindow) {
        if (iframes[i].contentWindow.HTMLElement) {
          iframes[i].contentWindow.HTMLElement.prototype.offsetWidth = HTMLElement.prototype.offsetWidth;
          iframes[i].contentWindow.HTMLElement.prototype.offsetHeight = HTMLElement.prototype.offsetHeight;
        }
      }
    }
  }`;
  //
  window.top.document.documentElement.appendChild(script_2);
  script_2.remove();
}
```

**Comment by kkapsner** [comment]
I already had a look at this addon: https://github.com/kkapsner/CanvasBlocker/issues/200#issuecomment-578158039
It's not very good, easy to detect and easy to circumvent.

Although I understand the need for a protection against font fingerprinting and agree that something has to be done against it I see no way to do thing in an addon in responsible way. So my opinion did not change since my last look at it.

**Comment by ilikenwf** [comment]
@kkapsner I believe what Tor does is either rely on RFP or there are a series of prefs, I forget the name off the top of my head, that restrict, based on the OS tor browser is running on, to a set list - I think a whitelist or standard list...and Tor typically brings those fonts with it on Linux so that everyone looks the same...

I know that CanvasBlocker aims more to randomize everyone everywhere but I tend to use it in a way that mixes blending with the crowd, but then also randomizing the fingerprints of canvas and webgl...without having to use RFP.
