### ISSUE TITLE
Is it show the fake value of "active plugins/plugins details" ? 

### ISSUE THREAD

**Issue by androidphone7** [kkapsner/CanvasBlocker#543]

**Comment by kkapsner** [comment]
I'm sorry, but I do not understand the question.

**Comment by androidphone7** [comment]
Hey thanks for your response. 


Actually, i want to know that  "is the canvasblocker hide or report fake value to website of how many add ons i am using on browser" ?

**Comment by kkapsner** [comment]
Information about the used  addons (webExtensions) should not be accessible for a web page (unless the addon explicitly exposes this information) and plugins should also not be detectable in Firefox directly (I have two plugins in my firefox and `navigator.plugins` returns an empty list). So there is no apparent need for a protection.

Or do you have a specific attack vector in mind that works in Firefox?

**Comment by androidphone7** [comment]
Thank you so much. :-)
