### ISSUE TITLE
random number generator: persistent  
(Its not working properly) 

### ISSUE THREAD

**Issue by androidphone7** [kkapsner/CanvasBlocker#544]
Hello...

I have changed the setting of random number generator to persistent.

I am using browserleaks to check. 
1st time its showing a random value which is should not be change after reload, 
but if i reload its changing the value. 

After changing the value 1 time, its working well...not changing the value again.  

And if i use new tab its also showing the different value. And after reload its showing the same value of other tab.

**Comment by emmetts** [comment]
Hello there. I encountered the same issue today, and I have figured it out.

If you want to show a persistent value to website A, you can open up a website B (you don't care about it) on a new tab. Then open website A on this tab. I tested the approach to fix the issue on browserleaks/canvas.

There are two reasons cause this issue:
1. required.js isn't loaded before initializing the extensions. A warn log is on console "[CanvasBlocker] invalid content script order: require not defined at {url}". It's easy to fix it by adding {file: "/lib/require.js"} on the line 31 of lib/main.js
2. The extension isn't initialized before browserleaks/canvas starts reading canvas fingerprint. For this reason, I haven't fixed it by code yet.

@kkapsner Please help check if I am correct. Thanks.

**Comment by kkapsner** [comment]
I confirmed that the problem only exists for the very first page that is loaded in a new tab. I guess it's a loading order problem but do not (yet) know what causes the problem exactly. To be honest I have the suspicion that it's a Firefox bug... but I have to investigate further first.

**Comment by kkapsner** [comment]
But as far as I see your true fingerprint does not leak.

**Comment by kkapsner** [comment]
I found the problem - but I do yet know how to solve it.

**Comment by kkapsner** [comment]
Version 1.6 is out: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.6
