### ISSUE TITLE
It only displays half of the photos on facebook profiles !

### ISSUE THREAD

**Issue by grysor** [kkapsner/CanvasBlocker#547]
On my firefox browser,the extension causes Facebook profiles to bug  :  only half of the photos of Facebook profiles are displayed !
example on this page : 
https://www.facebook.com/patrik.schlupf/photos

by scrolling to the bottom, the rest of the photos are no longer displayed ! while there is still half to see !
As soon as i deactivate canvasblocker then refresh the page, everything works again, the rest of the photos are displayed well.

how to solve this problem please?

**Comment by kkapsner** [comment]
It's working for me.

What settings are you using?

**Comment by kkapsner** [comment]
No answer for more than one month. So I guess the problem is gone. If it still exists please provide your settings and I can reopen this issue.
