### ISSUE TITLE
How to load the extension?

### ISSUE THREAD

**Issue by git-avinash** [kkapsner/CanvasBlocker#549]
I'm getting this error:
Name of a key "askdenymode_options.block" is invalid. Only ASCII [a-z], [A-Z], [0-9] and "_" are allowed.
Could not load manifest.

**Comment by kkapsner** [comment]
This is very weird. These keys part of CB since a very long time and I never saw any problems with them.

Which Browser (version) are you using?
When and where do you see this message?
How did you try to install CB?

**Comment by git-avinash** [comment]
I'm using chrome v90.x
I'm downloading the repo and adding the folder as the extension.

**Comment by kkapsner** [comment]
CanvasBlocker does not work in Chrome and is not designed to do so. See #65 and #145 for more information.
