### ISSUE TITLE
Why is kkapsner.de whitelisted?

### ISSUE THREAD

**Issue by Fritzer** [kkapsner/CanvasBlocker#55]
KKapsner said:
> At present, only my domain (kkapsner.de) is whitelisted by default.

* Why is your domain whitelisted in CanvasBlocker?
* Does CanvasBlocker contact your domain during operation?
* Can it be removed from the White list?

I notice your domain is still "Under construction."

**Comment by kkapsner** [comment]
1. This is just for my convenience.
2. No contact to my domain
3. Yes.
