### ISSUE TITLE
Cannot delete whitelisted URL

### ISSUE THREAD

**Issue by sbs4000** [kkapsner/CanvasBlocker#550]
## Description

When I click on the cross X next to a whitelisted URL (in the APIs tab), nothing happens. I'm assuming that this X is there to delete the URL. If not, how do I delete a whitelisted URL?

## Current Behavior

Nothing happens when I click X next to an URL.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CanvasBlocker Version used:
* Firefox version incl. 32- or 64-bit:
* Operating System and version (desktop or mobile):
* Installed addons:
Firefox latestest version.

**Comment by kkapsner** [comment]
When the entry is slightly greyed out it uses the default value. You have another setting set different for this URL. And for convenience reasons it's displayed then on all settings. You have to delete the value everywhere. Then you will get rid of the URL.

![grafik](https://user-images.githubusercontent.com/1105157/117189075-0f8a5100-adde-11eb-80d2-f50475e62c79.png)
vs
![grafik](https://user-images.githubusercontent.com/1105157/117189097-16b15f00-adde-11eb-88b3-c6c19133733e.png)

**Comment by sbs4000** [comment]
Thanks a lot. It was a hidden parameter that was set (historylength, don't know how this happened) so I had to enable hidden parameters first. That's why.
I would suggest to mention somewhere how to delete an URL: you have to set all parameters to default (by clicking on the X) and then the URL disappears by magic with the last one (but it has to be really the last one, including hidden parameters, that's the trick).

**Comment by kkapsner** [comment]
As this topic popped up several times already I think I should create a [FAQ](https://canvasblocker.kkapsner.de/faq/) for that.
