### ISSUE TITLE
Cannot change display language

### ISSUE THREAD

**Issue by sbs4000** [kkapsner/CanvasBlocker#551]
## Description

While it is nice to provide translations, they are usually barely understandable. Swithching to English is better but I found no way to do it. The addon takes the browser language automatically.

## Expected Behavior

Provide a way to force English language for the addon.

## Current Behavior

The addon takes the browser language.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CanvasBlocker Version used:
* Firefox version incl. 32- or 64-bit:
* Operating System and version (desktop or mobile):
* Installed addons:

**Comment by kkapsner** [comment]
Which translation is bad? You can help to improve it at https://crowdin.com/project/canvasblocker
Since WebExtensions do not provide an API to switch the language you have to use the browser tools available. Maybe [this](https://blog.mozilla.org/l10n/2019/04/02/changing-the-language-of-firefox-directly-from-the-browser/) helps. I do not plan to implement my own internationalization system.

**Comment by sbs4000** [comment]
I was just thinking of forcing English, no other language and I agree, certainly not an internationlization system, just English or the default browser language. But if it is not possible, no problem, I fully understand.
I'll have a look at helping with the translation (French). Your addon is absolutely great. I compared several, and you are the only one that resists all methods to reveal the real OS.

**Comment by sbs4000** [comment]
I just fixed a number of translations. Let me know if this is ok before I continue.

**Comment by kkapsner** [comment]
Yes, it's ok. My French is not good but your corrections seem fine.

**Comment by spodermenpls** [comment]
@theAlinP If you have a free minute, maybe you can proofread too, since you seem to be fluent in French.

**Comment by theAlinP** [comment]
> @theAlinP If you have a free minute, maybe you can proofread too, since you seem to be fluent in French.

Sure, I'll see if there's something that I can improve.

**Comment by kkapsner** [comment]
Thanks for the participation. Keep on translating but I will close this issue as it's no longer necessary.
