### ISSUE TITLE
Get CanvasBlocker Promoted on AMO

### ISSUE THREAD

**Issue by Riajyuu** [kkapsner/CanvasBlocker#553]
## Description

As per https://extensionworkshop.com/documentation/publish/recommended-extensions/
I believe this extension meets all requirements to be promoted officially.

badge on AMO:
![image](https://user-images.githubusercontent.com/16912240/118206129-65bd5b00-b494-11eb-891a-6519661105cd.png)

badge on about:addon:
![image](https://user-images.githubusercontent.com/16912240/118206171-81286600-b494-11eb-9913-af6e1302b137.png)

**Comment by DGjone44** [comment]
Selection process

While the Recommended program will always be on the lookout for great new extensions, the collection is intended to remain fairly fixed over time. Our aim is to promote Recommended extensions that Firefox users can trust to be secure and exceptional over the lifespan of the extension. This is achieved by nurturing a tightly curated list of extensions.

If you’d like to nominate an extension you feel deserves consideration for the Recommended program—even if it’s one of your own—please email us a link to its AMO listing page at amo-featured [at] mozilla [dot] org and briefly explain why you think your extension should be considered for the Recommended list.

**Comment by kkapsner** [comment]
I'm not sure if it's better if I nominate CB myself as the creator or if a user does it. I think user feedback counts more (and even so if more than one nominates CB).

Anyway I just wrote the mail - let's see what the response is.

**Comment by kkapsner** [comment]
Version 1.8 is currently in review for being recommended.

**Comment by kkapsner** [comment]
![image](https://user-images.githubusercontent.com/1105157/154723468-f53ac1f7-5d3f-4ebb-93cb-aa7aa01d9f4b.png)
