### ISSUE TITLE
Washington Post not impacted by CanvasBlocker

### ISSUE THREAD

**Issue by WhatNameDoYouMean** [kkapsner/CanvasBlocker#554]
## Description
Up until Friday, Washingtonpost.com allowed me to read as many articles as I wanted; and now it limits to 3 per day; no cookies are being set, so apparently they've found away around CanvasBlocker

## Expected Behavior
I'd like CanvasBlocker to return to its previous functionality.

## Steps to Reproduce (for bugs)

1.  Activate CanvasBlocker on FireFox (latest version of both)
2.  go to WashingtonPost.com and open more than 3 articles
3.
4.

## Your Environment

* CanvasBlocker Version used:  1.5
* Firefox version incl. 32- or 64-bit: 64-bit
* Operating System and version (desktop or mobile):  Windows 10
* Installed addons:  NoScript; Ghostery; AdBlock; FireShot; McAfee WebAdvisor; DuckDuckGo Privacy Essentials

## Your Settings
I only see tabs for Details and Permissions; no button for Expert mode.

**Comment by Riajyuu** [comment]
![image](https://user-images.githubusercontent.com/16912240/119095316-b6a8f280-ba44-11eb-8f09-f7ed2e2499c2.png)

I found no issue at all

**Comment by kkapsner** [comment]
They have to store something in cookies or localStorage. I use Cookie Auto Delete and if I close all tabs of that domain (and wait a little bit) the paywall gets away.

BUT to be clear: CanvasBlocker was not designed to leverage and does not encourage theft (which is what you are doing basically). If you like the articles at this page you should consider paying for it - the people writing these have to live from something as well.
