### ISSUE TITLE
CanvasBlocker slowing down FF on ebay.com.au

### ISSUE THREAD

**Issue by plague-doctor** [kkapsner/CanvasBlocker#555]
CanvasBlocker is slowing down Firefox 89.0 (64-bit) Linux Arch while searching on eBay.com.au. Website hangs completely for long seconds.

## Steps to Reproduce (for bugs)

1. Go to https://www.ebay.com.au
2. Search for something
3. Scroll down... Scroll more... A bit more...
4. Suffer :-(

## Your Environment

* CanvasBlocker Version used: 1.5
* Firefox version incl. 32- or 64-bit:  89.0 (64-bit) 
* Operating System and version (desktop or mobile): Linux Arch
* Installed addons: CSS Exfil Protection, Decentraleyes, Temporary Containers, Firefox Multi-Account Containers, uBlock Origin, uMatrix

## Your Settings

```
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {
		"displayAdvancedSettings": true,
		"blockMode": true
	},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "-------",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{}",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1622000009236,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "2",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"isStillDefault": false,
	"storageVersion": 1
}
```

**Comment by DGjone44** [comment]
Try selecting Canvas part to : Readout instead Input.

**Comment by kkapsner** [comment]
I can reproduce the problem and don't think it's the Canvas API but the DOMRect API:
![image](https://user-images.githubusercontent.com/1105157/120891409-cf9ad180-c608-11eb-93da-941ac60cdc9e.png)

Unfortunately I think there is little I can do to improve this situation (the DOMRect API is already highly optimized),
Since the problem is less apparent on ebay.com: 
![image](https://user-images.githubusercontent.com/1105157/120891494-459f3880-c609-11eb-962b-ecd8c324a1d7.png)
I would suggest that you whitelist ebay.com.au for this API.
