### ISSUE TITLE
Blocks certain functions on Twitter

### ISSUE THREAD

**Issue by TheJanzap** [kkapsner/CanvasBlocker#56]
I discovered that this addon blocks cetain functions on Twitter.com such as:
-Hashtags in tweets
-"Tweet" button
-"Follow" button
-"Direct Message" button

A possible solution to this problem would be to default whitelist twitter.com
But anyways keep up the good work!

**Comment by berrythesoftwarecodeprogrammar** [comment]
i mean when you go to twitter don't you get a canvasblocker notification? from there you can whitelist it yourself. there doesnt need to be a default whitelist

**Comment by kkapsner** [comment]
@TheJanzap: it seems that you are not using the fake mode. This mode should not block any functionality that just uses canvas to display something.

PS: I will not whitelist twitter.com by default for sure.
