### ISSUE TITLE
CanvasBlocker is causing ebay.co.uk to freeze

### ISSUE THREAD

**Issue by xpseudonym** [kkapsner/CanvasBlocker#563]
![Screenshot from 2021-06-15 17-37-36](https://user-images.githubusercontent.com/5032475/122092658-160ae000-ce02-11eb-925c-45f685d5db81.png)

Using ebay.co.uk is frozen by CanvasBlocker
## Description

See attached screenshot

## Expected Behavior

ebay.co.uk should be usable as if CanvasBlocker was not installed

## Current Behavior

CanvasBlocker causes ebay.co.uk to freeze

## Possible Solution

Remove CanvasBlocker...?  Not really a solution, sorry

## Steps to Reproduce (for bugs)

1.Install CanvasBlocker
2.Surf ebay.co.uk
3.
4.

## Context

I'm unable to use ebay.co.uk

## Your Environment

* CanvasBlocker Version used:
Version
1.5
* Firefox version incl. 32- or 64-bit: 78.11.0esr (64-bit)
* Operating System and version (desktop or mobile): Debian GNU/Linux 10 (buster); Gnome 3.30.2
* Installed addons: I can't see how to easily obtain this information

## Your Settings

[CanvasBlocker-settings_2021-06-15_17-46-52.json.txt](https://github.com/kkapsner/CanvasBlocker/files/6657331/CanvasBlocker-settings_2021-06-15_17-46-52.json.txt)

**Comment by wishIwastechsupport** [comment]
Hi! 

CanvasBlocker can be a resource intensive add-on to have installed in a browser, especially with websites that have a fair amount of information to be spoofed. I had a read of your settings and this is what I think:

As you are using the "fake" mode as well as the "non-persistent" mode, CanvasBlocker has to fake each readout _every time_  you load an element that has to be faked. Hence, for a website like eBay, there are a lot of elements to fake. I visited eBay UK myself, and there were a lot of elements that were being faked when I loaded the page.

**Behavior observed:** 

I have set my version of CanvasBlocker to your settings and have been unable to replicate this issue. This looks like an issue with the loading of 1 particular site, so I can assume this may be an isolated problem.

**Possible solutions:** 

1. I would recommend using the "persistent" mode in the "faking" menu. Some would argue that this is less secure, however it still spoofs your fingerprint, and would probably make CanvasBlocker run faster. All this does is keep your fingerprint consistent on that domain. It prevents your fingerprint being used in cross site tracking, and can also make the plugin harder to detect. If you're signed in to eBay, fingerprint protection is useless anyway, as you're already being tracked via your account and the cookie that you use to keep logged in. 

2. Disable some other browser extensions. I can see from your screenshot that you have a fair few other extensions like uBlock origin and others. Though there are usually few conflicts, these plugins will also slow down your browser. I know this might seem obvious, but if those plugins are altering the things canvas blocker needs to work with, it will slow down the plugin. 

3. Close some other browser tabs. I see you have a lot of tabs open. Whilst I'm guilty of this too, even when idle, those tabs take up computing power. If you have a lots of pages in which CanvasBlocker is being used, just think- that would be 10+ pages, all in which faking is occurring. Depending on your platform you may struggle with this.

4. Whitelist ebay.co.uk. Whilst not the most optimum solution, this sounds like your best option. If you just want functionality of that one site, just whitelist the top level URL. This would probably fix the problem, and I refer back to point 1- fingerprint spoofing isn't very useful when you are already carrying a cookie anyway. If you're faking it everywhere else, then you dont have a fingerprint to track, so this might be a good option for you.



Please try these steps. If they do not work please post again with additional information in regards to how this can be replicated.

Regards, 
Hafiz

**Comment by kkapsner** [comment]
As far as I know it's the same issue as #555. Unfortunately there is little I can do about that. I would recommend to just whitelist the DOMRect API for that domain.

**Comment by xpseudonym** [comment]
Thanks @wishIwastechsupport for your very detailed support.  I've saved all my tabs and started afresh - I do this periodically, but probably not periodically enough (all those jobs that'll never get done!!!)
@kkapsner & @wishIwastechsupport have I correctly whitelisted ebay.co.uk for the correct API in the image below:
![Screenshot from 2021-06-20 09-35-51](https://user-images.githubusercontent.com/5032475/122667497-05b08780-d1ab-11eb-80c8-72b82f8b7bea.png)
?
Thanks

**Comment by kkapsner** [comment]
Yes, this looks correct. Does it now work properly?

**Comment by xpseudonym** [comment]
Yup, that seems to have fixed it - thanks.

**Comment by kkapsner** [comment]
You're welcome.

**Comment by spodermenpls** [comment]
@kkapsner 
> As far as I know it's the same issue as #555. Unfortunately there is little I can do about that. I would recommend to just whitelist the DOMRect API for that domain.

I've ran into the same issue now on German ebay.de, so I'd suggest to add an DOMRect whitelist exception for ebay.* (TLD-agnostic) to the convenience preset.

**Comment by kkapsner** [comment]
I think it was just some UI/UX testing from ebay and they changed it again...
But as soon as it appears again and stays I will add it to the convenience preset.

**Comment by spodermenpls** [comment]
> I think it was just some UI/UX testing from ebay and they changed it again... But as soon as it appears again and stays I will add it to the convenience preset.

@kkapsner eBay continues to make problems, I ran into the same issues today. I tried deactivating notifications for ebay.de first, however that didn't change anything, only deactivating DOMRect protection for the domain did solve the issue (as it did in July 2021). I would therefore be pleased if you could follow through on my proposal from back then:

> I've ran into the same issue now on German ebay.de, so I'd suggest to add an DOMRect whitelist entry for ebay.* (ideally TLD-agnostic, if you're able to craft a RegEx that covers all eventualities [e.g. ".co.uk"]) to the convenience preset.

**Comment by spodermenpls** [comment]
@kkapsner Thank you very much! That's quite the RegEx for eBay.. 😅

**Comment by kkapsner** [comment]
No problem.

Yes, it has capture all ebay tld domains but has to also NOT capture a random domain that contains "ebay" somewhere...

**Comment by spodermenpls** [comment]
@kkapsner I think the `facebook.com` entry can be removed again from the preset, it is running stable again with activated DOMRect protection.

**Comment by kkapsner** [comment]
@spodermenpls: I follow your lead here as I do not use facebook at all...

**Comment by spodermenpls** [comment]
@kkapsner Good to see you back. Does the RegEx for eBay still work on your end? When I copy-pasted it in the settings for the DOMRect API (and removed the checkmark) the DOMRect still gets protection on ebay.de and so on on my end.

**Comment by kkapsner** [comment]
The convenience preset still works for me.
When you paste you have to make sure to remove the masking: `"^https://[^/]*ebay\\.([a-z]+|com\\.(au|hk|my|sg)|co\\.uk)(/|$)"` -> `^https://[^/]*ebay\.([a-z]+|com\.(au|hk|my|sg)|co\.uk)(/|$)`

**Comment by spodermenpls** [comment]
@kkapsner Ah, so the double `//` were the issue, thanks.

**Comment by kkapsner** [comment]
You're welcome.

BTW: I sent version 1.10 to Mozilla - so now we have to wait for them to validate it...
