### ISSUE TITLE
canvas and textMetrics are not Fake reading out on some website.

### ISSUE THREAD

**Issue by prompt53** [kkapsner/CanvasBlocker#567]
I am using one more add on is sereneblue/chameleon.

when I am using profiles of windows, iOS and android ( Firefox ) canvas and textMetrics both are reading out. 
But I if use android ( chrome ) profiles, its not reading out. 

The only problem with android (chrome) profiles.

**Comment by 1nousername** [comment]
hello, I've also seen this kind of issue on some website.  here is the link: https://emmamadchen.de/landing2?

**Comment by kkapsner** [comment]
What do you mean with "android (chrome) profile"? CanvasBlocker does not work with Chrome:  #145

**Comment by DGjone44** [comment]
> 
> 
> What do you mean with "android (chrome) profile"? CanvasBlocker does not work with Chrome: #145

I think he meant, User Agent set to Android-Chrome.

**Comment by prompt53** [comment]
Actually, I am talking about (sereneblue/chameleon) addon's  android-chrome profile.

 "chameleon" addon have many profiles, IOS, windows, andriod. 

when I am using other profiles and also android-firefox  its reading out canvas. 

but when I am using android-chrome profile its not reading out canvas.

**Comment by kkapsner** [comment]
I'm not able to reproduce the problem. Please give me a specific reproduction scenario.

Does disabling and re-enabling the two addons in different order solve the problem?
