### ISSUE TITLE
to use Selenium Chromium Based Browser ( Edge Browser )

### ISSUE THREAD

**Issue by eix128** [kkapsner/CanvasBlocker#568]
Hi , i wanted to use WebGL spoof on Selenium Based Browser
How to use WebGL , Canvas , Audio spoof on Selenium Java ?
I can run script on page load.
But which scripts do i need first order ?
then call what functions ?

**Comment by DGjone44** [comment]
I read CanvasBlocker is made for firefox.

**Comment by eix128** [comment]
Its javascript it should also work on chrome.I have seen same example on chrome also

**Comment by kkapsner** [comment]
It would if Chrome had the proper API to enable interaction between page scripts and addon scripts. See #65 and #145 for more information.
