### ISSUE TITLE
fingerprinting technique, named scheme flooding

### ISSUE THREAD

**Issue by iamjfk11** [kkapsner/CanvasBlocker#569]
## Description

hello, I am a regular user of CanvasBlocker, for years now, really good
I wanted to ask about this new fingerprinting technique
Does CanvasBlocker recognize it and protect us? It seems like no
will it do it in the future?

ref 1 : https://securityaffairs.co/wordpress/117933/digital-id/fingerprinting-technique-scheme-flooding.html
ref 2 : https://fingerprintjs.com/blog/external-protocol-flooding/
ref 3 : https://github.com/fingerprintjs/external-protocol-flooding
test page https://schemeflood.com/

version 1.6.1

**Comment by kkapsner** [comment]
CanvasBlocker does not protect against it and I'm not sure if it can. I will have a look.

But to be honest I think this should be addressed by Mozilla/Tor.

**Comment by iamjfk11** [comment]
thanks for your consideration
I appreciate to compliment you for the work you do with canvasblocker
I assume that torproject is already aware of the new technique
in my experience only disabling js in the torbrowser can be avoided
while with js enabled and html5 canvas enabled and / or disabled
the fingerprint also works in torbrowser
bye thank you

**Comment by Thorin-Oakenpants** [comment]
fyi:
- Tor: [40432](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40432) resolved fixed
- Bugzilla: [1711084](https://bugzilla.mozilla.org/show_bug.cgi?id=1711084) open

**Comment by Thorin-Oakenpants** [comment]
FF96+: [ACCESS DENIED: Bug 1723281](https://bugzilla.mozilla.org/show_bug.cgi?id=1723281) mark XHR load being an error load when send() fails
- https://hg.mozilla.org/mozilla-central/rev/b735ff2a23fd47ea0f2425f119e4f961e5cf8e5b

What does it all mean? It means this will be [fixed upstream](https://bugzilla.mozilla.org/show_bug.cgi?id=1711084#c12)

**Comment by kkapsner** [comment]
That's my preferred solution of this problem.
