### ISSUE TITLE
Warning with PDF.js

### ISSUE THREAD

**Issue by julienschmidt** [kkapsner/CanvasBlocker#57]
Currently it shows me a warning every time I open a PDF file in Firefox with PDF.js.
It would be nice if either
- the calling file resource://pdf.js/build/pdf.js could be whitelisted / ignored by default
- there would be an option to whitelist / ignore calling files instead

**Comment by kkapsner** [comment]
Whitelisting PDFs was done in previous version. But I removed it due to the possibility of bypassing the addon.

The option of whitelisting based on files is included in the branch stacklist as mentioned in #47. I will release a new version for that soon.

**Comment by julienschmidt** [comment]
Is there more info on the potential bypass available? Would whitelisting `resource://pdf.js/build/pdf.js` enable this bypass again?

**Comment by kkapsner** [comment]
the first approach was to allow the canvas-API in every document that has the pdf content type. Therefore a site could incorporate a iframe with a pdf with the same origin and use the API of this to create a fingerprint.

The whitelisting of this JS-file would not enable this bypass again

**Comment by julienschmidt** [comment]
Thanks for the explanation.
Since it ships with firefox, I'd suggest to whitelist `resource://pdf.js/build/pdf.js` then, if #47 gets merged into master.

**Comment by kkapsner** [comment]
This type of whitelist is disabled by default because it introduces a big overhead. So adding pdf.js to the list by default does not do anything.

**Comment by kkapsner** [comment]
In the script whitelist has to be ```[{"url": "resource://pdf.js/web/viewer.js"}]``` so that CB whitelists the PDF.js
