### ISSUE TITLE
CanvasBlocker interferes with built in Popup blocker for local files

### ISSUE THREAD

**Issue by schlaubstar** [kkapsner/CanvasBlocker#573]
## Description
To open several links in different tabs on demand I have created a local HTML file with a button, tied to a javascript function that uses "window.open(url)" repeatedly and opens several ULRs in tabs.
The first time, you execute this script, built in popup blocker will step in and you have to add either the local html file as an exception. After that, this works flawlessly.
If you install CanvasBlocker the behavior changes: Calling the function the first time (opening the tabs) works. If you browsed a while (and most likely visited websites that triggered canvas blocker) and you execute the function again then the firefox popup blocker will step in again (although an exception is set). The only thing that helps to make the script work again is restarting FF.

## Expected Behavior
The behavior of popups caused from local files should not be affected by the availability of canvas blocker.

## Current Behavior
As mentioned in the description: Popups are blocked from local files although the file is whitlisted in FF

## Steps to Reproduce (for bugs)
1. Extract the HTML file from attached ZIP file and store it locally
2. Open the HTML and click "open sites"
3. Go back to the tab with test.html and create exception for popups from that file
4. close all tabs opened from the "test.html" tab and try out again > will work
5. close all tabs opened from the "test.html" and visit e.g. google.com in the tab that shows test.html
6. go back to test.html and click again > will not work, although exception is set
7. you can now either restart Firefox to make it work again

## Your Environment
* CanvasBlocker Version used: 1.61
* Firefox version incl. 32- or 64-bit: 90.0.1 (64-bit)
* Operating System and version (desktop or mobile): Windows 10 desktop, 21H1
* Installed addons: not relevant as a clean installation with Canvas blocker causes the issue

## Your Settings
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"protectNavigator": false
	},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": xxxxx,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "10",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "dark",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by schlaubstar** [comment]
[test.zip](https://github.com/kkapsner/CanvasBlocker/files/6860431/test.zip)

**Comment by kkapsner** [comment]
I can reproduce your problem. But I have no clue what causes this behaviour. Need a deeper investigation.

**Comment by kkapsner** [comment]
It seems it's nothing special with CanvasBlocker but a bug in Firefox when using [browser.contentScripts.register](https://bugzilla.mozilla.org/show_bug.cgi?id=1738713).

So Unfortuntely there is nothing more I can do about that.

**Comment by schlaubstar** [comment]
Thank you so much for investigating and opening the issue @ Mozilla !

**Comment by kkapsner** [comment]
You're welcome. Let's see how long it takes for Mozilla to fix that.

**Comment by kkapsner** [comment]
That was quite quick. The issue is solved in the nightly build of Firefox. So it should be fixed when Firefox 96 comes out.

**Comment by schlaubstar** [comment]
Thank you so much for identifying the issue and addressing it at Mozilla !

**Comment by kkapsner** [comment]
You're welcome.
