### ISSUE TITLE
Settings resets themselves after some time

### ISSUE THREAD

**Issue by Manwithpants812** [kkapsner/CanvasBlocker#574]
## Current Behavior
Settings reset themselves after an undetermined cause and/or after undetermined amount of time.
Last time I changed any CanvasBlocker settings was 3 weeks ago.

## Expected Behavior
For settings to not reset themselves.

## Possible Solution
2 things I can think off, low disk space led to settings erasing themselves or Firefox update reset the settings by mistake.

I think at one point I closed Firefox with near or 0kb disk space left. I've noticed other applications lose their settings when there's low disk space because they try to save the settings once the program closes but, because there's no disk space, it can't save the settings file and overwrites the existing data with a corrupt/incomplete/empty file. If persistentRndStorage is constantly storing new info, perhaps it has to do with this if it's stored inside the same file all the other settings are.  Speculation but don't know if this is the case here. 

Firefox also auto-updated since I last touched CanvasBlocker's settings. Maybe auto-update did something funky?

Windows Updates installed some updates some few days ago. Extra bone just in case.

## Steps to Reproduce (for bugs)
1. Set different settings
2. Wait some time...
3. [insert unknown cause here]
4. Settings reset themselves

## Your Environment

Win10
Firefox 90.0.2 (64-bit) - Auto-Updated July 24, 2021
Canvas Blocker Version: 1.6.1 - Last Updated: June 28, 2021
Last time I changed CanvasBlocker's settings: July 9, 2021 (I know because I exported them into a json file).

## Your Settings

Below are the settings I had saved 3 weeks ago and want to use, not the resetted settings I found (I didn't save them).

{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"fakeMinimalScreenSize": true,
		"section_Canvas-API": true,
		"blockMode": false
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "persistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": REMOVED
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1625843775418,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "3",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment]
I have no clue what happened there. The handling of the storage is completely done by Firefox and the web-extension has to

**Comment by kkapsner** [comment]
As I got no further response and I cannot do anything I will close this issue.
