### ISSUE TITLE
[feature request]browserAction QoL improvements?

### ISSUE THREAD

**Issue by Jee-Hex** [kkapsner/CanvasBlocker#576]
## Description

Unlike most WebExtensions, CanvasBlocker's browserAction menu does not close itself automatically when, for example, the Settings button is clicked on. Apparently this goes all the way back to at least 0.5.8 but I only noticed this after upgrading to 1.6.1. I believe this can be useful when I need to quickly open both the Settings page and Test page, but it would be nice if there is an option to allow the browserAction menu to auto-close when a new page is opened by the extension.

**Comment by kkapsner** [comment]
I think our use case of quickly opening two pages there is too rare to justify another setting. So I will change the behaviour to close the browserAction when a new page is opened.

**Comment by kkapsner** [comment]
Release 1.7 is published: https://github.com/kkapsner/CanvasBlocker/releases/tag/1.7
