### ISSUE TITLE
Bypass CanvasBlocker using iframe #2

### ISSUE THREAD

**Issue by 14550** [kkapsner/CanvasBlocker#58]
Hello,

websites can circumvent the CanvasBlocker addon easily. It is possible to generate reproducible canvas images/fingerprints while CanvasBlocker is running in fake mode.

I tested CanvasBlocker versions 0.2.1, 0.2.0 and 0.1.8 from AMO and they all failed in fake mode with Firefox 42 on Linux.
This behavior was already reported before as issue #31. I don't understand why this case was closed.

Here is what I did:
1.) Write an html file with the following content. This is a slightly modified version, the original is from user DocumentRoot and can be found here: https://github.com/kkapsner/CanvasBlocker/issues/31#issuecomment-127083390

    <html><body>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <iframe id="iframe" sandbox="allow-same-origin" style="display:none"></iframe>
    <script>
    (function()
      { console.log('after : '+after());
      })();
    
    function after()
    { var fp_text = "BrowserLeaks,com <canvas> 1.0";
    
      // create window canvas
      var canvas = document.createElement('canvas');
      canvas.setAttribute("width", 220);
      canvas.setAttribute("height", 30);
    
      // draw image in window canvas
      var ctx = canvas.getContext('2d');
      ctx.textBaseline = "top";
      ctx.font = "14px 'Arial'";
      ctx.textBaseline = "alphabetic";
      ctx.fillStyle = "#f60";
      ctx.fillRect(125, 1, 62, 20);
      ctx.fillStyle = "#069";
      ctx.fillText(fp_text, 2, 15);
      ctx.fillStyle = "rgba(102, 204, 0, 0.7)";
      ctx.fillText(fp_text, 4, 17);
    
      // create iframe canvas and ctx
      var iframe_canvas = document.getElementById("iframe").contentDocument.createElement('canvas');
      iframe_canvas.setAttribute("width", 220);
      iframe_canvas.setAttribute("height", 30);
      var iframe_ctx = iframe_canvas.getContext('2d');
    
      // copy image from window canvas to iframe ctx
      iframe_ctx.drawImage(canvas, 0, 0);
    
      return iframe_canvas.toDataURL();
    }
    </script>
    </body></html>
2.) copy the file to a webserver and open it with Firefox.
3.) copy the data-url from the browser log to the Firefox address bar and watch the image.

CanvasBlocker makes barely visible changes to canvas images normally. It might not be obvious if a canvas image had been changed or not.
The output of this test is the unmodified image, you can see it at the homogenous orange part of the image.
To make it more obvious that the CanvasBlocker code isn't executed, you can modify line 52 in modifiedAPI.js

    data[i] = 255;
In this case the image should be all white, but it won't.

**Comment by kkapsner** [comment]
Uh... this is a bad regression. #31 was closed because with version 0.1.7 the iframe bypass did not work. I already found the problem and I'm working on a fix.

**Comment by kkapsner** [comment]
Version 0.2.2 should pass your test now.
