### ISSUE TITLE
one site only - a problem with recaptcha

### ISSUE THREAD

**Issue by ajay-gh** [kkapsner/CanvasBlocker#581]
## Description
while I am quite familiar how to use CanBlocker (CB) with a large number of websites, there is one website (www.leboncoin.fr) which got recently broken by CB no matter which API one turns on or of. It uses a recaptcha at start, AND  following the advice in the FAQ about window.name does not make any difference.

I know a developer cannot trouble-shoot a million websites on behalf of users ...
but I would really appreciate your help

## Expected Behavior
there should be a way to tweak CB with any website, but this time I cannot find it,
the log entries are inconclusive

## Current Behavior
CB works fine, but the website simply doesn't load as long as the CB extension is enabled in F.F. Just disabling CB by clicking on the icon inside the CB popup window does not do the trick either.

## Possible Solution
absolutely no idea, I tried many combinations of API on and off, without luck.

## Steps to Reproduce (for bugs)
enable CB, try to load www.leboncoin.fr in FF

## Context
n/a

## Your Environment

* CanvasBlocker Version used: 1.6.1
* Firefox version incl. 32- or 64-bit: 93, 64 bits
* Operating System and version (desktop or mobile): osx 10.14.6
* Installed addons: too many to list, most relevant uBlock

## Your Settings
irrelevant as I tried many combinations, see above

**Comment by ajay-gh** [comment]
Yes, I did read that section. Interesting in this context, the problem does not go away when you turn off CB (while keeping the add-on enabled). Only when CB is disabled, and a different VPN server is selected, and the browser gets restarted, the site comes back.
About the browser console, I find the following:
GEThttps://www.leboncoin.fr/   [HTTP/2 403 Forbidden 125ms]
AND
sendRemoveListener on closed conduit CanvasBlocker@kkapsner.de.274877906981 ConduitsChild.jsm:108
    _send resource://gre/modules/ConduitsChild.jsm:108
    _send self-hosted:1279
    removeListener resource://gre/modules/ExtensionChild.jsm:654
    removeListener resource://gre/modules/ExtensionChild.jsm:882
    onChanged chrome://extensions/content/child/ext-storage.js:332
    removeListener resource://gre/modules/ExtensionCommon.jsm:2499
    revoke resource://gre/modules/ExtensionCommon.jsm:2521
    close resource://gre/modules/ExtensionCommon.jsm:2526
    unload resource://gre/modules/ExtensionCommon.jsm:887
    close resource://gre/modules/ExtensionContent.jsm:935
    destroyed resource://gre/modules/ExtensionContent.jsm:1011
    observe resource://gre/modules/ExtensionContent.jsm:1029

**Comment by ajay-gh** [comment]
I think I do finally have some idea where this is going wrong. I noticed that adding websites to the exclusion list of the navigator api is not flawless. Sometimes it works (clicking + adds it), sometimes it doesn't (+ has no function), sometimes you have to close firefox and re-open it, and then a value (like *.leboncoin.fr) is accepted. Wildcards seem a problem too. Of course I cannot be sure, but it seems to trigger the captcha denial.

**Comment by kkapsner** [comment]
Clicking the + should add an URL specific value when something is entered in the input field. Do you have a reproducible scenario when it doesn't? I always works for me. I also never had the problem that I had to restart Firefox.

CanvasBlocker does not use wildcards. They are implicit. So if you enter "leboncoin.fr" also "www.leboncoin.fr" will use that value. 

> There also seems a problem with how values are interpreted once they are accepted in the mask. Hovering the mouse over the CB icon shows a description not in line with settings visible in the settings dialog.

I do not quite understand what you mean. Can make some screenshots that illustrate the problem?

> Finally, it appears that removing a value (~ website) from the list is not always successful. The website is no longer visible (after clicking the cross), but it is still excluded.

What do you exactly mean with "excluded"?

**Comment by ajay-gh** [comment]
Sorry, it took me a while. 
First question: I tried many times and scenarios, and first I couldn't reproduce it at all. Then I used * as a wildcard (now I know I shouldn't) and the problem started immediately. And when I remove the * the problem remains. So using a wildcard by accident seem to cause a problem which doesn't go away Please see if this could be (part of) the problem.
Second question: this may be related to the first observation. Probably not worth pursuing. 
Third question: once the problem starts (q1) this also re-appears. 

Here is the most simple example I could find / reproduce:
Enter exclusion for yahoo.com (or other), click +, this works as expected,
now enter exclusion for *.yahoo.com, click +, nothing happens
now try to replace *. from the last step with www. resulting in www.yahoo.com, click +, still nothing happens
enter exclusion web.de, click +, nothing happens

This cannot be fixed be disabling, followed by enabling the extension, or by simply restarting FF.
I hope this helps.

**Comment by kkapsner** [comment]
Sorry for the delay.

Your scenario is very helpsful and I now know exactly what is wrong.
