### ISSUE TITLE
Can't evade fingerprinting

### ISSUE THREAD

**Issue by slipk33** [kkapsner/CanvasBlocker#586]
All of the browser fingerprinting sites I know of can't identify me except https://noscriptfingerprint.com/
I always get the same Hash. 
All test from this plugin are working but I still get this issue.
Is there a way to spoof this detection as well or is it already working and I configured something wrong in my browser?

**Comment by ajay-gh** [comment]
Without uploading your settings for CB, and without explaining which other measure have or have not been taken to avoid fingerprinting, it will be impossible for the developer to give any reasonable answer.

**Comment by slipk33** [comment]
I tried different settings for CB but the question is if it is even possible/supported to avoid fingerprinting for this site with CB.

**Comment by kkapsner** [comment]
No it's not possible to protect against CSS-Fingerprinting with CB and I don't think it's feasible. It would be too slow.

**Comment by kkapsner** [comment]
I had some thought around it. As far as I see it would require to parse every HTML, JS and CSS for the fingerprinting vector and change it. This would be way too slow and therefore I will not be able to do anything about this fingerprinting.
