### ISSUE TITLE
Fingerprinting by scrollbar size

### ISSUE THREAD

**Issue by maverick74** [kkapsner/CanvasBlocker#587]
I've read that it's possible to fingerprint a user using the size of the scrollbar.
Is this protected in CB?

If not and if it's doable/worthy the work, i would like to suggest the option.

**Comment by rusty-snake** [comment]
> I've read that it's possible to fingerprint a user using the size of the scrollbar.

This is only OS AFAIK, which you can not hide.

**Comment by maverick74** [comment]
> This is only OS AFAIK, which you can not hide.

It makes sense... :)

**Comment by Thorin-Oakenpants** [comment]
> This is only OS AFAIK

It's not always equivalency of OS. Linux users vary widely. It's also affected by scaling and zoom. Additionally, there two measurements, the viewport and within an element, and combined they can eke out more buckets

**Comment by kkapsner** [comment]
No - this is not protected by CB. And I do not see a good way to do it.
