### ISSUE TITLE
PDFs are not correctly loaded until CB is deactivated

### ISSUE THREAD

**Issue by Kn0p3XX** [kkapsner/CanvasBlocker#59]
Yeah, looks like CanvasBlocker is preventing PDFs to be displayed.
When i start Firefox the first time, a PDF will be displayed until i reload or open a new PDF. It's loading forever. (The PDF.js menu is there, but it tries to load the PDF)

**Comment by kkapsner** [comment]
I cannot reproduce your problem. Which FF version are you using? Which mode?

Am 27.01.2016 um 15:26 schrieb Kn0p3XX:

**Comment by Kn0p3XX** [comment]
I'm using Firefox 44.0, CanvasBlocker 0.2.1-Release in only Whitelist mode. When i set to 'allow everything' it works too. But in 'Only whitelist' not. I tried it in Nightly 47.0a1 (2016-01-27) too and there works. I'm highly confused.

**Comment by kkapsner** [comment]
Ah... with this mode the PDF will not work due to the reasons mentioned in #57.

I highly suggest the fake mode or to wait for the next release which will provide the script based white list.

PS: In nightly the addon is complete not functional due to the activated multithreading.
