### ISSUE TITLE
`getTotalLength` and `getPointAtLength` seem to be not covered

### ISSUE THREAD

**Issue by KOLANICH** [kkapsner/CanvasBlocker#590]
Some websites can use `getTotalLength` and `getPointAtLength` for fingerprinting. It seems to be not protected by CB.

## Description
https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/getTotalLength
https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement/getPointAtLength

## Expected Behavior
This API should be covered.

## Current Behavior
Seems to be unprotected.

## Possible Solution
Hook the API and quantize the results and alter then them a little. Or even better, use a pure JS impl.

## Steps to Reproduce (for bugs)
https://github.com/abrahamjuliot/creepjs/commit/0216fed848ed8d5f73daf3c54175934a2c52391e#diff-ae4265b1c74438c698d4c5f2e60e43f039b91f8e4f01acd8a5555bee1051b503

**Comment by kkapsner** [comment]
getPointAtLength should be protected (https://canvasblocker.kkapsner.de/test/domRectTest.php) but getTotalLength not. Test for getTotalLength are created and alpha version with protection will follow soon.

**Comment by kkapsner** [comment]
Please test the latest alpha.

**Comment by KOLANICH** [comment]
Thank you for implemeting this. I'm sorry I currently cannot allocate the time to test it properly (in fact I have reconsidered using that website at all).
