### ISSUE TITLE
RNG modi, German Explanation

### ISSUE THREAD

**Issue by lsc64** [kkapsner/CanvasBlocker#591]
Hello, in v 1.7 following explanation for different RNG modi can be found in the extension settings:

> nichts (komplett weiß): es wird immer ein weißes Bild zurückgegeben. Hierbei sollte die Option "Alpha-Kanal auch vortäuschen" aktiviert werden. ACHTUNG: Nicht im Modus "Bei Ausgabe vortäuschen" verwenden.
> 
> nicht persistent: die Zufallszahlen werden bei jeder Vortäuschaktion neu bestimmt.
> 
> konstant: innerhalb einer Webseite wird eine Farbe immer gleich verändert.
> 
> persistent: für jede Domain werden die Zufallszahlen nur einmal bestimmt.

Roughly translated, this means:
> nothing (completely white): ...
> 
> not persistent: random numbers will be generated for every action
> 
> constant: within a website the color is changed the same way every time.
> 
> persistent: for every domain, random numbers are generated only once

I'm not sure how constant and persistent differ. If we have some URI  
sub.domain.tld/path/?query  
what needs to change to regenerate random numbers?  
And is "constant" actually "persistent" for that website or does it re-generate the numbers if I open the same website later?

**Comment by kkapsner** [comment]
Constant is not persistent. It will generate different numbers when you open the same website later.
Persistent will store the information and will not generate different numbers.

So constant is a variation of "not persistent". But it randomizes on a colour basis and not on a pixel basis.

PS: if it helps you to understand we could also talk in German...

**Comment by lsc64** [comment]
Okay, then please allow a follow-up question: When does "constant" generate new random numbers? Does it keep the same numbers if I just press F5/reload the page or does it always change no-matter the URI but keeps it consistent per page-load request? 
Now in German since it's about the specific wording:  

Danke fürs Angebot. Mich haben zwei Sachen verwirrt:
1. Der Ausdruck "immer gleich" bei konstant, da es eben nicht "immer" gleich ist sondern nur für den einen Aufruf/den einen Tab/den Request (?)
2. Dass konstant den Begriff "Website" benutzt und persistent den Begriff "Domain" nutzt. In Kombination mit 1. klang es für mich so, als würde "konstant" pro URI konstant/persistent bleiben und "persistent" für alle URIs einer Domain konstant/persistent bleiben.

To prevent this issue from being a pure Q&A matter, I would suggest that as a result of this discussion we implement a more precise description to be added to the extension.

**Comment by kkapsner** [comment]
> When does "constant" generate new random numbers? Does it keep the same numbers if I just press F5/reload the page or does it always change no-matter the URI but keeps it consistent per page-load request?

The later. It's only consistent per page-load.

> 1. Der Ausdruck "immer gleich" bei konstant, da es eben nicht "immer" gleich ist sondern nur für den einen Aufruf/den einen Tab/den Request (?)

Ja - ist etwas missverständlich geschrieben. Was wäre denn dein Vorschlag für eine bessere Bescheibung? Einfach das "immer" weg lassen?

> 2\. Dass konstant den Begriff "Website" benutzt und persistent den Begriff "Domain" nutzt. In Kombination mit 1. klang es für mich so, als würde "konstant" pro URI konstant/persistent bleiben und "persistent" für alle URIs einer Domain konstant/persistent bleiben.

Hm... pro URI passiert da nichts. Vorschläge?



> To prevent this issue from being a pure Q&A matter, I would suggest that as a result of this discussion we implement a more precise description to be added to the extension.

I'm always open to better descriptions!

**Comment by kkapsner** [comment]
Since the text is also confusing in English I will change it there as well - which means every language will be affected by this.
