### ISSUE TITLE
https://dood.so can't streaming properly. Show "Sandbox not allowed".

### ISSUE THREAD

**Issue by Pikemo** [kkapsner/CanvasBlocker#599]
Enable CanvasBlocker：

![Screenshot 2022-03-15 at 10-35-03](https://user-images.githubusercontent.com/22120513/158296347-cf7ba58b-c5a7-4643-bfa3-8662d6a7d191.png)

Add "https://dood.so" to APIs white list still no work. It must to disable CanvasBlocker to be work fine.

**Comment by kntjspr** [comment]
I think it's only in your settings. It's working on my browser (w/ canvasblocker enabled) Try using stealth preferences and try again.

**Comment by kkapsner** [comment]
What do I have to do exactly to get this error message?

What are your settings exactly?

**Comment by Pikemo** [comment]
> What do I have to do exactly to get this error message?
> 
> What are your settings exactly?

Default setting. I don't change anything. 

Try using stealth preferences. Video streaming still no work and get this error message.

**Comment by kkapsner** [comment]
Please describe the steps to take to get this message. Something like
1. go to dood.so
2. log in with credentials
3. ???

**Comment by kkapsner** [comment]
@Pikemo: please provied me with the steps. I'm not familiar with that website and do not have the time to tinker around with it.

**Comment by kkapsner** [comment]
OK - it seems to be the data URL protection: #208
![grafik](https://user-images.githubusercontent.com/1105157/164292284-4e46d029-3542-4769-8405-52f79fa819a7.png)

Please check if this also solves the problem at dood.so.

**Comment by spodermenpls** [comment]
> OK - it seems to be the data URL protection: #208 
> Please check if this also solves the problem at dood.so.

Yes, that's it. 

I actually don't run into any "Sandbox detection" problems with Doodstream either. Since I am using the site from time to time to watch videos, I would've raised this issue a long time ago, if it was being affected by CanvasBlocker.

**Comment by Pikemo** [comment]
> OK - it seems to be the data URL protection: #208 ![grafik](https://user-images.githubusercontent.com/1105157/164292284-4e46d029-3542-4769-8405-52f79fa819a7.png)
> 
> Please check if this also solves the problem at dood.so.

Problem solved. Thanks.

**Comment by kkapsner** [comment]
Good - you're welcome.

I asked for an update in the [bugzilla report](https://bugzilla.mozilla.org/show_bug.cgi?id=1475831). Hopefully I can get rid of this work around in the near future. For the time being there is unfortunately nothing else I can do about it.

But as the white listing works I will close the issue.
