### ISSUE TITLE
e10s compatibility?

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#60]
I cannot find this addon on https://www.arewee10syet.com/, so can someone please follow the instructions there and make sure this addon is compatible with the upcoming [multi-process architecture](https://wiki.mozilla.org/Electrolysis) of Firefox?

**Comment by kkapsner** [comment]
I'm currently working on it. But it's not so easy...

**Comment by rugk** [comment]
But it seems you addon was not submitted to https://www.arewee10syet.com/ until now...
Possibly you may do this so Mozilla knows how many add-ons still need to be adjusted.

**Comment by kkapsner** [comment]
the addon is not listed because it is still marked as preliminary (and I will change that on the switch to version 1.0.0 - but there are still some things to do for that).

But we are e10s now.

**Comment by rugk** [comment]
Nice :+1:
