### ISSUE TITLE
CanvasBlocker is slowing down Firefox

### ISSUE THREAD

**Issue by grysor** [kkapsner/CanvasBlocker#608]
Hello
On some sites i get this message :
"CanvasBlocker is slowing down Firefox."

and i read this solution that the dev proposes saying :

" the only solution is to whitelist ebay.co.uk for the DOMRect API "

but i don't know at all how to do that. Can you explain the manipulation to me by a screenshot for example? thank you

**Comment by crssi** [comment]
Are you sure that the `DOMRect API` is the culprit on `ebay.co.uk`?
If you disable `DOMRect API`, can you reproduce the problem?

**Comment by grysor** [comment]
> 

it's not ebay, he gave the solution to another person for ebay. Me it's for another site, this one precisely :
https://www.spliiit.com/fr/
the site remains completely frozen for several minutes with the message "CanvasBlocker is slowing down Firefox." :(

**Comment by crssi** [comment]
Which component does that?
I am asking, since I am using `DOMRect API`, but the page doesn't freeze.

**Comment by kkapsner** [comment]
Whitelisting can be done over the fingerprint icon in the address bar:
![grafik](https://user-images.githubusercontent.com/1105157/164416071-9bf520a6-bcd9-4796-8427-6785a98c10e8.png)
![grafik](https://user-images.githubusercontent.com/1105157/164416104-6a7937e5-0068-43db-901f-eb83587413a6.png)
![grafik](https://user-images.githubusercontent.com/1105157/164416133-d62d385e-2b76-40ae-8d2d-e428b580ffe4.png)

But my Firefox does not freeze on that site as well. So I do not know what causes your problem. Maybe it's something special in your settings.

If the white listing does not help I need more information.

**Comment by grysor** [comment]
> Which component does that? I am asking, since I am using `DOMRect API`, but the page doesn't freeze.

Hello,well i had this problem the first time i visited the site. But the following times the problem did not reappear i do not know why.
I tried to see if the problem reappeared by deleting cache + cookies from firefox then going back to the site and refreshing it but the problem did not reappear anymore. Good for me, i'm happy :)

thank you very much for your screenshots ! I will be able to whitelist a site in the future if i have a similar problem that lasts
