### ISSUE TITLE
Is there a better description of the "readout API" of Canvas?

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#61]
I have an issue with [explaining the Canvas "readout API"](https://git.gnu.io/h2p/Qvitter/issues/32).
> i don't know what the "Canvas Readout API" is, it gives me no hits on google, except for that canvasblocker plugin

So is there a better name for it, @kkapsner? Are there possibly some docs for this special API, which is blocked/faked by this addon? Can you show a code sample (which triggers this addon)?

Thanks in advantage.

**Comment by rugk** [comment]
Note: Please don't directly discuss the issue mentioned in https://git.gnu.io/h2p/Qvitter/issues/32. Just discuss the name. :smiley:

**Comment by kkapsner** [comment]
I'm not aware of a name that is commonly used. So I came up with my own.
You can look up the functions which fall into this category in https://github.com/kkapsner/CanvasBlocker/blob/master/lib/modifiedAPI.js#L63 - the ones label with ```type: "readout"```.

They should be all functions that read the content of a canvas in some way.

**Comment by rugk** [comment]
Okay, this helps at least a bit.
