### ISSUE TITLE
Great addon, Help to use CanvasBlocker in Playwright or Puppeteer

### ISSUE THREAD

**Issue by icesmartjuan** [kkapsner/CanvasBlocker#614]
Hi experts, 

Great to find this addon which seems promising to block canvas fingerprinting. 

Is there any doc or suggestion on using it in Playwright or Puppeteer? 

Many thanks!

**Comment by kkapsner** [comment]
Unfortunately I have never used it with Playwright or Puppeteer So I have no documentation or tip.

If you manage to use it feel free to share your findings.
