### ISSUE TITLE
[Feature] Ability to backup/import saved random value programmly

### ISSUE THREAD

**Issue by hkfsc** [kkapsner/CanvasBlocker#617]
I wonder is there a way currently, I can import/export those random values programmly? like with Python?
And I cannot find any info about how this plugin save the random strings, and make this persistent... Can anyone tell me which file it used for saving those containers random value data? is it saving the info to sqlite file or anything else?
Thanks!

**Comment by kkapsner** [comment]
The random values are only stored when the persistent rng is used. You can use the built in export function to create a json file of the settings where you can then see the persistent random values.

The extension uses the [storage api](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage) to save this. Firefox used to save the data in plain json files but I think at the moment they use a sqlite database. But not sure. You would have to look in the source code.
