### ISSUE TITLE
Sanitize Firefox/Browser Profiles?

### ISSUE THREAD

**Issue by Irvinehimself** [kkapsner/CanvasBlocker#622]
With reference to [this section ](https://wiki.archlinux.org/title/Firefox/Privacy#Sanitized_profiles) of the [Arch Firefox Wiki](https://wiki.archlinux.org/title/Firefox/Privacy), would it be possible to  implement a feature to strip out identifying `meta-data` from `prefs.js` in Firefox? _(Along with the equivalent in other browsers of course.)_

I have done some experiments with my `default-profile` and  CanvasBlocker installed against a bare bones, no extensions or other mods, `test-profile` on the [Fingerprint JS API Demo](https://fingerprintjs.com/demo). The `un-sanitised` profile is generating a consistent hash on each visit, whereas the `sanitised` version does not.

I don't think it should make a difference, but my environment is:
- Arch with the `linux-hardened` kernel
- A minimal `gnome-shell`, (no meta-packaging)
- Firefox sand-boxed with Firejail and Apparmor

_edited to change `uniquely identifiable` to `generating a consistent hash`_

**Comment by kkapsner** [comment]
A webExtension cannot change the `prefs.js` file. Older addons were able to do it but it was a security risk (you needed to trust the addon absolutely). So there is nothing I can do from CanvasBlocker.
