### ISSUE TITLE
Please fake the Plguins as well, some other extensions do it

### ISSUE THREAD

**Issue by NuLL3rr0r** [kkapsner/CanvasBlocker#624]
## Description

When you visit [coveryourtracks.eff.org](coveryourtracks.eff.org) with CanvasBlocker enabled, it's able to figure out the browser plugins.

## Expected Behavior

Browser plugins also have a role in fingerprinting. They should not be detected or randomized. I have tested [this](https://addons.mozilla.org/en-US/firefox/addon/browser-fingerprint-protector/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) and [this](https://addons.mozilla.org/en-US/firefox/addon/no-fingerprint/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), both of which are able to randomize the plugins' value on [coveryourtracks.eff.org](coveryourtracks.eff.org). 

## Current Behavior

CanvasBlocker indeed does not do that.

## Possible Solution

I guess, it could be faked like the other extensions.

## Steps to Reproduce (for bugs)

1. Visit [coveryourtracks.eff.org](coveryourtracks.eff.org)
2. Look at the detected plugins
3. Try with other extensions, I've mentioned above
4. Again look at the results for the plugins

## Context

It makes people finger printable. I've also tested on the latest Firefox.

## Your Environment
* CanvasBlocker Version used: Latest
* Firefox version incl. 32- or 64-bit: Mozilla Firefox 102.0
* Operating System and version (desktop or mobile): Gentoo Linux SMP Tue Jun 28 16:56:47 CEST 2022 x86_64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz GenuineIntel GNU/Linux
* Installed addons: Decentraleyes, FoxyProxy Standard, Gopass Bridge, Privacy Badger, uBlock Origin, User-Agent Switcher and Manager

## Your Settings

```json
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": ,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "6",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}
```

**Comment by Thorin-Oakenpants** [comment]
The Steps to Reproduce do not show that there is an issue with fingerprinting. Please do not use tainted datasets to push false narratives

FF99+ the plugins/mimeTypes in Firefox is a hardcoded list the same for everyone on all platforms, or none if `pdfjs.disabled` is `true`. And from FF85-99 plugins/mimeTypes were none, for everyone (in case you were wondering about ESR91).

Faking these is utterly pointless

**Comment by NuLL3rr0r** [comment]
The mentioned extensions are definitely able to fake the plugins value, regardless of they are hard coded or not. Did you even bother to check?

Well, faking is only pointless if my user agent is Firefox. Not when I want to pretend I am running another browser/platform.

**Comment by Thorin-Oakenpants** [comment]
I didn't say anything about extensions being able to fake the data. What I said was that faking these is pointless. Pretending to be a different engine than Gecko is also pointless. You cannot hide your engine.

Look, websites don't have to tell you that you are lying, it manifests in the metric data automatically. Lying about plugins, user agent will only make you stand out. I think I should know given my association in this area.

**Comment by NuLL3rr0r** [comment]
OK, just asking for education purposes. Why would the likes of brave randomize the plugins list? I am not sure how much EFF is credible. But, no matter what I do, or even I tried LibreWolf, it says your browser has a unique fingerprint among X amount of individuals. But, for Brave, it always says you have a randomized Fingerprint. So, I guess there might be a good reason Brave does randomize the plugins list as well.

**Comment by Thorin-Oakenpants** [comment]
These test sites are not real world. Use them to see what you return, but do not listen to the entropy they claim. I won;t explan why, because I am sick to death of doing it.

To understand why you randomize, read this: https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-fingerprinting

The more you randomize, the more scripts are likely to become naive. Chromium does not have, or didn't have, a stable plugins/mimeTypes (I'm not 100% sure as IDFC about chromium :) ) and since Brave has already set up the engineering to remember and protect the seed per session, per eTLD+1, per scheme, and per window type (tor window, normal, incognito), they can easily hook any metric up to randomizing. Personally, I think it's overkill.

Tor Browser, or RFP, doesn't care about that, because ALL the lies/randomizing can be detected (not to be confused with detecting the real value) - either mathematically, or simple by detecting the engine and RFP/Shield-level. So ultimately it's a waste of time, except for naive scripts

**Comment by NuLL3rr0r** [comment]
OK, thank you very much, Sir! Especially for your last point (and not to be confused with detecting the real value), now I get that. And, also for the link.

I understand what RFP in Firefox and Tor Browser do may be the best thing and as soon as you change something, you immediately stand out. But, I have a different use case. Now, with the knowledge I've gained from what you have mentioned, I have to re-think this carefully.

My use case is something of this kind. That's why I wanted to actually be unique!! Let's say I have 10 social media accounts on the same platform. I want them all to interact with each other and they are all on the same computer. If the algorithm detects, that one person owns those 10 accounts it will kill the impression and reach if they promote each other or interact. I've tested this. No matter the number of followers, or influence of the account. So, as a result, I thought of setting up Firefox profiles using a set of scripts that extract the required data from a CSV file. I thought the best strategy for those 10 accounts is to differ as much as possible. I could blend with the crowd for example using Tor Browser, but when those accounts interact with each other the algorithm detects them. So:

1. 10 Proxies from 10 different countries.
2. All accounts registered with phone numbers from those countries.
3. TZ variable set to the timezone extracted from GeoIP based on the proxies they use
4. LC_ALL variable set to the locale from that country
5. ACCEPT_HEADERS set to the languages from those countries
6. Canvas is completely disabled to not give away anything.
7. For fonts, audio, etc faked with a fingerprint addon.
8. Using letter-boxing and fake screen resolutions.
9. Other obvious things such as user agent, hardware fingerprint, etc are also faked.

The interaction was not done by WebDriver in a bot-like manner but a real human regularly uses those accounts. One could say, just rent 10 VPSes and be done with it. But, still, those VPSes won't give much variety and more money and time should be spent on them, which means more hassle.

The reason I did not choose RFP or Tor Browser is that. Though using Tor Browser on social media platforms has it's own downsides, like getting suspended because someone in the same IP range abused the platform, or, constantly asking you to solve a captcha, etc. That's why I thought, that may be creating 10 unique fingerprints that interact with each other might be better than 10 accounts with the same fingerprint interacting with each other. I hope that clarifies, why I thought changing plugins value is also valid.

**Comment by Thorin-Oakenpants** [comment]
> in Firefox [...] as soon as you change something, you immediately stand out

You already stand out if you do nothing. Read the wiki link. Your best and only hope in Firefox is to fool naive scripts. Just use the same profile and use CB to subtlety randomize canvas and audio, maybe screen and don't use RFP (which will break a few things).  Your setup is convoluted IMO.

Do not bother with font extensions, they all leak (20+ odd methods to get this info, and none of the extensions work and just end up breaking things. Ignore all the other crap you listed. Disabling canvas = breakage. Lie about user agent = breakage. Get on with your life and use the web. As for IP that's up to you.

**Comment by NuLL3rr0r** [comment]
Thank you for the info, I'll look into it deeper.

**Comment by kkapsner** [comment]
I think for your use case you should not pretend to have a different browser. And as Firefox has a fixed plugin collection there is little reason to fake it.
