### ISSUE TITLE
Where to set the renderer and vendor list?

### ISSUE THREAD

**Issue by hkfsc** [kkapsner/CanvasBlocker#625]
added {random vendor} and {random renderer} to UNMASKED_VENDOR_WEBGL and UNMASKED_RENDERER_WEBGL to use a random value from a given list

Where I can set the list values? Can retrieve by URL or just plain text? format?

**Comment by kkapsner** [comment]
The list for these settings are built in and cannot be changed. But you can use the `<option1|option2|...>` syntax to define your own list.

**Comment by hkfsc** [comment]
Where to define it?

**Comment by kkapsner** [comment]
![grafik](https://user-images.githubusercontent.com/1105157/178797628-6b60766b-831b-4713-acdd-eca9a7e0c253.png)

**Comment by hkfsc** [comment]
`expert|vendor1, vendor2, xxx, vendor3|renderer1,2,3`?

**Comment by kkapsner** [comment]
No - the input in the top is only the search to get the needed settings.

The lower four settings are the ones where you can use the `<option1|option2|...>` syntax.
