### ISSUE TITLE
Discord and Voice & Video Chatting Problems

### ISSUE THREAD

**Issue by Albusvesuvius** [kkapsner/CanvasBlocker#626]
I want to share my findings and learn more from others who are using a Firefox Profile with Canvasblocker specifically for Voice & Video Chatting. I mostly use Discord or Zoom inside the browser.

For Discord I have found protecting these API's to be problematic:

1- Audio API
When this is enabled, Voice & Video Settings page of Discord doesn't show microphone sensitivity going up and down, it's unmoving. Also I think when this is enabled you can't turn on Discord's own "Echo Cancellation", "Noise Reduction" settings etc.

2- SVG API
When this is enabled, Discord will bring up hcaptcha everytime you message someone new or try to join a new Server. I still get hcaptcha checks sometimes but not as much with this disabled. There's probably another setting that causes capchas but I wasn't able to figure it out.

3- Screen API
When this is enabled, the green overlay around the profile picture of someone who is currently talking might be showing in the wrong places of the screen. This should apply to Zoom meetings.

I am interested in finding out how to protect as many API's as I can without breaking popular Voice or Video Chatting websites.

**Comment by kkapsner** [comment]
I guess you are logged in at discord and/or zoom. So they can track you with that. So there is no need to prevent fingerprinting for "broken" APIs. I would simply allow the problematic APIs at these domains (easiest with the fingerprint icon in the URL bar:
![image](https://user-images.githubusercontent.com/1105157/188316114-ff2033c7-3896-46ed-91eb-c97d8d8f00ed.png)
![image](https://user-images.githubusercontent.com/1105157/188316121-a14e7d44-c61a-4fe6-88fe-51546f187303.png)
![image](https://user-images.githubusercontent.com/1105157/188316130-cc4684af-b0c4-4f91-aefa-a7c00418b997.png)
).

To you your points:
1. I'm not surprised that the Audio API protection messes with voice chat. So I think the only way out it is to allow it for Discord.
2. This is kind of weird. Is there a different domain involved? (can be seen in the fingerprint menu mentioned above)
3. Apparently they are doing weird position calculations. Whitelist zoom for this API - it does not provide very much entropy, if you are using a fairly common screen resolution.

**Comment by ItsCEED** [comment]
Captcha is triggered by Cloudflare and not by discord directly, which means the addon is detected by Cloudflare.

Also, is your account fresh? Cause only fresh accounts are getting captcha.

**Comment by kkapsner** [comment]
No answer from the original poster for some time. I will close this issue.

If you still have the problem and want to provide the requested information I can reopen this.
