### ISSUE TITLE
Is this extension necessary while having "fingerprinters" checked in Firefox's Enhanced Tracking Protection?

### ISSUE THREAD

**Issue by 1Phase1** [kkapsner/CanvasBlocker#628]
(Note, I've removed the standard issue draft text because this isn't an issue, just a question)

I have "fingerprinters" enabled in Firefox's Enhanced Tracking Protection menu, but I _don't_ have the privacy.resistFingerprinting setting enabled in about:config. Do I still need this extension, or will I have the performance issues that the readme warns about if I use it?

**Comment by kkapsner** [comment]
CanvasBlocker still provides additional value. You can use this built-in Firefox feature. It's the "new fingerprinting protection introduced with Firefox 67" from the description - I will update the readme.
