### ISSUE TITLE
Breaks options of Privacy Badger

### ISSUE THREAD

**Issue by rugk** [kkapsner/CanvasBlocker#63]
See https://github.com/EFForg/privacybadgerfirefox/issues/730

With CanvasBlocker installed the options page always reloads when I click on a slider position and after reloading the state is not changed. This even happens when I set CanvasBlocker to "allow all", so this does not seem an issue with blocking any Canvas, but rather with the addon itself.

**Comment by kkapsner** [comment]
I am not able to reproduce your problem with a fresh profile with only these two addons installed.

**Comment by rugk** [comment]
Hmm strange. Probably move some sliders around and try again...

**Comment by rugk** [comment]
Here are more information and a gif to show how to reproduce this: https://github.com/EFForg/privacybadgerfirefox/issues/730#issuecomment-192616525

Basically it only seems to happen when you use `Ctrl+F` to look (e.g.) for `google` in the options of PrivayBadger. If you use PrivacyBadger's built-in search function this does not happen.

**Comment by kkapsner** [comment]
The reload of the options page also occurs if CanvasBlocker is not installed. So this seems to be not related to it.
