### ISSUE TITLE
twitch.tv error "400 Bad Request"

### ISSUE THREAD

**Issue by Skip75** [kkapsner/CanvasBlocker#630]
## Description

When CanvasBlocker is enabled, I can't login in twitch.tv.
devtools show me the error "400 Bad Request" for URL "https://passport.twitch.tv/integrity"
![image](https://user-images.githubusercontent.com/44243520/194613582-6dbf9ad8-7192-4f73-84a0-4b50596856bc.png)

If I disable it, no more issue :
![image](https://user-images.githubusercontent.com/44243520/194613467-82a74009-6c8f-4aef-9911-5a6de9bb1d1c.png)

I can reproduce it easily.

## Your Environment

* CanvasBlocker Version used: 1.8
* Firefox version incl. 32- or 64-bit: 64
* Operating System and version (desktop or mobile): win 10 64bit

## Your Settings
~~~ json
I didn't paste it. But I can if you cannot reproduce that error on your side.
~~~

**Comment by kkapsner** [comment]
Sorry for the late response.

I'm not able to reproduce your problem. I can log in with CB enabled. Do you still have the problem?

**Comment by Skip75** [comment]
I'm going to close this ticket, I'm no longer able to easily reproduce the problem. I'm still having problems using Firefox, so I'm using Edge for this particular site. If I can reproduce the problem in the future, I won't hesitate to come back... :p
