### ISSUE TITLE
Misc - URL pages - cannot delete entries

### ISSUE THREAD

**Issue by ajay-gh** [kkapsner/CanvasBlocker#631]
In the Misc tab, item "block data URL pages", a number of websites is shown (which btw I am not aware how they got there).
These are url/s which I have certainly visited before, but anyway ... by clicking on the little x behind their name, the entry does not get deleted. This problems remains regardless of the state of the tab (protected or not).

## Expected Behavior
it should be possible to delete any entry in the  like in other fields of the settings page - I assume that is the intent ??

## Current Behavior
any click on the x is ignored 

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
obvious

## Context
this breaks certain websites shown in this tab. It even appears to me that disabling this protection doesn't help.

## Your Settings
macos Catalina, FF 105, CB v1.8

**Comment by kkapsner** [comment]
Sorry for the late response.

Is the checkbox greyed out? If so the entry for this site and setting is deleted. You might have a different setting set for this site. In that case it also appears there for convenience reasons.

The fastest way to find out what you have set for a specific site is to inspect your settings:
![grafik](https://user-images.githubusercontent.com/1105157/225123729-14b82b9a-848e-4fe8-be3f-e5f294c9e51d.png)
![grafik](https://user-images.githubusercontent.com/1105157/225124119-5d4b2c9f-1751-40ae-84ed-3c2717cd8d41.png)

**Comment by kkapsner** [comment]
No answer for more than two months so I guess the problem is solved. If not I can reopen it.
