### ISSUE TITLE
DOMRect API protection logs Discord out every browser restart

### ISSUE THREAD

**Issue by Gersonzao** [kkapsner/CanvasBlocker#633]
The DOMRect API protection option makes Discord log out every time the browser restarts

## Description

When the DOMRect API protection is enabled, Discord gets logged out each time the browser restarts

I'm not sure if it's a bug or known anti-fingerprinting behaviour, since I don't know if CanvasBlocker has preset exceptions. **Please, let me know if this is not a bug**

## Expected Behavior

If there are any accounts logged into Discord, they would still be there when the browser restarts

## Current Behavior

Discord logs out each browser restart

## Steps to Reproduce (for bugs)

1. Normally open the browser
2. Open discord.com/login
3. Log in
4. Wait for Discord to completely load
5. Normally close the browser and normally open it again or restart via the about:restartrequired page
6. Open discord.com/app
7. Realise that you're redirected to discord.com/login

## Context

Every time I open Discord in the browser, I need to log in again. And, sometimes, my VPN changes my location and I need to verify my session with my e-mail

No, I haven't reproduced the problem with a fresh Firefox profile

I'm using **LibreWolf 107**

## Your Environment

* CanvasBlocker Version used: 1.8
* Firefox version incl. 32- or 64-bit: 64-bit
* Operating System and version (desktop or mobile): Debian 11 (stable)
* Installed add-ons:
Adblock Plus - free ad blocker
AMPoo
Canvas Blocker  - Fingerprint Protect
CanvasBlocker
ClearURLs
Compat Report
Cookie AutoDelete
Dark Theme for Google™
Decentraleyes
DocsAfterDark
DuckDuckGo Privacy Essentials
Duolingo Sound Controls
Duolingo Word Bank Dnd
ezpp!
Find in Page with Preview
Ghostery - Privacy Ad Blocker
GitHub forks
Google Analytics Opt-out Add-on (by Google)
HTTPS Everywhere
IBA Opt-out (by Google)
InsuredVPN
jShelter
LibreWolf Updater
Linguist - web page translator
Malwarebytes Browser Guard
OpenTabs: Save trees by opening new tabs
OptiSearch
osu! preview
Privacy Settings
Protect My Choices
Quora Login Bypass
re:consent
refoorest: plant trees for free
Snowflake
Stylus
uBlock Origin
Ugly Emil
Watch on Odysee
Web Scrobbler
Wide GitHub
xBrowserSync

## Your Settings
~~~ json
<!--- Copy your CanvasBlocker settings here. -->
<!-- They can be retrieved by checking the expert mode and going to export settings. -->
<!--- You may consider deleting personal data - especially the "persistentRndStorage". -->
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {
		"protectDOMRect": false
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1669141119821,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "no",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "29",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": false,
	"displayDescriptions": true,
	"theme": "dark",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}
~~~

**Comment by d07434b2c08f** [comment]
I don't think it's CanvasBlocker causing the issue. I was having trouble staying signed into Discord as well, and it turned out that CookieAutoDelete was erroneously clearing localstorage (https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1462), which is where Discord stores your login credentials for whatever reason.

**Comment by Gersonzao** [comment]
Well, this isn't happening anymore. I think it was also because in the browser settings, "Clear history when Firefox closes" ("Offline web site data" was enabled) randomly activated itself :thumbsup:
