### ISSUE TITLE
Audio fingerprint is not blocked at audiofingerprint.openwpm.com and amiunique.org ?

### ISSUE THREAD

**Issue by slrslr** [kkapsner/CanvasBlocker#639]
https://github.com/sereneblue/chameleon/issues/556

**Comment by kkapsner** [comment]
I cannot reproduce your problem. I get "No value" for the audio data. But even if it would say "unique" that does not have to be a bad thing. Read https://canvasblocker.kkapsner.de/faq/#uniqueFingerprint for more info.

If you want to test if the audio API is protected you can use https://canvasblocker.kkapsner.de/test/audioTest.html
