### ISSUE TITLE
Navigator presets should have rv:109.0 for Firefox 110+

### ISSUE THREAD

**Issue by d07434b2c08f** [kkapsner/CanvasBlocker#641]
## Description
Currently the Firefox navigator preset has `rv:{firefoxVersion}` as you would normally expect, but in actual Firefox user agents it has been frozen at `rv:109.0`, per bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1805967

## Expected Behavior
User agents for Firefox 110+ contain `rv:109.0`

## Current Behavior
User agents for Firefox 110+ contain `rv:110.0`, `rv:111.0`, etc.

**Comment by kkapsner** [comment]
Wow - userAgents got even worse...
