### ISSUE TITLE
I can't turn off notifications

### ISSUE THREAD

**Issue by ThorstonHowlw** [kkapsner/CanvasBlocker#642]
Notificatell me the app is working on specific sites, popping up to the right in stacks that obscure the scroll bar. I click off each one to make it go away. The notification options I see have not allowed me to turn these pop-ups off yet. 

What can I do?

**Comment by kkapsner** [comment]
No response for more than two month -> I will close this issue.

If you still have the problem and share the requested information I can reopen it.
