### ISSUE TITLE
Question to the offscreen canvas

### ISSUE THREAD

**Issue by bugreporter321** [kkapsner/CanvasBlocker#644]
## Description
If firefox's resistfingerprint is enabled, on the testsite https://canvasblocker.kkapsner.de/test/test.html, all canvases despite the offscreen canvas seem to contain the firefox readout, i.e. just some noise. The officescreen canvas however, shows an image with "browserleaks" in it.

Restarting firefox without canvasblocker showed all the canvases display just noise for me.

Reading that there is some conflict between RFP and canvasblocker, I am not sure if my observation is as documented. The browserleaks canvas is I assume the one from canvasblocker, and its hash is said to be different each time the page is refreshed.

## Expected Behavior
I assumed all canvases are first firefox-protected, and canvasblocker-protected if the html5 readout is granted.

## Current Behavior
See description.

## Possible Solution
To be left to the experts.

## Steps to Reproduce (for bugs)
1. Go https://canvasblocker.kkapsner.de/test/test.html with canvasblocker on
2. restart FF
3. Go https://canvasblocker.kkapsner.de/test/test.html with canvasblocker off

**Comment by kkapsner** [comment]
No - this behaviour is not intended. I think I know what the problem is.

**Comment by Thorin-Oakenpants** [comment]
^ https://bugzilla.mozilla.org/show_bug.cgi?id=1825378#c1

**Comment by kkapsner** [comment]
Once the extension verification works again on AMO a new alpha version can be tested.

**Comment by kkapsner** [comment]
Alpha version can be tested: https://canvasblocker.kkapsner.de/versions/
