### ISSUE TITLE
Disabling CB for private tab adds domain from normal window in the background

### ISSUE THREAD

**Issue by spodermenpls** [kkapsner/CanvasBlocker#649]
## Description

I've just noticed that when I try to deactivate CB for a specific tab inside a private window (by clicking the CB logo in the browser action toolbar menu, turning it from blue to gray), it doesn't add that tab's domain, but instead the currently active tab in the "normal" window in the background (in my case instead of "google.de" it added "discord.com").

## Expected Behavior

The private tab's domain gets added and set to "allow everything".

## Current Behavior

The non-private tab's domain in the background gets added and set to "allow everything".

## Possible Solution

You tell me..

## Steps to Reproduce (for bugs)

1. Have tabs open in a normal window
2. Have tabs open in a private window, and disable one of them via the browser action menu
3. Watch and observe what happens in the CB settings

## Your Environment

* CanvasBlocker Version used: 1.8
* Firefox version incl. 32- or 64-bit: 111.0.1 64-bit
* Operating System and version (desktop or mobile): Windows 10 22H2 Pro
* Installed addons: Yes.

Also, I noticed that the reload circle button in the mentioned browser action menu doesn't seem to work anymore on my end, can you reproduce? Maybe needs some fixing as well..

**Comment by kkapsner** [comment]
The problem with the reload button is related. Please try the latest beta.

**Comment by spodermenpls** [comment]
> The problem with the reload button is related. Please try the latest beta.

Okay, looking for what is happening in the background after a click on "reload" would've been too easy. 😄 Thanks for the quick fix.
