### ISSUE TITLE
Any chance of a Chromium version?

### ISSUE THREAD

**Issue by 9Morello** [kkapsner/CanvasBlocker#65]
Theres no equivalent for Chromium-based browsers. None that can completely block canvas reading requests, at least.

Any chance of it being ported?

**Comment by kkapsner** [comment]
Yes, there is a chance. But spare time is rare... I have never built a addon for Chromium and would have to learn the basics first.

If someone can help me to figure out the parts that have to differ between FF and Chromium I would be glad to provide a port.

**Comment by Paulbapet** [comment]
on chromium-based browser you can block it with "--disable-reading-from-canvas" commandline flags/switches

**Comment by kkapsner** [comment]
This would be equivalent to the block-readout mode. But this would limit the use of some websites that use the readout for legit purposes.

**Comment by dezhavu** [comment]
hey there, thanks for great addon, but could you please look at the possibility of faking canvas readout with not just random per request, its really chaotic, but to say 1 per session (till restart of browser) or even better if it could be manually crafted to match the proper hash value - this would be priceless

**Comment by kkapsner** [comment]
@dezhavu Your request has nothing to do with a version for Chrome. There is already an issue for a fixed hash (#64). Please provide more information there why you dislike the "chaos" and need a "constant" hash.

**Comment by dezhavu** [comment]
Ok lets try, still its trivial

1) chaotic
All unique random canvas readouts crafted by CanvasBlocker are so unique, that are identified and never a single one gets into database of https://www.browserleaks.com/canvas
From https://panopticlick.eff.org point of view all those random canvas readouts crafted by CanvasBlocker get into the range of 1 per 137000-140000 user.

2) constant per session or till browser restart
If say there's a website checking canvas readout twice from different domains (using scripts) and get 2 different values, it flags the user.

If by chance you could create a possibility to set constant hash, I guess everybody would be happy, as one can adjust hash to more common and widely used in some area.
Or at least make an option to leave it unchanged per session.

**Comment by kkapsner** [comment]
Still wrong issue...

**Comment by 9Morello** [comment]
Dezhavu, CanvasBlock can just block the website from reading it, right?
So whats the problem?

**Comment by jawz101** [comment]
@9Morello have you tried ScriptSafe?

**Comment by kkapsner** [comment]
Also the new WebExtension will not work in Chromium because I have to use Fifefox specific APIs. I do not see a good way to provide a good version without these APIs.
