### ISSUE TITLE
Which API's of CanvasBlocker conflict with "resist-fingerprint"? [Question]

### ISSUE THREAD

**Issue by jackjr79** [kkapsner/CanvasBlocker#653]
Hi, 

I use Firefox (Desktop, latest stable) with CanvasBlocker and resist-fingerprint enabled (from about-config).

I only enable below features of CanvasBlocker:

- Audio API
- DOMRect API
- SVG API
- TextMetrics API

Will this make conflicts with resist-fingerprint option of Firefox? I could not find any official documentation by Mozilla. I mean they did not documented which API are manipulating if resist-fingerprint is enabled.

Thank you

**Comment by kkapsner** [comment]
CB should work well with RFP in any API (even Canvas). If it does not I will try to fix it.
