### ISSUE TITLE
persistent rng not working in Fennec (Firefox for Android)

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/CanvasBlocker#654]
## Description
The persistent rng data is not stored in Fennec (Firefox for Android).

## Expected Behaviour
With persistent rng faked data does not change after refresh.

## Current Behaviour
With persistent rng faked data still changes after refresh.

## Possible Solution
Fix persistent rng data storage

## Steps to Reproduce (for bugs)
1. set the rng to "persistent"
2. navigate to https://canvasblocker.kkapsner.de/test/test.html
3. refresh the page -> the hash should not change

## Your Environment
* CanvasBlocker Version used: 1.9
* Operating System and version (desktop or mobile): Mobile

**Comment by Do6PbIu4eJlOBek** [comment]
Hello! How long to wait for that issue fix? Please check your email I have sent some private questions

**Comment by Do6PbIu4eJlOBek** [comment]
Pls upload new version to Mozilla site

**Comment by kkapsner** [comment]
I will when it's ready. And then the review process may take some days...

**Comment by Do6PbIu4eJlOBek** [comment]
Also please check 'preset' option. Doesn't work also

**Comment by kkapsner** [comment]
Please open a separate issue for that (with detailed information and step by step scenario to reproduce). I will then have a look.

**Comment by Do6PbIu4eJlOBek** [comment]
Still no update?
