### ISSUE TITLE
Allow adding domain whitelist from urlbar dropdown

### ISSUE THREAD

**Issue by Riajyuu** [kkapsner/CanvasBlocker#655]
This feature simply means adding another button here:
![image](https://user-images.githubusercontent.com/16912240/236445553-8a4f02c4-7a18-43e4-a687-51f58de2842e.png)

The only thing is, is still necessary to ask whether whitelist current subdomain only or the whole domain.
Take gist.github.com for an example, when click on the new button, shall it be like adding gist.github.com to the whitelist only (quickest for operating but least configurable)?
Or display both gist.github.com and github.com and ask user for a choice (a bit more configurable but slower)?
Or add gist.github.com to the whitelist input for user editing (slowest sometimes but most configurable)?
Or any better idea?

This is how another extension do this:
![image](https://user-images.githubusercontent.com/16912240/236447033-6821ec45-2b9e-4c21-addf-f05fd6d55551.png)

**Comment by kkapsner** [comment]
If you hover over the URL in the dropdown you will see some options for this URL:
![image](https://github.com/kkapsner/CanvasBlocker/assets/1105157/5a7f5f36-7ded-4d09-bffd-c8060aed6b4c)

The green checkmark whitelists and you are guided through the process.
