### ISSUE TITLE
Option to replace first-run page with default settings

### ISSUE THREAD

**Issue by allo-** [kkapsner/CanvasBlocker#656]
This is more meant as general discussion for a solution to two use-cases:

1) For tools like [FFProfile](https://github.com/allo-/firefox-profilemaker) I try to reduce the number of first-run pages when pre-installing addons.
2) I also often use temporary profiles which I throw away afterward for testing things. Installing basic privacy addons using enterprise policies is useful, but getting the first-run pages of each addon is inconvenient

I wonder what options are there to reduce the steps on first run in such cases and if you would be willing to implement helpful features for that when possible. I think the new addon API also limits the access to "about:config" settings for addons, but especially for enterprise policies one also cannot ship other files for the profile.

**Comment by allo-** [comment]
Thank you.

**Comment by kkapsner** [comment]
You're welcome.
