### ISSUE TITLE
Blocks the page

### ISSUE THREAD

**Issue by wbak1102** [kkapsner/CanvasBlocker#657]
CanvasBlocker is blocking this page and can't do anything about it  >>https://tubelessceliolymph.com/blocked  >> https://voe.sx/blocked
 version 1.9 OK ,  1.10Alpha20230419 blocks pages.

**Comment by kkapsner** [comment]
Please write a step by step reproduction scenario. The URLs above always show the same result - even when CB is disabled.

**Comment by kkapsner** [comment]
No further context given... so I have to close this issue. If you provide the missing information I can reopen it.
