### ISSUE TITLE
'deepl.com/translator-mobile' - site is not usable

### ISSUE THREAD

**Issue by WebworkrNet** [kkapsner/CanvasBlocker#658]
## Description

The URL keeps changing between https://www.deepl.com/translator-mobile and https://www.deepl.com/translator.

## Expected Behaviour

I expect that the mobile version of the website will open properly and that functionality will not be compromised.
## Current Behaviour

See above.
## Possible Solution

No proposals
## Steps to Reproduce (for bugs)

1. Enter URL.
2. Wait for the web page to load.

## Your Environment

* CanvasBlocker Version used: 1.9
* Firefox version incl. 32- or 64-bit: 115.0a1 (Build #2015952833), 52bf22861f+
GV: 115.0a1-20230526094428
AS: 115.20230526050248
* Operating System and version (desktop or mobile): Android 13
* Installed addons: 
CanvasBlocker
ClearURLs
Cookie AutoDelete
Firefox Multi-Account Containers
First Party Isolation
LocalCDN
NoScript
Skip Redirect
Smart Referer
Temporary Containers

## Your Settings

```
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1685192512982,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "15",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}

```

**Comment by kkapsner** [comment]
I can reproduce the issue with an old Firefox nightly and the problem is "Fake minimal screen size" (fakeMinimalScreenSize).

But with the latest build (115.0a1 - Build #2015953219) it's gone. Please check if it works for you as well now.

**Comment by WebworkrNet** [comment]
I will test again when version 115.0a1 - build #2015953219 has been rolled out for me in GooglePlay. I currently have version 115.0a1 (build #2015953217), 4a743b68e9+.
GV: 115.0a1-20230527212147
AS: 115.20230528050413 installed.

**Comment by kkapsner** [comment]
I dug a little bit deeper. This setting should be false by default in mobile. But I think my mobile check is not working properly any more.

So there is definitely something to fix in CB.

**Comment by WebworkrNet** [comment]
I don't want to push, but would like to know when version 1.10 will be released. As far as I understand the current process, the bug was already fixed at the end of May. Thanks for that :-)

I already use the site quite often and currently always have to switch to another browser.

**Comment by spodermenpls** [comment]
@WebworkrNet You could try to bridge the gap between official releases with the latest of the self-hosted alpha versions, which are hosted here: https://canvasblocker.kkapsner.de/versions/.

**Comment by WebworkrNet** [comment]
@spodermenpls Thanks for the tip, can also import the xpi file directly on the smartphone without a desktop computer? I have not found instructions in a hurry and so the file can not be opened (no suitable android application).

**Comment by spodermenpls** [comment]
@WebworkrNet I've dug around a little bit, I guess the "new" Firefox for Android only lets you choose between officially hosted AMO addons (via "Collections"), without a sideloading option (installing an .xpi from file or link).. it's still a sad state of affairs, unfortunately.

**Comment by WebworkrNet** [comment]
@spodermenpls That is also my level of knowledge. Nevertheless, many thanks for your efforts!

**Comment by spodermenpls** [comment]
@WebworkrNet Maybe you already heard about it, but Firefox for Android 122 allows you to install addons from a local file.

**Comment by WebworkrNet** [comment]
> @WebworkrNet Maybe you already heard about it, but Firefox for Android 122 allows you to install addons from a local file.

No, I haven't noticed that yet. I think it's very nice that you pointed out this innovation to me. Thank you

There's certainly an official source for this, right?

And how do I proceed in this case?

**Comment by spodermenpls** [comment]
@WebworkrNet Since you're a German Landsmann, I will direct you to the German article where I saw this coincidentally yesterday (and was quickly reminded that half a year ago we talked about this feature missing): https://www.soeren-hentzschel.at/firefox-android/installation-lokale-erweiterungen/

5 taps on the Firefox logo in the "About Firefox" submenu, and the "Install addon from file" entry appears in the settings menu.

**Comment by WebworkrNet** [comment]
@spodermenpls Thank you very much!

**Comment by WebworkrNet** [comment]
I have activated the debug mode of the browser as described (tap the Firefox logo 5 times). As a result, I was able to install `canvasblocker_beta-1.10Alpha20240216.xpi`. Is this an alpha or beta version?

At first glance, Deepl now looks usable again. Thanks again

**Comment by spodermenpls** [comment]
> I have activated the debug mode of the browser as described (tap the Firefox logo 5 times). As a result, I was able to install `canvasblocker_beta-1.10Alpha20240216.xpi`. Is this an alpha or beta version?

@WebworkrNet Good to hear that it works. The self-hosted .xpi's are Beta versions.

**Comment by WebworkrNet** [comment]
Looks like 2 versions are now installed.

![Screenshot_20240318_142308_Firefox Nightly.jpg](https://github.com/kkapsner/CanvasBlocker/assets/43509007/ff87727f-7150-4af8-bbcb-01f83730ec81)

I'd better deactivate the older version that I have integrated via my collection.

**Comment by spodermenpls** [comment]
> Looks like 2 versions are now installed.
> 
> I'd better deactivate the older version that I have integrated via my collection.

Yes, one CB version has to be deactivated (in this case the Release version, until the Beta changes have been implemented there as well).

**Comment by kkapsner** [comment]
I hope the next official release will be soon...
