### ISSUE TITLE
'nodeName' called on an object that does not implement interface Node

### ISSUE THREAD

**Issue by welwood08** [kkapsner/CanvasBlocker#66]
On https://accounts.firefox.com/ with block mode as either of the ask permission settings I get this error:
`TypeError: 'nodeName' called on an object that does not implement interface Node. askForPermission.js:15:1`

Tested in Firefox 45.0a1, 46.0 and 48.0a2 on Windows 8.1. Asking for permission works on other sites.

**Comment by kkapsner** [comment]
This is a realy weird error. But I could reproduce it and it will be fixed in the next release.
