### ISSUE TITLE
Display version information

### ISSUE THREAD

**Issue by WebworkrNet** [kkapsner/CanvasBlocker#661]
## Description

Version information is not displayed.

![Screenshot_2023-05-29_22-53-35](https://github.com/kkapsner/CanvasBlocker/assets/43509007/7fb822ca-241c-43ac-8b80-4bb70697172d)

## Expected Behaviour

Version information is properly displayed.

## Current Behaviour

Another window opens with a changed address line. However, the newly opened window contains the identical contents of window 1, as far as I can see.

## Possible Solution

No proposal

## Steps to Reproduce (for bugs)

Activate button "Show".

## Context

No further information

## Your Environment

* CanvasBlocker Version used: 1.9
* Firefox version incl. 32- or 64-bit: 115.0a1 (Build #2015953217), 4a743b68e9+
GV: 115.0a1-20230527212147
AS: 115.20230528050413
* Operating System and version (desktop or mobile): Android 13
* Installed addons: 
CanvasBlocker
ClearURLs
Cookie AutoDelete
Firefox Multi-Account Containers
First Party Isolation
LocalCDN
NoScript
Skip Redirect
Smart Referer
Temporary Containers

## Your Settings

```

{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 0,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "18",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}
```

**Comment by kkapsner** [comment]
I have no clue what the problem is there.
Same happens for me with the settings export page.

You can close the browser completely and reopen it. the page will the be loaded properly. My guess is that it's a "nightly" thing...

**Comment by kkapsner** [comment]
But I found a way around that bug... now I have to apply it everywhere... welp.

**Comment by WebworkrNet** [comment]
I can confirm that calling up the version number now opens a new tab containing a changelog that starts with the current software version and is then sorted in descending order. 

Thanks :-)

**Comment by WebworkrNet** [comment]
Tested version: `canvasblocker_beta-1.10Alpha20240216.xpi`, compare #658.
