### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by QueenUlyana** [kkapsner/CanvasBlocker#667]
**CanvasBlocker is an analogue of Canvas Defender? 
Is it possible to set a time interval in CanvasBlocker when the print will change as in Canvas Defender? (I have not found such an option in CanvasBlocker). I would also like to know if there is an option to enable notifications if some site tries to get my print as it is done in Canvas Defender? 
Am I correct in assuming CanvasBlocker cannot be used with DuckDuckGo Privacy Essentials since it has "Escape Fingerprinting - help stop companies from creating a unique identifier for you by blocking their attempts to combine specific information about your browser and device settings."?**

**Comment by QueenUlyana** [comment]
@kkapsner

**Comment by kkapsner** [comment]
Sorry for the late response...

CanvasBlocker and Canvas Defender are not related and have different features.

If you use the persistent random number generator you can delete the persistent data after a certain time period:
![grafik](https://github.com/kkapsner/CanvasBlocker/assets/1105157/e705f0ba-6450-4cf9-b1dc-8235d096e76f)

Notifications are handled via the finger print icon in the URL bar:
![grafik](https://github.com/kkapsner/CanvasBlocker/assets/1105157/c7fc9c8e-a9b7-494b-8387-a37c18d478dc)
You can click on it and get more details about the protection.
Be aware that not every notification is a finger print attempt.

I do not know of any problems with DuckDuckGo Privacy Essentials. You can go to https://canvasblocker.kkapsner.de/test/ and perform some test with only one enabled and both enabled and see if there are any problems.
Unfortunately I do not have time to test this myself.
