### ISSUE TITLE
CanvasBlocker is causing accounts.google.com to prohibit login.

### ISSUE THREAD

**Issue by KiARC** [kkapsner/CanvasBlocker#669]
## Description

When CanvasBlocker is running, attempting to sign in on `accounts.google.com` causes this error:
![image](https://github.com/kkapsner/CanvasBlocker/assets/73847484/213bc31c-1764-434e-bf01-38eb3f8644ea)
## Expected Behaviour

User is able to sign into their account.
## Current Behaviour

`accounts.google.com` determines that the browser is "not secure."
## Possible Solution

Not sure, since I can't tell exactly what is causing it, but it seems it has happened before in #564.
## Steps to Reproduce (for bugs)

1. Make sure cookies are cleared on `google.com` and all subdomains, and that CanvasBlocker is enabled
2. Go to any Google service and attempt to sign in
3. Input Gmail address
4. Click "Next"
5. Error occurs

## Context

It is preventing me from signing into google, and by disabling other add-ons I have determined that CanvasBlocker is in fact the offending add-on.
## Your Environment

* CanvasBlocker 1.9
* Firefox 116.0b8 (64-bit)
* Windows 11 Pro

## Your Settings
~~~ json
{
	"logLevel": 1,
	"hiddenSettings": {},
	"expandStatus": {
		"protectAudio": false
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "input",
	"minFakeSize": 10,
	"maxFakeSize": 0,
	"rng": "constant",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 3,
	"minColors": 3,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"storePersistentRnd": true,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "7",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": true,
	"navigatorDetails": {
		"osPreset": "Windows",
		"windowManager": "Windows",
		"platform": "Win32",
		"platformDetails": "Windows NT 10.0; Win64; x64",
		"oscpu": "{undefined}",
		"browserPreset": "Chrome",
		"appVersion": "5.0 ({platformDetails}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{chromeVersion} Safari/537.36",
		"buildID": "{undefined}",
		"productSub": "20030107",
		"userAgent": "Mozilla/{appVersion}",
		"chromeVersion": "115.0.0.0",
		"vendor": "Google Inc."
	},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}
~~~

**Comment by Thorin-Oakenpants** [comment]
try turning off `protectNavigator` - you're blatantly lying that you are webkit, and you cannot hide that you are really gecko - this is a massive paradox and one thing that will trigger fraud/bot detection

**Comment by kkapsner** [comment]
As my testing went the problem is when you try to fake a chromium based browser (i.e. Edge, Opera or Chrome). Faking Safari works. I guess they use a proprietary Chromium API to do some "magic" which fails in Firefox...
There is nothing I can do about this on the CB side. 

So you should disable the navigator protection for this URL.
