### ISSUE TITLE
Notification icon instead of bar

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [kkapsner/CanvasBlocker#67]
Right now, the notification bar is HUGE, it takes up a lot of valuable vertical space and grabs a lot of your attention due to the roll-out animation.
Would it be possible to make the notification smaller so that it takes up less space?

Maybe an optional small icon that turns red when canvas is being blocked, like flashblock.

![canvasblock notification icon instead of bar](https://cloud.githubusercontent.com/assets/12411527/15138008/5e3048e8-168d-11e6-9290-23b4ec4c8750.png)

**Comment by kkapsner** [comment]
There is no way to make the notification smaller since it's provided by Firefox itself.
A button with a changing icon can be done... I just have to find the time for it.

PS: The place that you suggest is deprecated in Firefox 29 and removed in Firefox 38.

**Comment by kkapsner** [comment]
The new WebExtension now uses a page action button that appears when something was faked.
