### ISSUE TITLE
Not issue - question!

### ISSUE THREAD

**Issue by privacyguy123** [kkapsner/CanvasBlocker#672]
I assume yes but I thought I'd ask the author - I assume that having these settings toggled on within FireFox would mess with what CanvasBlocker is doing?

![image](https://github.com/kkapsner/CanvasBlocker/assets/50337995/42217eca-a125-49e1-8d9b-0692fda71d9a)

**Comment by kkapsner** [comment]
Yes, @AtmosphericIgnition is right: these settings should not interfere with CanvasBlocker.

**Comment by Thorin-Oakenpants** [comment]
actually .. `Suspected fingerprinters` (I think the name is not very good) is actually FPP which in 120+ will randomize canvas, including workers and has nothing to do with blocking scripts
