### ISSUE TITLE
witwiw

### ISSUE THREAD

**Issue by markjpT** [kkapsner/CanvasBlocker#673]
## Steps to Reproduce (for bugs)

1. create a fresh Firefox profile
2. 
3. 
4. 

## Your Environment

* CanvasBlocker Version used:
* Firefox version incl. 32- or 64-bit:
* Operating System and version (desktop or mobile):
* Installed addons:

## Your Settings
~~~ json
<!--- Copy your CanvasBlocker settings here. -->
<!-- They can be retrieved by checking the expert mode and going to export settings. -->
<!--- You may consider deleting personal data - especially the "persistentRndStorage". -->
~~~

**Comment by kkapsner** [comment]
This is junk
