### ISSUE TITLE
Need of Firefox Multi-Account Containers ?

### ISSUE THREAD

**Issue by DomOBU** [kkapsner/CanvasBlocker#677]
## Description
Hello,

Attached is a message from Firefox.

Does CanvasBlocker require the use of Firefox Multi-Account Containers?

Thank you for your answer.

## Steps to Reproduce (for bugs)

1. create a fresh Firefox profile
2. 
3. 
4. 

## Your Environment

Windows 10 Famille  Version: 22H2
Firefox 120.0.1
CanvasBlocker 1.9

## Your Settings
~~~ json
<!--- Copy your CanvasBlocker settings here. -->
<!-- They can be retrieved by checking the expert mode and going to export settings. -->
<!--- You may consider deleting personal data - especially the "persistentRndStorage". -->
~~~
![CB Capture](https://github.com/kkapsner/CanvasBlocker/assets/95876663/649956c4-48a5-4504-b0fa-9f296da6b03f)

**Comment by markmfrost** [comment]
no need any other extension

**Comment by marinegundoctor** [comment]
In case anyone else is wondering, using CanvasBlocker will require that you have the "Container Tabs" option enabled in Settings-->Tabs and the Settings page is alerting you that that is the reason the option to enable/disable is greyed out and enabled by default. It is giving you the option to disable the CanvasBlocker extension if you want to be able to disable the Container Tabs option/setting.
![Screenshot 2024-03-14 at 17 53 39](https://github.com/kkapsner/CanvasBlocker/assets/8253497/b8787ab7-8ca1-4201-8f8d-dd5fac7466c3)

**Comment by kkapsner** [comment]
CanvasBlocker itself does not need the container tabs. The issue was already discussed in #381. It is a limitation of Firefox and requires changes there. You can upvote the bugzilla tickets linked in the other issue. Maybe someone at the dev team will then look at it...
