### ISSUE TITLE
CanvasBlocker breaks Tinkercad and causes possible GPU driver issues

### ISSUE THREAD

**Issue by Blarnix** [kkapsner/CanvasBlocker#680]
## Description
 Using TinkerCad's 3D editor to design an object, CanvasBlocker seems to cause performance issues in the website, as the FPS of the editor drops significantly, stutters, and causes my other windows and wallpaper on my PC to flicker. Disabling it for the site caused it to run perfectly once more. Possibly related to AMD cards and MSI afterburner, but testing did not change anything.

## Expected Behaviour
 It should run smoothly with minimal interruption, as functionality should be preferred over blocking in this specific case.

## Steps to Reproduce (for bugs)
 https://www.tinkercad.com/
1. create a fresh Firefox profile
2. Open TinkerCad
3. Import or create new object
4. Move around the editor and notice the stuttering/fps drops.

## Context
 Just trying to edit an object in TinkerCad and it is very difficult to work on.
 Yes.

## Your Environment

* CanvasBlocker Version used: Version 1.9
* Firefox version incl. 32- or 64-bit: mozilla-MSIX - 1.0 Version 1.21.0 (64-bit)
* Operating System and version (desktop or mobile): Windows 11 Pro 22H2 (OS Build 22621.2861)
* Installed addons: uBlock Origin, DarkReader, Sponsorblock, Return YouTube Dislike, Decentraleyes

## Your Settings
~~~ json
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": true,
	"whiteList": "octopi.local, 192.168.86.54, octopi, tinkercad.com, 192.168.86.26, localhost",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1703612357375,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "color",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "16",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "dark",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}

~~~

**Comment by kkapsner** [comment]
Hm... framerates seem fine for me (Laptop with integrated graphics).

I think the only solution for you is to whitelist this page for the canvas API:
![image](https://github.com/kkapsner/CanvasBlocker/assets/1105157/3ca75fc2-487b-46d7-be5b-b39f8e844553)
