### ISSUE TITLE
CanvasBlocker breaks overlays on windy.com map

### ISSUE THREAD

**Issue by Termuellinator** [kkapsner/CanvasBlocker#682]
When CanvasBlocker is active, the different overlays (rain, clouds and so on) on the windy.com map don't work anymore. They are either very distorted or completely gone, depending on the overlay.

As there hasn't been an update, probably due to some change on windy.com's side.
Disabling CanvasBlocker returns page to normal working state again.

Verified behaviour on fresh FF profile with only CanvasBlocker installed.

## Your Environment
* CanvasBlocker Version used: 1.9
* Firefox version incl. 32- or 64-bit: 121.0 64bit
* Operating System and version (desktop or mobile): Arch Linux, Kernel 6.6.10-arch1-1, KDE Plasma 5.27.10, AMD 6900xt
* Installed addons: a lot, but on fresh profile only CanvasBlocker

## Your Settings
As it also can be reproduces with a fresh profile with default settings, i don't think these are helpful? If needed anyway, just let me know :)

**Comment by kkapsner** [comment]
It works if you whitelist the Canvas API (they use the webGL readPixels function - not sure why this breaks so hard)...

There are some things you could do:
1. whitelist this domain for the Canvas API
2. enable the file specific white list and specify the exact position in the code where the problem stems from - this might break with future updates of the site and also it might have a performance impact
3. not protect readPixels (not recommended - this is a global setting)

I don't think that there is anything I can do to improve the situation on the CB side.
