### ISSUE TITLE
FAQ website not working

### ISSUE THREAD

**Issue by baum3001** [kkapsner/CanvasBlocker#683]
As the Title states, your entire website @kkapsner seems to be inacessible due to a end of file error. I stumbled upon this while trying to acess the FAQ so i'm opening the Issue here.
![image](https://github.com/kkapsner/CanvasBlocker/assets/61051834/7494e635-4aa7-4340-a840-fd8a85d307a7)

**Comment by baum3001** [comment]
Works again on my side too, I don't know what happened but it fixed itself

**Comment by kkapsner** [comment]
Maybe my provider had some maintenance... but thank you for informing me.
