### ISSUE TITLE
Breaks Gamestop's webpage, Even while whitelisted

### ISSUE THREAD

**Issue by nebulousking1** [kkapsner/CanvasBlocker#685]
Trying to get into my gamestop account, cant find the sign in button, only have canvasblocker enabled and when i disable it the site works normally again

I'm on firefox 122.0 (64-bit)

My current settings are;
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "https://www.gamestop.com",
			"blockMode": "allowEverything",
			"highlightBrowserAction": "none"
		},
		{
			"url": "mail.google.com",
			"protectDOMRect": false
		},
		{
			"url": "onedrive.live.com",
			"protectDOMRect": false
		},
		{
			"url": "paypal.com",
			"protectWindow": false
		},
		{
			"url": "dhl.de",
			"protectWindow": false
		},
		{
			"url": "github.com",
			"blockMode": "allowEverything"
		}
	],
	"hiddenSettings": {},
	"expandStatus": {
		"blockMode": true,
		"highlightBrowserAction": true,
		"highlightPageAction": true,
		"showNotifications": true,
		"section_faking": false
	},
	"displayHiddenSettings": true,
	"whiteList": "https://www.gamestop.com/",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 1000000,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1706999365155,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "13",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "dark",
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}

**Comment by kkapsner** [comment]
This is a very weird one... I found the place in the code that causes the problem (extension.createProxyFunction -> the proxy on toString). I found a fix but have to validate that it does not break other stuff.

**Comment by nebulousking1** [comment]
Hey, thanks!

**Comment by kkapsner** [comment]
Version 1.10 will be available when Mozilla reviewed it.
