### ISSUE TITLE
ff 28.0

### ISSUE THREAD

**Issue by chunga1** [kkapsner/CanvasBlocker#69]
Hello, with the browser FF 28.0 running version 0.1.3.1 and later, but they do not support "fake random canvas", could you make support a "fake random canvas" with FF 28.0 version?

P.S
"Version 0.1.6\0.1.5.1\0.1.5\0.1.4 - Works with Firefox 26.0 and later" - Does not work with FF 28.0\26.0

**Comment by kkapsner** [comment]
To be honest: I did not test these versions with outdated versions of Firefox. I think the current FF on release date was FF 34. The changes made for version 0.1.3.1 require Gecko 29 which is used after FF 29. I changed the entries on AMO.

I think I managed to make the "other" version 0.2.2.2 work with FF 28: https://github.com/kkapsner/CanvasBlocker/releases/tag/0.2.2.2-OtherRelease
