### ISSUE TITLE
"iFrame Protection" test page for CanvasBlocker hard to interpret.

### ISSUE THREAD

**Issue by ajay-gh** [kkapsner/CanvasBlocker#691]
## Description
When running each test of the test page(s), 
- with FF 124.0, and 
- all other extensions disabled, and 
- the default settings of CanvasBlocker, 
the "Iframe Protection" does not work as expected.  

## Expected Behaviour
Using the configuration (explained above) I should be able to a page similar to other test pages. With a description, some "features", and results.

## Current Behaviour
The iframe protection page does not load properly, first I see is the explanatory text in the beginning, and one empty frame, then a few frames, then the frames disappear, and all there is left is the header. No hashes, or test results. 

## Possible Solution
The browser console shows several warnings when the test page is reloaded. But I have to admit that with limited explanation on the iframes test page, the console output is difficult to interpret. May be the page's behavior is normal, and I am simply not equipped / trained to interpret the results shown in the browser console. 

## Steps to Reproduce (for bugs)
should be clear from the above

## Context
 testing CB with the test pages provided, in order to understand whether CB works as expected, and whether there is interference with other addons. 
 yes
 It is obvious that more and more websites are trying to escape the flood of bots and hacks by using cloudflare and similar services. It is my impression that CB gets detected (may be other addons too ?), at least when 3p-frames are allowed in uBlock), and this does either result in rejected connections, or broken websites. Disabling CB does not (not always) fix these issues, but CB seems to be part of the problem. And as I am not willing to give up on using CB, I am running extended tests to better understand how to work around these problems.

## Your Environment
* CanvasBlocker Version used:   version 1.9
* Firefox version incl. 32- or 64-bit:    64-bit, v 124.0
* Operating System and version (desktop or mobile):   Macbook pro, Monterey, 12.7.4
* Installed addons:   all disabled for the tests

## Your Settings
default settings after choosing settings -> general -> reset -> stealth

**Comment by kkapsner** [comment]
I'm not able to reproduce your problem. This is displayed when I run the iFrame protection test page:
![image](https://github.com/kkapsner/CanvasBlocker/assets/1105157/4885e8b3-2f57-4283-9c7d-d3163aa6b65c)
I find the text understandable, BUT I also know the ins and outs of CB... So if you have any suggestions what exactly to clearify, go ahead.

Please show me a screenshot of the page and the console if it is different.

**Comment by ajay-gh** [comment]
Thanks for your answer !! 
If have run the iframe test again from a completely fresh copy of FF, with only one addon installed (CB).
When I open the console, clear all entries, and re-run the iframe test, the lines with test / OK / match are shown now [that is good  ;) ], but I also get many many repeating lines which look similar to this.
<img width="622" alt="image" src="https://github.com/kkapsner/CanvasBlocker/assets/46941311/8c6d8bbd-fc92-451d-b962-4026490b90bc">
I think this is what (probably) had me overlook the important lines just before I posted my issue.
If this doesn't help please let me know.

I would like to ask another question (related) :
when I first started using CB a few years ago, you explained that CB cannot protect a page if iframes are used. I think I remember it was mainly a performance issue. Now I see (through this test) that CB covers iframes. How did this major advantage come about ... in a few words ? Or did I misunderstand back then >

**Comment by kkapsner** [comment]
These error messages are a problem in Firefox (see #471 and the linked bugzilla ticket for more details). So there is nothing I can do about them.

> I would like to ask another question (related) :
> when I first started using CB a few years ago, you explained that CB cannot protect a page if iframes are used. I think I remember it was mainly a performance issue. Now I see (through this test) that CB covers iframes. How did this major advantage come about ... in a few words ? Or did I misunderstand back then >

The iFrame protection is in place since 2017 (but not in the full form). So I do not remember this conversation... if you point me to it I can judge if and what was the misunderstanding.
