### ISSUE TITLE
cancel option on `Protect windows API` prompt doesn't cancel

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [kkapsner/CanvasBlocker#695]
testing canvasblocker_beta-1.10Alpha20240216 - as per title

**Comment by kkapsner** [comment]
Thanks for testing. The prompt is only about reCAPTCHA. So hitting "cancel" will still set the window API protection but will not enable the specific whitelist fo reCAPTCHA.

Maybe I should replace the "Cancel" with "No".

**Comment by Thorin-Oakenpants** [comment]
My bad, I didn't read it properly, and I was lacking coffee. I'm sure it's fine :)

**Comment by kkapsner** [comment]
OK - no problem.
