### ISSUE TITLE
TZP: isPoint* returns a type error (when checked)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [kkapsner/CanvasBlocker#696]
see
- https://github.com/arkenfox/TZP/blob/88b30adb0bd14cbf5ec48cf676b1959ab3960be6/js/canvas.js#L120
- and there's one for isPointInStroke
- so what I do is test the first value's type (context.isPointInPath(0, 0))
   - in RFP, in FF with no spoofing etc, it is always a boolean
- CB returns undefined

![undefined](https://github.com/kkapsner/CanvasBlocker/assets/16656956/c453eda7-e4ff-4d7a-b00d-b7bada6e287e)

**Comment by kkapsner** [comment]
I'm not able to reproduce your problem. What are your settings? Which Version of FF and CB are you using?

**Comment by Thorin-Oakenpants** [comment]
Oh, it's been doing it for years (I assumed you knew and it was some limitation) and in any setting where I have isPoint* protected

lemme set up a new FF124 profile and install CB and leave at defaults .. brb

**Comment by Thorin-Oakenpants** [comment]
OK, visually all the settings look identical, I even had nightly and FF124 side by side looking at the settings for CB in each one

Anyway - nightly has had CB in for about a year (new machine) and I've played a few times with all sorts of canvas settings. But in my old machine I also saw this. This is the "bad" one. The good one is a brand new profile and a brand new CB install (except I turned on some UI stuff and disabled everything except default canvas)

The diffs appear to be `bad`
```json
	"protectedAPIFeatures": {
		"length @ history": false,
		"mozGetAsFile @ canvas": true,
		"toBlob @ canvas": true,
		"convertToBlob @ canvas": true,
		"toDataURL @ canvas": true,
		"getImageData @ canvas": true,
		"isPointInPath @ canvas": true,
		"isPointInStroke @ canvas": true,
		"getContext @ canvas": true,
		"strokeText @ canvas": true,
		"fillText @ canvas": true
	},
```

vs `good`
```json
	"protectedAPIFeatures": {
		"length @ history": false
	},
```

and yes the good one is protecting the values.

brb.. I have an idea. I think all you need to do is toggle the options

**Comment by Thorin-Oakenpants** [comment]
> I think all you need to do is toggle the options

nope. Anyway, I imported `bad` into `good` and I get the issue.

Here are the two files
- [cb-bad.json](https://github.com/kkapsner/CanvasBlocker/files/14887639/cb-bad.json)
- [cb-good.json](https://github.com/kkapsner/CanvasBlocker/files/14887640/cb-good.json)

**Comment by kkapsner** [comment]
It's the persistent rng.

**Comment by Thorin-Oakenpants** [comment]
hmm .. where is that settings .. AFAICT I have "manually" reset things to default regards canvas - and the settings UI are identical (maybe I am blind)

**Comment by kkapsner** [comment]
What do you exactly mean by "label"?

Something like this?
![image](https://github.com/kkapsner/CanvasBlocker/assets/1105157/3446b79c-ef85-484d-bfe6-07ea89c1f15a)

**Comment by kkapsner** [comment]
Check the latest version at https://canvasblocker.kkapsner.de/versions/

**Comment by spodermenpls** [comment]
@kkapsner Maybe a good occasion to finally hyphenate "non-persistent" and "nicht-persistent".

**Comment by Thorin-Oakenpants** [comment]
> Something like this

yup

**Comment by kkapsner** [comment]
> @kkapsner Maybe a good occasion to finally hyphenate "non-persistent" and "nicht-persistent".

does it really need to be hyphenated? Both my German and English Grammar regarding this are quite vague. What is the rule?
What is the difference to "Canvas API"?

> yup

I do not quite like the extra noise in the text... especially when I do it for all drop downs: 
![image](https://github.com/kkapsner/CanvasBlocker/assets/1105157/1b76f87c-872d-4178-89a9-14bbe46c9247)

**Comment by spodermenpls** [comment]
@kkapsner I am not a licensed English or German language surgeon, but I am very certain that one can use "nonpersistent" or "non-persistent" in English, but not "non persistent", without an hyphen. In German one might be able to use "nicht persistent", but I figure "nicht-persistent" looks more professional (and more harmonious to the English locale's "non-persistent").

Regarding the other change, how about "(default"/"(Standard)" only gets displayed in the dropdowns when the default setting is **_not_** selected? 😅

**Comment by Thorin-Oakenpants** [comment]
> I do not quite like the extra noise in the text... especially when I do it for all drop downs

you do you :) 🧀 

 just wasn't paying attention, it's not like I test CB often - and when I do I totally change everything to see what happens. I should just use the reset feature in future - I kinda think I set that persistent rng a while ago not thinking it was to do with the generator but rather that a same canvas result is persistent (per session + eTLD etc = as per TZP's notations) - in other words I am overworked and under-drinking 🍺  and should have known it was cached anyway

**Comment by kkapsner** [comment]
@Thorin-Oakenpants : I like the idea of being able to tell which settings were changed and which not. I just do not like the execution. I think it will involve the idea of @spodermenpls in the end.

@spodermenpls: I will talk to an English teacher tomorrow and act after that.

**Comment by kkapsner** [comment]
I think I quite like this approach:
![image](https://github.com/kkapsner/CanvasBlocker/assets/1105157/d436f936-1edd-48a0-b2fb-a1e0008957ac)

Having a way to search for all changed settings with the `:changed` tag and then have the default value be marked as such in the drop down.
But not having the marking when the default is selected:
![image](https://github.com/kkapsner/CanvasBlocker/assets/1105157/4700ce28-4ba6-47d3-bbf8-4c5358d7fbbf)

**Comment by kkapsner** [comment]
The [current beta version](https://canvasblocker.kkapsner.de/versions/) is my candidate for 1.10.1 - please test it.

**Comment by spodermenpls** [comment]
@kkapsner I have to correct myself. First of all "non-persistent" consists of a prefix and an adjective, got myself loopy there yesterday morning. 😅 I read further up on it, in German, "nicht-persistent" would be in fact wrong (I probably read it written that way too many times in the past), only "nichtpersistent" and "nicht persistent" being right. In English "non-persistent" is correct ("non persistent" being indeed wrong), but more so in a British English style, with American English usually refraining from using hyphens. My final proposal therefore is connecting the words, "nichtpersistent" and "nonpersistent".

Regarding the "default"/"Standard" thing, I think this solution is quite slick.

**Comment by Thorin-Oakenpants** [comment]
hyphenation of a prefix in english is pretty simple
- if it qualifies more than one word then you hyphenate, otherwise it is optional
- except latin phrases

e.g
- non-profit making (always)
- e.g. non-smoker, nonviolent, non-persistent, nonpersistent (optional)
- non sequitur (never, it's latin)

you're doing just fine :) have some 🧀
