### ISSUE TITLE
gmail connection not working with last canvasblocker release 1.10 04 Apr 2024

### ISSUE THREAD

**Issue by marreident** [kkapsner/CanvasBlocker#698]
With last release of Canvasblocker (1.10 from 4 Apr 2024) just installed today, gmail connection page not working. After entering the email @ nothing happens and the answer is that I must use an other explorer. When deactivating Canvasblocker, it works perfectly as it worked also with previous release of Canvasblocker.
Firefox 124.0.2 64 bits
windows10
canvasblocker 1.10 4Apr 2024

**Comment by kkapsner** [comment]
I deactivated 1.10 for the time being...

**Comment by spodermenpls** [comment]
> It's commit [87790c9](https://github.com/kkapsner/CanvasBlocker/commit/87790c9731a2fd4de42526bb3a0744f8f2d3bbcd)

I doubt that.

**Comment by kkapsner** [comment]
You're right... I shifted one line down. It's 200f6b31f3225b5ab33652bec69fc6fce278dfbc

**Comment by kkapsner** [comment]
Please try [canvasblocker-beta-1.10.1.20240405.zip](https://github.com/kkapsner/CanvasBlocker/files/14880459/canvasblocker-beta-1.10.1.20240405.zip)

**Comment by kkapsner** [comment]
@marreident: I'm not sure if I tested your scenario right. Please check the latest version on https://canvasblocker.kkapsner.de/versions/

**Comment by kkapsner** [comment]
The [current beta version](https://canvasblocker.kkapsner.de/versions/) is my candidate for 1.10.1 - please test it.

**Comment by marreident** [comment]
I load the last beta release. It sounds good for me. Thank you for your support !
