### ISSUE TITLE
YouTube hanging with 1.10 on Firefox stable builds, downgrade to 1.9 fixes the issue

### ISSUE THREAD

**Issue by spacesynth** [kkapsner/CanvasBlocker#699]
## Description
"A website is slowing Firefox, do you want to stop it?" warnings appearing in the browser.
I first suspected uBlock Origin being the culprit, but when I checked only CanvasBlocker was recently updated.

## Expected Behaviour
The expected behaviour is that of version 1.9, which was restored as soon as I downgraded. So I strongly believe the upgrade to 1.10 caused the hanging during Youtube video playback. In particular when searching and jumping to offsets in the video.

## Current Behaviour
I don't know what further details I could add. A software regression is a type of software bug where a feature that has worked before stops working. 

## Possible Solution
Downgrade to 1.9

## Steps to Reproduce (for bugs)
1. upgrade to 1.10
2. the problems appear when searching a youtube video during playback

## Context
There is no further explanation needed, really.

## Your Environment

* CanvasBlocker Version used: 1.10 (affected)
* Firefox version: 124.0.2, x64 stable channel, release version
* Operating System and version (desktop or mobile):  Win10 64pro 22H2 build 19045.4239
* Installed addons: numerous

## Your Settings
Glad to provide them!
https://github.com/spacesynth/userscripts-collection/blob/master/addon_settings/CanvasBlocker.json

I'm quoting this guy though:
https://github.com/kkapsner/CanvasBlocker/issues/698

As other Google / Alphabet sites seem to be affected.

**Comment by kkapsner** [comment]
I deactivated 1.10 for the time being...

**Comment by JohnPlanetary** [comment]
I noticed in the Firefox 124.0.2, with CanvasBlocker 1.10, that memory consumption would go from 84 MB (without CanvasBlocker 1.10) in https://translate.google.com to 3GB (with CanvasBlocker 1.10) and memory would be consumed until the computer completely freezes, and I had to force the restart by using the physical power button.
In the CanvasBlocker 1.09 I didn't have issues.

**Comment by kkapsner** [comment]
Please try [canvasblocker-beta-1.10.1.20240405.zip](https://github.com/kkapsner/CanvasBlocker/files/14880459/canvasblocker-beta-1.10.1.20240405.zip)

**Comment by spodermenpls** [comment]
> Please try [canvasblocker-beta-1.10.1.20240405.zip](https://github.com/kkapsner/CanvasBlocker/files/14880459/canvasblocker-beta-1.10.1.20240405.zip)

Works again.

**Comment by spacesynth** [comment]
@kkapsner 
Thanks for the fast fix, I was able to load your beta as temporary addin in ```about:debugging``` because stable channel does not allow to use ```xpinstall.signatures.required``` and the YouTube issues are fully gone!

**Comment by kkapsner** [comment]
You should be able to install it permanently via https://canvasblocker.kkapsner.de/versions/

**Comment by spacesynth** [comment]
Thanks for the link to signed betas! This works great. I close the issue now, unless someone still needs it.

**Comment by spodermenpls** [comment]
@kkapsner The auto-update of your self-hosted versions has some issues, after I installed the latest 1.10.1 version, Firefox immediately tries to "update" to version 1.10 from March 30th, which re-introduces the "CB slows down this site" problem.

**Comment by kkapsner** [comment]
I know... the version scheme has to be changed for the betas. I think I will create a new alpha tomorrow with a version that prevents this problem.

**Comment by spodermenpls** [comment]
@kkapsner Is there a real need for a split between "Alpha" and "Beta" versions though?

**Comment by kkapsner** [comment]
not really... and the split is very fuzzy already...

**Comment by kkapsner** [comment]
Update for "beta" should work now again.

**Comment by kkapsner** [comment]
The [current beta version](https://canvasblocker.kkapsner.de/versions/) is my candidate for 1.10.1 - please test it.
