### ISSUE TITLE
How safe is CanvasBlocker to use with TOR Browser?

### ISSUE THREAD

**Issue by utsubushi621** [kkapsner/CanvasBlocker#70]
Since the code is not open-source, I'd like to know if the Canvas Blocker app communicates in any way with the internet that might break the anonymity of Tor if this add on is added to Tor Browser. At the same time I would like to request -if it isn't already compatible with Tor browser without jeopardizing the anonymity that is offered with Tor- that it be made compatible and secure enough to trust. In other words not only should it be compatible with Tor, but it should increase the anonymity Tor has to offer by default. I wanted to add this add-on to Tor but was unsure whether there is any communication going on in the backend of CanvasBlocker that might jeopardize the anonymity or defeat the purpose of using said browsers.

**Comment by kkapsner** [comment]
The code from CanvasBlocker is completely open-source... why do you think it's not?

But to answer your question: CB does not communicate with anything on the internet. I do not see any problem in using it with Tor Browser (but a independent review on that would be great!). But as far as I know the Tor Browser has a build-in feature that serves the same purpose as CB - to be sure you should check that.

**Comment by utsubushi621** [comment]
I'm sorry I must have misunderstood when I was reading through the license files. I thought it was close sourced haha. Well then I am relieved to hear that it is open-source and glad to hear there would be no problem in using it with Tor. I didn't know also about the built-in feature that acts similar to CB in Tor, so thank you for informing me and for resolving my inquiry! Also thanks for making CB you are awesome!
