### ISSUE TITLE
Enable/Disable/Whitelist Not Working

### ISSUE THREAD

**Issue by smashedr** [kkapsner/CanvasBlocker#718]
This extension is preventing Grafana from loading even when toggling the extension off for the site, verifying it is in the whitelist, and all whitelist boxes, including All APIs, are checked. 

## Expected Behaviour
I would expect Grafana to load after disabling the extension for that site. 

## Current Behaviour
This error is throw in the console and the site fails to load:
```Uncaught TypeError: `target` argument of Reflect.getPrototypeOf must be an object, got null```

## Possible Solution
The only solution is to disable the extension in the addon manager.

## Steps to Reproduce (for bugs)
1. Install the addon
2. Attempt to load Grafana
3. Disable the addon for the site
4. Refresh the page

## Context
Makes the addon unusable since it must be completely disabled to load Grafana.

## Your Environment
os 	Windows 10
applicationName 	Firefox
architecture 	x86-64
buildId 	20240725162350
version 	128.0.3
vendor 	Mozilla
xpcomAbi 	x86_64-msvc 

## Your Settings
```json
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "redacted",
			"blockMode": "allowEverything",
			"blockDataURLs": false
		}
	],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": false,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 0,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "0",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": false,
	"displayDescriptions": false,
	"theme": "auto",
	"showPresetsOnInstallation": true,
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}
```

**Comment by spodermenpls** [comment]
Yes, it is a known regression that affects Grafana and other sites (#705 #707 #709 #715). @kkapsner already started working on it, but unfortunately wasn't able to publish a fixed version yet.

**Comment by snpaul22** [comment]
Following for the same issue

**Comment by solonovamax** [comment]
this issue, quite annoyingly, occurs even if canvas blocker is set to "allow everything"

**Comment by kkapsner** [comment]
Close as a duplicate from #705

**Comment by knaggsy2000** [comment]
I can confirm that the whitelist isn't working at all.

Tried individual IPs and even netmasks - nothing seems to work.  The issue is certainly with CanvasBlocker as when you disable it, Grafana works fine.

**Comment by law** [comment]
This is great - I've been suffering through this for 6+ months now, WITH GRAFANA, and I finally went through the troubleshooting steps of disabling extensions in turn, zeroing in on Canvasblocker, etc.  I come here to file a bug, search, and... not even an hour beforehand, I learn there's a fix in the works haha.  

Following, so I can get notified when the Mozilla verification is in flight.  In the meantime, I've been using Grafana in Private Mode (where CanvasBlocker is not enabled) with no issues.  

Do we have a rough ETA on when the latest version will be verified by Mozilla?

**Comment by kkapsner** [comment]
No - I have no ETA.

**Comment by knaggsy2000** [comment]
Using grafana in recent days for me - hasn't produced the same.

Maybe something has happened outside of grafana?
