### ISSUE TITLE
NO FAKE READOUT ON SOME WEBSITES

### ISSUE THREAD

**Issue by jurassa** [kkapsner/CanvasBlocker#72]
FIRST ISSUE:

thanks for sharing this addon, it works great with a lot of sites however there is no fake readout on certain sites

for ex.  when you open WWW.GUMTREE.COM with the Tor brower it will notify you about the canvas fingerprinting but not with Mozilla (with your addon installed).  However the addon works fine on many other websites

Could it be that Gumtree have already discovered about the fake readouts and have found a way to defend against this?

 SECOND ISSUE: 

is there any way of changing the settings of the canvas blocker, there seems to no 'dialogue box' for blacklisting/whitelisting websites?

i would really appreciate any advice/help on these issues

**Comment by kkapsner** [comment]
For the first: does the Tor browser provide any additional information about this incident? E.g. the information which script file that causes the warning would help to investigate further. With no further information it will take a lot of time to find the reason for the different behaviour.
Maybe it's a false alert on the Tor browser side.

For the second: You can change the settings of CB by going to about:addons and clicking the "settings" button next to the addon. Then you see a site with all the settings. Why would you need a separate dialog?

PS: It's better to have two different tickets open if you have two different issues.

**Comment by jurassa** [comment]
thanks for the reply, regarding the GUMTREE issue, just open gumtree.com on Tor and see what happens:

this is the exact message you get from Tor:  **THIS WEBSITE (GUMTREE.COM) ATTEMPTED TO EXTRACT HTML5 CANVAS IMAGE DATA WHICH MAY BE USED TO UNIQUELY IDENTIFY YOUR COMPUTER.  SHOULD TOR BROWSER ALLOW THIS SITE TO EXTRACT HTML5 CANVAS IMAGE DATA?**
 
this website seems to have a way of identifying every user uniquely, you can remove cookies, change brower, change ip etc but still they will know that its the same user, i don't know if it's the canvas fingerprinting or they are using some other methodology

what is strange for me is that your addon works on the majority of sites that use canvas fingerprinting but with Gumtree there is no Fake Readout, so I think Gumtree have already figured what your addon is capable of and have found a method of circumventing it, since they want to track every single user

any advice on this would be greatly appreciated

**Comment by kkapsner** [comment]
If you install CB in the Tor Browser it fakes the readout and gives a notification. So I think this website detects if you are using Tor and deliveres a different content to identify the user.

**Comment by jurassa** [comment]
this still doesn't explain why you do not get any fake readout on Mozilla (with CB addon installed);

Are you saying that when using for example Mozilla, chrome or Opera browser Gumtree does not use canvas fingerprinting, but it does with Tor?  How would gumtree know that someone is using Tor.

I want to add one very important point to this:  I remember on the first day when I installed your addon on Mozilla and opened Gumtree it gave a fake readout, this happened for next 1 or 2 days, and after that nothing.  But on other websites there is a fake readout every single time

I think Gumtree have found a way around your addon, just can't figure how they've done this.

**Comment by kkapsner** [comment]
It does explain why you do not get a fake readout. If you just install httpFox and record the resource that are loaded look out for bk-coretag.js - it is loaded on Tor but not on FF. And in this file the canvas access is performed.

I think it's not difficult to detect if someone is using Tor.
