### ISSUE TITLE
MSN: Expand news articles

### ISSUE THREAD

**Issue by WebworkrNet** [kkapsner/CanvasBlocker#720]
News: "Expand article" button is not always displayed.

## Description

News articles are only touched on with a teaser. To read the full article, click on the "Expand article" button. This button is not always visible. It is suspected that Canvas is responsible for this. However, several tests on my part have not yet been able to clearly verify this.

## Expected Behaviour

The "Expand article" button should always be displayed.
## Current Behaviour

The "Expand article" button is often not displayed.

Sample:
https://www.msn.com/de-de/nachrichten/other/jacht-ungl%C3%BCck-milliard%C3%A4r-feierte-freispruch-nun-ist-er-verschwunden-und-ein-mitangeklagter-tot/ar-AA1p7hia

![Screenshot_20240820_172320_Firefox Nightly](https://github.com/user-attachments/assets/11be6848-cbf0-4f63-84cc-2d1675b5c0cd)

Note: Do not confuse this with the blue "Read more in the app" button.

## Possible Solution

No proposed solution at present

## Steps to Reproduce (for bugs)

1. ~~create a fresh Firefox profile~~
2. Use Fenix (Firefox for Android) in standard or private mode.
3. Carry out a web search, usually via Startpage (`startpage.com` or primarily `eu.startpage.com`).
4. Call up a linked news page on MSN from the search results.

## Your Environment

* CanvasBlocker Version used: `1.10.1`
* Firefox version incl. 32- or 64-bit: `Nightly 131.0a1 (Build #2016039319), hg-cd88b12ff5ec+
GV: 131.0a1-20240818204048
AS: 131.20240815050258`

* Operating System and version (desktop or mobile): `Android 14, One UI 6.1`
* Installed addons:  
  * `CanvasBlocker`
  * ~~`Checkmarks` (currently disabled)~~
  *  `ClearURLs`
  * `Cookie AutoDelete`(not activated in private mode)
  * ~~`floccus bookmarks sync` (currently disabled)~~
  * `Firefox Multi-Account Containers` (not available in private mode)
  * ~~`Firefox Translations` (currently disabled)~~
  * `First Party Isolation`
  * `LocalCDN`
  * `NoScript`
  * ~~`Skip Redirect` (currently disabled)~~
  * ~~`Smart Referer` (not activated in private mode)~~
  * `Temporary Containers` (not available in private mode)
  * ~~`uBlock Origin` (currently disabled)~~

## Your Settings

~~~ json


{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {
		"displayAdvancedSettings": false,
		"blockMode": false,
		"disruptSessionOnUpdate": false
	},
	"expandStatus": {},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1724165754633,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "19",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": false,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"showPresetsOnInstallation": true,
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}

~~~

~~⚠️ I will provide further information later.~~

**Comment by kkapsner** [comment]
Even without CB being enabled the button is not always visible. I think it's a MSN thing...
