### ISSUE TITLE
CanvasBlocker causing Facebook to think my browser is outdated

### ISSUE THREAD

**Issue by emcdarby** [kkapsner/CanvasBlocker#725]
When I go into Facebook, I get a popup in the bottom left corner saying "Your browser is no longer supported. Please update to a newer version for the best experience."

## Description

The issue happens then I go into Facebook while I have CanvasBlocker enabled.

I think this might be a bug because I find it only happens when CanvasBlocker is enabled.

## Expected Behaviour

What should happen is I shouldn't be getting this message.

## Current Behaviour

Like I said, I get this "Your browser is no longer supported. Please update to a newer version for the best experience." popup in the bottom left corner while I have CanvasBlocker enabled.

## Steps to Reproduce (for bugs)

1. Create a fresh Firefox profile
2. Log into Facebook while CanvasBlocker is enabled.
3. 
4. 

## Context

It effects me because it makes me worried that I may get blocked from Facebook.

## Your Environment

* CanvasBlocker Version used: 1.10.1
* Firefox version incl. 32- or 64-bit: LibreWolf 118.0.1-1
* Operating System and version (desktop or mobile): Windows 10
* Installed addons: CanvasBlocker

## Your Settings
~~~ json
<!--- Copy your CanvasBlocker settings here. -->
<!-- They can be retrieved by checking the expert mode and going to export settings. -->
<!--- You may consider deleting personal data - especially the "persistentRndStorage". -->
~~~
{
	"logLevel": 1,
	"urlSettings": [],
	"hiddenSettings": {},
	"expandStatus": {},
	"displayHiddenSettings": true,
	"whiteList": "facebook.com",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1728448482658,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "6",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "colorful",
	"showPresetsOnInstallation": true,
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1

**Comment by Thorin-Oakenpants** [comment]
> LibreWolf 118.0.1-1

Firefox 118 was released over a year ago - on [2023-09-26](https://whattrainisitnow.com/calendar/). Even if you were on ESR you would be on 128 by now. The current release is 131. It wouldn't surprise me if Facebook requires a feature such as Segmenter API that 118 doesn't have.

There is no reason what-so-ever to run an unsupported browser version

**Comment by emcdarby** [comment]
Alright, I just found there was an up

**Comment by emcdarby** [comment]
Alright, I just found there was an update to LibreWolf, which is a privacy oriented fork of Firefox, and updated it to LibreWolf 131.0.2-1 to see if that solves this issue or not, even though I will mention it here if it continues to happen.

**Comment by Thorin-Oakenpants** [comment]
>  I'm not closing it yet until I know its resolved

is. it. resolved? :) Have you stomached visiting Facebook since Oct 15th?

**Comment by kkapsner** [comment]
I guess it's solved...
