### ISSUE TITLE
Whitelist domains in Cookie exception (allow) list

### ISSUE THREAD

**Issue by notDavid** [kkapsner/CanvasBlocker#73]
Please consider adding a feature to have a checkbox to turn on/off "Whitelist domains in Firefox Cookie exception (allow) list".

The domains in cookie exception list can recognize you by the cookies anyway, and then you don't have to manage 2 separate lists.

**Comment by kkapsner** [comment]
Well... the idea is neat but this is a little bit different. If domain A and domain B are both in your cookie exception list they can both recognize you. But they are not able to create a connection your two profiles on this separate domains. If I would autoinclude these in the whitelist they would be able to do this.
The CB whitelist is therefore more powerfull than the cookie exception list.

**Comment by notDavid** [comment]
ahh yes that makes sense... 👍
