### ISSUE TITLE
Youtube with User-Agent blocker extension fails

### ISSUE THREAD

**Issue by gelavat** [kkapsner/CanvasBlocker#730]
## Description
On Firefox, when we enable the CanvasBlocker extension, and also a User-Agent blocker extension together, then accessing to Youtube website lets only see about 20 seconds of video, and then it gets stuck.
I can reproduce this by simply installing CanvasBlocker in Fake mode, and then install "Random User-Agent" extension from Paramtamtam, and then restart Firefox and go to youtube watch a video.
It always fails after 20 seconds, the video stops and shows a ring like if the internet would be cut.
If I install another User-Agent blocker, like "User-Agent Switcher and Manager", the behaviour is exactly the same.
Hence I suppose that this is a compatibility problem in CanvasBlocker only.

Please note that this setup was working fine until end of october 2024, and it might be that youtube is using a flaw somewhere which detects that both extensions are enabled, to block them, because it prevents them to trace those people.

## Expected Behaviour
Be able to access and watch Youtube videos more than 20 seconds when those two extensions are enabled.

## Current Behaviour
Videos on Youtube blocks after 20 seconds of play.

## Possible Solution
Disable the User-Agent extension and it works. But this is not the solution of course, we should be able to enable both extensions.

## Steps to Reproduce (for bugs)
See above

## Your Environment
* CanvasBlocker Version used: 1.10.1
* Firefox version incl. 32- or 64-bit: 64 bits
* Operating System and version (desktop or mobile): Windows 11 64 bits
* Installed addons: CanvasBlocker, Random User-Agent

## Remarks

Can someone already try to reproduce this bug with the provided reproduction procedure and validate that it also fails ?

**Comment by kkapsner** [comment]
You have to allow the domain `jnn-pa.googleapis.com` to get the real user agent.
