### ISSUE TITLE
CanvasBlocker stops YouTube video loading even with all APIs allowed. It only starts loading again if you completely disable the extension

### ISSUE THREAD

**Issue by hjk789** [kkapsner/CanvasBlocker#734]
Since a few days ago, YouTube videos started to stop buffering after around 20 seconds of video when this extension is enabled. Even if you allow all of the APIs, this still happens. If you completely disable the extension, the videos load fine again. Because it always happen after around 20 seconds, I guess it has something to do with CanvasBlocker for some reason conflicting with YouTube's ability to download the next chunk, so it only downloads the first chunk. Or YouTube itself is refusing to load when it detects this extension is enabled, maybe.

## Your Environment
* CanvasBlocker Version used: 1.10.1
* Firefox version incl. 32- or 64-bit: 133.0.3 64-bits
* Operating System and version (desktop or mobile): Windows 10 desktop

## Your Settings
~~~ json
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "https://www.google.com",
			"protectDOMRect": false,
			"protectNavigator": false,
			"protectWindow": false
		},
		{
			"url": "https://www.youtube.com",
			"protectedCanvasPart": "nothing",
			"blockMode": "allow",
			"protectNavigator": false,
			"protectDOMRect": false,
			"historyLengthThreshold": 10000,
			"protectScreen": false,
			"protectSVG": false,
			"protectWindow": false,
			"protectAudio": false
		},
		{
			"url": "www.google.com",
			"protectedCanvasPart": "readout"
		},
		{
			"url": "play.google.com",
			"protectDOMRect": false,
			"protectNavigator": false
		},
		{
			"url": "drive.google.com",
			"protectNavigator": false,
			"protectedCanvasPart": "nothing",
			"protectDOMRect": false,
			"protectWindow": false
		},
		{
			"url": "content.googleapis.com",
			"protectWindow": false,
			"protectNavigator": false
		},
		{
			"url": "accounts.google.com",
			"protectNavigator": false
		},
		{
			"url": "ogs.google.com",
			"protectNavigator": false
		},
		{
			"url": "clients6.google.com",
			"protectWindow": false
		},
		{
			"url": "www.youtube-nocookie.com",
			"protectNavigator": false,
			"protectDOMRect": false
		},
		{
			"url": "www.youtube.com",
			"historyLengthThreshold": 10000
		}
	],
	"hiddenSettings": {
		"protectedAPIFeatures": false
	},
	"expandStatus": {
		"protectAudio": false,
		"historyLengthThreshold": true,
		"allowWindowNameInFrames": false,
		"protectNavigator": true,
		"protectDOMRect": true,
		"protectedCanvasPart": false,
		"protectScreen": true,
		"blockMode": false,
		"protectWindow": true,
		"protectTextMetrics": true,
		"highlightBrowserAction": false,
		"section_DOMRect-API": false,
		"section_Canvas-API": false,
		"section_Audio-API": false,
		"section_History-API": false,
		"section_Window-API": false,
		"section_TextMetrics-API": false,
		"section_Navigator-API": false,
		"section_Screen-API": false,
		"section_SVG-API": false,
		"protectSVG": true
	},
	"displayHiddenSettings": true,
	"whiteList": "",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "blockEverything",
	"protectedCanvasPart": "everything",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {
		"getBoundingClientRect @ domRect": true,
		"userAgent @ navigator": true,
		"toDataURL @ canvas": false
	},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": false,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "{}",
	"persistentIncognitoRndStorage": "{}",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1734221016301,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": true,
	"storeNotificationData": true,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": true,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "minimal",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "17",
	"historyLengthThreshold": 2,
	"protectWindow": true,
	"allowWindowNameInFrames": true,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": true,
	"navigatorDetails": {
		"browserPreset": "Chrome",
		"appVersion": "5.0 ({platformDetails}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{chromeVersion} Safari/537.36",
		"buildID": "{undefined}",
		"oscpu": "{undefined}",
		"productSub": "20030107",
		"userAgent": "Mozilla/{appVersion}",
		"osPreset": "Linux",
		"windowManager": "X11",
		"platform": "Linux x86_64",
		"platformDetails": "X11; Linux x86_64",
		"chromeVersion": "71.0.3578.98",
		"vendor": "Google Inc."
	},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": true,
	"theme": "auto",
	"showPresetsOnInstallation": true,
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}
~~~

**Comment by spodermenpls** [comment]
Have you allowed `jnn-pa.googleapis.com` on youtube.com in uMatrix? I also had this issue, albeit on my end, any YouTube video would stop playing at exactly 1:00 minutes. After I greenlit the aforementioned domain, videos are playing again without any issue, so at least on my end the issue wasn't actually CanvasBlocker-related.

**Comment by hjk789** [comment]
I did, but it didn't help. I even completely disabled uMatrix, but it only started working again after disabling Canvas Blocker. I also had that problem with the video stopping at 1:00, and indeed allowing jnn-pa.googleapis.com makes it work again. But I think this 0:19 issue is caused by another thing. It's likely to be some kind of conflict with Canvas Blocker, otherwise it would work again after allowing all APIs.

**Comment by spodermenpls** [comment]
@hjk789 Okay, and what if you turn off the navigator spoofing? It must be some issue with your configuration, I run the same CB and FF version as you, but have no issues playing Youtube videos.

**Comment by hjk789** [comment]
Even with all APIs turned off it it still breaks the video, including navigator.    
If I change the block mode to "Allow all" or "Block only blacklist" it works again, but if I change to any other mode, the video stops loading.

**Comment by hjk789** [comment]
Ok, finally fixed the problem. So the real problem here is that Canvas Blocker is blocking `jnn-pa.googleapis.com` but is not notifying about it. After disabling the Navigator API protection it started working again, then I added `jnn-pa.googleapis.com` and enabled Navigator protection, and it solved the problem.

**Comment by kkapsner** [comment]
It depends on which level the navigator protection is triggered. One is on a loaded page (i.e. using the navigator object) and the other is on the http request level when the user agent is spoofed. I guess that YouTube is doing something different when they see a Chrome user agent in the http request which then breaks the video playback.

So I will add this exception to the convenient preset.

**Comment by spodermenpls** [comment]
@kkapsner Glad to see you back!

**Comment by kkapsner** [comment]
@spodermenpls: was a rough year...
