### ISSUE TITLE
fsf + IceCat and CanvasBlocker

### ISSUE THREAD

**Issue by orencio** [kkapsner/CanvasBlocker#74]
Hello, I use IceCat. It is a fork of firefox to be completely free.
It has a extensions list (http://directory.fsf.org/wiki/IceCat) but CanvasBlocker doesn't appear in it.

Would you like it appear there? I don't know if MPL license is valid for fsf, I think it is valid.

**Comment by kkapsner** [comment]
Yes - why not. What do I have to do?

**Comment by kkapsner** [comment]
Thanks for putting CB there: http://directory.fsf.org/wiki/IceCat/CanvasBlocker
