### ISSUE TITLE
Whitelist applying to fake readout too.

### ISSUE THREAD

**Issue by Devices** [kkapsner/CanvasBlocker#75]
Like the title suggests, I would like it, if it's possible, for the whitelist to also apply to the fake readout setting. I'd like to give fake readouts to every website, besides the ones that don't work properly without canvas.

Is it this possible and is someone willing to put their time into this?

**Comment by kkapsner** [comment]
I do not quite get what you exactly want. The whitelisted sites/domains should not get faked readouts.

**Comment by Devices** [comment]
You are correct. I thought the whitelist only worked in 'block' mode because of the wording.
