### ISSUE TITLE
RNG is probably flawed

### ISSUE THREAD

**Issue by Bergfried** [kkapsner/CanvasBlocker#76]
Thank you very much for this addon. I am really concerned when it comes to privacy so this is why I use your addon in the first place. And it is also the reason for this post.

The RNG currently in use appears to be broken, at least from what I can tell. In `lib/randomSupplies.js` there is a line that reads `Math.floor(Math.random() * 0xFF)`. Apparently, it is part of a loop that is supposed to create `128 * 8 = 1024` bits of random noise. However, in reality, it will always be less noisy than expected. The reason is that `Math.random` will always return a value less than 1, so due to said expression, `0xFF` will never appear in any of the 128 bytes. The fix is easy in this case: replace `0xFF` with `0x100`. But I think the following is even simpler (and probably more secure):

    persistentRnd[domain] = new Uint8Array(128);
    window.crypto.getRandomValues(persistentRnd[domain]);

It would be really helpful if you add comments to your code (that is, the algorithms in `exports.persistent` and `exports.nonPersistent`, respectively) so we can understand what it is supposed to do. Otherwise, it just looks like magic that is hard to understand and, therefore, not secure. And since this addon is all about security, understanding the algorithms is actually important.

**Comment by kkapsner** [comment]
You are completely right. I will change that bit of code and add some comments.

But be aware that the persistent supply is not as "secure" as the nonPersistent.

**Comment by Bergfried** [comment]
You are welcome!
