### ISSUE TITLE
Maximal Fake Size Unit of Measurement

### ISSUE THREAD

**Issue by russ6100** [kkapsner/CanvasBlocker#77]
What unit of measurement is represented by the "Maximal Fake Size" value? Canvas height? Square pixels? Is there any sort of "normal range" that one might find being used in desktop web browsers?

Thank you so much for your work!

**Comment by kkapsner** [comment]
The size is measured in total pixels. I.e. width times height.

I can not give a normal range. The point of this option is that the browser freezes (and may even crash for very big canvas) if a large canvas is read. Therefore it highly depends on your computer and your patience. Personally I would not go below 30000. But the higher the saver - the lower the less annoying.

**Comment by russ6100** [comment]
Thanks so much for your reply! So - let me see if I am understanding something correctly - if allowing an extremely high canvas size could potentially result in a browser crash or some instability, does that indicate that CanvasBlocker doesn't just spoof a large canvas size value, but it sort of creates a virtual canvas of a random size and allows the the visited website's script to fingerprint that?

**Comment by kkapsner** [comment]
Partially right. Yes a temporary canvas is created but the size is the same - the color information is altered randomly.
