### ISSUE TITLE
CanvasBlocker and loading 360-photo on Facebook causes Firefox to be unresponsive

### ISSUE THREAD

**Issue by kenrick95** [kkapsner/CanvasBlocker#78]
> On Facebook, whenever I scrolled through a 360-photo, my Firefox gets unresponsive. After a while (around a minute), a pop-up box shows to prompt me to kill the unresponsive script, and after that, irregardless of me killing it or continuing the script, both my Firefox and the 360-photo works fine.

[I posted this issue on Firefox subreddit](https://www.reddit.com/r/firefox/comments/50kv2x/on_facebook_whenever_i_scrolled_through_a/) and someone pointed out that it may be addons issue, so I tried disabling all addons and turn on addon one by one to see which one causes my issue. It turns out to be CanvasBlocker (that uses Fake Readout option).

**Comment by kkapsner** [comment]
This is a known issue and the core idea of the faking mode is causing this problem. That's why I added the option to specify a maximal canvas size to be faked in version 0.3.1.
See #77 and #53 for more information.
