### ISSUE TITLE
Console errors in latest Nightly (FF52)

### ISSUE THREAD

**Issue by Vednier** [kkapsner/CanvasBlocker#80]
Hello, since several days ago i started to get this errors in console

console.error: 
  Message: SyntaxError: "use strict" not allowed in function with destructuring parameter
  Stack:
    @resource://canvasblocker-at-kkapsner-dot-de/lib/notifications.js:12:NaN
@resource://canvasblocker-at-kkapsner-dot-de/lib/main.js:12:19
@resource://canvasblocker-at-kkapsner-dot-de/lib/main.js:5:2
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:816:7
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise-backend.js:747:11
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise-backend.js:779:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise-backend.js:714:7
readURI/<@resource://gre/modules/commonjs/sdk/net/url.js:50:9
NetUtil_asyncFetch/<.onStopRequest@resource://gre/modules/NetUtil.jsm:128:17

using 52.0a1 (2016-10-27) build, addons version is latest 0.3.1

**Comment by kkapsner** [comment]
Thank you for letting me know that. I was not aware that this new Firefox version would break the addon... this will be fixed in the next version which will come soon.
