### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by joshzi** [kkapsner/CanvasBlocker#81]
Hi, first I would like to thank you for your efforts. I installed your addon today. But I get the feedback that my browser is still uniquely identifiable. I have tried various settings in the options of CanvasBlocker. 
Am I doing something wrong?

![2016-11-02 at 12-36-50](https://cloud.githubusercontent.com/assets/7757537/19928112/58d925cc-a0fd-11e6-9f41-e197c4e8eeec.jpg)

**Comment by kkapsner** [comment]
This is intentionally. If you are using the "fake output" mode, the addon creates a different output every time/session (depending on the rng supply chosen). So the canvas hash has to be unique. If you go to https://www.browserleaks.com/canvas you will see that the actual signature will change.
