### ISSUE TITLE
Please, include changelogs into the xpi so that Firefox could show them in the Add-Ons Manager

### ISSUE THREAD

**Issue by Drugoy** [kkapsner/CanvasBlocker#83]
Subj.

**Comment by kkapsner** [comment]
As far as I know the description in the addon manager is not given by the xpi but fetched from addons.mozilla.org. It's not common to show them there and I do not want them to show up there.

But eventually I wil add a button that shows them.

**Comment by Drugoy** [comment]
> As far as I know the description in the addon manager is not given by the xpi but fetched from addons.mozilla.org.

May be so.

> It's not common to show them there and I do not want them to show up there.

Why?

**Comment by kkapsner** [comment]
Because the place for release notes is at the version not the general descirpition on the addon.
