### ISSUE TITLE
Remove notification bar with a timeout?

### ISSUE THREAD

**Issue by shvfn** [kkapsner/CanvasBlocker#85]
Hi, I want to suggest the option to remove the notification bar after x seconds. 

I like to see the notifications, but it would be great, if they would be temporary (like eg Ghostery does it).

In any case: Thanks for the add-on!

**Comment by kkapsner** [comment]
Nice idea. I will create a setting for that.

**Comment by shvfn** [comment]
Great! Thank you!

**Comment by kkapsner** [comment]
You're welcome.
