### ISSUE TITLE
Firefox hangs on some xda-developer webpages

### ISSUE THREAD

**Issue by RoxKilly** [kkapsner/CanvasBlocker#88]
To reproduce:

- Install `CanvasBlocker 0.3.2` on `Firefox 49.0.2`
- Set block mode to `fake readout API`
- Set random number generator to `non persistent`
- Load [this XDA-developer page](http://forum.xda-developers.com/xposed/modules/xposed-appopsxposed-appops-4-3-t2564865)

The browser will become unresponsive and CPU usage will skyrocket.  If you add `forum.xda-developers.com` to the whitelist and reload, things work fine (except for the canvas spoofing of course).

Might be related to #84 , but maybe not because that bug report claims that whitelisting doesn't help that issue whereas it helps this one.

**Comment by kkapsner** [comment]
I can not reproduce your problem... I do not even get a faking notification every time - only sometimes. And when I get one it's from tpc.googlesyndication.com. So it's an add that tries to track us.

Can you confirm the same behaviour on your site? Is there a faking notification? What is the full calling stack?

I'm currently working to get rid of the performance issues. So hopefully this will also solve this problem.

**Comment by kkapsner** [comment]
Please check with the new released version 0.3.3.

**Comment by RoxKilly** [comment]
@kkapsner I no longer get the spoofing notification (I'm still on `0.3.2`) so I cannot test what I initially reported. Maybe the scripts run on the site have changed since my initial post.

Feel free to close.

**Comment by kkapsner** [comment]
I think it was an ad...

Tell me when you notice some similar behaviour somewhere - helps a lot.
