### ISSUE TITLE
Performance issues when using CanvasBlocker and uBlock

### ISSUE THREAD

**Issue by mcbarky** [kkapsner/CanvasBlocker#91]
I've noticed that www.tomshardware.com hangs at load when both CanvasBlocker and uBlock Origin are installed. This only occurs when CanvasBlocker is set to fake readout. The site also loads fine when either addon is disabled (fake readout + disabled uBlock shows no issues). This was tested using a fresh Firefox 50 x64 profile. Is this reproducible for anyone else?

**Comment by kkapsner** [comment]
Since I do not get any fake notification on this website - is this still present? I would guess that it was an ad that causes the issue.

But nevertheless there will be a new version soon that should improve the performance further.

**Comment by kkapsner** [comment]
Version 0.3.4 is out - it should be avaiblabe for update soon. Please check if your problem is solved.

**Comment by mcbarky** [comment]
The issue is still present for me with the latest version of CanvasBlocker, tested with a fresh profile on both FF 50 and nightly. It only occurs when both uBlock and CanvasBlocker are installed, and when CanvasBlocker is set to fake readout. Also, I do get the fake notification notification on the website. Not sure which addon is the cause of the conflict, or if this is a firefox issue.

**Comment by nkestrel** [comment]
Can confirm with 0.3.4 in a clean FF50 profile with e10s on and off. I get a faked readout notification and the website renders very slowly when uBlock Origin is active (default settings).

**Comment by kkapsner** [comment]
I'm still not able to reproduce this problem (but sometimes I get a fake notification) and therefore I think the more that it's related to an ad. Are you logged in to that website? Does the problem occure on specific sites of that domain or on all sites?

**Comment by toshiya44** [comment]
Specific URLs would be easier to work with. @mcbarky

**Comment by nkestrel** [comment]
It's working fine for me now, most likely an ad.

**Comment by mcbarky** [comment]
Yea, I can no longer reproduce. Must have been a specific ad issue like you said.

**Comment by kkapsner** [comment]
That are the best problems, that solve itself... ;)
