### ISSUE TITLE
Google Street View won't function while CanvasBlocker is active

### ISSUE THREAD

**Issue by spodermenpls** [kkapsner/CanvasBlocker#92]
CanvasBlocker is a great add-on that functions normally very well, unfortunately I noticed today that Google Street View (on maps.google.com) doesn't seem to function with an faked Canvas API. 

With an activated blocker (regardless which block mode) I only see a frozen picture of the street (after a reload only a black pic) and I am not able to navigate at all. If I set the blocker on "Allow everything", the site functions normally again. Is Google really able to notice that the canvas API is faked, and if so, is this problem solvable or did Google indeed "eliminate" this privacy tool for at least its Street View service for good, so you're forced to deactivate it while using it?

**Comment by kkapsner** [comment]
This is in fact a bug - I will fix this and the next version (coming soon) will work with google street view.

**Comment by kkapsner** [comment]
Version 0.3.4 is out - it should be avaiblabe for update soon. Please check if your problem is solved.

**Comment by spodermenpls** [comment]
I had now the chance to test the new update. It did improve the perfomance of Google Maps noticeably, unfortunately the Street View service is still not useable while CanvasBlocker is working. What do you think could be the reason for it, now that "readPixels" is fixed?

**Comment by kkapsner** [comment]
This is really weird. Street view is working fine on firefox nightly - but not on the normal one. I will have to investigate further what's going wrong there.

**Comment by spodermenpls** [comment]
I just got the 50.0.1-update for Firefox and all of a sudden Street View functions flawlessly with CanvasBlocker at work. According to the changelog, the update is only supposed to fix a HTTP redirecting vulnerability and an issue with the Chinese IME. I doubt these two changes had something to do with this, but I'll take it.. seems like Google and CanvasBlocker are getting along now.

**Comment by kkapsner** [comment]
Maybe they fixed something without mentioning... but great that it's working now.
