### ISSUE TITLE
stopped working on Firefox for Android 50.0

### ISSUE THREAD

**Issue by 8bitp** [kkapsner/CanvasBlocker#94]
Since the update of [Firefox for Android 50.0](https://www.mozilla.org/en-US/firefox/android/50.0/releasenotes/) the Add-On stopped working in any block mode.
I tested the Add-On against [https://browserleaks.com/canvas](https://browserleaks.com/canvas)
It always shows the same unchanged sha265 hashed Fingerprint.

(On Firefox for Android 49.0.2 it worked in any block mode.)

**Comment by kkapsner** [comment]
Does the problem stil exist in 50.0.2? In #92 we had also a probem with version 50.0 that was solved by 50.0.1.

**Comment by 8bitp** [comment]
Yes, the problem still exist in 50.0.2

**Comment by kkapsner** [comment]
This is very unfortunate since I do not have a android device to test this...
Can you please check if any older version of CB works - mabye 0.3.2 or 0.3.0?

**Comment by 8bitp** [comment]
I tested 0.3.1-0.3.4: All have had the same behaviour
-> 0.3.0 is not installable (also your release notes tell it isn't fennec compatible until 0.3.1)

(I also tested on [android-x86](http://www.android-x86.org/), but has had the same behaviour...)

**Comment by kkapsner** [comment]
Well... I guess then I have to go in the depths of debugging an addon on a mobile device. Let's see what jumps out of the rabbit hole.

**Comment by kkapsner** [comment]
Version 0.3.5 is out and should be available soon. Please check if your problem is solved.

**Comment by 8bitp** [comment]
It is solved. Thank you very much.

**Comment by kkapsner** [comment]
Great. You're welcome.

**Comment by kkapsner** [comment]
Version 0.3.6 is out - please check if this version still works with your Fennec.

**Comment by 8bitp** [comment]
Version 0.3.6 works for me on Fennec 50.1.0
Thank you for the Update!

**Comment by kkapsner** [comment]
Great. Thank you for checking.
