### ISSUE TITLE
Crashes on Firefox 50.1.0 when loading most webpages

### ISSUE THREAD

**Issue by tur-ium** [kkapsner/CanvasBlocker#95]
Using 0.3.4-Release on Firefox 50.1.0 (windows 10), the browser will crash in the later stages of loading most (but not all webpages), examples of ones which do crash: wired.com, outlook.com. Ones which do not crash: youtube.com (I think).
Other addons:
1. Self-destructing cookies
2. Ghostery
3. Better Privacy

Error log:
```
Faulting application name: plugin-container.exe, version: 50.1.0.6186, time stamp: 0x584a057c
Faulting module name: mozglue.dll, version: 50.1.0.6186, time stamp: 0x5849ff8b
Exception code: 0x80000003
Fault offset: 0x0000ec79
Faulting process id: 0x2a3c
Faulting application start time: 0x01d2577658933c63
Faulting application path: C:\Program Files (x86)\Mozilla Firefox\plugin-container.exe
Faulting module path: C:\Program Files (x86)\Mozilla Firefox\mozglue.dll
Report Id: 9fcf4f16-144b-4a3a-a54a-439c50523ef4
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by spodermenpls** [comment]
I can't confirm the problem, I am using the same setup (except for "Self-destructing cookies" and a couple of additional add-ons) and I didn't have any problems related to CanvasBlocker lately. I am able to use wired.com and outlook.com without problems.

**Comment by kkapsner** [comment]
I highly doubt that CB is the root of the problem. plugin-container.exe is related to plugins (e.g. flash) and not add.ons.

**Comment by tur-ium** [comment]
@kkapsner True ... but it disabling CanvasBlock prevented the crash twice even after clearing cache. I have re-enabled a third time and no crashes so far in the past day. @spodermenpls disabling self-destructing cookies did not seem to do anything. Perhaps there is a clash between canvas block and a plugin?

**Comment by kkapsner** [comment]
Which plugins do you have installed?

**Comment by tur-ium** [comment]
![image](https://cloud.githubusercontent.com/assets/20628325/21286012/489ff3fa-c440-11e6-9233-fd0375c06398.png)

![image](https://cloud.githubusercontent.com/assets/20628325/21286006/30578c22-c440-11e6-8b71-29e15fe105c9.png)

**Comment by kkapsner** [comment]
You can set all your plugins to "never activate" and activate them bit by bit. Then we can see what causes the problem.

PS: Your Flash is outdated...
PPS: You should leave the plugins you are not using at "never activate".

**Comment by spodermenpls** [comment]
I am only using the Flash Player on "Ask to activate" (to prevent Flash-cookies and font finger-printing) and if needed the Unity Web Player. You should delete/deactivate all plugins that aren't needed to surf the Internet (so preferably all but Flash). Do you use an ad-blocker? Maybe CB is choking on some ads, I think we had this problem in another Issue.

**Comment by tur-ium** [comment]
Ok, I am not sure if that was the cause but have updated all plugins as suggested by @kkapsner . Will close thread if no more problems are reported by anyone

**Comment by tur-ium** [comment]
The next day I did have issues and had to disable CB.
@spodermenpls Good call! I do have an adblocker, I have tried Ghostery and UBlock Origin (separately) and in both cases the same problem - the key diagnostic being trying to load http://outlook.com, which leads to the browser immediately crashing.
Do you have any recommendations on some way to log what is going on?

**Comment by spodermenpls** [comment]
Firefox creates binary logs as .dmp-files when it crashes, maybe that would be helpful to get some grip on your problem. Viewing them is unfortunately not so simple, the only option I see at the moment is to submit them via about:crashes to Mozilla to viem them on mozilla.com (maybe @kkapsner knows a better way to analyze them).

**Comment by tur-ium** [comment]
Right, I have it. The relevant details from the Details tab are:

```
Product 	Firefox
Release Channel 	release
Version 	50.1.0
...
Total Virtual Memory 	4,294,836,224 bytes (4 GB)
Available Virtual Memory 	3,327,754,240 bytes (3.1 GB)
Crash Reason 	EXCEPTION_ACCESS_VIOLATION_READ
Crash Address 	0x10
System Memory Use Percentage 	54 
Processor Notes 	processor_ip-172-31-42-44_1314; MozillaProcessorAlgorithm2015; skunk_classifier: reject - not a plugin hang
```
Obviously the full raw_dump is huge and contains sensitive information, let me know what I should look out for.

**Comment by kkapsner** [comment]
This is very weird - an addon should not be able to trigger an EXCEPTION_ACCESS_VIOLATION_READ. If so it's a bug in Firefox - CB only uses JS which has no direct memory access.

Are you logged in to outlook.com?
Can you please install the nightly Firefox Built and check if this also crashes?

**Comment by spodermenpls** [comment]
The error code is very common, I would assume that CanvasBlocker is only a symptom, not the root of the problem. As I did some research myself, I found out that the hardware acceleration support for graphics (so Canvas's too) and videos could be a cause, you should check your graphic card for driver updates and do a clean installation, at least to rule that possible reason out.

**Comment by tur-ium** [comment]
Currently testing with Firefox Nightly 53.0a1 (2016-12-22) (64-bit), with same plugins and addons as before. No problems so far including using outlook.com.

**Comment by kkapsner** [comment]
This suggests that either Mozilla fixed a problem or you have a problem with your normal Firefox installation.
Please close this issue if you're satisfied.

**Comment by tur-ium** [comment]
Will do so as soon as the next stable release is committed, interestingly Canvas Defender does not cause this issue on Firefox 50.1.0... and happy new year!

**Comment by kkapsner** [comment]
Is this issue resolved?

**Comment by tur-ium** [comment]
No problems on Firefox 51.0.1, yes resolved - thank you!

**Comment by kkapsner** [comment]
Great. You're welcome.
