### ISSUE TITLE
Uncatchable error on reading toDataURL from webgl context

### ISSUE THREAD

**Issue by DocumentRoot** [kkapsner/CanvasBlocker#96]
Hey

On reading toDataURL from gl.canvas with enabled `fake readout API` or `fake at input` i got webgl error

> Error: WebGL: readPixels: \`pixels\` type does not match \`type\`. 

It doesn't stop script execution, but produce lag up to 400 ms, and it cannot be catched.

```
<script>

var t1 = performance.now();

try {
    var canvas = document.createElement("canvas");
    var gl = canvas.getContext("webgl");

    // occurs even with empty canvas

    var dataUrl = gl.canvas.toDataURL();
}
catch(err) {
    console.log('catch', err);
}

var t2 = performance.now()
console.log('time %s ms', t2-t1);

</script>
```

**Comment by kkapsner** [comment]
This has due to changed behaviour of FF. I rember checking that and it worked.

But what ever... I know what's wrong and will fix it.

**Comment by kkapsner** [comment]
Version 0.3.6 is out - please check if the problem is really solved when the version is approved by mozilla.
