### ISSUE TITLE
Modify WebGL2RenderingContext

### ISSUE THREAD

**Issue by DocumentRoot** [kkapsner/CanvasBlocker#97]
Hey 

WebGL 2 will be enabled by default in next stable release - Firefox 51. It's already enabled in Developer Edition (and probably in Beta).

So in addition to WebGLRenderingContext, readPixels should be modified in WebGL2RenderingContext.

**Comment by kkapsner** [comment]
Good point - I thought it would be inherited for WebGLRenderingContext, but it's not. The next version will also modify that.
