### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by jugi1** [kkapsner/CanvasBlocker#98]
Not really a issue,
but just a note that CanvasBlocker is using much more memory then previous versions.
Now it is around 1,5 mb  (in previous versions was much lower)

So if you can do something with it,
this would be great.

**Comment by kkapsner** [comment]
Can you please provide me your settings?

**Comment by jugi1** [comment]
Standard settings
[](https://yadi.sk/i/ef08Yd4839UTeT)

memory 1,3 mb
[](https://yadi.sk/i/fb0SEdX-39UUjf)

**Comment by kkapsner** [comment]
Thank you for the input. The increased memory usage is created by the fix for #94.

I will keep an eye on it, but so long I think there is not much I can do about it. Maybe the redesign as a webextension can fix this problem.

**Comment by kkapsner** [comment]
The eye was open and found something unpleasant: there is also a memory leak introduced with that. Maybe I can find a way to fix this...

**Comment by kkapsner** [comment]
Version 0.3.6 is out - please check if the problem is really solved when the version is approved by mozilla.

**Comment by jugi1** [comment]
I am testing 0.3.6
It works good so far, no craching.

Memory usage: 
about:addons-memory is around 500 kb 

about:memory
23,653,912 B (04.35%) -- top(https://github.com/kkapsner/CanvasBlocker/issues/98, id=1457)

Good work!
Waiting for stable at firefox site 0.3.6

**Comment by kkapsner** [comment]
Thanks for testing - I'm also waiting for it to be approved...

**Comment by spodermenpls** [comment]
Where is it now in the queue?

**Comment by kkapsner** [comment]
64 of 162

**Comment by spodermenpls** [comment]
Only 13 spots in 4 days? What is taking them so long...

**Comment by kkapsner** [comment]
I guess missing manpower.

**Comment by spodermenpls** [comment]
0.3.6 is finally approved. 64 spots in only 1,5 days.. the manpower seems to be back. 😅

**Comment by kkapsner** [comment]
... let's see how long the next version will take.
