### ISSUE TITLE
PDF image rendered with low color space

### ISSUE THREAD

**Issue by nkestrel** [kkapsner/CanvasBlocker#99]
Version: 0.3.5-Release on FF50.1.0

Just a little rendering issue I noticed with this PDF image when CB is enabled.

![Low color space PDF image](https://i.imgur.com/iSWxyZn.png)

[PDF link](http://www.boral.com.au/brochures/ordering/PDF/Midland%20Brick%20Masterpave50%20Brochure%20OCT15.pdf)

**Comment by kkapsner** [comment]
Great sample for image distortion. The Problem is not a low color space but that the randomization is done too heavily.
I will change that to only alter the last bit.

**Comment by kkapsner** [comment]
Version 0.3.6 is out - please check if the problem is really solved when the version is approved by mozilla.

**Comment by spodermenpls** [comment]
Worked great on my end.

**Comment by nkestrel** [comment]
Verified here too, thanks for the fix.

**Comment by kkapsner** [comment]
Thanks for testing.
